### ISSUE TITLE
Gene IDs and labels need to be resolved by a third-party service in Minerva

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#101]
Gene IDs and labels need to be resolved/verified by a third-party service in Minerva. Due to changes necessary for the new model, the old way of adding GP IDs is no longer viable. The workaround to move forward on more pressing development will be to do no checking of IDs, depending on Noctua to give something sane through policy/widget.

One of the reasons that we're not switching directly using the shiny production GOlr for this are serious worries with selewis/touchup#8.

While very necessary, this should not be blocking and can be worked on in parallel.

**Comment by cmungall** [comment]
Not totally sure of the context. Remember that in LEGO/RO enabled_by holds between an activity and a gene product.

Not to be discussed right now, but just noting for future reference: there is always the option of serving the autocomplete directly from minerva. It should have everything

**Comment by kltm** [comment]
@hdietze can probably answer better, but the context here is the legality (and label resolution) of inputted gp ids. The current temporary workaround is to forget the labels and assume everything is legal. To do this without completely letting anarchy rule, @hdietze has added the "--skip-class-id-validation" flag for starting up Minerva, added to MolecularModelServer/src/main/java/owltools/gaf/lego/server/StartUpTool.java.

**Comment by kltm** [comment]
@hdietze has made some progress on this I believe?

**Comment by kltm** [comment]
As proven by @jnguyenx , this works upstream, but the loader actually needs to capture the labels into the class expressions.

**Comment by cmungall** [comment]
Can we capture this, e.g. in http://www.websequencediagrams.com/

**Comment by kltm** [comment]
...I believe that this was actually completed a few weeks ago, but slipped through as it was mostly a minerva fix (although there were a few adjustments in the startup scripts, etc).
