### ISSUE TITLE
Model IRIs should not contain a ':' (colon)

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#103]
Shouldn't have a ':' in there, the ';:'s should only be in the CURIEs

**Comment by kltm** [comment]
@cmungall bugs should contain sensible titles so they can be browsed--I changed this to what I think you're saying. To be sure, could you give an example? (Also helpful.)

**Comment by cmungall** [comment]
But the general issue is model IRIs. Need to document, ensure robustness etc

**Comment by kltm** [comment]
Title to "Model IRIs need to be robust and documented"?

**Comment by kltm** [comment]
@hdietze is changing a bunch of stuff for the migration for #76, this will be included in some upstream code drop.

**Comment by kltm** [comment]
This was completed by @hdietze last week.
