### ISSUE TITLE
Import of external ontologies

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#104]
http://go-genkisugi.rhcloud.com/seed/model/gomodel:548253760000052#

needs to import wbbt classes

(should we have a Label for data bugs that can't be fixed via the interface?)

**Comment by hdietze** [comment]
The solution of this issue has changed: The approach is now to include wbbt into the Golr instance which drives the auto-complete (Noctua) and labels (Minerva).
The actual model should not contain any specific imports any more, only the global http://purl.obolibrary.org/obo/go/extensions/go-lego.owl import file.

**Comment by kltm** [comment]
Kicking this to a larger issue of having a separate GOlr instance for Noctua #125 .
