### ISSUE TITLE
in_absence_of and in_presence_of relationships are not available

### ISSUE THREAD

**Issue by rbalakri** [geneontology/noctua#105]
in_absence_of and in_presence_of relationships are not showing up in the auto-complete box. Can you please help?

Thanks,

Rama

**Comment by kltm** [comment]
Added coherent/browsable title.

**Comment by kltm** [comment]
If these are new terms in RO, noctua has not been rebooted in a while and may not have access to them. I'll try and find the history.

**Comment by rbalakri** [comment]
I am assuming this is the current RO file-
http://obo-relations.googlecode.com/svn/trunk/src/ontology/ro.obo
These two relationships are not in this file (hence not showing up in LEGO). I don't know who is the keeper of this file. I will look into it.

Rama

**Comment by kltm** [comment]
Yes, after the redirects, the upstream seems to be here: https://obo-relations.googlecode.com/svn/trunk/src/ontology/ro.owl. You might want to contact @cmungall about it.

**Comment by cmungall** [comment]
Always use the purl:

 * http://purl.obolibrary.org/obo/ro.owl

Did we agree to these relations on the call? Can't the equivalent statements be composed using existing primitives? E.g. rather than "A is executed in the absence of C", we'd say there exists a function A' that is enabled by C, and A' inhibits A?

**Comment by kltm** [comment]
@cmungall The purl is indeed used in the loading; just referencing the final file to figure out its history.

**Comment by kltm** [comment]
It looks like @hdietze was never tagged onto this.

**Comment by cmungall** [comment]
Always use the purl
http://purl.obolibrary.org/obo/ro.owl
(it happens to redirect to gcode now, will redirect to gh soon)

it's unlikely we'd add these to RO as AFAICT they are only required for 
limited expressivity in annotation extensions; is it not possible to 
describe the biology more directly in a lego model?

**Comment by cmungall** [comment]
These relations
