### ISSUE TITLE
Manipulation of types through the API does not trigger automatic annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#115]
The manipulation of types through the API does not trigger automatic annotations (contributor and date) getting added to the manipulated individual.

This is a previously known issue in Minerva that @hdietze will look at.

**Comment by hdietze** [comment]
The minerva code has now been fixed. See owlcollab/owltools@e66b7120e0d5643fba997c6affa255b1e4dd97ea

**Comment by kltm** [comment]
This now seems to be working as expected.
