### ISSUE TITLE
Handling of automatic annotations needs to be updated and standardized

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#116]
We should take another look at how automatic annotations are handled on the server side (and make sure that they're exposed properly on the client).

Model annotations:

* any modification to anything in the model counts as an update
* contributor is additive
* date is the last date anything is modified in the model; not additive

Individual annotations:

* needs to be updated during any manipulation directly to the individual
 * types, comments
* contributor is additive
* date is last modified date; not additive

Edge annotations:

* needs to be updated during any manipulation directly to the edge
 * comments
* contributor is additive
* date is last modified date; not additive

This is mostly an upstream Minerva issue that @hdietze will take a look at first.

**Comment by hdietze** [comment]
The upstream minerva code has been updated to reflect the requested behavior. Dates are now updated instead of added.

**Comment by hdietze** [comment]
See commit owlcollab/owltools@3e11d86d4379fd1c7c75cb27a9c3be388337efff

**Comment by kltm** [comment]
Talked to @hdietze, still a couple of issues around deleting evidence and having that update in the referenced individual or fact.

Models seem to be working fine.

**Comment by hdietze** [comment]
Bug fix for missing edge case of deleted evidence:
* owlcollab/owltools@ffa60c7f2463dfee0de5017f21566825407c8c32
* owlcollab/owltools@b88b7ec98adbc5416b49fb4b870276a91e8f1764

**Comment by kltm** [comment]
Checked and looks good!
