### ISSUE TITLE
Generally, add button for updating contents of field rather than only supplying add

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#117]
The idea is that many text fields have the ability add, but updating a value requires a cycle of deleting and then adding. This is a bit annoying.

This could be fixed in many cases by adding an "update" button, which essentially batches the delete and add into a single transparent operation.

**Comment by kltm** [comment]
Okay. talking with @hdietze about something else and this came up.

It's important to remember why we don't have this now. Annotations on the Minerva side are sets, meaning that we can have multiple titles, dates, states, etc. if we want to. To avoid having to:

* get the current values of the keys in question
* delete them
* add new k/v(s)
* send

We essentially lock the UI once there is a value, making the user delete the single value, and then add another. This made a lot of sense with the one-action-per-request world we used to be in, but with the batching, we can do better.

There are a few approaches though:

1. deal with the heavy lifting on the client (loopy loops)
2. have an "update" path on minerva
3. enforce field cardinality in minerva

For the time being, we're looking at "1", which may not be too bad with a function like:

```js
entity.update_annotation(key, values)
```
that (maybe) returns a request (from the requests package).

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for now.
