### ISSUE TITLE
Switch Makefile based build and deployment over to gulp, create more coherent environment

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#119]
The idea is to move away from the build and deployment system (with all the associated workarounds) that was cribbed from the early JS days with AmiGO and start fresh with modern tooling.

The idea is to have a single unified runtime for client and server code, likely a combination of:

* ~~npm~~
* ~~gulp~~
* ~~jsdoc~~
* ~~unit tests/BBD (mocha/chai)~~
* ~~uglify ("production" compress target)~~
* ~~browserify [jQuery being a PITA, need browserify-shim **at app end**]~~
* ~~release tools (gulp-bump, gulp-git, etc.)~~
* ~~watch~~(ify)
* SCSS
* ~~JS and (S)CSS lint~~ <- not going to bother here since it requires external tooling (ruby, etc.)

I'll cross these out as I add them to the project and get an example going (this may fall out of sync with committed code).

Can possibly serve as a starting model for monarch-initiative/monarch-app#665.

**Comment by kltm** [comment]
Step back from this with recent commits to give a stable base to @jnguyenx .
Next pass (after graphs) will be to browserify each page's client separately and completely.

**Comment by kltm** [comment]
@jnguyenx You'll have to pull again, but this should be the last bad one for the tooling for a while. It seems to work alright at my end, and I've done a little testing, but I might have missed something.

The "build" target is now necessary to get JS files ready and updated; you probably want to go ahead and get "./node_modules/.bin" into your path. Also, I'm guessing you might want to use the "gulp watch" target (auto-rebuild on change).

**Comment by jnguyenx** [comment]
@kltm thanks I'm good to go now :sunglasses:
