### ISSUE TITLE
Load IntAct complexes for use in "enable_by"

### ISSUE THREAD

**Issue by rbalakri** [geneontology/noctua#120]
Can you please load the IntAct complexes so they can be used as objects that enable a function?

Thanks,
Rama

**Comment by kltm** [comment]
@hdietze Is this something easily done?

**Comment by hdietze** [comment]
There are multiple questions/tasks associated with the underlying issue:
 * The current auto-complete mechanism is relying on the available amigo/golr data. Making complexes available here would mean including all IntAct complexes in the load. This is completely untested at the moment.
   One alternative could be a different auto-complete (source?) for complexes/IntAct in a different dialog.

 * How to actually make use of IntAct complex details
   Regardless of the source given, the current mechanism for a complex would be handled as simple identifier. The question remains: how to at least use the taxon information for the complex (or better also the constituents parts)

 * As a potential related issue is the question about using RNAs as enablers.

**Comment by kltm** [comment]
@hdietze for the first, I'm a little worried about having a different (or multiple) autocomplete sources--I think it would be easiest to try AmiGO first, then look elsewhere. We can easily have fairly divergent loads between production and labs.

For the second, one could conceivably squeeze a bit more out of the AmiGO communication at the Minerva end if we had this information loaded as well...something could probably be worked out around there.

Somebody can fill me in about the third item at some point, but I think progress is fairly well blocked by the first (and second).

**Comment by vanaukenk** [comment]
Closing this ticket for now.

If a group includes protein-containing complex ids in their gpi file, they are available for use in Noctua.

We can re-open this ticket if there are any future questions/issues wrt this.
