### ISSUE TITLE
Load PRO IDs for use in "enabled_by" and to get better labels

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#122]
Hi,
In order to model some signaling pathways correctly, we will need to annotate to gene product identifiers for modified or non-covalently bound proteins.
One use case, for example, is to be able to annotate an MF to a GTP-bound form of a Ras-related protein (see March 2015 annotation consistency exercise models).
We will also need to sort out how to deal with this in upstream (creating the IDs) and downstream (annotation files, etc.) annnotation pipelines.
Thanks,
--Kimberly

**Comment by kltm** [comment]
Assuming a similar work profile to #120 .

**Comment by cmungall** [comment]
Another option would be to post-compose the bound form (same approach can be used for complexes too). This wouldn't preclude inferring equivalence to a PR class downstream in the pipeline.

**Comment by vanaukenk** [comment]
Closing this issue.

Groups can add modified forms of proteins to their GPI files for use in Noctua.

We can re-open this ticket in the future if further discussion is needed.
