### ISSUE TITLE
Ensure Noctua works for multi-species models

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#131]
Moved from: https://www.ebi.ac.uk/panda/jira/browse/GO-281 for @dosumis 

We know that with the all-individual model the modeling is sufficient to handle the case where the same organism instance is co-referenced. Is see no reason why this wouldn't all work by default by allowing access to exploded view, but leave this ticket open until we can produce a demo of this working.

**Comment by vanaukenk** [comment]
Not actively being worked on; still need some curator documentation/guidelines about annotating multiple species within a single model.
