### ISSUE TITLE
Ensure that no functionality was lost during the transition to the new core/libraries

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#132]
There have been a lot of changes since we started the most recent code cleaning/refactor, including changing to bbop-graph-noctua, a new request system (request_set), and the new models.

This is an umbrella item to get/ensure all of the previous functionality is available for users with the new libraries.

We'll also hopefully start adding end-user level units tests with this.

**Comment by kltm** [comment]
With meeting this morning, will now go through systematically and test everything (hopefully getting unit tests done as well).

**Comment by kltm** [comment]
This is considered to be more-or-less done with many of the recent small fixes, at least as a first pass. Will need #53 to prove it.

**Comment by cmungall** [comment]
woohoo!
