### ISSUE TITLE
Allow "deeper" evidence models in the interface and libraries (deeper folding)

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#141]
Discussed with @hdietze, @cmungall, and @jnguyenx.

In addition to the current evidence model, it _may_ be that the evidence individual has an annotation (value-type=IRI, possibly key=dc:source) to another individual (type "publication") that contains the terminal evidence information in an annotation (e.g. "source" PMID).

Moreover, these publication individuals _may_ be shared between various evidence individuals:

![img_20150714_141322](https://cloud.githubusercontent.com/assets/2687900/8685853/69ff58b0-2a36-11e5-9bee-a681cc7ab6d9.jpg)

To support the real folding of this pattern, there will have to be a reference count implemented to ensure that after all of the separate subgraph clones are made that the publication individual is "eliminated" in the top-level graph.

**Comment by kltm** [comment]
After talking with @hdietze, we'll give this a lower priority for now as 1) editing can still be done (albeit with more steps) in "exploded" modes and 2) GO will be using the simpler model for the immediate future.

**Comment by kltm** [comment]
Had another discussion with @cmungall and @hdietze about how we will be handling some forms of evidence moving forward.

![img_20150722_155335](https://cloud.githubusercontent.com/assets/2687900/8839487/ad1a69a0-308a-11e5-92ed-486ed9cc97b4.jpg)

The immediate takeaway is that berkelebop-graph-noctua folding should go from referenced individuals to (arbitrary) referenced subgraphs, and that evidence folding will have to be a little more clever, with the possibility of having shared nodes in referenced subgraphs.

@hdietze will take care of the additional needs of managing creation with pre-defined IRIs, it should be not too bad.

**Comment by kltm** [comment]
Most recent. Note that once the reference jump is made, there are no more references in this model (as discussed with @cmungall and @hdietze ).

![img_20150723_184438](https://cloud.githubusercontent.com/assets/2687900/8920715/97ef1526-3481-11e5-81bd-e7ab9ce4e59b.jpg)

**Comment by kltm** [comment]
We have re-prioritized this for the time being as 1) it's not needed for the upcoming meeting and 2) maintaining the two code paths for the display and editing is kinda nasty.

We will ready it and do a single switchover event similar to the model conversion that we did a couple of months ago. Namely, we will:

* freeze the production server
* ready the code on labs
* switch the models on labs (expand the current modelling into the new "deep" version)
* work out any bugs in the interface, etc.
* push the new code and models onto production
* unfreeze production

**Comment by kltm** [comment]
Okay, back on this and just talked to @hdietze and @cmungall .
We're still looking at case 4, but instead of the span being an individual, it will be an annotation on the evidence. @hdietze , what would be the key for this one?

**Comment by kltm** [comment]
First blocking TODO: test naked IRI creation for individuals. (Need to make sure my API takes this.)

**Comment by kltm** [comment]
Let's take a closer look tomorrow, but I think I have the tools and pattern down for this now, and they seem to be behaving in the expected fashion:

![screenshot from 2016-06-08 00 19 24](https://cloud.githubusercontent.com/assets/2687900/15885883/d426ff78-2d0e-11e6-89c2-61408e8b1083.png)

Let's double check and then I'll go on to multiples and the deletions tests.

**Comment by kltm** [comment]
Tagging @mellybelly @mbrush @cmungall for comment about merged Monarch and GO models for evidence before a final push to implement it.

**Comment by cmungall** [comment]
For the benefit of others, am I right this ticket involves removal of the hacky literals and implements this? https://github.com/geneontology/minerva/blob/master/specs/owl-model.md#axiom-annotations-and-evidence

(@balhoff, should we use SHACL for constraining the shapes here?)

**Comment by kltm** [comment]
@cmungall Yes, that's the end product of this. Minerva already supports it (theoretically, we did a little testing before Heiko left), but the rest of the stack is unaware.

**Comment by kltm** [comment]
One example that we were working around:
http://noctua.berkeleybop.org/editor/graph/gomodel:a1a2a3a401
http://noctua.berkeleybop.org/editor/graph/gomodel:a1a2a3a402

**Comment by vanaukenk** [comment]
Not actively being worked on.
