### ISSUE TITLE
Include link to owl spec in README.md

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#142]
The noctua repo serves as top level entry point to the troika

currently there is no easy way to navigate to specs concerning the semantics of noctua. We have some specs here in minerva:

https://github.com/geneontology/minerva/tree/master/specs

Still not sure the best way of organizing the docs for all this. There are different levels: docs for deploying, docs for the semantic aspects that are aimed at both core developers plus the ontology group, ...

**Comment by kltm** [comment]
One approach would be to keep the repo READMEs, top-levels, and the like more focused on the code itself and immediate developer issues, with the wiki encompassing more of the expanded universe. 

Other possible GitHub controlled entry points are places like: https://geneontology.github.io/noctua/ (which is currently rather outdated).

Thinking a bit bigger with GO, as there are quite a few things that inthere could also be a controlling book or set of documentation links with an overview out the the geneontology.org Drupal.

Or, if "noctua" spans too many groups and projects, it could reasonably be spun out into its own org-level entity, with things like minerva and the editor being projects, and http://noctua.github.io being the main entry point.

**Comment by kltm** [comment]
I was going to move this over to the Minerva wiki at some point: https://github.com/berkeleybop/bbopx-js/wiki/MinervaRequestAPI , but given that spec, they should probably end up in the same spot.

**Comment by kltm** [comment]
Is this cleared, or at least far enough along that it will proceed naturally?

**Comment by cmungall** [comment]
We have documentation on the OWL modeling along with the OWL models - https://github.com/geneontology/noctua-models

LANDING.md now has a quickstart for different types of users/consumers
