### ISSUE TITLE
When in a folded mode, the "contained" entities in the subgraph should also be deleted

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#144]
When in a folded mode, the "contained" entities should also be deleted.

For example, the "complete" subgraph contained within a folded individual should recursively delete all subgraph individuals (the edges will be picked off by Minerva).

Note that this does not really work for evidence beyond the first level as there start to be reference issues (so there might need to be additional thought put in to that later on), but we're fine for GO for now.

**Comment by cmungall** [comment]
Do we have a spec for the folding?

I wrote this when we were planning for the all-ind model but things may have drifted/it was incomplete as it only considered collapsing biological individuals, not evidential/provenance side of things individuals:
https://docs.google.com/document/d/1scuE-BJwJwAMEBrsanIvTDI26YqlRvBQf7m4xwBDS3c/edit#heading=h.15fqmpdpuy6j

**Comment by kltm** [comment]
What spec there is is mostly in the API of berkeleybop/bop-graph-noctua. Looking at the docs, I think our overall attack on the problem has changed, leaving more (all) to the client and Minerva only ever dealing with the exploded model. This is done with the "absorbing" features of bbop-graph-noctua.
