### ISSUE TITLE
Find some way to exposed the evidence of "folded" elements

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#145]
Find some way to exposed the evidence of "folded" elements. Currently, only the direct evidence is displayed. This is fine in the exploded views, but may leave people wonder whether or not that actually added evidence, or what it was, in more folded modes.

**Comment by cmungall** [comment]
Consult with users, but I would be happy with something simple. E.g. if a folded edge (enabled_by, say) has any axiom annotations then indicate this in a boolean fashion (e.g. Protege has the '@' symbol). If the editors wants to know more then they double click on the box or whatever is required to zoom in

**Comment by kltm** [comment]
Yes, this was going to be more or less the first pass, then once the hooks are in it will be easier to change later.

**Comment by kltm** [comment]
Closed with a little addition; will need to revisit later when the more expanded evidence is being used in anger.
