### ISSUE TITLE
Export response is now silently dropped

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#146]
Export response is now silently dropped when an export is attempted.

The export interface actually needs to give the user the requested file.

Should be a simple UI poke to fix.

**Comment by kltm** [comment]
The fact that one can save and just grab the thing from github the next day should also be mentioned.

**Comment by kltm** [comment]
Earlier fix did not have proper response fix, now fixed and /tested/.

**Comment by hdietze** [comment]
Verified together with @kltm that there is still an issue with export of a model.

**Comment by kltm** [comment]
So far, cannot be duplicated locally, only on the "production" site. Huh.

**Comment by kltm** [comment]
Started working again after last night's complete refresh on the server. Or maybe it only works on even-numbered days.
