### ISSUE TITLE
Box nesting for part_of

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#15]
This will be a gather involved enhancement.
Should go after other refactors.

**Comment by kltm** [comment]
Hrm, I thought there was more here--I'm wondering if the discussion is  hiding on another ticket (probably related to folding).

I believe the "strong" nested box model would be quite hard given the current framework.
Another option would be to build something around the folding system.

**Comment by cmungall** [comment]
From email to list from Ruth:

> Looking at Paul’s Wnt signaling LEGO model I do wonder if it would be possible to take the ‘Reactome’ type approach of circling (with shaded background?) some of the annotons to identify 
> those which belong to (are part of) large pathways, rather than simply having a part_of line between a pathway and 5-20+ annotons. I think the users will find this much easier to read.

**Comment by cmungall** [comment]
the jsplumb docs mention 'containers', is this something different?

**Comment by kltm** [comment]
At the Caltech mini-meeting we talked about using the background canvas to give some of this effect, but I suspect that the reality would be rather underwhelming as it would require an uneasy balance between automatic and free layout.

We are also looking into what can be done with more complicated nodes and "folding".

I believe containers are something different from what is being described here.

**Comment by cmungall** [comment]
Adding a mockup just to help people coming to this ticket orient

![nestednedd4](https://cloud.githubusercontent.com/assets/50745/14396610/67c1f668-fd8d-11e5-8c12-fd7bc026e17f.jpg)

Note that this shows containment within a continuant (nucleus, cell), by following occurs_in (and then part_of, once you are in the continuant hierarchy). I think the main requirement is to just do containment within the occurrent hierarchy (ie just following part-of). Thus the outermost box would be the overall pathway in many cases.

**Comment by kltm** [comment]
People coming in should also note that the final product is unlikely to look too much like this.

**Comment by kltm** [comment]
Although, I think that I might have thought of a cheat to simulate this (node points defining a dumb polygon). More exploration will be necessary; however, nesting boxes would have to exists entirely outside of the jsplumb and layout systems.

**Comment by kltm** [comment]
Also, maybe this could be accomplished with a workbench rather than in the "main" graph editor.

**Comment by goodb** [comment]
Would be nice if this feature worked on has_part as well as part_of relations.

**Comment by kltm** [comment]
At this point, I think we need to give up with this for the main graph editor and figure out what we want for the "pathway" views, which can use the more malleable cytoscape.js (as demonstrated by the part-of boxing we can do there).
If there is no complaint, I'll reframe this ticket to add what @goodb wants in the pathway workbench.

**Comment by goodb** [comment]
@kltm one alternative to consider might be to focus some team effort on an exporter designed to produce Cytoscape ingestible files.  It most likely needs to be done anyway, gets the user immediate full access to all of their network layouts and analysis tools, and would allow for Web development time to focus on the editor ui.  Does require the user to download Cytoscape though, don't know users well enough to know if thats a showstopper.  (I could help with an exporter service if this was desirable.)
