### ISSUE TITLE
Add a wizard-let/form that allows the user to add an individual of class X

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#152]
Add a wizard-let/form that allows the user to add an individual of class X.
This comes from David's use case where we want to just have "citrate" (guessing CHEBI:16947, http://amigo2.berkeleybop.org/amigo/term/CHEBI:16947) as an element in the model. The autocomplete would be unlimited.

One more noodle in the pile of spaghetti.

**Comment by cmungall** [comment]
but this is the ubernoodle

**Comment by kltm** [comment]
I actually think I'm just going to stick it in the dropdown or somewhere for the time being as a button creating a literally empty individual and them leave it to the user to fill it in as desired. We'll revisit later when we take a hatchet to the UI.

**Comment by kltm** [comment]
A question for @hdietze: with the current API, it seems to be impossible to add an empty individual; it this correct?

```json	
[{"entity":"individual",
  "operation":"add",
  "arguments":{"model-id":"gomodel:55ad81df00000001",
                       "assign-to-variable":"a794b2f0-beeb-4a66-a415-7ff16c5b72bd"}
}]
```

results in an error with:

```
"Could not successfully handle batch request. Exception: org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException. Expected non-null value for: request.arguments.expressions"
```

I'm assuming this is expected behaviour.

**Comment by hdietze** [comment]
In the inner working of Minerva, I believe, there is no requirement for individuals to have a type. But usually a missing type/expression is a good indicator for a problematic request.
One other thing to try is sending an empty list instead of a null value for `request.arguments.expressions`

**Comment by cmungall** [comment]
This can always be bypassed by passing owl:Thing (which is redundant, as 
every individual is necessarily an owl:Thing)
