### ISSUE TITLE
Error message trying to delete an individual

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#159]
Hi,

I'm trying to delete an existing individual and am getting this error message:

Error (error): Empty batch calls are not supported, at least one request is required.; your operation was likely not performed.
null

The individual is an anatomy term that has an incorrect part_of relation to an MF individual.
I was able to delete a similar individual yesterday, so am not sure what might be happening.

Thanks,
--Kimberly

**Comment by kltm** [comment]
You'll need to supply the model and individuals numbers for us to track this down.

**Comment by vanaukenk** [comment]
Thanks, Seth.

The model URL is:  http://noctua-dev.berkeleybop.org:8909/seed/model/gomodel:542732ad00000010
and the individual is: obo:#542732ad00000010%2F5595c4cb00000338

Let me know if you need anything more/different.

**Comment by kltm** [comment]
Hey, neat--that's not right! I've confirmed this on production and locally. I think I know what's going on--I should have a quick fix after lunch.

**Comment by vanaukenk** [comment]
Awesome; thanks, Seth!

**Comment by kltm** [comment]
@vanaukenk this should be fine now--the client code has been updated; refresh your browser and try again.

**Comment by vanaukenk** [comment]
All is working now; thanks for the quick fix, Seth.
