### ISSUE TITLE
Public beta release catch-all ticket

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#160]
* Remote orchestration commands for Minerva: https://github.com/geneontology/minerva/issues/15
 * Auto-refresh barista when user metadata is updated

**Comment by kltm** [comment]
The actual item I'm looking at right now for Barista would be to take remote orchestration commands, like Minerva. This could be a separate "admin" manager, or could possible piggyback on the infrastructure already there. This will be a separate ticket eventually, and deleted from this catch-all item.

(I'm going to have at the title at some point.)

**Comment by kltm** [comment]
Remote orchestration will likely be from #209. Dropping this ticket as time is short and the road clear.
