### ISSUE TITLE
Add ability add evidence to folded edge

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#163]
Currently enabled_by and occurs_in are folded in by default

So in order to add evidence to these these, you need to switch to compact view in which these are unhidden, double click the edge, add the evidence, then go back to editors view. The presence of evidence is indicated by a superscript e.

![screen shot 2015-08-18 at 5 44 18 pm](https://cloud.githubusercontent.com/assets/50745/9346373/e124e5bc-45d0-11e5-9c2e-4e3c0e7cdcb2.png)

For efficient editing the expand/contract step needs to be omitted. Would it be possible to have the "e" be clickable. This would bring up the exact same dialog as double clicking on the equivalent edge in the compact/exploded view

**Comment by cmungall** [comment]
Note that this enhancement does not necessarily supersede or replace other enhancements, such as extending the wizardlets on the left to include evidence. But I believe that the enhancement in this ticket should be sufficient for efficient editing and wider rollout

**Comment by kltm** [comment]
Collapsible relations are stored in config/collapsible_relations.json.
The current list is:
```json
[
    "RO:0002333",
    "BFO:0000066",
    "RO:0002233",
    "RO:0002488"
]
```

**Comment by kltm** [comment]
Thought it was low-hanging fruit, but maybe not so much. Have something in there now though.
