### ISSUE TITLE
Create training material for using Noctua for GO modeling

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#166]
This ticket intentionally vague for now, may be split into separate tickets, TBD:

 * Does this encompass two distinct pieces of material (use of the tool, fundamentals of lego modeling)? Or should this be rolled into one?
 * Does this documentation integrate loosely, tightly with Noctua, or is it something that lives separately alongside other GO documentation?
 * How do we manage this material? GitHub/markdown, wiki (GO vs GH), Drupal, Google docs, YouTube, ...? May be a mix.

Who wants to claim this: @dosumis @rbalakri @ukemi @pauldthomas @vanaukenk?

**Comment by vanaukenk** [comment]
I would definitely like to help with Noctua documentation.  
If possible, it'd be great to have a Noctua camp to focus efforts on this; there's a lot to think about here.

**Comment by rbalakri** [comment]
Chris,

Thanks for opening this ticket. From PAINT experience I think a detailed description of how the tool works (how to do X or Y, Click here to see blah) helps. Of course documentation of fundamentals of LEGO modeling has to be there.
http://wiki.geneontology.org/index.php/PAINT_User_Guide
We should do a jamboree to go through models, and train people.

I am happy to help with tool and modeling documentation.

Rama

**Comment by cmungall** [comment]
Great idea for jamboree/camp - added this as a discussion item to go agenda: http://wiki.geneontology.org/index.php/2015_Washington_DC_GOC_Meeting_Agenda#Common_Curation_Environment_and_LEGO_annotations

**Comment by kltm** [comment]
Is this being taken care of elsewhere now?

**Comment by cmungall** [comment]
All relevant material now linked from noctua landing page
