### ISSUE TITLE
Missing uberon labels on individuals

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#167]
E.g.
http://noctua-dev.berkeleybop.org:8909/seed/model/gomodel:55ad81df00000001

Adding individuals of type 'brain' works; whereas 'brain marginal zone' is rendered with the ID

Hypothesis: 'brain marginal zone' is in uberon but not the module extracted for loading into go-plus. Somehow minerva is looking up only go plus but not the full set of ontologies loaded into golr.

**Comment by kltm** [comment]
Should probably be moved to the geneontology/minerva tracker--has nothing to do with the code here (and so makes it harder to tag, keep track of, cross-reference, etc.).

**Comment by hdietze** [comment]
Fixed the underlying issue in the Golr client and extended the test case in minerva.
Should be fixed once @kltm rebuilds owltools, minerva, and restarts it on the server.

**Comment by kltm** [comment]
/Now/ it's noctua issue :wink:

**Comment by kltm** [comment]
Refreshed up and down the line--all the "marginal brains" are yours now. (At least I got one ticket closed today.)
