### ISSUE TITLE
For "restricted" autocompletes, when the gene product is selected, search the bioentity for the process/function

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#168]
This is pretty self-explanatory: for "restricted" autocompletes, when the gene product is selected, search the bioentity for the process/function. The main thing to get out of this is to eliminate the current issue with repeats in the autocomplete (and make the search generally more coherent).

This is from a discussion with @mugitty (about the general lacking in the autocomplete widgets) and @cmungall.

**Comment by cmungall** [comment]
The eventual goal here would be to have some kind of dialog or popup that is an amigo component that provides some subset of amigo search functionality. But eliminating repeated terms should get us a long way.

For now, autocomplete only on direct annotations. If someone really wants to generalize an existing annotation they can do it via freeform. Showing only directs should limit the autocomplete to a manageable amount

**Comment by kltm** [comment]
Well, as it often turns out, there are actually good reasons we have not already done this. The short of it is that there is no single ontology term to get from a bioentity document, only lists (even the direct annotation class is a list (obviously)), so the autocomplete widget cannot work as designed--it works on documents, not inspecting single documents.

A different widget, or a refactored widget using grouping or Solr 5 features, would fit the bill. But I think this current widget is as far as it will go as-is.

**Comment by kltm** [comment]
Preference would be to quit work on these hacky "internal" widgets and switch over to external "widgetized" search boxes anyways--they'll be easier to work on and test, and quit complicating the main codebase.
