### ISSUE TITLE
Create an AmiGO-based annotation selection bridge for adding elements into a model

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#170]
Create an AmiGO-based annotation selection bridge for adding elements into a model.

An example would be that when a user selects a gene product, they get a pop-up that is a pin in an AmiGO annotation search, where the user can select annotations that are then ported into the current model, including evidence, etc.

More deeply, we're looking at ways that AmiGO parts can be reused to interact with/add elements to Noctua.

**Comment by kltm** [comment]
Thinking about doing this as a "workbench" first. Will let #172 go first to see if the multi-window/tab thing can work out for something this divorced from the flow of listening to callbacks (the proper editors).

**Comment by kltm** [comment]
Have run into a hiccup in that we have no real way of extracting ECO IDs from the current GOlr loads. IIRC, there was some push back from going all in early on, and as a temporary hack, we used the three letter codes for evidence_type and the ECO labels for evidence_type_closure. Oh well.
 
@cmungall, do we have a handy list somewhere of three letter codes to ECO IDs? That would tide us over until we can load the real deal.

**Comment by kltm** [comment]
Two things left: the ECO issue (above) and whether or not to "bundle" same annotation classes in the same request. A little cleaning maybe and then push to public.

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

But it would be better to avoid a dependency. I think it would be acceptable to make the evidence type be IC (ECO:0000305) as a default on a first pass, then loop round to this later.

**Comment by cmungall** [comment]
Or if you don't mind doing another lookup, get it from golr, e.g

http://amigo.geneontology.org/amigo/search/ontology?q=synonym:%22IDA%22&fq=source:%22eco%22&sfq=document_category:%22ontology_class%22

http://geneontology-golr.stanford.edu/solr/select?defType=edismax&qt=standard&indent=on&wt=json&fl=annotation_class,id,annotation_class_label&fq=source:%22eco%22&fq=document_category:%22ontology_class%22&q=synonym:%22IDA%22

**Comment by kltm** [comment]
No, don't want to look it up--I'll just use the map file as the temporary hack.

Now the final question: do we want to collapse annotation classes, or are we good for now?

**Comment by kltm** [comment]
Talked to @cmungall; essentially we want to collapse as much as possible (class->gp->ev), and use the patterns as much as possible outlined below (accepting that when multiple ones are ambiguously selected that the process will fail with an explanation).

![img_20150824_162603](https://cloud.githubusercontent.com/assets/2687900/9455198/795bd16e-4a7d-11e5-82e0-32cad6c9b276.jpg)

**Comment by kltm** [comment]
Talked with @cmungall, there is some impossibility here in trying to be able to select multiple aspects using the same AmiGO search interface. I'll either back down to the "compacted shovel-over" or try and add another box to the workbench.

**Comment by kltm** [comment]
Time is short and the workbenches will make a nice staging area for prototypes as we move forward.
We'll probably open a new item for something for paul, but I think this thing (whatever it is) is done as an enhancement in its own right.

**Comment by kltm** [comment]
From @cmungall, forgot to change the filters to do direct taxon instead of closure.

**Comment by kltm** [comment]
Now remember why I was confused--this was /already/ the default in AmiGO, but the npm libs had not been updated so it was not showing up here. Now pushed.
