### ISSUE TITLE
Create a model overview using cytoscape.js tools - demo

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#172]
Using cytoscape.js to visualize one of the larger graphs with a better layout (thinking about the seeding hairballs). A fun little thing to do on a lazy day.

This is actually distantly related to other "workbench" items in that it's giving me a chance to refresh some of the noctua.js webapp code into something a little more manageable before the weightier task of getting the AmiGO "companion" in as one of the other workbenches.

**Comment by cmungall** [comment]
It would be fun to see *all* models in cytoscape.js, See also http://www.reactome.org/PathwayBrowser/

**Comment by cmungall** [comment]
Just looked at 
http://noctua-dev.berkeleybop.org/workbench/cytoview/gomodel:5362b2ed00000016?barista_token=

:grin:

**Comment by cmungall** [comment]
that's a grin btw
