### ISSUE TITLE
Minor improvements to CytoView

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#176]
1. Add layout options (e.g. radial), as in http://beta.monarchinitiative.org/labs/cy-explore-demo
 2. Color code nodes according to broad class (molecular, activity, process, cell component, cell, anatomical)
 3. Folding (possibly with some texty hack)
 4. View multiple/all models in mega-cyto-view
 5. connect nodes that have identical class ids (for connecting models in 4)
 6. ...

**Comment by kltm** [comment]
Will want to make some clarifications with you tomorrow.

**Comment by kltm** [comment]
My druthers would be to not spend too much time on this, as it was essentially a test bench for what an easy extension might look like, but here are my thoughts on the list:

1. No problem
2. This would require a separate lookup for all the nodes using GOlr (this information is not native in the noctua-model information), which is a fair bit more code overhead and possible a slowdown for large models.
3. Folding in what sense? The noctua folds?
4. This is unlikely as all models would have to be loaded into Minerva at the same time and run over the wire--I'm guessing timeouts would get us there if memory didn't. Might be something for AmiGO though, as once we have the model loads in, we could get those much easier.
5. This would happen automatically during the graph merge process.

**Comment by kltm** [comment]
Essentially, I think 1 & 3 are realistic for what this widget is trying to do, with 2 needing a little more thinking.
