### ISSUE TITLE
Add a progress bar that shows how much of biology is modeled

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#177]
meta-note: this functionality may go in amigo feel free to move to amigo tracker, it at least relies on golr.

Given the BP subset from an appropriate GO subset (e.g. go_slim), report back on how complete the set of all models is.

This can be calculated easily from `process_class_closure` in `model-ann-config.yaml`. Naively, for any process `P`, if there exists a model_unit where `process_class_closure` is in `P`, then `P` is covered.

(of course, the model may only be a partial model of the process, so notion of covered will ultimately be more nuanced)

We can imagine fun ways of showing this, charts etc. See also DOVEs in Monarch.

The same thing would work for other ontologies; e.g. disease for monarch

**Comment by kltm** [comment]
Will want to make some clarifications tomorrow, but very likely an AmiGO item.

**Comment by kltm** [comment]
Yeah, almost certainly AmiGO. Moved to: geneontology/amigo#227.
