### ISSUE TITLE
Import an annotation set from a publication

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#181]
Comments on this solicited from Paul T, Pascale and @selewis 

We have many historic annotations, and some we know are problematic, and need fixed. As an alternative to chasing up an email trail to fix at source I propose the following.

In Noctua, the user can create/seed a new model from a publication. There are similarities in seeding from a process, but there are some differences in algorithm and crucially GOC workflow.

On selecting a PMID (either typing the number or possibly some pubmed browser), a new model will be created seeded with all original annotations from that PMID. The approach could be to dump the pile of individuals on the floor and leave it to the user to connect up, or to apply some heuristic to predict the correct connections (e.g. if there was a single P in the publication, assume all are part of this; or if a single C then all occur in this). The details here can be iteratively refined.

The crucial thing is this: this model now becomes the definitive source for that PMID. The annotations to this PMID can be masked from all submission GAFs after the model is switched to production state. The final GAF for a species will be made by concatenating (lossy) GAFs coming from noctua-models with non-masked submission GAF lines. This is expected to make things easier, e.g. for PAINT users, they can effectively correct things immediately.

This would be a transition stage to a point whereby we could be managing all our annotations, legacy and Lego, all in noctua-models. However, technically speaking we are not ready to store ~20k models per species (assuming a parent publication as a unit of work), not to mention non technical aspects of such a transition.

**Comment by kltm** [comment]
This would have to fit in with the larger pipeline then. For example, once seeded, the fact that this seeding happened would be stored (possibly as an annotation in the model metadata); when the models are loaded (or scanned), a filter set is created, which informs the later GAF filtering. This would only happen then for models that had reached a "production" state.
