### ISSUE TITLE
Gene vs gene product

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#186]
Devise a solution that will allow continued use of genes as referents (particularly MOD IDs) whilst retaining correct semantics.

**Comment by cmungall** [comment]
(technically this a bug in the data and not an enhancement but regardless..)

Some background.

Current IDs are massively undercommitted. Both with respect to a URI that is intended to be consumed in a semweb stack, and the ontological commitments of that URI. In some ways this gives us freedom to do as we please. But this is unsafe. Consider if we use a URI as if it were a protein class and somewhere else in our import chain it comes in as a gene class then we have a problem.

One safe solution would be to use PR class URIs. These have ontological commitments consistent with being the domain of enabled_by. One issue would be ensuring availability for all organisms but this is not really an issue, gene-level PR class URIs are constructed using the UniProt accession so we could do this deterministically. We *may* have to put some gloss in the UI as a sop to some MODs who want to see their own IDs there. Other than that this is largely a simple translation job on the GCRP files, @hdietze has code for this already. A similar solution would be easy for RNA central.

Alternatively we could formalize the existing situation, either relax the domain of enabled_by so it can chain over transcription (allowing the gene to be the subject), but this is ugly. Another path is to commit the MOD gene URIs to be a conceptual union of gene OR protein. I do not dislike this as much as when I first thought of it, but there are dangers in over-undercommitting (committing to a more general level than is intended)

**Comment by ukemi** [comment]
My two cents. The chains might be a better solution for global issues. We already have relations like RO:0002204, gene_product_of. Couldn't we use those kinds of relations express relationships between genes, transcripts and proteins to make straightforward chains? I think at the end of the day we are still going to have to take this route for the annotation extensions when we consider processes like gene expression, trnascription, splicing, translation and protein processing. I forsee that people are going to want to mix and match identifiers to describe these and eventually we will get back down to chains of the basic relations.

**Comment by cmungall** [comment]
We can do this, it adds a certain level of complexity or hackiness. 
Either the user has to choose the most appropriate relation (which was 
we know isn't a good idea) or the system is smart enough to choose it 
for them (not that smart really, it's just awkward)

**Comment by cmungall** [comment]
This ticket resolved with the introduction of https://github.com/geneontology/neo
