### ISSUE TITLE
Add a way to remove has_inputs without exploding view

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#187]
See the instance with
`has_input(MAP2K1)`

I'd like to remove the has_input (possibly to add a new one)

Clicking the green button gives me this:
![screen shot 2015-09-04 at 1 12 34 pm](https://cloud.githubusercontent.com/assets/50745/9693628/b6e2e040-5306-11e5-8a5c-7dcdbee69527.png)

I can explode the view and remove the link but this is suboptimal

Possibly related: the nomenclature "Add bundle" isn't really clear. There is possibly some vestige of when we were modeling enabledBy etc as class expressions. This is probably best discussed in person rather than in a ticket

**Comment by kltm** [comment]
Hm, yes. There used to be a method of destroying the folded items when they were still "part" of the individual, but after the all-individual-ification, they were moved out.

I think the easiest thing would be to allow them to be deleted from within the same display as they used to be; probably not too big a change, and would bring the interface back to something a little more intuitive.

It will be good to get more user feedback and watch them--not all operation can be supported in the main editor view, and we need to know where the best place to draw the line will be. Obviously, all of the most common operations should be supported, as well as the widely used macros.

**Comment by kltm** [comment]
Talked about this today, and implemented...maybe #248? Will mark this as a dupe for the place where it was implemented.
