### ISSUE TITLE
Global fix required for handling the fact that multiple genes share the same symbol

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#188]
It is impossible to select a desired gene from the class expression maker. See screenshot for why

![screen shot 2015-09-04 at 1 23 09 pm](https://cloud.githubusercontent.com/assets/50745/9693809/261a59f6-5308-11e5-9666-670cca78d473.png)

This is in part a duplicate of
https://github.com/geneontology/amigo/issues/132#issuecomment-60323490

But the solution for Noctua may not be identical to what we want for AmiGO. This should be analyzed as part of broader requirements. For example, in Noctua that majority of a time the user will have selected some particular context, e.g. a species. Autocomplete should generally restrict to this context (mostly for genes, but also to restrict ontologies chosen, or subsets within those ontologies). Ultimately I think only Minerva has the intelligence for this but @hdietze and @kltm do not like the idea of Minerva doing autocomplete... anyway

For now, a quick fix is using the same selector for bioentities that is used in the left panel. The difficulty is that the user may want either a class or a bioentity so the autocomplete has to be a union. The division is more amigo specific and doesn't belong here.

**Comment by kltm** [comment]
Hm. I think that a correctly designed schema (a lot of different similar AmiGO issues around this, like #131 and #102) would allow the dynamic addition and removal of filters. The species set for a model could be saved as annotations and used to hint the autocomplete (and be able to be removed if desired). All in all, I think a fix for AmiGO for some of these is a fix for Noctua here.

**Comment by kltm** [comment]
At this point, I believe functionally solved by NEO.
