### ISSUE TITLE
Bundle minerva JAR from branches into repository

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#193]
Bundle minerva JAR from branches into repository.

This has been very nice with AmiGO, making provenance, testing, and deployment easier.

Will require coordination with @hdietze.

**Comment by hdietze** [comment]
The relevant project is minerva-cli. This project includes both the server and all command-line methods.
The command-line now also properly reports version information via `--version`.

**Comment by kltm** [comment]
Thanks!
What's the entry point for the minerva server from the minerva-cli.jar?

**Comment by hdietze** [comment]
`java -cp ./minerva-cli.jar org.geneontology.minerva.server.StartUpTool`
