### ISSUE TITLE
Start using enriching minerva; update all models to "enriched" version

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#197]
@hdietze has completed a minerva that will "enrich" on save. We need to get this version into production and then update all the models into the enriched version.

Start by taking Noctua down?

**Comment by cmungall** [comment]
do it

**Comment by kltm** [comment]
Sorry, rhetorical question to mark where I am in the process.

**Comment by kltm** [comment]
Server restarted, all updated now.
