### ISSUE TITLE
Make GAF information obtainable from noctua annotation process

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#200]
This is intentionally a little vague right now.

The idea is for people to be able to make us of the annotations they make in noctua within their local pipeline. While it would be nice to have people get the model->GAF directly from the interface (as mentioned by @ukemi), that would not really scale for a whole bunch of reasons.

A better (and possibly complimentary) solution would be to periodically commit the GAF (or GAFs, grouped by contributors or something) of the models to a repo for download, filtering, whatever by downstream. This sounds like it building towards the repo model as discussed with @cmungall earlier, so we'd want to make sure we're compatible with that.

Any solution will involve @hdietze consolidating the model loader code and the current GAF output code. Also, the code would run outside the production minerva in some periodic Jenkins job, maybe on noctua-model commits.

**Comment by ukemi** [comment]
I'm not sure we need them directly from the interface, but should be able to get them from the export tab at the top of the opening page (maybe that is what you mean by the interface). Currently there are three choices under that page; OWL, GAF, and GPAD. The potential functionality is great, but the GAF format is lacking things like evidence codes and has orcid ids in it , etc. if we could download a tidy/complete GAF even in this way, it would be usable. Eventually we would probably be able to export multiple models based on annotators or groups.

**Comment by kltm** [comment]
Correct--the export tab is what I was talking about. And while that's fine for occasionally grabbing something, it's not really suitable as a primary method of getting data back to curators who are using GAFs, which I'm guessing you'd probably agree with?

**Comment by ukemi** [comment]
Absolutely I agree. The repository model would be best for automatically grabbing annotations for import. However, maybe just because I am a throwback to an earlier time and the visualization of complex models is difficult for me, I find it easy to look at a GAF to check my annotations. If they are all contained in one mega file, then it would be hard for me to just look at the ones I created for a specific model or gene or paper or.....

**Comment by kltm** [comment]
Fair enough. I think for everybody to be happy, we'll have to have both by the "release".

**Comment by cmungall** [comment]
Although it may not be obvious, this ticket #189 will make people very happy. Of course, some people just want a GAF as that's familiar, but a gene-centric inference view is what people really want

**Comment by ukemi** [comment]
Yup.

**Comment by kltm** [comment]
While this is still being tuned, this is part of the pipeline, not really an open question.
