### ISSUE TITLE
Add new initial tab to noctua landing page, needs to be explanation/user friendly

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#206]
Add a new initial tab to the noctua landing page that gives an overview of what noctua/minerva is/are, along with some training, videos, etc.

Possibly start by cribbing some stuff from the README.md.

**Comment by cmungall** [comment]
cc @selewis @thomaspd

**Comment by cmungall** [comment]
Curator docs: https://docs.google.com/document/d/18ihslb7prB6CWtu2yjF-pMHZBTY1-AdXJAu-ZyuyXS4/edit

**Comment by kltm** [comment]
Use a more general format for the landing--maybe markdown (consumed on compile).
