### ISSUE TITLE
Generalize the function companion to allow BPs and CCs

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#212]
Generalize the function companion to allow BPs and CCs.

To be filled in after further discussion with @thomaspd

**Comment by kltm** [comment]
Yes, this could use further clarification. Is this just to release restrictions on the current tool?

**Comment by thomaspd** [comment]
See the powerpoint mockup I emailed the other day.  We'd need a component-companion and a  process-companion as well.

**Comment by cmungall** [comment]
<img width="612" alt="screen shot 2015-10-30 at 3 22 15 pm" src="https://cloud.githubusercontent.com/assets/50745/10859357/09dd7e7e-7f1a-11e5-8ab4-672a3c69a2b2.png">
<img width="1134" alt="screen shot 2015-10-30 at 3 22 37 pm" src="https://cloud.githubusercontent.com/assets/50745/10859364/13d9592a-7f1a-11e5-99e1-51f755be030f.png">

**Comment by cmungall** [comment]
Generalized form:

Ancestor  | Relation
------------- | -------------
molecular_function  | Class_N enabled_by Entity_E
biological_process | molecular_function_MMM part-of Class_N, molecular_function_MMM enabled_by Entity_E
complex | Class-N has_part Entity_E
other component | molecular_function_MMM occurs_in Class_N, molecular_function_MMM enabled_by Entity_E

**Comment by kltm** [comment]
Couldn't we just allow multiple entities in the autocomplete, a la the current macromolecular complex companion?

**Comment by cmungall** [comment]
> Couldn't we just allow multiple entities in the autocomplete, a la the current macromolecular complex companion?

Not following...

**Comment by thomaspd** [comment]
This issue is the same as #224 so please merge these issues, and see my most recent comment with more detailed requirements
