### ISSUE TITLE
Make it easier to use gene product isoforms

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#213]
There are a few ways to approach this, this ticket deliberately left open for now.

Background:

Depending on evidence available, the object used to fill the 'enabled by' field may be at different levels of generality. For example, generic human Shh (i.e. any or all products of the Shh gene) vs specific isoforms of Shh.

In UniProt, isoforms are denoted using a dash-number suffix. In PRO, these are simply subclasses of the species-gene-level protein.

The discussion here is complicated by the fact that in Noctua we are currently allowing the use of a MOD 'gene' ID to stand in for the protein (genes do not have activity; it is their products that have activity).

Additional questions:

Are we concerned solely with isoforms here? What about phosphorylated forms etc? I assume these would be post-composed but this needs explicitly documented in advance.

Approach:

The simplest approach is to load all isoforms into Golr in advance, and allow the curator to choose the appropriate object for the enabled by field. But what should be the source? UniProt, PR or both? The ready-made ontology translation in PR simplifies some things, but introduces complications, due to the fact that PR precomposes various other kinds of modified forms leading to an explosion of classes.

Even with this simple approach we need curation guidelines. For a MOD, do they continue to use a MOD gene ID for the generic form, and only use an isoform ID if it there is evidence that function is unique to an isoform?

GAF translation:

the approach here affects GAF and GPAD translation. In GPAD the annotation is always to isoform. in GAF there are two fields.

**Comment by cmungall** [comment]
Blocked on: https://github.com/geneontology/neo/issues/2

**Comment by kltm** [comment]
@cmungall It looks like upstream was cleared; is there additional action here besides a reload?

**Comment by cmungall** [comment]
We're good here. For a description of what isoforms are available see the [NEO README.md](https://github.com/geneontology/neo/blob/master/README.md)
