### ISSUE TITLE
All RNA as enablers

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#214]
All RNA as enablers.

May just be a matter of translating RNAcentral to obo/owl and loading into Golr

However, see #213 for some subtleties.

**Comment by kltm** [comment]
@cmungall, could you clarify this a bit--I'm not quite seeing the direct action to take.

**Comment by cmungall** [comment]
Blocked on:
https://github.com/geneontology/neo/issues/1

**Comment by kltm** [comment]
@cmungall Was this cleared upstream?
