### ISSUE TITLE
Allow Function Companion to Accept Lists of Genes/Gene Products

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#216]
Hi,

Following on from the LEGO call of 2015-11-02, having the ability to enter lists of genes/gene products in the Function Companion would be an efficient way to seed models.

Thanks,
--Kimberly

**Comment by kltm** [comment]
@vanaukenk , have you taken a look at the current functionality presented? 

My recollection from the meeting was that we might want to extend the function companion functionality to the command line tool for testing, and it the behaviour was desirable (compared to other types of seeding), we would add that as a new seeding method off of the front page.

The way the plugin architecture works, your formulation is not possible.

**Comment by cmungall** [comment]
Not quite

 1. I have a gene product in mind, and I want to create a new annoton (or update an existing one?) use existing annotations for that G
 2. I have a small set of specific gene products in mind, I want them all to appear in my model, and I want to select existing annotations
 3. I have a mid to large set of gene products, perhaps I know in advance they are all involved in a developmental process I want to model a pathway of. I want the system to make a best guess at the entire model

The existing companion does 1, and #212 describes an alternate way. Seeding does 3.

@vanaukenk may want to do 2 or 3 at this time, but 2 may still represent a distinct use case.

Doing 2 via iterations over 1 may be quite efficient if #212 is implemented.

We may ultimately want a certain level of blending. E.g. for seeding we can imagine an intermediate matrix being shown, with genes as rows and (f,c) pairs as columns, with the best-guesses being initially checked. This starts to look like the companion on steroids.

**Comment by kltm** [comment]
True, but it's still not as described: Function Companion cannot take a list (would need a different UI) and we were going to work on the behaviour with the CLI. Skipping the second bit is fine if that's the known desired behaviour from the get-go, but the first just is. I'm mostly trying to reformulate this ticket into more concrete action (there has been some fuzzier items recently and I'm trying to avoid that).

**Comment by vanaukenk** [comment]
Hi @kltm and @cmungall 
I tried the function companion this morning and have successfully seeded a new model, Anchor Cell Invasion, with some function annotons, one-by-one (1 above).
I was initially interested in 2 as a distinct use case, but think that the blending idea is really interesting to explore as a way of pruning what is actually imported into a model.  In fact, I am particularly interested in the (f,c) pairs as a way of specifying particular combinations for developmental processes.  This would be aided by including AE values for C such as tissue type and life/developmental stage, but one step at a time.....

**Comment by kltm** [comment]
Okay, great! It might be easier to fully specify in a separate planning session (can you make this Friday?) then on the tracker. Once we have a concrete plan, I can then break it up into tracker tasks.

**Comment by vanaukenk** [comment]
@kltm 
Yes, I am planning to be on the call on Friday, so would be happy to flesh things out more then.

**Comment by vanaukenk** [comment]
We no longer use the Function Companion, but this ticket could be revisited in the context of improving overall workflows.
