### ISSUE TITLE
Error message when creating a function annoton

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#219]
Hi,
I'm getting the following error message when trying to create an annoton this morning:

Error (error): Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Could not retrieve a class for id: WB:WBGene00001674; your operation was likely not performed.
org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException: Could not retrieve a class for id: WB:WBGene00001674

This happens for multiple WB genes when I try to add a free form function.

Thanks,
--Kimberly

**Comment by kltm** [comment]
Duplicated, use "gpe-12".

**Comment by kltm** [comment]
@vanaukenk 
With some legwork from @hdietze, the application has been redeployed and should now work as expected.

**Comment by cmungall** [comment]
How was this resolved?

**Comment by vanaukenk** [comment]
Hi @ktlm,

All seems to be working fine this morning.
Thanks for the fix.

--K.

**Comment by kltm** [comment]
@cmungall from the tracker tags:
https://github.com/geneontology/noctua/issues/219#ref-commit-1413d8c
https://github.com/geneontology/minerva/commit/1413d8c06a4d47a8c6abda1191877552576ff4ca
