### ISSUE TITLE
Create embeddable widget or thumbnail for other databases to embed

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#221]
Attached is a super-fake mockup of how a page like http://flybase.org/reports/FBgn0000490.html may be enhanced with a noctua thumbnail. The example is fake (gene is dpp, but dpp doesn't appear in the example model)

![screen shot 2015-11-20 at 1 03 51 pm](https://cloud.githubusercontent.com/assets/50745/11311856/7132ddc6-8f87-11e5-94d1-5646494ce7f4.png)

Is this the right approach?

Some genes may be in multiple models. What do we do here?

If there are no models for the gene, we could also show models 'one hop along' - e.g. to an ortholog, to an interacting gene...

Gene pages would have highest impact, but we of course could have BP pages. Most groups don't do this though, and just like to amigo, where we would have the models on a per GO-term basis.

**Comment by kltm** [comment]
Some points for consideration:

* any ability here will be predicated on loading models into a GOlr index; easy to do, but we're not doing it yet and minerva cannot support being a general access point. this could be done at the epione level, but it's probably best handled with the OWLTools loader
* this functionality almost already exists as the cytoscape-based workbenches and AmiGO cytoview
* I'm not sure the full graph editor view is the way to go here, especially as it is very heavy and finicky; again, variations and expansions of cytoview might work better (to be seen)
* another question is who hosts this
** embedders download a JS file and use it in their pages, along with a little JS to make the view
** embedders get the JS from a CDN which we can update
** both of these have their pros and cons, but I think the first may be more tenable, with the serious downside that the API would have to be functionally frozen :(
** another tack would be an embedded image service a la amigo's embeddable visualize, which might give us the best balance--simple API for embedders and control of API and code changes upstream.

**Comment by cmungall** [comment]
embedded image: if we went this route we would probably want imagemaps, with genes going to right page etc

**Comment by kltm** [comment]
It will almost certainly be images; not sure if the package I'm thinking
of supports imagemaps, will check.

**Comment by kltm** [comment]
To add to the above list of possible methods, we could also have the client sites use JS as we do. This would allow for better API freezing (although we don't version GOlr itself, so hm) through npm, at the cost of putting more effort at their end.

Further considering image generation, it would probably have to be a service that passed over the current contents of the index and added/updated the images where model information was found.

**Comment by kltm** [comment]
With discussion by @vanaukenk and others, it looks like the system is now in place to deliver data (via AmiGO) and manage/parse it (via the usual JS request, response, and manager libraries). It seems likely that the heavy lifting, at least initially, may be done by consumers. But we may fold any useful patterns back into this upstream code.
