### ISSUE TITLE
Restrict selection of GO terms to exclude overly composed terms

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#222]
Two parts
1. Create an "anti-slim"
2. Restrict users from selecting these

Step 1 could be iterative. For testing we can just use the do_not_annotate subset. We can then extend this with e.g. TG-created terms.

**Comment by kltm** [comment]
I assume that this could be taken care of at the NEO level now? Would another field be needed (more general solution) or could they just be dropped (narrow use of NEO as just an autocomplete service).

**Comment by cmungall** [comment]
Not related to NEO: this is purely a slim of GO

**Comment by cmungall** [comment]
Additional comment: at LEGO meeting we discussed using Regulation-of-X as the first set of terms in the anti-slim. But this is awkward for things like Alan's regulation of dauer entry example. TBD

**Comment by vanaukenk** [comment]
@cmungall @kltm 
Is this something we still want to pursue?  I agree these terms aren't suitable for a GO-CAM model, but perhaps a better approach would be to obsolete them in the ontology?
Can we close this ticket?
Thx.

**Comment by ukemi** [comment]
I would propose importing the annotations correctly into the decomposed expressions and then obsoleting.

**Comment by vanaukenk** [comment]
Closing, no longer relevant.
