### ISSUE TITLE
Test noctua for latency issues when connecting from remote site

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#226]
@pgaudet may be able to help us test for any .ch->USA latency issues prior to the meeting. Do we have a script to follow?

**Comment by kltm** [comment]
Honestly, this can/should be done via #53, using #227. While it would be good to get a feel from somebody on the ground before this is finished, this should be deployable on a remote cloud and tested/timed headless without needing people.

**Comment by kltm** [comment]
@pgaudet, if you find the latency from your end acceptable, please let us know. Our other choices are to run something on AWS out of Frankfurt or locally on a machine at the site.

**Comment by kltm** [comment]
I've tested using my VPN provider from somewhere in Switzerland, and noticed nothing wildly different. I'll continue to get the automated deployment working (#227), but give it a lower priority, and do it with an eye as a failover in case something goes /really/ wrong at the meeting.
