### ISSUE TITLE
Build turnkey system for deploying Noctua stack

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#227]
Build turnkey system for deploying Noctua stack. It should be able to be done with few commands and minimal configuration, with the following configurable:

* noctua-models, public or scratch
* golr lookup location
* optional seeding golr lookup (public default?)

Should have both embedded epione/golr for quick lookups and fronted by a proxying webserver so that all traffic and interaction can take place on port 80.
Likely related to #209 and #226.

**Comment by kltm** [comment]
Exploring why supervisor is not great at killing noctua stack jobs (maybe of interest to @cmungall from previous conversations), it seem that the more serious group kill stuff was introduced relatively recently. Unfortunately, the ubuntu package rather lags behind here, meaning that this might be better once the new LTS comes out in April. (3.0a8 vs. 3.0b1 vs. 3.2)

**Comment by kltm** [comment]
It should be noted that trivial deployment gets a lot easier with switch to Solr 6.x  (berkeleybop/bbop-js#16) and running the Solr server as embedded runnable in gulp.

**Comment by kltm** [comment]
tagging on @nakao

**Comment by kltm** [comment]
@nakao there is some starting work for this item in /deployment/

**Comment by kltm** [comment]
As this has a huuuge amount of overlap with the similar amigo items, I'm moving the work files over to the working directory at https://github.com/berkeleybop/ansible-machine-bootstrap; after completion, it will either be bumped to the geneontology org, or into the component repos. This ticket will remain open get tagged with relevant work.

**Comment by kltm** [comment]
I'm switching over to the 16.04 Ubuntu image as the base due to java8 requirements (repo management).
Because of this, a prerequisite step will be installing python(2.7) with:

```
apt-get -u install python
```

**Comment by kltm** [comment]
@nakao Now have a slightly specialized docker playbook for noctua that uses the same tasks as the aws one. I'm going to finish creating the aws builder and circle back around to the docker part later. If you wanted, you might be able to figure out some of the remaining permissions/path issues with the ansible-in-docker setup; it doesn't matter who the user is since it's a disposable image at this point.

**Comment by kltm** [comment]
With the last commit, it seems that noctua installs reasonably well, ignoring the amigo golr install (will need to debug as we go).

**Comment by kltm** [comment]
Note that this is only for AWS. More work needs to be done for Docker.

**Comment by cmungall** [comment]
Regarding Docker, what @lpalbou did here seems like a good start: #603

**Comment by goodb** [comment]
I think it would be worth spending some time on this and suggest adding configurations for the ontology stack to use as well as simplifying the authentication system.  Based on feedback from my presentations I think there are a lot of groups out there that might want to run their own stack.  (Specifically spoke to people in Larry Hunter's group, NIH, and somewhere else I can't remember that all wanted the same thing.) Would be best case scenario if that happened and we actually got contributions back from their developers.  

It doesn't appear at this point to be too far away, but there are a few rough edges to polish up.
