### ISSUE TITLE
Add support for filling in a model title

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#228]
I think it helps to breakdown into two broad categories of model
1. A big-picture complete model of a GO biological process for a species or clade
2. 'fragmentary' models or paper-based

For 1, I think a simple "Process, Species" notation is good.
For 2, how about naming it after the core paper? E.g. name, title, year. This may be a review or the most recent paper used.

Once we have decided on an SOP for model naming, we may decide to add tool support to assist with this. We may even choose to downplay the user title and enforce capture of relevant metadata and use that to generate titles.

Minimally we way to just have some kind of way of forcing people to use a minimal length of characters? Just to avoid 50 "My Models".

**Comment by kltm** [comment]
It might be an automated default, with the option of switching it to "My Awesome Model"; I suspect that some of the auto-generated titles would not map cleanly to what modellers have in mind.

At least, there could be suggests text around any title input.

**Comment by kltm** [comment]
Given that we will have better and specific searching, and the user request for #342 , I think we can put this by the wayside for now.
