### ISSUE TITLE
C. elegans gene names have lost their '-' in the autocomplete

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#230]
Hi,

Just trying to enter some new individuals and see that C. elegans gene names have lost their dash, e.g. nlp-31 -> nlp31.
Can this be fixed?

Thanks,
--K.

**Comment by kltm** [comment]
@cmungall I'm guessing this is a NEO issue?

**Comment by cmungall** [comment]
Will be fixed next load of neo. For now just work-around it, sorry. Don't worry, the underlying store will use the IDs.

**Comment by vanaukenk** [comment]
Okay, thx.  As long as I know, for now I'll just search without them.  No worries.

**Comment by vanaukenk** [comment]
Hi,
This seems to be fixed now, so I'm closing the issue.  
Thanks,
--Kimberly
