### ISSUE TITLE
Noctua should support some version of model copying

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#231]
A common pattern will be that somebody wants to copy a model. This will take several forms, such as:
- using a model as a base template for further work
- "extending" a model to be more specific or generic
- "referencing" a model

While it may take time to encompass all of these as an initial effort, we would like to have: the ability to "seed" a new model with the structure of an existing model, along with model or individual level references to the original model (model/individual ids plus either time or version stamps). It is likely that this can pretty much be done completely at the client level (scan model, request something just like it while adding stamps), and gives a space for further exploration.

**Comment by kltm** [comment]
Related to #39 (concrete implementation of part).

**Comment by cmungall** [comment]
Template use case described in #245

**Comment by kltm** [comment]
Will use this as a work ticket for a light prototype implementation from the templates discussion: http://wiki.geneontology.org/index.php/LEGO_December_21,_2015 .

**Comment by kltm** [comment]
For templates, we'll need some kind of way of getting the manager mostly "off" in the interface, but still allow for queries and annotation changes (to get template mode off again).

**Comment by kltm** [comment]
Sorry, pushed out another update after this and accidentally reverted the config. Could you look again (refresh browser) and see if that's correct now.

**Comment by kltm** [comment]
This should complete backend and interface threading issues.
Next, we need to provide a stable way of bringing in the templates in question, via a workbench.

**Comment by kltm** [comment]
@balhoff @cmungall 
Another part that we'll need for this from Minerva is where a model was derived from, supplied from the client. I'm not sure if this was added/planned already, but I'm guessing something like dc source? This could probably be temporarily punted, but I can see a lot use cases for this moving forward, especially with work reporting.

**Comment by kltm** [comment]
This came up again during the GO meeting. In addition to the issues above about derivation, there is also the additional wrinkle of what to do with groups (#350)--both from the source and target models.

**Comment by lreiser** [comment]
Operating on a suggestion to add this here...
When models  are imported into Noctua through the function companion, the model author defaults to the user who has imported the model and the creator of the original model is lost.  It would be good to be able to have some from of provenance tracking of these model components. In the case of TAIR our in house annotations are publicly associated with a generic curator (although we do have the specific IDs in our database). We also have annotations that are supplied by our community (who may or may not have ORCIDs). 

Is there a unique identifier for an annotation in GO that could be used as a reference?

**Comment by kltm** [comment]
I think that's mostly covered here (https://github.com/geneontology/noctua/issues/231#issuecomment-246869867). The issue is not so much getting at the data, but making sure that this type of information has a consistent place to land across different use cases (e.g. model copying, annotation import, etc.). We currently track "modifying user" and "user group/hat" as "contributor" and "provided-by" respectively; this is why we were thinking about using "dc:source" as a possible place to put this type of information, but we just want to think through all of possibilities and combinations. For example, when copying a model, do we want to reference the just model, or the model and all of the contributors? What dublin core category would those be? Etc.

**Comment by kltm** [comment]
Note conversation with @cmungall here
https://github.com/geneontology/noctua/issues/459#issuecomment-333378084
that implies we will not need dc:source for now.

**Comment by tmushayahama** [comment]
@suzialeksander for SAE, the issue will be here https://github.com/geneontology/simple-annoton-editor/issues/5 ,last comment with steps

**Comment by kltm** [comment]
@tmushayahama @suzialeksander Is this for annoton copying (both interfaces have this) or model-level copying (which is what I assume you're asking)? For the latter, there is no current mechanism and some of the implementation details are being discussed.

**Comment by tmushayahama** [comment]
@kltm  model-level copying. SAE doesn't copy as such, it kinda just populate the form with values and a user has to manually click save. This is because SAE cannot edit. More info on this comment https://github.com/geneontology/simple-annoton-editor/issues/5#issuecomment-377393844

**Comment by kltm** [comment]
@tmushayahama The scope of this ticket is model-level copying.
Model-level copying will either be handled by clients/libs playing a model forward into minerva and having minerva resolve all of the new IDs or having a command for minerva to do this internally.

**Comment by suzialeksander** [comment]
@ktlm, yes, I was asking about model level.  Our group wants to try and start with the same model, but edit it without interfering with each other- basically, we want to make branches (forks?) of the same model.  Not necessarily merge them (that would take discussion and manually editing makes sense).  

I'm pretty sure I should interpret this as a no, for now.
Thanks

**Comment by kltm** [comment]
@suzialeksander My apologies, especially since this is an old request, but there is nothing for you all at the moment.
This should be a top priority as Noctua development ramps up again.

**Comment by lpalbou** [comment]
Closing in favor of new ticket: https://github.com/geneontology/noctua/issues/606
