### ISSUE TITLE
Make obsoletion obvious or hidden on autocomplete

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#241]
This is a subset of:
https://github.com/geneontology/amigo/issues/230

**Comment by kltm** [comment]
Which autocomplete? For the way a lot of the term ones works now, we'd have to add obsoletion data to the annotation doc.

**Comment by cmungall** [comment]
should be ubiquitous for ontology_class (which is the only document type with the required field)

**Comment by kltm** [comment]
Yes, we can add that; but keep in mind that most term ACs don't have that in noctua right now--they are driven off of the annotation documents and do not currently have that information (I assume that obsolete annotations are not loaded?).

**Comment by cmungall** [comment]
Not following. Surely all the ACs in Noctua are driven off ontology_class documents. It's only the workbenches that make use of annotation documents, e.g. to search for existing annotations in the main GO

**Comment by kltm** [comment]
No, many are driven off of the annotation documents, which causes all sorts of various problems (documented here and there in the tracker); however, it does allow us to do various kinds of locking on bioentities, which was considered the driving requirement in many locations.

**Comment by cmungall** [comment]
This came up again at the noctua workshop, just noting here.

(and there should be a single autocomplete source at the moment)

**Comment by kltm** [comment]
Well, to clarify, there is a single GOlr core being used. However, the data in that core (general vs. ontology_class, etc.) is variously used in the interface.

**Comment by cmungall** [comment]
AC works off general, which unfortunately has no metadata about obsoletion. We could always hack and filter based on string...

**Comment by kltm** [comment]
Currently, the autocomplete works off of different document_types depending on the input.

**Comment by cmungall** [comment]
Actually we must be using ontology_class for the ACs other than add-individual, if they are constrained?

**Comment by cmungall** [comment]
OK, I think this whole thing is fixed by using ontology_class universally. I assume the fact that add-individual is hooked into general is due to back before we had a uniform golr, and we were needed to interrogate general to get gene products from a convential amigo-golr instance.

This would presumably address the oddity we were looking at earlier today with the rice genes too

**Comment by vanaukenk** [comment]
It doesn't look like obsolete terms are available in the Noctua autocompletes.  Closing this for now.
