### ISSUE TITLE
bug in term suggestions for process search

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#242]
![bug1](https://cloud.githubusercontent.com/assets/7359272/11656369/94b39cee-9dac-11e5-9433-5ca69c493876.jpg)

**Comment by ValWood** [comment]
Above I was searching on "G2/M transition"
Some suggestions are duplicated.
Some are unrelated (the top ones).
I was expecting to see
"G2/M transition of mitotic cell cycle" (not shown)

**Comment by kltm** [comment]
#168 #48 -- hard to explain, but this is both a feature and a bug. If you use "free form" instead of restrict, I believe this will not happen.

**Comment by kltm** [comment]
Essentially, you are completing on annotations, not ontology terms.

**Comment by ValWood** [comment]
Yep David explained this....
