### ISSUE TITLE
All autocomplete fields should support URI fragments/local IDs

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#243]
Every autocomplete field should allow search using the local part (post-prefix part) of the identifier. This should be for all fields but is particularly important for any box in which an enabler entity (enabled_by, add-individual, add-type). A common use case is trying to find a gene by an "identifier" like WBGene00019198, and noctua users not steeped in GO identifier understanding may not know the magic prefix is "WB"

Note that these "identifiers" can not be assumed to be unique, since they are divorced of their prefix. But this doesn't matter for autocomplete. This is particularly true for OBO IDs, in which the local part is purely numeric. But this doesn't matter.

Could presumably be implemented either by tokenization on ':' within solr, or simply by adding a new indexable token by splitting on ':' at owltools golr population time

Reported here, presumably the fix is universal
https://github.com/geneontology/amigo/issues/120

**Comment by krchristie** [comment]
I would really like to be able to paste in complete IDs with prefixes and not have to wait for the autocomplete to search for that item. I'd be fine with needing to press return or tab or in some way indicate that I'm done with that box. I'd like it work more like Protein2GO which also has an autocomplete in the GO term selection, but if I just paste in the ID I want and go to another box, it will accept what I pasted in without telling me I haven't selected something from the autocomplete.

I often search for my terms using another tool, and find it quite slow to have to wait for the autocomplete suggestions to find my term when I already know what I want.

thanks,

Karen

**Comment by kltm** [comment]
AS well #401 .
