### ISSUE TITLE
Ability to clone evidence off of evidence currently found in model

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#245]
There is a common use case where users want the ability to clone evidence. After some talking, a probably good implementation would be being able to select evidence currently found in the model.

**Comment by cmungall** [comment]
One option is simply to reuse the same evidence individual. But I think it better to copy.

Note that this should be a shallow copy, not a deep copy. Before #141 these options are equivalent (as the restriction to literals makes the tree depth=1 maximum).

After we switch from literals the individuals for entities referenced in the evidence individual, then the reference is copied.

For example

Given a source
```
ev001 rdf:type ECO:0001234
ev001 dc:source pmid:123456
ev001 rdfs:comment "this is a literal"
```



the copy would be

```
ev002 rdf:type ECO:0001234
ev002 dc:source pmid:123456
ev002 rdfs:comment "this is a literal"
```
With no attempt to make a new pmid. Modifying the comment for ev002 will not affect ev001, nor will changing the reference to a publication. But changing the title of pmid:123456 will obviously be visible in both evidences 1 and 2

**Comment by kltm** [comment]
Anyways, I've got something basic in there now. I'll get feedback from @ukemi when I get a chance, but there is unlikely any time before the meeting. We'll see.

**Comment by cmungall** [comment]
Do we have unit tests for the logic, as described above?

**Comment by kltm** [comment]
This is all UI code, although more could be pushed down into bbop-graph-noctua (actually, should--there are a lot of patterns for evidence that should be captured). There is really not much at all for UI unut tests.

The copy is quite transparent in the code though, pull class_expression, sources, and withs, apply them elsewhere.

**Comment by vanaukenk** [comment]
For evidence cloning, it would be very helpful to have some basic bibliographic information listed next to the PMIDs listed in the table for evidence selection.  If there are multiple papers associated with a model, it will be difficult for curators to keep track of papers just from the PMID.
It'd be great to show (from the PubMed XML):
Title - <ArticleTitle>
Authors - <AuthorList>
Journal - <MedlineTA>
Publication Date - <PubDate>
Thx.

**Comment by kltm** [comment]
@vanaukenk You should go ahead and add a separate enhancement ticket for this (this addition is unrelated to the cloning itself).

**Comment by vanaukenk** [comment]
Okay, the additional bibliographic info request is now housed in this issue:

https://github.com/geneontology/noctua/issues/308

Thx.
