### ISSUE TITLE
Add ability for user to control reasoning

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#246]
In response to https://github.com/geneontology/minerva/issues/28

What if the user had control, like in Protege? Explicit options such as "select reasoner", "switch reasoner on/off" and "synchronize reasoner"

Rather than per-user this would typically be per-open-model (which results to the same thing whenever no model has more than one simultaneous user)

Selecting the reasoner could be dangerous. E.g. we want to prohibit non-SLME versions of HermiT. But just giving even a simple on/off gives the user the ability to control whether they sacrifice some latency for seeing inferred types and getting direct immediate reports on inconsistencies (as opposed to downstream, in jenkins)

cc @hdietze

**Comment by kltm** [comment]
I think this would be rather odd, especially as users could have different models open, and different models could have multiple users. Ideally, the reasoner wouldn't slow things down, or would at least be well behaved. As well, given our "best effort" attitude, I'm trying to imagine what switching the reasoner on/off would do when you had requests in the queue, etc.--wouldn't that be rather hard to deal with?

**Comment by cmungall** [comment]
The option would be per-model (just like it's per-ontology in Protege).

I don't *think* that there is much overhead involved in the initial switching things on, at least when using the SLME approach. AFACIT the module is created fresh each time and the reasoner is not incremental.

**Comment by kltm** [comment]
This is upcoming with a fix from @hdietze. The response will always have an "is-reasoned" bool and the request an optional "use-reasoner" request arguments (that takes strings "true" and "false", defaulting to false).

**Comment by kltm** [comment]
After some pondering, I think that I'm going to /not/ worry about the barista aspects. If users get confused, we can set a more complicated set of client rules.

Got some testing in; the remaining issues look like:
* need to ensure that the reasoner environmental variable is passed to widgetry.js
* when the user gets a reasoned response, their button should click over (i.e. once a user starts using the reasoner, it tends to propagate)--I believe this makes the most sense
* (likely a separate issues) the reasoned results are no longer displaying--this probably broke sometime during the meeting; if it's less-than-trivial to fix, I'll move it to a separate issue

**Comment by kltm** [comment]
In the commit notes, but it needs to be repeated: it is setup now so that other clients will only detect the reasoning when an action occurs--users can individually view reasoned results with no consequences for other users.

The last few commits cover us for 2 and 4.

**Comment by kltm** [comment]
Some local testing between clients, and I'm now satisfied that it works reasonably well in a reasonably intuitive way. Thanks to the work from @hdietze, it looks like we're good.
