### ISSUE TITLE
Add a complex companion

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#247]
The UI could be almost identical to the function companion, but it may be desirable to make some changes. The user would start by selecting an existing GO protein complex term `C` and a species. This could be via autocomplete, or a UI like the function companion where existing gene associations could be selected.

On completion, we would create a new individual `Ci` where `Ci` is an instance of `C`.

For each gene association `<G C>` (where G is in the species, and is either all the genes associated with that complex or a selected subset), we would generate an individual `Gi` and an edge `Ci has_part Gi`

This could be seen as a subset of #212 by generalizing the function companion to components and using a `has part` relation instead of `enabled by`

**Comment by cmungall** [comment]
cc @ValWood to receive further notifications on this ticket

**Comment by cmungall** [comment]
cc @RLovering

**Comment by vanaukenk** [comment]
This now exists in the Visual Pathway Editor.
