### ISSUE TITLE
Add ability to use negation/complementOf for types

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#249]
It should be possible to add

```
i type ComplementOf(C)
```

Any place it's already possible to do

```
i type C
```

Could be done visually using checkbox next to the autocomplete for any class or filler.

bbop-class-expression already supports ComplementOf, assume Minerva already implements, have not tested

(note: negating an edge should be a separate ticket, this involves possible changes to minerva)

**Comment by kltm** [comment]
...is this not pretty much #218? I understand that we're talking type and not relation, but from user user perspective, it should be pretty uniform. A more or less ubiquitous "not" check might work, but how often is this practically done? I worry that this might be something that takes a bit of effort and real estate, but is rarely used. Do you think a bang before or after in inputs be acceptable?

**Comment by cmungall** [comment]
> ...is this not pretty much #218

Nope, 218 refers to [NegativePropertyAssertions](http://www.w3.org/TR/owl2-primer/#Object_Properties)

This ticket refers to [ComplementOf](http://www.w3.org/TR/owl2-primer/#Complex_Classes)

 * ```NOT(jim owns fido)```
 * ```jim own fido. fido type ComplementOf(dog)``

**Comment by cmungall** [comment]
I'm going to close this to consolidate in #218, we'll punt on ComplementOf for now
