### ISSUE TITLE
Add ability to add additional someValuesFrom type expressions for an instance

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#25]
Example:

User has created an instance of a molecular function. The interface allows them to add two additional SomeValuesFrom class expressions,

 * occurs_in some L
 * enabled_by some M

The user would like add arbitrary additional someValuesFrom expressions

 * R some Y

Particular example:

 * has_direct_input some GeneProduct123

But any relation from the RO can be used.

This could be at the time of initial box creation, or a post-create edit on the box

**Comment by kltm** [comment]
This is now a sub-issue of #108.
