### ISSUE TITLE
Exports should be run through server and not client callbacks (will enable usable stable URL)

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#251]
Makes it easier to paste a URL into Protege

**Comment by kltm** [comment]
Chris's example:
```
Export OWL option should resolve to a stable URL
```

**Comment by kltm** [comment]
Long-term, that would be good for quick dev and play, but I'd think that this should all either be flushed quicker to git or delivered through amigo. Short-term, yes, the system in there is a bit embarrassing and a product of how some of the very early comms worked.

**Comment by kltm** [comment]
In an ideal future, most users will get downloads, etc, either from amigo or github--minerva should not be a file server. That said, for now for our early stage and few models and users, we can work with this.
