### ISSUE TITLE
Explore possibility of extending core species in neo with minimal metadata classes with a wider set of species

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#256]
We don't want to load too many species into neo: minerva slow down, overloading of autocomplete.

A SIB requirement is to have a wide range of species. But all they care about is entering an identifier.

One possibility is to have super-minimal classes in neo:

```
[Term]
id: UniProtKB:P123456
is_a: CHEBI:23367 ! molecular entity

[Term]
id : ...
```

If autocomplete works with IDs then these will be valid classes to be entered.

**Comment by cmungall** [comment]
@hdietze and me can do a test

**Comment by kltm** [comment]
@cmungall Is this still relevant?

**Comment by cmungall** [comment]
subsumed by the annotate anything in uniprot ticket
