### ISSUE TITLE
Manager error messages this morning

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#258]
Hi,

I'm working on a generic insulin receptor signaling pathway model this morning and all was going great until about 30 minutes, and 8 individuals, ago when I started getting the manager error message:

There was a manager error (error): message and message_type must always exist

Hard reload gets me out of the Relax message, but I'd like to save the latest additions, if possible.   My model still has the asterisk next to it in my browser. 

Here's the model:
http://noctua.berkeleybop.org/editor/graph/gomodel:5667fdd400000696

Way fun working on these templates....

Thanks,
--K.

**Comment by kltm** [comment]
@vanaukenk I've gone ahead and saved this manually. Just ping me manually if more saving needs to be done (or open a ticket like here).

This is a duplicate of #151.
