### ISSUE TITLE
Replace all current autocompletes with new super-widget

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#261]
All current ad hoc autocomplete widgets should be replace with a single

The widget should be flexible and driven from bbop-rest-managers. The requirements are essentially the union of all open autocomplete tickets (e.g. #257 #243, #241, etc.), plus:
- a check appearing when minimal acceptable input is achieved.

This will also greatly improve the readability and flexibility of the various noctua clients.

Either working from @jnguyenx 's code or basing from it.

**Comment by cmungall** [comment]
Additionally:

if a model is annotated to be relevant to a taxon T, the autocomplete should use `in taxon` axioms in the ontology to restrict or prioritize autocompletes.

**Comment by kltm** [comment]
As well, look at notes from #401.

**Comment by vanaukenk** [comment]
For information only or actually prioritizing/restricting autocomplete values based on taxon, see: 
https://github.com/geneontology/go-ontology/issues/19759

**Comment by vanaukenk** [comment]
Closing this for now, as I think we have addressed many of the outstanding autocomplete issues and anything remaining has been covered in newer tickets.

**Comment by kltm** [comment]
@vanaukenk I'd note that this is something a little different: this is about getting ubiquitous standardized AC in place with a generalized widget that can work across frameworks. It may be that we want to shelve that, but I think it's distinct.
