### ISSUE TITLE
Cannot render with editor's (fully folded) view

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#264]
Some models (so far only @ValWood 's gomodel:5667fdd400000125) do not render in editor's (fully folded) view., leaving only a blank. They render when unfolded.

This is very strange as 1) no errors are apparent in the debuggers I've looked at so far and 2) the nodes are recognized by other parts of the system (meta-info). Very very odd.

**Comment by cmungall** [comment]
is this UI, or to do with graph folding? If the latter, perhaps a unit test could be constructed?

**Comment by kltm** [comment]
AFAICT, this is purely UI rendering (I finally have a lead--there should be a fix soon). The unit tests for graph and folding are pretty complete.
