### ISSUE TITLE
Macromolecular complex creator is creating edges the wrong way round

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#265]
Complexes are bigger than proteins

It's always

    small thing part-of big thing

Or, on the individual level, the equivalent

    big thing has-part small thing

they currently have this inverted (unfolded):

<img width="502" alt="screen shot 2015-12-21 at 6 50 38 pm" src="https://cloud.githubusercontent.com/assets/50745/11946883/4b0a0caa-a814-11e5-976d-a6c30247254b.png">

strangely the folded view looks fine:

<img width="249" alt="screen shot 2015-12-21 at 6 48 58 pm" src="https://cloud.githubusercontent.com/assets/50745/11946875/3325c516-a814-11e5-93ea-e225f397aea1.png">

which means the code that generates the class-expression like labels is also inverted

**Comment by cmungall** [comment]
I made this one using the superjudonoodle, this is correct:

<img width="528" alt="screen shot 2015-12-21 at 6 56 56 pm" src="https://cloud.githubusercontent.com/assets/50745/11946915/b123ae10-a814-11e5-9b62-3408f4fa4aa0.png">

**Comment by cmungall** [comment]
kind of surface issue, kind of totally hoses reasoning (which is off...)

**Comment by kltm** [comment]
Sorry--that's what I get for late nights. Probably was used to looking at the part_of.

**Comment by kltm** [comment]
Yes, I seem to have been focused on the final product, so didn't notice the two reversals. I think I had it in my head that a "reverse" folding was needed, so added that, the rest being what was needed to make the final display "correct". Have a fix coming for both, along with a couple of bugs caught along the way.

**Comment by kltm** [comment]
The fix should be in, although anything that was created with the creator now will look funny (e.g. Scratch / gomodel:55ad81df00000001 ).

Nothing to do with class expression creation, just folding order plus reversed edges on creation.

**Comment by cmungall** [comment]
Looks good:

<img width="309" alt="screen shot 2015-12-22 at 9 29 11 am" src="https://cloud.githubusercontent.com/assets/50745/11961603/7d0644a6-a88e-11e5-8771-2ef3b81a11ec.png">

Broken:

<img width="226" alt="screen shot 2015-12-22 at 9 29 55 am" src="https://cloud.githubusercontent.com/assets/50745/11961624/9a2e918c-a88e-11e5-9ebf-e99b41fb88ab.png">

(not sure how this can be broken, without the enabled-by folds also being broken).

Need to check the spec, but it should be

Given:

```
i1 type C
i1 R i2
i2 type D
```

And `R` is an OP to be folded, then the visual display should be

```
 C
---
R(D)
```

(a more OWLish visual syntax would be `C and R some D`)

This rule should be consistent regardless of R

**Comment by kltm** [comment]
Sorry, pushed out another update after this and accidentally reverted the config. Could you look again (refresh browser) and see if that's correct now.

**Comment by cmungall** [comment]
perfect!
