### ISSUE TITLE
Early error message - not finding model for id

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#266]
Hi,
I just got this error message when trying to retrieve the insulin receptor signaling pathway.  Not sure what it means/how to proceed.
Thx.
--Kimberly

Early error (error): Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Could not find a model for id: http://model.geneontology.org/5667fdd400000696; org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException: Could not find a model for id: http://model.geneontology.org/5667fdd400000696

**Comment by kltm** [comment]
Hm, this works for me now:
http://noctua.berkeleybop.org/editor/graph/gomodel:5667fdd400000696
It's very possible this was triaged by the fix to minerva file reading that we were working on today: geneontology/minerva/issues#34 .

**Comment by vanaukenk** [comment]
Thanks, Seth.  
This is working for me now, too.
