### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#267]
(need a label for nice-to-have-but-not-urgent)

add standard keyboard shortcuts
- zoom in/out
- toggle screenshot
- explode-out/collapse-in
- edit annotations (shortcut for edit title?)
- find annoton

The last may be tricky: we would probably want to search by type label, but this may of a folded entity etc. http://jbrowse.org/ search is quite nice. But hardly urgent as normal browser search works perfectly fine.

**Comment by kltm** [comment]
Actually, for various reasons, I think they're all really tricky (I used to do a lot of these)...

**Comment by vanaukenk** [comment]
Closing for now until we have more user demand for something like this.
