### ISSUE TITLE
Only two models currently shown in Select list

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#271]
Hi,
I was just going to work on a LEGO model I started last week, but it looks like right now there are only two models available in the Select list, both from today.
Thanks,
--Kimberly

**Comment by kltm** [comment]
@vanaukenk How is it looking now?
I believe this is just a consequence of trying to get the pipeline loading into GOlr again: the occasional purge of the index, including noctua model meta info.

**Comment by vanaukenk** [comment]
Looks fine now.

Thanks, Seth.

**Comment by kltm** [comment]
For this type of thing, the ticket is fine, or nudging one of us (we're probably busy looking at the results of a load fail and didn't notice). And I guess, practically, by "one of us" I mean me.

**Comment by kltm** [comment]
Actually, re-opening this ticket might be a good signal as well--best of both worlds.
