### ISSUE TITLE
Selection table should allow free-text search over all labels in the model

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#273]
use case: I know my model used the FOO gene, but I didn't put FOO in the title. Should be able to find it easily.

Discussed on this call: http://wiki.geneontology.org/index.php/LEGO_January_18,_2016

solution: gather all labels for all classes directly instantiated in a model, concat into giant searchable text field (recall that genes etc are classes too). We don't worry about closures here (though this would be a reasonable extension). The text field will be indexed for Selectable Table on the front page

**Comment by kltm** [comment]
Hrm. This would should probably be driven from AmiGO loads, probably with a widget from the product of geneontology/amigo#291.

...or, this could actually be pealed out using epione, and then integrate better with the table that's already there for selection. Although, that is starting to fight the current table widget, it may be fast and easy to implement.

Either way, we'll leave this as a holder for its expression in Noctua.

**Comment by cmungall** [comment]
Is there documentation on epione & it's use cases?

> This would should probably be driven from AmiGO loads, probably with a widget from the product of geneontology/amigo#291

Presumably not the main AmiGO load, which would only index production documents? So there would be a separate solr index, following an identical schema to the model config in AmiGO, using the same loading code (but configured to load all models), and with a more frequent load cycle?

**Comment by kltm** [comment]
Epione is mostly a work in progress exploring a more "dirty deeds done dirt cheap" approach to getting metadata out of a model (#195 #196 #202 etc.). There is no formal API for it, and it is currently very hacky (which may be solved by moving to a more parseable format). It is, however, very fast, for both wiping the index and rebuilding it from nothing to monitoring changes on-the-fly.

For the use case you're describing though, we could hopefully get multiple AmiGO loads per day for the models, or at least one; and I'd hope that a user wouldn't forget their model so fast they couldn't depend on that. I see epione as slightly different use case, although they obviously overlap a lot, and more so if the frequency of the main model load increases. Although, as you point out, the "production" tag does reduce the utility of the AmiGO load for other purposes.

The addition of labels to the load is easy, although I don't think we'll be showing them in the interface as that would get ugly (and again, I'm not sure how flexible that table widget is).

**Comment by kltm** [comment]
Depending on what you're describing, likely https://github.com/geneontology/noctua/issues/484, epione2, or extracting species information in metadata load (or all three).

**Comment by goodb** [comment]
For clarity.  (not prescribing how to do it).  We want to be able to filter model search results by species (as well as gene, ontology term, etc.).  This functionality will also likely be of value within Noctua itself (or workbenches) as editors will want ways to see related content from other models in the collection.

**Comment by vanaukenk** [comment]
Search capabilities have been improved by the newer version of the Noctua landing page.  Closing this ticket; any future requests should be handled with new tickets.
