### ISSUE TITLE
There should be a route for seeing identifiers for classes (GO, also entities) in main display

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#274]
Feature request from ??? on annotation call http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-01-26

It's sometimes nice to be able to see IDs as well as labels. This would not be desirable *all* the time, the display is nice and compact right now.

There are various ways this might work. E.g. mouseover highlights IDs.

I am partial to the ID of having different configurable renderers as in OBO-Edit and to a lesser extent Protege, where the user could switch between `${class.label}` and `${class.id} ${class.label}` (invented syntax but you get the idea). But this may be overkill for this use case.

**Comment by kltm** [comment]
Huh, surprised we didn't already have this in there. There will now be additional ID information on hovers and expanded views.
