### ISSUE TITLE
Add ability to migrate Type assertions from obsolete classes to their replacements

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#279]
This may end up being a minerva ticket. Came up in ontology class, cc @hdietze 

Classes may become obsolete over time. Obsolete classes may either have
1. A single `replaced_by` annotationAssertion
2. N `consider` annotationAssertions
3. Neither of the above

These guide either automated or manual migration of Type assertions.

For 1, we could do this entirely automatically within minerva. Or we can have some kind of prompt in Minerva if this level of automation is too unnerving. Get feedback from @ukemi and @vanaukenk here.

For 2, we can imagine a UI component to help user choose replacements. However, this feature may be relegated to 'nice to have but not essential' if we have a decent ClassInfo browser within Noctua (they can see the consider annotations and use this to guide their replacement).

For 3, the curator is on their own; but they should still be informed. E.g. deprecated classes should be shown in strikethrough or red, as in Protege. Or whatever solution we use for AmiGO: https://github.com/geneontology/amigo/issues/230

Additionally, instances of deprecated classes should figure into a more general QA check for models. We can imagine the biocurator in charge of QA looking through a list of models that fail checks such as this and following up with the original model curators or fixing this themselves.

**Comment by kltm** [comment]
Right now, I would advocate a combination of some process that updates the model on the backend (minerva-on-save?) and letting the UI highlight issues for the user.
As well, there probably needs to be a sweep and report system to help keep models maintained or reviewed in Jenkins.
