### ISSUE TITLE
Need additional workbench type for edges / relations

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#282]
From the discussion about curator workflow out of issue #147 , it seems that a likely class of kickouts to Textpresso would be best started from edges/relations. To accomplish this, we will add a new workbench type that is launched/displayed from the edge/rel pop-up.

**Comment by kltm** [comment]
Tagging @goldturtle and @vanaukenk.

**Comment by vanaukenk** [comment]
Some thoughts on what kinds of Texptresso searches I'd like to have available for curators from within annotons:

1) If a gene product is entered, curators would be able to search using the gene product name as a keyword and a combination of categories for identifying experimental evidence for:
     MF - enzymatic activities
     MF - macromolecular interactions
     MF - union of one or more types (i.e., enzymatic activities AND macromolecular interactions)
     CC - subcellular localization 
Case sensitivity, or other differences between gene and gene product names, can be critical for getting decent precision so we may need to make it easy for curators to toggle between upper and lower cases wrt keyword, or devise some other rules for how to populate genes vs gene products as keywords (rules seem harder than toggles, though).

2) If gene product is not known, could perform search with entire category of gene and/or protein names for a given species using the same categories as above.
     Best source of entity names and synonyms? UniProt?

Other types of MF categories, e.g. transporters, will be included in the future.

**Comment by kltm** [comment]
With the refactor work on #260, this is pulled almost completely through. That said, edges only have the "annotation" editor (compared to the fuller individual UI); I'd like to wait until we are on a new framework #399 to pull it the rest of the way.
