### ISSUE TITLE
Missing label for relation in Noctua display

### ISSUE THREAD

**Issue by hdietze** [geneontology/noctua#289]
For some relations, there is no label in the noctua model editor. For example `gomodel:56aac7ad00000236` with the relation `obo:GOREL_0002006`. The expected label would be `results_in_organization_of`.

I have checked the json response of the server and the label is returned as part properties
```
{
  "type": "property",
  "id": "obo:GOREL_0002006",
  "label": "results_in_organization_of"
}
```

link to model: http://noctua.berkeleybop.org/editor/graph/gomodel:56aac7ad00000236

**Comment by kltm** [comment]
It's likely that this is an historical code issue where the labels are determined by the context blob rather than looking for a label. Now that labels are available, the order should be: 1) context, 2) label, 3) ID.

**Comment by kltm** [comment]
After discussion with @hdietze , we'll probably get rid of properties, add property-label.

**Comment by kltm** [comment]
This should be functionally complete, mostly due to upstream changes.

**Comment by kltm** [comment]
Will take a little time to percolate out to production though.

**Comment by cmungall** [comment]
> After discussion with @hdietze , we'll probably get rid of properties, add property-label.

Why deviate from the owl model?

**Comment by cmungall** [comment]
Where is this currently documented? is property-label for both OPs and APs?
