### ISSUE TITLE
Column 3 (Gene Symbol) in GAF contains species abbreviations from NEO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#292]
Hi,

Not a deal breaker, but just to record the issue.

When GAF files are dumped from Noctua, Column 3 contains the species abbreviations from NEO.
For example:
WB	WBGene00006364	syd-2 Cele	
While these abbreviations are very helpful for curation, we probably don't want them in the GAF output.

This should not be an issue with GPAD.

Thanks,
--Kimberly

**Comment by kltm** [comment]
Tagging @hdietze and @cmungall for comment.

**Comment by kltm** [comment]
Fair enough. However, the labels shouldn't be finding themselves in others' pipelines, correct? While I understand the annoyance here, I'm also tempted to say "noted" and pass this "wontfix", as the labels aren't particularly functional parts and it's a product of separate issues (e.g. geneontology/amigo#131, geneontology/amigo#24, etc.). Bumped to "wishlist" for now.

**Comment by vanaukenk** [comment]
This likely wouldn't break anything from, say, a parsing perspective, as MODs who consume the GAF are likely to just work with the IDs in Column 2.  
Just good to be aware that these are cropping up, though, as it's not expected and doesn't match what DBs would normally put in Column 3.

**Comment by cmungall** [comment]
not totally sure what the significance of amigo 131 here.

we should fix this, as having the correct GAF is important. the correct fix is to have two annotation properties in neo.

 1. rdfs:label - conforms to OBO norms and is uniquified by species suffixing
 2. gene symbol - species context is assumed

The straightforward thing to do is to map 2 to column 3 when producing the GAF.

However, if we're already doing some hacky things in the post-processing to produce the GAFs then this is a trivial post-processing hack, up to @hdietze

**Comment by kltm** [comment]
@cmungall the whole reason we have those label in there in the first place is because of the trouble getting the autocomplete to behave as desired.
