### ISSUE TITLE
Create an Annoton Companion

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#293]
It would be nice to have a feature that is similar to the function companion that creates an annoton from existing annotations. Curators would then be able to import process and cellular component information from the legacy annotations.

**Comment by kltm** [comment]
@ukemi In my understanding, the Function Companion *is* the Annoton Companion. The reason that CC and BP annotation lines are dropped in the import now is that there is currently no model for how to do that from the annotation lines.
Would a better formulation of this ticket them be to get an import model for how to bring in BP and CC annotations, and then add that to the current function companion (or make a separate pair of companions)?
