### ISSUE TITLE
duplicate existing annotation

### ISSUE THREAD

**Issue by mcourtot** [geneontology/noctua#296]
One feature of P2GO I use all the time is "create another annotation like this" which allows to duplicate the statement, and then just update one part of it. Often, when curating a paper, the PMID, entity ID, evidence code is the same, and only the GO terms changes. The option to copy/paste an existing statement and then just update that one variable part would be great.
Probably related to the "cloning" function, but with the option to modify the clone.

**Comment by kltm** [comment]
After talking with @mcourtot about the workflow, this item is either detailed in #284 #245, or #117 .

**Comment by mcourtot** [comment]
this is so efficient :) 👍
