### ISSUE TITLE
Bug in legend stating number of annotations?

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/noctua#298]
In the model that Kim is creating live, the legend always says "annotations: 2" but that's just how many she started with - it didn't change whether she added 1, or whether she added a new MF or BP. Looks like a bug?

**Comment by kltm** [comment]
We'll be clarifying the interface with more feedback, but there are always at least two: date and contributor.

**Comment by cmungall** [comment]
users should be aware that these are owl annotations, not annotations sensu biocuration
