### ISSUE TITLE
Please add Dicty Anatomy ontology

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#299]
add DDANAT to Noctua please

Thanks,
Petra

**Comment by cmungall** [comment]
Fixed with http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/go-lego.owl?r1=30801&r2=32787

will be visible next minerva load in a few hours

**Comment by kltm** [comment]
Will assume that the new go-lego.owl has already propagated out. Will re-close once the servers have been restarted.

**Comment by kltm** [comment]
Restarted. It all looks fine.

**Comment by cmungall** [comment]
Alas, I can find no mexican hats, nor any other dicty terms (except for 
the stuff confusingly duplicated in CL - Petra we may want to add a 
tracker to CL here)

Maybe just a delay? This is the "Add individual" box

Random sample of expected terms:

  DDANAT:0000014 ! surface sheath of the loose aggregate
  DDANAT:0000015 ! surface sheath of the mound
  DDANAT:0000016 ! prestalk region of the tipped mound
  DDANAT:0000017 ! prespore region of the tipped mound
  DDANAT:0000018 ! surface sheath of the tipped mound
  DDANAT:0000019 ! prestalk region of the standing slug
  DDANAT:0000020 ! tip-organizer of the standing slug
  DDANAT:0000021 ! prestalk A region of the standing slug
  DDANAT:0000022 ! prestalk O region of the standing slug
  DDANAT:0000023 ! prestalk AB core region of the standing slug
  DDANAT:0000024 ! prespore region of the standing slug
  DDANAT:0000025 ! basal region of the standing slug

**Comment by pfey03** [comment]
mexican hat is a narrow syn for DDANAT:0000009 early culminant. These fun names are just synonyms:-'finger' is also more seriously called 'standing slug'
