### ISSUE TITLE
Add Export OWL Module to model menu

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#303]
The export option returns the OWL ontology faithfully, along with import directives. This OWL is difficult to load in Protege because of the import.

Can we export the OWL module, i.e. the output of the SLME step when running the reasoner?

**Comment by kltm** [comment]
Tagging @hdietze for input, as the command needs to be passed back to minerva.

**Comment by cmungall** [comment]
It's not even clear this request makes sense any more. I'm not sure if we are working with SLME, and if we are, if we need to be (slme+Hermit ==> too slow; slme+Elk ==> what's the point in incurring overhead? just use Elk!)

See: https://github.com/geneontology/minerva/issues/33#issuecomment-255427389

It may still be useful to extract the abox + tbox module for advanced users to debug in Protege, but this would be better done using external tooling than Protege
