### ISSUE TITLE
Add menu option to perform visual transitive reduction

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#304]
Note: we may choose a "wont't fix" for this

Discussion on:
http://wiki.geneontology.org/index.php/LEGO_May_2,_2016

See linked model. We may want to add seemingly redundant relationships, e.g. direct between mom-1 activity and Wnt pathway. Visually (and possibly logically, depending on edge labels) these may be redundant, but we need to capture the evidence. However, this 'clutters'.

Therefore if there is a menu option to perform transitive reduction (ignoring edge labels) in the visual model

**Comment by kltm** [comment]
It may be good to follow the pattern currently used for inferences, where the payload is optionally included, but a fundamental part of the client model.

**Comment by ukemi** [comment]
Would this option be a choice under the view menu?

**Comment by cmungall** [comment]
> Would this option be a choice under the view menu?

Absolutely
