### ISSUE TITLE
molecular_function doesn't autocomplete

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#306]
In many cases, I want to create an annoton where I do not know the molecular function of the gene product I am annotating. To do that, I use the root node molecular_function GO:0003674 in the individual. I find that I cannot get the term name to autocomplete, but if I use the ID, I can pick the term just fine. Would it be possible to have the autocomplete for the term name?

**Comment by kltm** [comment]
@ukemi I'm not sure I'm able to duplicate. In the [Add annoton] panel, for the "molecular_function" field, if I type "mole", molecular_function appears towards the top of the list.

**Comment by ukemi** [comment]
Hi Seth. Weird! I tried it yesterday and it worked fine. I thought you had fixed whatever it was. I will close this ticket and let you know if It pops up again.

**Comment by kltm** [comment]
Very occasionally there can be hiccups on the net that can cause things to misbehave.
If it happens again, you might try doing a hard refresh of the browser to try and clear whatever net error.
If may have been slow for some reason at this end with the autocomplete as well.
