### ISSUE TITLE
Add bibliographic info to list of PMIDs in evidence cloning box

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#308]
For evidence cloning, it would be very helpful to have some basic bibliographic information listed next to the PMIDs listed in the table for evidence selection. If there are multiple papers associated with a model, it will be difficult for curators to keep track of papers just from the PMID.
It'd be great to show (from the PubMed XML):
Title -
Authors -
Journal -
Publication Date -
Thx.

**Comment by kltm** [comment]
Ideally, I'd like to slave this to https://github.com/geneontology/amigo/issues/397, so we can just re-use that API.

**Comment by kltm** [comment]
Now looking at picking this up as part of BH17.

**Comment by kltm** [comment]
Good enough:
```sparql
    PREFIX wd: <http://www.wikidata.org/entity/>
    PREFIX wdt: <http://www.wikidata.org/prop/direct/>

    SELECT ?rtcl ?title ?author ?journal ?date
    WHERE
    {
      ?rtcl wdt:P698 "999".
      OPTIONAL { ?rtcl wdt:P1476 ?title. }
      OPTIONAL { ?rtcl wdt:P2093 ?author. }
      OPTIONAL { ?rtcl wdt:P1433 ?journal. }
      OPTIONAL { ?rtcl wdt:P577 ?date. }
    }
```
I'm going to want a template runner for all of this.

**Comment by kltm** [comment]
It's unlikely that we'll be able to get something "nice" until #399 is in. However, I think that as a compromise we can essentially have active hover for certain identifiers pretty uniformly. This might even be a nice hack for ORCIDs and the like as well.

**Comment by lpalbou** [comment]
Quick question, PubMed has several APIs to retrieve such information. For instance to retrieve meta data about two PMIDs, we can call:

[PubMed Example Query](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=22368089,3539452&retmode=json)

Perhaps we could use that API to handle PMIDs since Wikidata does not always have metadata on PMIDs ?

**Comment by kltm** [comment]
I'd honestly like to avoid PubMed where possible, as their recent TOS changes are not necessarily going to work out very well for us.
While wikidata does not always have the information upfront, we've been pretty successful in seeding it: https://github.com/dbcls/bh17/wiki/Noctua-SPARQL-Interactions

**Comment by vanaukenk** [comment]
Closing this for now as this likely pertained to the graph editor, but will open a new ticket in the noctua-form tracker to see about having this info for field value reuse.
