### ISSUE TITLE
Model summary tab or page

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#31]
(file under non-urgent)

col1: molecular entities (things that are the subject of enabled bys, possibly the leaves in the class expression if a complex/class expression)
col2: ontology classes (targets of direct type assertions, plus targets of occurs in)
col3: publication(s). The first one listed should be any annotation assertion at the level of the model

For look and feel, see:
http://curation.pombase.org/genotypetest/curs/23297b95cc45755a

Might also by nice to eventually have a user page like this:
http://curation.pombase.org/genotypetest/

**Comment by vanaukenk** [comment]
@kltm - I'm doing more tracker cleanup.

Does the existence of the new Noctua landing page and https://geneontology.cloud/browse satisfy what was desired for this ticket?

If so, let's close this one.
