### ISSUE TITLE
Addition of traditional qualifiers to noctua models

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#310]
In order to be 100% compliant with conventional annotation. We need to figure out a way to accommodate the traditional GO qualifiers, colocalizes_with, contributes_to, and not.

1)Colocalizes with should no longer be necessary using the strategy that we are trying to annotate the place where a gene product functions.
2)Contributes to should be computationally possible. It can be used when a GP is part of a complex that executes a function.
3) Not is more problematic. Can we even express negation?

**Comment by ukemi** [comment]
In OWL it looks like 'not' would be the complement class but this might be problematic in the way we use it. We need to discuss this.

**Comment by cmungall** [comment]
On 20 May 2016, at 3:51, David Hill wrote:

> 1)Colocalizes with should no longer be necessary using the strategy 
> that we are trying to annotate the place where a gene product 
> functions.

Yes

> 2)Contributes to should be computationally possible. It can be used 
> when a GP is part of a complex that executes a function.

Have a look at the notes on
http://purl.obolibrary.org/obo/RO_0002326

The definition is strict and hard to capitulate through OWL inference, 
but we could have a rule for this

Thinking more broadly, it's time to restate some the use case for GO. 
These two qualifiers were probably never used much by users.

> 3) Not is more problematic. Can we even express negation?

See #249

**Comment by kltm** [comment]
@paolaroncaglia @cmungall I was wondering if there could be a clarification on this closure, or if it was a wrong ticket?

**Comment by cmungall** [comment]
Mostly in https://github.com/geneontology/noctua/issues/310#issuecomment-220660467

 1. no longer necessary
 2. can be done explicitly with complexes
 3. existing ticket #249
