### ISSUE TITLE
Annotation import use cases unclear, needs more input

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#314]
Hi,

This ticket is being created as a result of the conference call on 2016-06-13 where we discussed some specifics about annotation import wrt the function companion.

This led to a broader discussion of different use cases for importing existing GO annotations and the expected behavior for each.

There are some tickets that currently touch on this area:
#212
#216
#293

But, we think it would be beneficial to review use cases and make sure we agree on how import should work.   The overarching goal is to make best use of existing curation. 

Possible use cases for annotation import:
1) Import GAF
2) Import GPAD
3) Function Companion
4) Model Seeding
5) Others?

Points to consider:
1) Evidence attribution
2) Annotation extension information
3) Dealing with information-rich gene products
4) Dealing with BPs with many annotations
5) Others?

For now, this ticket is meant to be a place to collect and flesh out specific ideas.

**Comment by kltm** [comment]
It might be good to get some of the notes from the call here--I think that covers a lot of ground. With out new evidence model, once it's out, we'll have a lot more flexibility about what we can capture in a structured way.

**Comment by mcourtot** [comment]
It would be useful to have the ability to load annotations from a specific PMID (or entity ID). Curators could then add the bits of LEGO model to complement existing annotations.
