### ISSUE TITLE
Explore endpoint connection between PubAnnotation and Noctua

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#316]
Conceptually following the same lines as #147, we would like to explore interaction between Noctua and PubAnnotation.

This work is being looked at on the geneontology/noctua/tree/experimental-biohackathon-16 branch.

The idea would be that we link out to pubannotation.org, supplying a return url and arguments,
something like:

```
RETURN_URL=http://foo.com/path
RETURN_ARGS={'json': 'we supply'}
```

pubannotation.org would maintain these values during operations and supply a button to POST to the RETURN_URL. When POSTing, they supply the JSON values, as well as additional information gathered during the annotation process.

This would require some exploration by @jdkim in https://github.com/pubannotation/pubannotation, but conceptually similar to mechanisms they currently maintain. We could also look at supplying certain values as part of the return args, such as orcid, so that pubannotation could fully capture the annotation in the process if complete and/or desired.

There is more to be discussed, but this is maybe a place to start.

This item was generated during the BioHackathon 2016.

**Comment by kltm** [comment]
@jdkim Reviewing #147 and what we already have in production, we could probably re-use a lot of the implementation on the Noctua end and use the same endpoint.

The JSON payload we would provide could be something like:

RETURN_ARGUMENTS=
```JSON
{
   "barista-token": "123",
   "user-id": "http://orcid.org/foo",
   "model-id": "gomodel:01234567",
   "client-id": "pubannotator.org"
}
```
and a RETURN_URL=http://foo.com/endpoint

Given this, the returning POST would just be a decoration/addition to RETURN_ARGUMENTS, POSTed as *Content-Type: application/json* to http://foo.com/endpoint:

```JSON
   "barista-token": "123",
   "user-id": "http://orcid.org/foo",
   "model-id": "gomodel:01234567",
   "client-id": "pubannotator.org"
   "requests": [
      {
         "key1": "value1",
         "key2": "value2",
         "comments" : ["foo", "bar"]
      }
   ]
}
```

Essentially then, pass back the RETURN_ARGUMENTS and add any number of objects defined by pubannotation.org to the *requests* field. A simulation from our point of view, using httpie, would look like:

```
http --json http://foo.com/endpoint barista-token=123 model-id=gomodel:01234567 client-id=pubannotator.org requests:='[{"key1": "field1"}]'
```

If you're interested in pursuing this way of doing things, if you could think about what the added payload POSTed back to us would look like, we can start coding that on our end.

**Comment by kltm** [comment]
Ideally, this idea is general enough that it could be applicable to any group that wanted to use you as their external annotation service.

**Comment by kltm** [comment]
BTW: I'm not married to the all-caps arguments; in fact, they probably shouldn't be.

**Comment by kltm** [comment]
In work on #283, we have done a bit of refining to the package and arguments kicked to external resources; we have tried to make something that would work generically for any resource. A potential bridge with other resources would have a different outgoing (and incoming) _x-client-id_ and _requests_.

**Comment by kltm** [comment]
The most up-to-date proposal for this interaction is now at: https://github.com/pubannotation/pubannotation/issues/3 .

**Comment by kltm** [comment]
Noctua can now generate link/jumps into PubAnnotation (will put into production in a little bit). They are of the form:
http://pubannotation.org/docs/sourcedb/PubMed/sourceid/10089213?endpoint_url=http%3A%2F%2Fhttp%3A%2F%2Flocalhost%3A8910%2Ftractorbeam&endpoint_arguments=%7B%22token%22%3A%221234567890abc%22%2C%22x-model-id%22%3A%22gomodel%3A55ad81df00000001%22%2C%22x-client-id%22%3A%22pubannotation.org%22%2C%22x-fact-source-id%22%3A%22gomodel%3A55ad81df00000001%2F55ad81df00000004%22%2C%22x-fact-target-id%22%3A%22gomodel%3A55ad81df00000001%2F55afdcd900000001%22%2C%22x-fact-relation-id%22%3A%22BFO%3A0000050%22%2C%22x-return-url%22%3A%22http%3A%2F%2Flocalhost%3A8910%2Feditor%2Fgraph%2Fgomodel%3A55ad81df00000001%3Fbarista_token%3D123%22%2C%22requests%22%3A%5B%5D%7D
Which gives a JSON payload of:
```json
{
  "requests": [],
  "x-return-url": "http://localhost:8910/editor/graph/gomodel:55ad81df00000001?barista_token=123",
  "x-fact-relation-id": "BFO:0000050",
  "x-fact-target-id": "gomodel:55ad81df00000001/55afdcd900000001",
  "x-fact-source-id": "gomodel:55ad81df00000001/55ad81df00000004",
  "x-client-id": "pubannotation.org",
  "x-model-id": "gomodel:55ad81df00000001",
  "token": "1234567890abc"
}
```
Similarly, Noctua can now take a request with this form:
```json
{
  "requests": ["http://pubannotation.org/docs/sourcedb/PubMed/sourceid/10089213/spans/321-795"],
  "x-return-url": "http://localhost:8910/editor/graph/gomodel:55ad81df00000001?barista_token=123",
  "x-fact-relation-id": "BFO:0000050",
  "x-fact-target-id": "gomodel:55ad81df00000001/55afdcd900000001",
  "x-fact-source-id": "gomodel:55ad81df00000001/55ad81df00000004",
  "x-client-id": "pubannotation.org",
  "x-model-id": "gomodel:55ad81df00000001",
  "token": "1234567890abc"
}
```
at the specified return url and (mostly) do the right thing:
```
http --json localhost:8910/tractorbeam token=123 x-model-id=gomodel:55ad81df00000001 x-client-id=pubannotation.org requests:='["http://pubannotation.org/docs/sourcedb/PubMed/sourceid/10089213/spans/321-795"]' x-fact-relation-id=BFO:0000050 x-fact-target-id=gomodel:55ad81df00000001/55afdcd900000001 x-fact-source-id=gomodel:55ad81df00000001/55ad81df00000004 x-return-url='http://localhost:8910/editor/graph/gomodel:55ad81df00000001?barista_token=1234567890abc'
```
Assuming that you had a localhost client setup and a usable token, this cli http request would create a comment on the specified edge in the specified model in Noctua, with the specified user (as given by the token).

**Comment by kltm** [comment]
TODO: We need to actually go to the given redirect URL, rather than returning the gross minerva results.

**Comment by kltm** [comment]
@jdkim Interestingly, PubAnnotation already seems to preserve the GET parameters in some cases. Looking at the URL given in https://github.com/geneontology/noctua/issues/316#issuecomment-273709208 , the parameters are preserved for span selection and on the JSON and TXT data pages.

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for now.
