### ISSUE TITLE
Tidy up landing page and coordinate with quickstart guide

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#322]
* Landing page needs link to quickstart guide
 * There is a lot of stuff on the landing page that is redundant with the quickstart guide. Not clear if people read this. There is some useful stuff on it that is not yet in the main docs, e.g. hiding part-of. Maybe this could be made into a separate "tips" section, with general material going into quickstart google doc

cc @ukemi @vanaukenk

**Comment by kltm** [comment]
In general, especially with different branches and versions running around, if the quickstart guide is far enough along, it would be good to fold it into the repo itself. It would also make it easier to integrate with the (eventual) inline tutorials I've been looking at.

**Comment by kltm** [comment]
@cmungall I've tried to port the document in. There's a bunch of change to make this a little more clean (e.g. start getting ri of LANDING*, ABOUT*, etc.), but this should tide you over until we can get in there more.

The #333 path creation means that you can add whatever markdown documents you want into that directory and reference them, I just can't guarantee preserving login at this point (back works fine).

**Comment by kltm** [comment]
@cmungall go ahead and close if this is sufficient for now, or after you tidy.

**Comment by vanaukenk** [comment]
Hi @cmungall @kltm 
Doing some prep for the workshop and wondering what the status of the landing page clean up is.  Specifically looking for the Quick Start Guide, but have some other questions as well.  We can talk Tuesday when you get to Hinxton.  Thx.

**Comment by cmungall** [comment]
I guess the fix will take effect next time noctua starts up?

We can always make temporary bit.ly links for things too, can be useful when you want people to follow along on their machines

**Comment by kltm** [comment]
The repo-ed Quick Start Guide should now be referenced in the live landing page. While not a live document live GDocs, it will be picked from disk fresh every time, so we can update easily.

**Comment by kltm** [comment]
FYI, for the time being, updates to ABOUT/LANDING require a client restart, but that only puts the system down for about ten seconds, with no loss of any state.
