### ISSUE TITLE
There should be a non-drag method for deleting relationships (see individual deletion)

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#328]
From @mcourtot 

Currently the only way to delete an edge is to drag it into limbo

The edge editor provides ways of adding evidence etc, but no way to delete the edge

Ability to change the object property would also be useful

**Comment by kltm** [comment]
Well, given the way things currently work in there, there are three options:
* to keep things consistent, add an edge editor box, like there is for nodes (green vs grey)l this box would be rather lonely, but that may not be an issue as more things are moved in
* overload the annotation editor with edge (or node) specific ops
* wait until I can get a little capacity and add halos, which is kinda where I want to go eventually anyways: https://github.com/geneontology/noctua/issues/286#issuecomment-180663221

**Comment by kltm** [comment]
Something like http://heelhook.github.io/chardin.js/, or one of the other "tutorial" tools may be usable, but I suspect that a click pop-up is easy enough to do.

**Comment by kltm** [comment]
If it's not pressing, and by *wishlist* I'm guessing it's not, I would prefer closing this out in favor of a halo experimentation ticket.

**Comment by kltm** [comment]
Looking at #349 for implementation.

**Comment by vanaukenk** [comment]
Closing for now as this would require further development of the graph editor.
