### ISSUE TITLE
You seem to have a bad token... (Error while logging in)

### ISSUE THREAD

**Issue by kunduk** [geneontology/noctua#329]
I have successfully created a login username/password in Noctua.
On logging in I am being taken to a Session Manager page that show my email but other fields like name, color and token are blank. In this page there are two buttons - Return and Logout.
I am clicking on 'Return' buttom and its taking me the the page where I see the link "Create noctua model" but the following error messages are popping from the browser -  

"**There was a manager error (success): bad response
You seem to have a bad token; will try to clean...**"

and then its logging me out automatically.
I am using  Google Chrome (Version 52.0.2743.116 m).

Can anyone suggest what is going on? Am i missing any thing? Using Firefox gives the same error message as well.

Thanks,
Kunal

**Comment by kltm** [comment]
You probably just created a Persona account, which is the authentication layer. However, you are not an authorized GO user for Noctua (authorization), so do not have access to the system.
If you are interested in gaining access, you might want to contact the GO Helpdesk (http://geneontology.org/form/contact-go) with your use case for gaining editor access to Noctua.

**Comment by kunduk** [comment]
Thanks Seth. Appreciate your prompt message.
