### ISSUE TITLE
Incorrect GAF generated from GPAD WRT isoform annotations

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#330]
When creating an isoform annotation in Noctua, the isoform value populates column 2 instead of column 17 in the gaf. Column 2 should be populated with the gene or GCRP in the gaf.  See model 5745387b00001874 and the resulting gaf.

**Comment by cmungall** [comment]
Technically this is an error in GPAD->GAF. In GPAD, annotations are directly to the isoform.

As a workaround, can you consume GPAD?

**Comment by ukemi** [comment]
We don't need a workaround. We do consume GPAD because in the GAF we lose metadata that we want to retain. However, I think some people will want the GAFs.

**Comment by cmungall** [comment]
Noctua no longer exports GAF so this ticket doesn't make sense any more, so can be closed.

We may still want to track the fact that an easy path to getting GAF may be required by MODs, and track in this tracker. If so, I think new ticket asking specifically for this would be best

**Comment by pgaudet** [comment]
This assumes all groups will consumes GPAD.
