### ISSUE TITLE
Provide (temporary) improved relation selection when adding edges

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#331]
As opposed to the "clever" solution for relation selection presented in #165 , this aims to be a stopgap measure to make relation selection for edges more tolerable in the interim.
The idea is to work from the list here https://github.com/geneontology/noctua/issues/165#issuecomment-229416977, giving users the option to choose from the compacted GO selections, or the complete list of known relations.

**Comment by cmungall** [comment]
This looks great. Reopening for minor fixes:

 * 'has part that occurs in' (RO:0002479) is neither a common relation nor a sub-property of part-of
 * 'causal relation between processes' is a grouping relation and would never be used directly; remove

Some possible enhancements. I leave it to you to decide whether to fold these in or punt until the #165 fix:

 * IDs can be linked either to their purl (which currently goes to OntoBee but we may change this to OLS, which is more curator friendly)
 * Indicate context in which relation should be used. E.g. domain range. This could be an ascii arrow with mnemonics (e.g. `F/P --> F/P`)
