### ISSUE TITLE
Contributor attribution when changing layout?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#334]
Hi,
I was looking at Paul T's mismatch repair model a few days ago and rearranged the layout so I could see things better.  
In the course of doing that, I noticed that the * appeared next to the model name in my browser tab, although I didn't (knowingly) make any changes to the actual annotations.
I saved the model so as not to lose anything, but now am listed as a contributor, when in fact, I don't think I made any contributions.
Unfortunately, I can't reproduce this now, but just thought I'd mention it in case there's a ready explanation and something curators should know about when viewing a model.
Thx.

**Comment by ukemi** [comment]
Karen and I also saw this when we were working on a model.

**Comment by kltm** [comment]
Coordinates are annotations to the nodes, and all changes are recorded, including who did it. If you wish to make changes without "editing", you can do so by using a session that is not logged in.

Later on, we may with to filter out these annotation before loading elsewhere, but for the time being, this is the expected and correct behavior.
