### ISSUE TITLE
Restore link to Noctua models in AmiGO instance

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#337]
The link to amigo-models seems to have disappeared in one of the front page refactors

**Comment by kltm** [comment]
Say whaaaa...!?

**Comment by kltm** [comment]
A /think/ this went AWOL during an earlier PR.

**Comment by kltm** [comment]
I take that back: it works locally, and I have not been able to duplicate.
I think this might just be a production configuration issues then.

**Comment by kltm** [comment]
Even though the configs appear the same, the production does not "see" the configured external browser.
```html
    <script type="text/javascript">var global_external_browser_location = null;</script>
```
...possibly something in supervisord config?

**Comment by kltm** [comment]
No...
The only difference I can find right now is the difference in the Node.js version (4.5 local versus 0.12.15 production). Given the other weird issues that cropped up around the version change, I think that's now a possibility. After things settle down tonight, I want to upgrade and try restarting.

**Comment by kltm** [comment]
Came back around: config error. Fixed and in production.
