### ISSUE TITLE
pombe pds5 SPAC110.02 not recognised by noctua

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#339]
stuck!

**Comment by kltm** [comment]
@cmungall Want to check on Val?

**Comment by ValWood** [comment]
now its there?

**Comment by ValWood** [comment]
gone again?
![bug](https://cloud.githubusercontent.com/assets/7359272/18126902/40e3733c-6f75-11e6-93cf-7bdc74237ac2.jpg)

**Comment by cmungall** [comment]
A few things going on here:

 1. Until we fine-tune autocomplete, sometimes the entry for your species does not show up in the top-N returned by autocomplete
 2. In the rest of the Noctua interface, this is not a problem as you can disambiguate by typing `SPACE` `Spom`. However, in the complex creator the space is interpreted as a break between genes

**Comment by cmungall** [comment]
One workaround for this is to type in the ID... but I think the `.` in pombase IDs is confusing the solr tokenizer.

For example, if I type `SPAC110` anywhere in Noctua, I expect all IDs that start with this:

```
id: PomBase:SPAC110.01
id: PomBase:SPAC110.02
id: PomBase:SPAC110.03
id: PomBase:SPAC110.04c
id: PomBase:SPAC110.05
```

However, only 05 shows up.

ccing @jnguyenx

**Comment by kltm** [comment]
I've tried this a few times, but have been unable to duplicate. I'll need @ValWood or @cmungall to walk me though.

**Comment by cmungall** [comment]
I retract my comment above, space is not interpreted as a break. So the workaround is to disambiguate by typing space-Spom.

Obviously we want to have the option of restricting all autocompletes on a species basis across all noctua but that's a separate ticket

**Comment by kltm** [comment]
Okay, looking at this with @cmungall, I think this is #261, #257, and the like.

**Comment by cmungall** [comment]
The ordering seems random, so it's not guaranteed that it will be in the top-N. But you can type space-Spom to find yours
