### ISSUE TITLE
Add a second import button to the function companion for grouped annotation import

### ISSUE THREAD

**Issue by RLovering** [geneontology/noctua#346]
@kltm hijacking @RLovering's original reminder.

Currently, the function companion will import each annotation a as separate annoton. We'd also like to have a second import button that takes each selected GP and has a single representative one and links it to all associated functions, summing the evidence.

**Comment by vanaukenk** [comment]
The function companion is probably not widely used, so closing for now.  This would be relevant for requirements gathering for model seeding, though.
