### ISSUE TITLE
Use Jenkins pipeline to produce GAFs from LEGO

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#35]
Use the Jenkins pipeline to produce GAFs from LEGO. Probably for Heiko.
Questions:
* annotation extensions?
* should we use BP and CC in the extension column?
* should it go to GPAD-1?

**Comment by cmungall** [comment]
Comment from @hdietze  on https://www.ebi.ac.uk/panda/jira/browse/GO-288
```
A first pass of the export to GPAD is available as an owltools method. See 'owltools --lego-to-gpad' for details
```

**Comment by cmungall** [comment]
http://build.berkeleybop.org/job/export-lego-to-legacy/

How should we make GAFs? Leave as GPAD?

**Comment by kltm** [comment]
As a side question, is this the same conversion method that's used in the Noctua interface?

**Comment by cmungall** [comment]
Dupe with: geneontology/minerva#18

**Comment by hdietze** [comment]
Yes the export in noctua and the command-line (Jenkins job) use the same code to generate old GO style annotations (GAF/GPAD).
