### ISSUE TITLE
Add an interface for fast editing of form-oriented information

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#352]
Note: even though this involves form editing this proposal should not be mistaken for previous suggestions for GAF or GPAD like forms for novice users or simple use cases. It is v similar to the spreadsheet view @vanaukenk proposed (can't find link)

The point here is to allow full expressivity, but to use different kinds of displays to their optimum level. The graph display is hyper-optimized for connecting activities and arranging them, but suboptimal for anything form-like, such as entering the Types of individuals.

The idea is the user can start by entering a list of `N` gene/product/complex symbols, submit these, and after resolution a set `N` individuals `A_1 ... A_N` of type `molecular_function` are created, with 3 triples `A_i enabled_by G_i`, where `G_i` is an individual of the specified type. At this point the user enters the graph display.

At this point (or at any point during graph editing) the user can select some or all (say all for now as we don't have bounding box selectors) activity individuals. This brings up a form/table with `N` rows. The columns might be configurable, but at a default, at least `enabled_by` and `occurs_in` (plus perhaps evidence for each).

Each cell would offer a ranked list of types of the appropriate class based on existing annotations. For example, if `G_i` is in golr annotated directly to `kinase activity x 3`, `protein binding x 1` then these 2 would be available with the more popular first. Note mapping to leg-slim is likely here. Selecting one would choose the evidence for that assertion (not clear what to do with multiple evidences). Override with any MF if you don't like available options.

references could be auto-filled in with PMIDs if the model has a dc:source annotation.

Ideally the table could be tabbed through, no mouse clicks necessary.

**Comment by kltm** [comment]
Related: #150 #128.

**Comment by kltm** [comment]
Also part of this has a description of #344 .

**Comment by cmungall** [comment]
Comment from a user:
>Why can’t we edit a sub node or simply anything in an annoton? Drives me nuts, especially when you collaborate on a model or when you ‘practice’.

**Comment by kltm** [comment]
Until #399 has been dealt with, I believe that the geneontology/simple-annoton-editor will be covering this use case.
