### ISSUE TITLE
login issues

### ISSUE THREAD

**Issue by satra** [geneontology/noctua#353]
i'm trying on OS X with http://noctua.berkeleybop.org

on chrome, i tried to login, but it keeps logging me out, when i try to return back from the persona login. keeps saying barista token undefined.

on safari, clicking login hangs on the session manager for ever. doesn't even launch the persona popup.

**Comment by kltm** [comment]
@satra You are not currently an identified user for the GO instance of Noctua (i.e. https://github.com/geneontology/go-site/blob/master/metadata/users.yaml), so would not have access to the system for editing; you should be able to view models just fine though.

Are you associated with GO or OBO in this case? We have another public instance at http://noctua-obo.berkeleybop.org:8910/ that has a different use profile.

**Comment by satra** [comment]
@kltm - thanks for the response. the other public instance has the same issue. i'm not associated with GO or OBO. we simply wanted to use the platform to check some of the functionality with our own owl files.

**Comment by kltm** [comment]
@satra That is expected as you are not a registered user for either system.

If you are interested in looking at OWL/functionality, I suspect that the OBO instance would be of more use to you. Tagging @cmungall for opinion.
