### ISSUE TITLE
Use Jenkins pipeline to seed LEGO from GAFs?

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#36]
Using the Jenkins pipeline to seed LEGO from GAFs?
Possibly for Chris.

**Comment by kltm** [comment]
@cmungall I'm no longer sure what this was meant to be, or if it is still relevant. I'll likely close it out without clarification.

**Comment by vanaukenk** [comment]
@kltm 

This ticket now seems out-of-date.

I'm closing, but please re-open, if I'm mistaken.
