### ISSUE TITLE
Looking at upgrading and/or changing the graph toolkit

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#360]
We are currently using the 1.x series of the open source jsPlumb ("Community edition"). Looking at what's available in the closed source 2.1.7 version of jsPlumb ("Toolkit edition") has left me both envious and irritated--the maintainer is quite openly trying to monetize at this point. Items like:
- improved layout
- overview thumbnail
- dynamic cell editing
- drag and drop interactive node creation
- group selection (aka rubber band)
- others...

which are not available in the open source line has left me wondering if there is a more fully functional toolkit available for use.

The purpose of this item is too explore ideas around other toolkits. As we have a working prototype done (our current graph editor), I'd think it would be about a week of work, assuming that the new toolkit was a superset of functionality.

**Comment by kltm** [comment]
Some initial thoughts on this appear in item #95. From there, I've breifly looked at jointjs, newer "community" jsplumb, and wireit (from yui3). It's not looking good out there.

The other possibility is to rethink some of the core visualizations (i.e. more minimal, less full and nesty) and use something more d3/cytoscape.js-y.

**Comment by goodb** [comment]
I think this issue also subsumes at least the more specific issues #173 and #15 so commenting here.  The introduction of a bunch of new imported models, some of them fairly large, (per Issue #37 ) has brought this up in my work.  Feedback I get on imported models from curators like @ukemi begins with "it was difficult to look at".  Looking through the thoughts above I'm curious to know what the current plan is?  Is there a design documented somewhere?  The separation of the model hierarchy navigation (via a basic tree view) from the graph editor as mentioned in [this comment](https://github.com/geneontology/noctua/issues/15#issuecomment-209299088) seems like a fruitful path - notably its the pattern used by Reactome which I believe is a reasonably effective design.

**Comment by kltm** [comment]
@goodb Currently, there is no design doc. The toolkit redo is more bound by the features desired and the libs/frameworks available. And currently, it's pretty grim, meaning that we are likely to have more special purpose interfaces than a unified interface.

**Comment by goodb** [comment]
At some point, sooner or later, some one is going to work on doing automatic layouts for GO-CAMs or graphs derived from GO-CAMs.  When they do, this paper will be a nice reference for starting points 
https://academic.oup.com/bib/article/21/1/62/5115270 

abstract
The use of signalling pathway hypergraphs represented as process description diagrams is steadily becoming more pervasive in the field of biology. This makes ever more evident the necessity for an effective automated layout that can replicate high-quality manually drawn diagrams. The complexity and idiosyncrasies of these diagrams, as well as the specific tasks the end users perform with them, mean that a layout must meet many requirements beyond the simple metrics used in existing automated computational approaches. In this paper we outline these requirements, examine existing ones and describe new ones. We demonstrate state-of-the-art layout techniques enhanced with novel functionalities to meet part of the requirements. For comparatively small signalling pathways our enhanced algorithm provides results close to manually drawn layouts. In addition, we suggest technical approaches that may be suited for fulfilling the identified requirements currently not covered.

**Comment by kltm** [comment]
@goodb This is for toolkit (which may relate), but I would suggest deleting these two comments and adding to https://github.com/geneontology/noctua/issues/173

**Comment by goodb** [comment]
Sure... that one seemed overly specific but I guess so does this one.

**Comment by vanaukenk** [comment]
Closing for now; not actively being worked on.
