### ISSUE TITLE
Annotating to a 'novel' concept

### ISSUE THREAD

**Issue by raymond91125** [geneontology/noctua#365]
I am trying to use Noctua to annotate cell/anatomy function. My first test case is a statement:
"The role of the excretory cell is probably osmotic/ionic regulation and waste elimination, analogous to the renal system of higher animals."
Just for the first part, I think I need a concept like 'regulation of organism osmolarity'. Is there a way that I can construct this concept within Noctua? I have not found a similar concept in GO.

**Comment by kltm** [comment]
@raymond91125 You probably want to try the noctua-models tracker, where there is some discussion about models, the noctua-minerva@lists.lbl.gov list that we could add you to, or the annotation calls, where David and Kimberly have been working out guidelines for modeling various concepts.

**Comment by kltm** [comment]
https://github.com/geneontology/noctua-models/issues

**Comment by cmungall** [comment]
```
[your mf]--regulates-->[osmolarity]--inheres_in-->[multicellular 
organism]
```

you should be able to find similar concepts in GO (use go-plus or the 
editors file and look at it in Protege). The RoBQ terms use the same 
pattern (using pre-composed terms from OBA, but these have OWL 
equivalence axioms using this pattern)

**Comment by ukemi** [comment]
Hi Raymond,

I'm pretty sure we can do these kinds of things. Maybe the route of relating the cell and the process would be the way to go. 

worm excretory cell capable_of some multicellular organismal water homeostasis. 

or stronger
worm excretory cell enables some multicellular organismal water homeostasis

Would the homeostasis GO terms work?

-D
