### ISSUE TITLE
No check for GO ID in With using IC evidence code

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#369]
I noticed this when I was going to make an IC evidence statement.
As I was filling in the WITH field, I assumed I would type in the GO id or term name and it would autocomplete. However, I found this did not happen, and I could type in anything, and it would save, AND I would get a GAF ok with the bogus term in the WITH field
curator inference used in manual assertion; http://orcid.org/0000-0003-2689-5511; PMID:1234456; with: because; date: 2016-10-26
Use of IC requires a valid GO term in WITH.

**Comment by kltm** [comment]
This is essentially part of #261 and the evidence conversion that we'll do.
At this point, it functions as intended.
