### ISSUE TITLE
Pipeline from Reactome

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#37]
Pipeline from Reactome. Ideally, the user is able to just input an ID somewhere and have the converted model loaded/merged in.

Questions about exactly when in the process this would be best.

**Comment by kltm** [comment]
cc guanmingwu

**Comment by kltm** [comment]
cc @guanmingwu

**Comment by kltm** [comment]
Meeting notes:
Data API access may be much faster and more detailed.
Also thinking about a file dump from the Reactome pipeline.
It may be easiest to have a light exchange format, going both directions; ideally this format is light and easily generated, something short of OWL, but less abstract than a graph. Will need to talk to 
Will also want to include a separate export ticket.
@cmungall .
Also @guanmingwu .

**Comment by cmungall** [comment]
We should be able to take in any OWL Abox from the web, and optionally shallow copy/clone

**Comment by kltm** [comment]
I would agree, but I was thinking about a lightweight exchange format for: 1) people not wanting to use the OWL API to produce a file that can be used for bulk upload and 2) a file that is easily parsable and usable from JS as that is our current scripting language. Pondering that, I suppose that the graph response format would probably fit the bill.
(Although, our libraries should still work in rhino, I think it might get weird to use the OWL API from in there (although I've never tried)).

**Comment by cmungall** [comment]
Example Minerva-json:

https://raw.githubusercontent.com/cmungall/reactome-in-lego/master/Homo-sapiens/DNA_Damage_Reversal.json

Is there a secret power-user option to bring this in? The desired behavior is to do the equivalent of  a clone (ie new Individual IRIs would be minted, as I am the external provider I should not be in the business of minting stable model instance IDs)

**Comment by guanmingwu** [comment]
Hi Chris,

As long as there is a format specified, we can bring it in for Reactome pathways :)

Thanks,

Guanming

**Comment by cmungall** [comment]
Great!

We should probably split this ticket. It originally started out with the requirement to bring in an existing reactome pathway into noctua, for exploratory purposes. What should the biopax<->lego mapping look like? What is hard to map? Do the start and end boundaries line up? What would we do differently if modeling using the LEGO approach?

that's what the static json dump is (in fact I think the version of reactome I used is a few iterations old, but the first step is to see if it works at all)

After your discussion with Seth at OHSU I think we can start moving along in parallel on the next phase, which could involve more connections at the UI level, bidirectional interchange (depending on resources).

When you say Bring in, do you mean as a means of importing into Reactome?

**Comment by guanmingwu** [comment]
“Bring in”: I mean to use this as a file format. We in the Reactome will export all pathways for you in this format.

Guanming

**Comment by kltm** [comment]
```
> In case this may be useful, our EBI group recently just developed a
> graph database for Reactome:
> 
> http://www.reactome.org/pages/documentation/developer-guide/graph-database/
> 
> The views in your two web applications are very similar to Neo4j graph
> database models to me. So probably working with our graph database may
> simplify things for you? Just a wild guess.

For the direct Noctua communication options, I don't think it would matter too much what your backend is as you'd be constructing the objects to send over the wire yourself; although, you might find it easier to work with.

For batching, I think it's a modeling issue that would require a few cycles with Chris to work out the details. The graph database may make it easier to explore the source data to begin with though. Chris could probably speak more to that.

I'll copy this into the ticket to make sure that information is captured.
```

**Comment by kltm** [comment]
Talk with @guanmingwu and @cmungall 

We've decided that the best way forward, so that we can easily iterate on the modeling and figure out any problems would be to:
- base ourselves (for the time being) on @cmungall json models (see: https://github.com/geneontology/noctua/issues/37#issuecomment-207529278)
- fix (or create, I forget) json model import into noctua
  - like the syngo import, initial mark as delete

**Comment by kltm** [comment]
Well, for a very first pass and to get us started with whether the current conversions are satisfactory, it turns out we have a way of viewing JSON-ified models right now, with a few caveats:

- they cannot be edited
- one cannot use workbenches on them

Currently, there are no labels, but this seems to be caused by (incorrectly) using `rdfs:label` as an annotation rather than `label` within type (ex: https://github.com/berkeleybop/bbop-graph-noctua/blob/master/tests/minerva-09.json). (pinging @cmungall for this)

To access this functionality, copy a JSON-ified model, go to http://noctua.berkeleybop.org, select "Danger Zone" from the menu at the top, copy the JSON-ified model into "JSON Debugging", and click [Load]. There is no need to be logged in.

**Comment by goodb** [comment]
I took a first pass at converting Reactome Biopax to the GO-CAM structure.  The models are accessible for the moment at noctua-dev.  For example, the [Glycolysis pathway](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:helloworld0.7023149901925296) ([Reactome view](https://reactome.org/PathwayBrowser/#/R-HSA-70326&SEL=R-HSA-70171&PATH=R-HSA-1430728,R-HSA-71387)) or the [Apoptotic Execution Phase](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:helloworld0.5197743672006522) ([Reactome view](https://reactome.org/PathwayBrowser/#/R-HSA-75153&PATH=R-HSA-5357801,R-HSA-109581)) .  Feedback about the mapping would be most appreciated.  cc @ukemi @cmungall @kltm @thomaspd @yy20716 @vanaukenk

**Comment by goodb** [comment]
The generated Reactome models on [noctua-dev](http://noctua-dev.berkeleybop.org) and the [documentation for the mapping rules](https://docs.google.com/document/d/1xKr4sMBMioEYnHFpnFl0lL2gQzpeHX-eY3wT0fyZXEA/edit) have been updated.  Would be great to get some feedback on this.  See e.g. [updated glycolysis pathway](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:-1622611792).  Note that its pretty big and is definitely best viewed using the Pathway View workbench.

**Comment by vanaukenk** [comment]
@goodb  - I'm doing some noctua tracker cleanup.

Would you like to leave this ticket open or close it and note that this work now has its own repo:  https://github.com/geneontology/pathways2GO
