### ISSUE TITLE
Relax the constraint on the complex generator to macromolecular complex

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#378]
Currently the complex generator requires that a complex be a protein complex. This is too stringent since macromolecular complexes can also contain proteins. We need to relax this constraint.

See ontology ticket 12782 for details on this discussion.

**Comment by kltm** [comment]
Re: geneontology/go-ontology#12782
Not quite following the conversation there, but as an action here, how would this do: constrain the mmc workbench to use "macromolecular complex" instead of "protein complex"?

**Comment by ukemi** [comment]
Yup. That will work.

**Comment by kltm** [comment]
Term to use: http://amigo.geneontology.org/amigo/term/GO:0032991

**Comment by kltm** [comment]
Interestingly, in the code, it seems that we used to use "macromolecular complex", but changed it to "protein complex". Is there any red flag in #169 that would indicate why the initial loose constraint was tightened?

**Comment by cmungall** [comment]
> Is there any red flag in #169 that would indicate why the initial loose constraint was tightened?

Nope - it was just intended as default it was the most commonly used. But this is moot now PC is being merged into MMC
