### ISSUE TITLE
Dump to cytoscape formats over total model set

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#38]
The ability to export global(!) data for viewing.
Flat?
XGMML?
How do we link?
Webcytoscape or desktop?

**Comment by kltm** [comment]
While we have a script somewhere to knit (and display) the totality of models in the client from the JSON models, with the conversion to the graph store, I suspect that this might be better accomplished at the Minerva end.

**Comment by cmungall** [comment]
Probably not minerva (which generally doesn't load all models) but rather a client consuming API wrapping triplestore
