### ISSUE TITLE
Display user and group labels from minerva metadata

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#380]
When the menu of models used to appear on the home page, it used to show the names of people who have worked on a model. Now it shows an ORCID instead. If you try to search on a name to get models where someone has contributed, if you don't know their ORCID, it is a bit of a pain. Is there a way that we can either repopulate the menu with the names or at least have them searchable?

**Comment by kltm** [comment]
I thought we had this mentioned somewhere separately , but it was apparently wrapped up in other closed tickets.

Now that epione has been removed from the stack, there is no intermediary to map orcids to human-readable name labels. Fixing this comes in three parts.

- [ ] work with @cmungall and @balhoff to get users.yaml and groups.yaml into a form that can be read by minerva
- [ ] work with @balhoff to get the label information into the metadata where possible
- [ ] thread the new data through noctua and into the display

**Comment by cmungall** [comment]
Should be straightforward to map users yaml to rdf and load into
blazegraph. Not sure Minerva needs to know about it as such

Jsonld or python to convert?

**Comment by balhoff** [comment]
Minerva will need to be updated to return the labels. Currently it's just returning a set of annotation properties and values, but it will need to go one level deeper to get labels for the values.

**Comment by cmungall** [comment]
@balhoff not totally followig you here.

**Comment by balhoff** [comment]
@cmungall the Minerva metadata service returns entries like this:

```json
{
"gomodel:5745387b00001254": [
                    {
                        "key": "contributor",
                        "value": "http://orcid.org/0000-0001-7476-6306"
                    }
]
}
```
Wouldn't this need to be changed so that the value has both an `id` and a `label`?

**Comment by cmungall** [comment]
Ah I see. Ok I'm not sure how this was handled previously

**Comment by kltm** [comment]
@cmungall Previously this was done by epione, cheating and looking things up in a cache of users.yaml before pushing the metadata out to golr.

**Comment by cmungall** [comment]
* [ ] include metadata as ttl as part of releases
 * [ ] include metadata RDF in go-lego import chain (available via either owlapi or sparql)
 * [ ] modify meta-get operation to include curator labels
 * [ ] modify GPAD export to include group label (#119)

**Comment by balhoff** [comment]
JSON-LD context for converting to ttl here: https://github.com/geneontology/go-site/pull/442

**Comment by balhoff** [comment]
The blocker for work on this in Minerva is the two steps outlined by @cmungall above:

> - include metadata as ttl as part of releases
> - include metadata RDF in go-lego import chain (available via either owlapi or sparql)

Where do we need a ticket for these things (go-site?) and who can do this? Basically the JSON-LD context which I added in https://github.com/geneontology/go-site/pull/442 needs to be used to render the YAMLs as RDF, and the result needs to be made available.

cc: @kltm @dougli1sqrd

**Comment by kltm** [comment]
Okay, I think the question then was if we were going to bring in Ruby dependencies into the pipeline or if we were going to use Jena.

**Comment by kltm** [comment]
@balhoff Just so you know, while we haven't merged it in with the snapshot releases yet, we have some initial product for the users and groups TTLs:
 http://experimental.geneontology.io/metadata/users.ttl
 http://experimental.geneontology.io/metadata/groups.ttl

The forever home will be http://snapshot.geneontology.org/metadata/users.ttl, etc., when we've done a few more merges.

**Comment by balhoff** [comment]
@kltm the metadata will now include a `label` key for annotations describing contributors (next time you update minerva from master). You can use this to display user names.

**Comment by kltm** [comment]
@balhoff The forever homes went live a few days ago:
http://snapshot.geneontology.org/metadata/groups.ttl
Same data, different day.

@lpalbou was looking at this for the landing page.

We still need to work on getting this into the Graph Editor and maybe SAE.

**Comment by lpalbou** [comment]
So yes, if minerva provides the `label` field for a contributor, it is a very easy fix in NoctuaLanding.js::_model_contributor_list:
`			    var url = '<a href=' + row.value +
				    ' target="blank">' + row.label +
				    '</a>';
` 
(replacing row.value by row.label)

If minerva does not always returns the label field for a contributor, it seems that [users.ttl](http://snapshot.geneontology.org/metadata/users.ttl) is up to date, so we could use that.

@kltm will minerva always send a label field for a contributor in `models_meta[model_id]` or do we have to take care of undefined values ? If undefined values are to be expected, I will have to change my code to use [users.ttl](http://snapshot.geneontology.org/metadata/users.ttl) before submitting a PR.

**Notes**: 
* a fresh local install of both minerva/noctua did returns the `label` field, but using a local noctua interrogating the public minerva provided no label field:
`
{key: "contributor", value: "http://orcid.org/0000-0002-1706-4196"}
`
* In case of multiple contributors, I added a bit of formatting to take less place (first letter of first names + last name, like): Laurent-Philippe Albou => L.P.Albou

**Comment by balhoff** [comment]
Returning contributor labels was recently added to Minerva, so it's only deployed on noctua-dev so far. This comes from users.ttl via go-lego.owl.

**Comment by balhoff** [comment]
I would still assume in the display code that it is possible for a label to not be provided.

**Comment by kltm** [comment]
Also, the landing page should only really be using data from Minerva, rather than using external information. The display code should be robust enough to work if the label is not provided.

**Comment by lpalbou** [comment]
Just to be clear on what we want: if no label is provided, do we want something like `<a href="orcid-url">Contributor</a>` or do we want to try and find the label by other means (e.g. name from users.yaml ?)

**Comment by kltm** [comment]
The lack of a label should be a bug in the data more-or-less. The label should be shown if there and I'd fall back on the local ID of the ORCID if not--the lack of a label means that somebody needs to go and fix the data.

**Comment by vanaukenk** [comment]
Names are displayed on the current Noctua landing page.  If curators request groups to be displayed as well, we can open a new ticket.
