### ISSUE TITLE
resolve PRO IDs to something more useful

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#381]
Hi,

I am finding it really difficult to understand my own models using modified protein forms indicated by PRO IDs,  e.g. PR:000049741, PR:000004201 since they don't show what gene I'm talking about. Here's a model that uses PRO IDs both for organism specific modified forms and for a gene level term that is the parent term for the human and mouse specific terms for ARF1 (to represent that the authors specify use of Arf1 without making it clear which species they used).
http://noctua.berkeleybop.org/editor/graph/gomodel:581e072c00000473 

It would be really helpful if these PRO IDs, resolved to something more human readable in the annotation boxes. I know the PRO term names are ridulously long and not always that helpful anyway, but I think we could do something more user friendly.

**PRO terms that resolve to a specific gene from a specific organism**
For terms that are organism specific (organism gene, organism-modification, or organism-sequence category terms), could we include the gene name as well as the PR:## ID in the brown boxes for the **enabled by** entities, perhaps something like this:
* from **enabled by(PR:000049741)**
* to **enabled by(Asap1 Mmus:PR:000049741)**

**PRO terms that are NOT organism specific**
For terms that are NOT organism specific (gene or sequence), could we include the PRO synonym of the type **PRO-short-label**, so something like these:
* **has input(ARF1: PR:000004201)**
* **has input(KALRN/iso:9: PR:000037839)**

**Additional info on mouseover**
It would be really helpful if the mouseover info for PRO terms. Looking at the entry pages for various entries on the PRO website, the pieces of information I would find helpful are in the **Synonyms** and **Definition** fields. It seems it might also be good to include the **PRO Category**. I usually don't find the **PRO name** to be very useful, so I'm not asking for it to be included, but I don't have any objection if someone else feels it should be included.

thanks,

-Karen

_Sample organism-modification level term_
* an Asap1 proteoform: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000045553/

_Sample gene level terms:_
* ARF1: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000004201/
* ASAP1: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000004338/
* AGER: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000003828/
* KALRN: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000009238/

_Sample sequence level terms:_
* KALRN:ISO:9: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000037839/ 
* KALRN:ISO:2: http://research.bioinformatics.udel.edu/pro/entry/PR%3A000038224/

**Comment by kltm** [comment]
Dupe #122.
