### ISSUE TITLE
Mouse proteoform annotations are not in the GPAD file

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#384]
Hi @balhoff ,

Hopefully this is the right tracker for this issue. In this model:

http://noctua.berkeleybop.org/editor/graph/gomodel:581e072c00000473

Karen made this model and made annotations using PR:000049741. This represents a non-modified proteoform of a mouse gene. The annotation is not showing up in the production GPAD file even though with the current rules it should. The entity is in the MGI GPI file.

@krchristie 

-David

**Comment by kltm** [comment]
geneontology/minerva#78
