### ISSUE TITLE
Unclear where to send bug reports for Noctua

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#386]
It is not obvious for curators using Noctua that they should use this tracker to report bugs. Does it make sense to have a link to it from the Noctua home page?

**Comment by kltm** [comment]
Both **About** and **Help** can get you back here. What are you looking for exactly? Maybe directly into the issue tracker instead of the project?

**Comment by cmungall** [comment]
I agree with @kltm - if it's in the QS guide too then we're golden (see PR above)
