### ISSUE TITLE
Change hard coded relations heirarchy in noctua

### ISSUE THREAD

**Issue by dosumis** [geneontology/noctua#392]
![image](https://cloud.githubusercontent.com/assets/112839/21237186/cef44da8-c2f5-11e6-9d1a-ae0c5f456708.png)

directly inhibits -> directly negatively regulates (RO:0002630)
directly activates -> directly positively regulates (RO:0002629)

**Comment by kltm** [comment]
Tag back: https://github.com/geneontology/go-ontology/issues/12811

**Comment by cmungall** [comment]
We also want these two:

```
As discussed on the annotation call this morning, the two additional Noctua relations to be added to the hardcoded GO relation hierarchy are:

id: RO:0002304
name: causally upstream of, positive effect
comment: holds between x and y if and only if x is causally upstream of y and the progression of x increases the frequency, rate or extent of y
property_value: http://purl.org/dc/elements/1.1/creator "cjm" xsd:string
is_a: RO:0002411 ! causally upstream of

id: RO:0002305
name: causally upstream of, negative effect
comment: holds between x and y if and only if x is causally upstream of y and the progression of x decreases the frequency, rate or extent of y
property_value: http://purl.org/dc/elements/1.1/creator "cjm" xsd:string
is_a: RO:0002411 ! causally upstream of
```

**Comment by kltm** [comment]
Not recently, this just jogged my memory. I'll retest sometime soon and let you know. But what we will do is:

    Take Minerva offline.
    Make a backup copy of the journal.
    Run a series of SPARQL updates against the journal using minerva-cli.
    Relaunch Minerva.
    Trigger the normal dump to ttl procedure and inspect the git diff as a sanity check.

**Comment by cmungall** [comment]
This is purely a client side change, not sure why SPARQL updates are relevant?

**Comment by kltm** [comment]
As this is part of the action for  geneontology/go-ontology#12811

**Comment by dosumis** [comment]
@kltm - Any idea when this might be fixed.  It's causing confusion in discussion of modelling in noctua and related design patterns.

Cheers.

**Comment by kltm** [comment]
I've penciled this in for Monday. Hopefully we can use that downtime to also coordinate the model updates (@balhoff, maybe we can touch bases at meeting next week?).

**Comment by dosumis** [comment]
Sounds good.  Can the synapse OWL files  be test loaded a the same time? It would be great to have them in time for the synapse meeting on Tuesday.

**Comment by kltm** [comment]
Maybe we could pick this up in a separate forum, but the models are currently on an unmerged branch pending fixes; as well, we have not discussed their lifecycle within Noctua.

**Comment by dosumis** [comment]
> Maybe we could pick this up in a separate forum, but the models are currently on an unmerged branch pending fixes; as well, we have not discussed their lifecycle within Noctua.

Ahh.  Missed that you'd already tried loading.   I'll reply on the Pull request.
