### ISSUE TITLE
Update Minerva to release 0.3

### ISSUE THREAD

**Issue by balhoff** [geneontology/noctua#395]
I decided to start tagging releases of Minerva so we can better track what is deployed. The latest, which includes the OWL API bug fix for RDF processing, is https://github.com/geneontology/minerva/releases/tag/v0.3.

**Comment by kltm** [comment]
Great! It might also be good to get it to self-report, adding it to the info when using the `--version` flag.

**Comment by kltm** [comment]
@balhoff Could you also tag on the tickets this will fix/affect?

**Comment by kltm** [comment]
@balhoff I'm still a bit bandwidth limited (literally); for the main use of this change, we don't need to re-deploy Noctua, right? It's mostly for the pipeline, IIRC?

**Comment by balhoff** [comment]
It's actually both. The RDF problem causes some model annotations to not show up, for example a model tagged as `production` may show up as `development` if the annotation isn't read (this is random). Then the model may end up with two values for the annotation if someone makes a change.

**Comment by balhoff** [comment]
This will address https://github.com/geneontology/minerva/issues/82 and I think https://github.com/geneontology/minerva/issues/81.

**Comment by kltm** [comment]
Okay, I don't really have time to test, but I do have time to put it up, and revert if necessary, before I disappear for a few days. I'll go ahead and deploy it now--nobody seems to be actively doing anything.

**Comment by kltm** [comment]
Should now be deployed.
