### ISSUE TITLE
Include all/more of RO in go-lego.owl

### ISSUE THREAD

**Issue by balhoff** [geneontology/noctua#396]
Not sure if this is the right place for this issue... For more complete GPAD inference we need to have more of RO loaded than is currently coming in via go-lego.owl. So we could change go-lego, or instead add configuration to Minerva allowing the full RO to be separately used in GPAD inference (complicating things). Would including all of RO by default cause problems?

**Comment by cmungall** [comment]
Other than making the list in the selector longer, no problems AFAICT. the selector list is not a huge problem as we now have the hardcoded hierarchy with common relations. So go ahead and do this (do you have permission on svn?)

curious as to why go-plus (imported by go-lego) doesn't have the rels you need? Other option is just to ensure they are included.

**Comment by balhoff** [comment]
There are some from the annotation relation list missing, at least `acts_upstream_of`, `acts_upstream_of_or_within`. Perhaps it would be enough to just add these, but I feel like there were some other inferences I was missing before I added the full RO to the graphstore.

**Comment by cmungall** [comment]
OK, it makes sense that these aren't in the main GO module since they 
aren't used in the ontology.

Let's do all of RO for now, we can go back and figure out how to make 
the module later

**Comment by balhoff** [comment]
Chatted with @cmungall about this and he will make the change to go-lego.owl.

@kltm that is right.

**Comment by cmungall** [comment]
Fixed in r38030

Should be visible in the purl in <1hr
