### ISSUE TITLE
Add ability to toggle to ID views

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#397]
(Edit from @kltm to have working ticket at top)
```
One thing that would make checking GPAD output easier 
would be to have gene IDs displayed somewhere in the editorial 
view on Noctua. It would probably be too much clutter to include 
them in the box with the activity, but when clicking on the green 
square, it would be nice to have the gene ID listed next to the 
entity name. These IDs are present in the autocomplete list 
when we first add entities. I can add a ticket to the Noctua 
tracker, if this request is more appropriate there.
```
(original below)

From https://github.com/geneontology/minerva/issues/61#issuecomment-271904829

This would be a toggle similar to screenshot mode etc.

It would affect rendering of all classes generically. If on, rather than `$label` we would show `$label ($id)` or similar. I suppose `$id` would also be an option but not sure if there is a use case.

**Comment by vanaukenk** [comment]
Thx @cmungall 

Yes, a toggle that would allow for display of label and id for all classes generically would be great.

**Comment by kltm** [comment]
This should be a relatively quick fix, without spaghetti. However, IIRC, it will be specific to this case and not affect rendering more generally.

**Comment by kltm** [comment]
I think this is no longer needed from creation of #437

**Comment by cmungall** [comment]
Would still be useful...

But we can wait and fold this in to a generic customizable renderer feature, OBO-Edit had it spot on here.

**Comment by kltm** [comment]
I think a lot of these can be revisited when we have a real framework--the overhead for adding features like this will then be minimal.
