### ISSUE TITLE
Autocomplete on NEO from within TPC

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#400]
Hi,

I'd like to be able to use NEO to autocomplete curation fields in TextpressoCentral so that the two tools are always working off the same lists of allowable entries for:

- GO terms
- Evidence codes
- Relations
- Entities, i.e. entries in the gpi file
- With/From values, e.g. WBbt terms

Is this possible via web services, and if so, how should we construct the URLs?
If not web services, would another approach be better?

Thx.

**Comment by kltm** [comment]
@vanaukenk 
Hm. While we can carry on some discussion here, it is likely no Noctua code will be touched in the closing of this issue. This is mostly a load issue. For all Noctua autocomplete, we feed off of public GOlr instances, so you can just pick things up there. That said, we did not have plans to make these full-on documented public instances, but we can come back to that--there is something to think about there.

So going down the list:
* GO terms: GO; "NEO" GOlr instance http://noctua-golr.berkeleybop.org/select
* Evidence codes: ECO; I *think* that's in NEO as well, but can be loaded separately or just use a public AmiGO endpoint; looking at what it going over the wire right now, it's aimed at http://amigo-dev-golr.berkeleybop.org/select
* Relations: RO; Noctua does not query these dynamically from a remote service, but rather uses a static listed generated by Minerva, but it is pretty much just RO.
* Entities: NEO, as above
* With/From values: Hm, I think his is more free-form right now, with no completion, etc; this could be revisited

At the end of the day, everything that you can use for your autocompletes *should* be included in the "NEO" GOlr load as above. If not, all of our interfaces are designed to work over GOlr/Solr, so it should be easy to piggyback there. As well, we have JS APIs for all of this stuff, so if you are just doinging client autocomplete, you should just be able to re-use/drop it in.

**Comment by vanaukenk** [comment]
Okay, thank you @kltm 
I'll confer with Michael and we'll be in touch if we need more help.

**Comment by kltm** [comment]
No problem. Just for reference, the fields we have for our solr loads, and the weights we use for queries, are kept in metadata files https://github.com/geneontology/amigo/tree/master/metadata
Mainly, we use the "general", "ontology_class", and "bioentity" configurations.

**Comment by vanaukenk** [comment]
Hi @kltm 
I'm at Caltech today and Michael and I are working on implementing the autocomplete for the TPC Noctua curation form.  Could you just send us an example URL of what a search for a GO term would look like?
Also, if you have any documentation we can look at for using the URLs above, that'd be helpful.
Thank you!

**Comment by kltm** [comment]
Sorry, the timing may be a little off--we're in CT (JAX) right now.
What language are you writing in? We technically use vanilla Solr (and that can be scraped easily from the wire on AmiGO pages), but we also offer a JS API as well.

**Comment by goldturtle** [comment]
Hi @kltm 
the system is programmed in C++. We would need some sort webservice call or postgres database call to retrieve list to fulfill autocomplete functionality. Does the above URL http://noctua-golr.berkeleybop.org/select provide this webservice, and if so, how?

**Comment by kltm** [comment]
Well, one could use Spidermonkey to get at the JavaScript directly, but that is probably a bit much here, unless you were wanting to do things like try and directly remote Noctua.

The URL that you mentioned is the current autocomplete/entity lookup server for Noctua. It is a completely standard Solr instance, something like version 3.x. The schema it run would look a lot like AmiGOs, http://amigo.geneontology.org/amigo/schema_details , often using the "ontology", "annotation", or "bioentity" personalities. This instance is loaded with @cmungall 's NEO (Noctua Entity Ontology, IIRC).

If you are using autocomplete in the HTML/JS browser client, it would probably be best to just use it there as a widget. If the C++ subsystem is requiring the autocomplete internally, that is a bit stickier. As a first pass, I would just mimic the generated REST queries that are getting passed when a user is using the autocomplete of interest. This is an unfortunately brittle method, as the schema may change in the future at some point (no plans now).
For AmiGO, in the future, we may offer a less fully featured "light" autocomplete API, maybe through the biolink api, but plans there are not yet concrete.

**Comment by goldturtle** [comment]
Ok, thanks. It makes it a bit clearer now. I'll follow up shortly.
