### ISSUE TITLE
Reasoner broken in noctua?

### ISSUE THREAD

**Issue by dosumis** [geneontology/noctua#402]
I expected to see some inference on this model:

![image](https://cloud.githubusercontent.com/assets/112839/22646632/3d9520fa-ec65-11e6-9ecc-ba3bff14c324.png)

Including these inferences on the cell proliferation node:

![image](https://cloud.githubusercontent.com/assets/112839/22646673/6ed9e4b6-ec65-11e6-9f59-96b3a4f42037.png)

Any clue why this is not working?

**Comment by kltm** [comment]
The reasoner seems to be working as far as the stack goes. Maybe @cmungall or @balhoff could speak to why you're not seeing what you expect here.

**Comment by cmungall** [comment]
Unfortunately the configuration is not very introspectable, but I suspect it's because minerva is using `--slme-elk`. The deeper classes will typically not be in the module.

We experimented with just using elk, no module extraction. I hypothesized this would actually be much faster since most of the slowness was actually in the module extraction step. AFAICR we were still somewhat reluctant to switch the config, but I don't recall why

**Comment by cmungall** [comment]
Previous discussion here: https://github.com/geneontology/minerva/issues/33

And yes, use of slme-elk is hardcoded in the gulpfile:

https://github.com/geneontology/ansible-machine-bootstrap/blob/master/templates/noctua/supervisor-minerva

**Comment by balhoff** [comment]
I checked and `slme-elk` is in use in the deployed Minerva. However I loaded that file into Protege and after running ELK I don't see the inferred types that @dosumis showed. @dosumis are you using only official release ontologies?

**Comment by balhoff** [comment]
The model has an instance of `CL:0002405` **gamma-delta thymocyte** which doesn't have any semantics in `go-lego.owl`. **gamma-delta T cell proliferation** `GO:0046630` refers to **gamma-delta T cell** `CL:0000798` in its logical definition.

**Comment by cmungall** [comment]
@balhoff if you have the same abox model combined with go-lego, and the proliferation class is not deepened, it could be because

 * Elk is not complete for Aboxes (still not sure which cases it covers and which it does not)
 * Different DP and/or OP is being used

**Comment by balhoff** [comment]
This works if you additionally import the complete `cl.owl`, but not with `go-lego.owl`. @dosumis had you added an import of CL?

**Comment by dosumis** [comment]
> This works if you additionally import the complete cl.owl, but not with go-lego.owl. @dosumis had you added an import of CL?

Yep.  

The inference to regulation of proliferation should work without this though.  I’ve seen work it in other models.

**Comment by dosumis** [comment]
Similar inference on reg seems to be working fine here:

http://noctua.berkeleybop.org/editor/graph/gomodel:580685bd00000071

**Comment by dosumis** [comment]
> If you can reference any CL or UBERON term within Noctua models, reasoning will always be potentially incomplete if the full versions of these ontologies aren't included.

Would it be viable to run a reasoner with complete ontologies (rather than just imports). If not, can we run SLME in the background to generate ontology slices on the fly for use in reasoning.  Perhaps this could be run in the background as terms are added?

BTW - doesn't TermGenie cope with this issue, and if so, how?

**Comment by kltm** [comment]
Any comment on the current status of this ticket? If it is still open/ongoing, please change the title to something more specific.
