### ISSUE TITLE
Function companion no longer working

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#404]
Hi,

I just tried to use the Function Companion but no annotations appear.  Is it down at the moment?

Thx.

**Comment by kltm** [comment]
Contacted URL empty.
http://amigo-dev-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=document_category:"annotation"&facet.field=source&facet.field=assigned_by&facet.field=aspect&facet.field=evidence_type_closure&facet.field=panther_family_label&facet.field=qualifier&facet.field=taxon_label&facet.field=annotation_class_label&facet.field=regulates_closure_label&facet.field=annotation_extension_class_closure_label&q=*:*&packet=2&callback_type=search&json.wrf=jQuery22407131653506979004_1486678603008&_=1486678603010

**Comment by kltm** [comment]
Load failure due to:
https://build.berkeleybop.org/view/GOlr/job/load-golr-tomodachi/314/
```
2017-02-05 00:26:02,336 ERROR (CommandRunner:4165) could not parse:http://purl.obolibrary.org/obo/go/extensions/go-lego.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/ro/annotations.owl> Cause: handshake alert:  unrecognized_name
```
See:
https://github.com/geneontology/go-ontology/issues/12998
https://github.com/geneontology/go-site/issues/65
https://github.com/owlcollab/owltools/issues/171

This was a few days ago, so I'm just going to reload immediately: https://build.berkeleybop.org/view/GOlr/job/load-golr-tomodachi/315/
@vanaukenk If you need it sooner, let me know and I can maybe juggle it over to the "production" AmiGO.

**Comment by vanaukenk** [comment]
@kltm - if it will be back up again by tomorrow, that's fine.

**Comment by kltm** [comment]
Apologies--there was a rash of pipeline breakages dues to some (mostly unknown) HTTPS/SSL issues in (probably) Java. See above.

The services offered by that workbench will be available in about seven or eight hours.

With the work completed on #260, after it is deployed to production, we will be able to fix workbenches separately and quickly.

**Comment by kltm** [comment]
Should be working  now.

**Comment by vanaukenk** [comment]
Thanks, @kltm 
All is working fine this morning.  I'll let you close out the ticket in case there's anything else you want to add.

**Comment by vanaukenk** [comment]
Ah, github page hadn't refreshed.  I see you closed it earlier this morning :-)
