### ISSUE TITLE
Remote resolution calls (autocomplete, IDs, etc.) not working

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#406]
The autocomplete for entities is down this morning. In addition, all the models are showing identifiers rather than gene symbols as the annotated object.

**Comment by kltm** [comment]
noctua-golr.berkeleybop.org/ down.
On `oven`.  We were wondering what else was on the machine when it went down. Looks like we have an answer. Will head up to restart.

**Comment by kltm** [comment]
This ticket will be closed when:

- [ ] the server is back up
- [ ] we have a monitor on it

**Comment by kltm** [comment]
@ukemi I'm away from a computer, but my reports are that it should be working now. I'll reopen if you're still having issues.
