### ISSUE TITLE
Curator notes

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#409]
Would be nice to be able to put a note or two pertaining to the whole model; 
Example: I have a list of PRO ids to be used but Noctua does not have them loaded yet; other things that one might want to make notes-to-self, other comments

**Comment by kltm** [comment]
You can indeed add notes to the whole model:

* On a model page
* Select [Model]
* Select [Edit annotations]
* Scroll to the bottom of the pop-up, enter text into "Comment", click "Add"

These will also appear then in the model editor screen at the bottom of the default tab under annotations.

If you are thinking more along the lines of an external notebook, we also have a feature coming up with #408 (partially implemented, if you look at the "Scratch" model on the Noctua landing/search page as an example) that will allow GitHub tickets and Noctua to talk to chat a little with eachother. Things that need to be done withing a model can then be accessed and managed via GitHub.

As I think this ticket is either covered, done, or already has a ticket, I'm going to mark this as all that and close for now.
