### ISSUE TITLE
Pipe-separated references coming from function companion treated as separate references in GPAD output

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#410]
Hi,

I'm working on a model:

http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00001662

and imported some MF annotations using the function companion.

The corresponding line in the GAF we upload to GO looks like this:

WB	WBGene00001401	fbf-1		GO:0003730	WB_REF:WBPaper00024407|PMID:15454534	IDA		F		H12I13.4	gene	taxon:6239	20071016	WB

The evidence for the imported annotation in Noctua looks like this:

direct assay evidence used in manual assertion; date: 2017-04-10; PMID:15454534; http://orcid.org/0000-0002-1706-4196; source: WB_REF:WBPaper00024407

The lines in the GPAD output look like this:

WB	WBGene00001401	enables	GO:0003730	WB_REF:WBPaper00024407	ECO:0000314			20170403	GO_Noctua		contributor=http://orcid.org/0000-0002-1706-4196|lego-model-id=gomodel:586fc17a00001662

WB	WBGene00001401	enables	GO:0003730	PMID:15454534	ECO:0000314			20170403	GO_Noctua		contributor=http://orcid.org/0000-0002-1706-4196|lego-model-id=gomodel:586fc17a00001662

So it looks like I am getting duplicate lines in the GPAD for each of the originally pipe-separated reference IDs.

Thanks,
--Kimberly

**Comment by cmungall** [comment]
This is ultimately due to overloading in the GAF. We're using the GAF to state ID mappings for paper IDs.

When it comes into Noctua, we lose the fact that 

`WB_REF:WBPaper00024407 owl:sameAs PMID:15454534`

I don't think Noctua should get into the business of mapping paper IDs.

Should we just pick one when we import in? The PMID?

**Comment by vanaukenk** [comment]
We might want to have a tiered approach, whereby PMID is the preferred paper ID for import, followed by doi, followed by MOD paper reference.

While looking into this issue, I was double-checking the GAF specs wrt references.  We make this statement about MOD paper IDs:

Note that if the model organism database has an identifier for the reference, that identifier should always be included, even if a PubMed ID is also used.

I don't recall why that is, but maybe someone else remembers?

**Comment by vanaukenk** [comment]
@balhoff @cmungall @kltm 
Just checking on the status of this ticket.  Is this something that is easy to fix, or does it require significant work under the hood?
Several groups, at least including FB, MGI, SGD, and WB, have multiple, pipe-separated entries in their reference column when there is both a PMID and a internal DB reference ID for a single reference.
Can the function companion be modified to import preferentially, as outlined above and summarized here:
1) PMID
2) doi
3) MOD reference

**Comment by balhoff** [comment]
@kltm where is the code that imports these GAFs? Is this a Minerva issue?

**Comment by kltm** [comment]
@balhoff The code that imports the "GAFs" (actually pulling info from Solr fields) is client JS Noctua code. If the model is correct in Noctua, it is the fault of the JS; if the model is correct, it would be the fault of the exporter (Minerva).

**Comment by balhoff** [comment]
@kltm the OWL model has triples like this describing the evidence:

```turtle
<http://model.geneontology.org/586fc17a00001662/586fc17a00001665> rdf:type owl:NamedIndividual , <http://purl.obolibrary.org/obo/ECO_0000314> ;
    <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0002-1706-4196"^^xsd:string ;
    <http://purl.org/dc/elements/1.1/date> "2017-04-03"^^xsd:string ;
    <http://purl.org/dc/elements/1.1/source> "PMID:15454534"^^xsd:string , "WB_REF:WBPaper00024407"^^xsd:string .

```

So the evidence has separate `source` relationships to "PMID:15454534" and "WB_REF:WBPaper00024407" (the comma is shorthand).

Either this is the "fault" of the JS, or the assumption in Minerva is flawed. Meaning Minerva *could* join together any sources that are related to the same evidence individual.

**Comment by kltm** [comment]
@balhoff 
Ummm...okay, this doesn't seem to be in 1.0; should it be?

Digging in:
```json
 "reference":["PMID:10508609","WB_REF:WBPaper00003692"],
```

Going into the client JS Companion code, it seems that I pass a list of refs to minerva as part of the evidence, but apparently get back the comma separated list above? If true (and I want to check some more), that would push the responsibility back onto Minerva.

**Comment by cmungall** [comment]
Yes, sounds like minerva just needs to do a `CONCAT` in the SPARQL that generates the GPAD
