### ISSUE TITLE
Autocomplete issues in Noctua

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#411]
@dosumis says:
https://github.com/geneontology/go-ontology/issues/13150#issuecomment-293315764

> I’ve been noticing general flakiness in GO term autocomplete this afternoon.  Was halfway through writing a bug report when it fixed itself.  Autocomplete on all other OBO terms seems to be working fine.

@BarbaraCzub says:

https://github.com/geneontology/go-ontology/issues/13150#issuecomment-293321257

> Unfortunately my autocomplete issues have not resolved themselves. In fact new ones (which can be seen in the same Nactua model 'SynGO no. 1c') have emerged since I sent the last message.

@BarbaraCzub, I don't have sufficient info to replicate this. Can you give more details? Is the problem lag, or that the term does not exist?

**Comment by kltm** [comment]
As it stands now, Noctua is unusable as no ontology autocomplete actually returns anything useful.
As the servers are responding, the issue would be the load. The loads were successful, so we need to dig into the data.

**Comment by cmungall** [comment]
It may be an issue with loads

This seems fine:
http://noctua-amigo.berkeleybop.org/amigo/load_details

However, this is not so good:
http://noctua-amigo.berkeleybop.org/amigo/search/ontology

One hypothesis is clobbering, but it should not be possible to clobber a whole ontology, and I believe owltools should load everything together in memory to begin with.

**Comment by cmungall** [comment]
Hmm,
http://noctua-amigo.berkeleybop.org/amigo/load_details

has this:
> 2017-04-10	2017-04-10	http://purl.obolibrary.org/obo/extensions/go-plus.owl

but this is an incorrect URL (which returns S3 XML which unfortunately the OWLAPI treats as an empty ontology)

I filed this https://github.com/owlcs/owlapi/issues/657

But it may not be directly related. It may be that gave the wrong IRI in go-plus which causes issues with imports

**Comment by kltm** [comment]
@BarbaraCzub 
I believe that Noctua autocomplete should now be working as expected and with the expected terms in place (when I tested).

@cmungall For future reference, could you give a little detail about the exact nature of the error?

**Comment by cmungall** [comment]
Thanks Seth!

Just to be clear, I was not reporting an error myself, I was transferring the information from the ontology tracker. I provided all the info I had.

**Comment by BarbaraCzub** [comment]
Hi @kltm and @cmungall 

Thank you for resolving the autocomplete issue. I have just checked my models and all the terms that were previously displayed as the GO term ID, are now displayed as GO term name. So this fix appears to have worked. Thanks!

Barbara
