### ISSUE TITLE
Add additional relations to hardcoded relation hierarchy selector

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#414]
cc @vanaukenk

**Comment by kltm** [comment]
Ticket needs an actionable body.

**Comment by vanaukenk** [comment]
@kltm @cmungall 

As discussed on the annotation call this morning, the two additional Noctua relations to be added to the hardcoded GO relation hierarchy are:

id: RO:0002304
name: causally upstream of, positive effect
comment: holds between x and y if and only if x is causally upstream of y and the progression of x increases the frequency, rate or extent of y
property_value: http://purl.org/dc/elements/1.1/creator "cjm" xsd:string
is_a: RO:0002411 ! causally upstream of

id: RO:0002305
name: causally upstream of, negative effect
comment: holds between x and y if and only if x is causally upstream of y and the progression of x decreases the frequency, rate or extent of y
property_value: http://purl.org/dc/elements/1.1/creator "cjm" xsd:string
is_a: RO:0002411 ! causally upstream of

Thank you.

**Comment by kltm** [comment]
How about https://github.com/geneontology/noctua/issues/392

**Comment by kltm** [comment]
Ideally, we can close these both into one ticket. Is #392 still valid?

**Comment by cmungall** [comment]
OK, let's move over there

**Comment by vanaukenk** [comment]
IIRC, there was additional work that needed to be done wrt #392, as discussed in https://github.com/geneontology/go-ontology/issues/12811

**Comment by balhoff** [comment]
That's right, the Minerva stuff I did for https://github.com/geneontology/go-ontology/issues/12811 is all done except for coordinating with @kltm to actually make the database edits, which hasn't actually happened yet.

**Comment by kltm** [comment]
@balhoff Which database are you referencing here?

**Comment by balhoff** [comment]
The embedded Blazegraph store in the production Minerva instance.

**Comment by balhoff** [comment]
We need to run some SPARQL updates on the content, for which I made a minerva-cli option.

**Comment by kltm** [comment]
It's slowly coming back to me. You've tested that on the current contents of noctua-models/minerva?

**Comment by balhoff** [comment]
Not recently, this just jogged my memory. I'll retest sometime soon and let you know. But what we will do is:
1. Take Minerva offline.
2. Make a backup copy of the journal.
3. Run a series of SPARQL updates against the journal using minerva-cli.
4. Relaunch Minerva.
5. Trigger the normal dump to ttl procedure and inspect the git diff as a sanity check.

**Comment by kltm** [comment]
Ah, that explains a bit why this stalled out.

**Comment by cmungall** [comment]
This ticket seems to be mixing two things:

 1. adding 2 additional relations to the hardcoded selector
 2. rewiring some of the existing models

Can we not just proceed on 1?

**Comment by cmungall** [comment]
OK, I see we have another ticket with the same title. I marked this as a dupe and then closed this. But I think this ticket has morphed into the ticket about rewiring the models? If so we should retitle it.
