### ISSUE TITLE
Noctua client unusable while owl:Nothing returns can be found by autocomplete

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#415]
Hello,

I keep having the problem that Noctua doesn't identify Dicty IDs when I try to add a full annoton or a function and in the enabled_by fields. It does recognize the ID when adding an individual, but since I'm still trying to learn the best way to add annotations this hampers my possibilities to try all options. For example DDB_G0280043, DDB_G0293936

Thanks,
Petra

**Comment by pfey03** [comment]
I should say I figured out how to work with using just the 'add individual' function, but still thought you should look at why it's not responsive, or is it because I'm in Europe and work on VPN? My internet seems fast enough to stream things.

**Comment by kltm** [comment]
Well, the good news is that understand what's going on. The bad news is that we'll have to purge the system, and that will take a few hours.

**Comment by kltm** [comment]
As noted, this could also be fixed by eliminating `topology_graph_json` from the autocomplete results, which are just a profile of the ontology_class search right now, but that is another ticket, and owl:Nothing is not a reasonable result for a search anyways (although not a showstopper).

**Comment by kltm** [comment]
See: https://github.com/geneontology/amigo/issues/428

**Comment by kltm** [comment]
As a note `rab8a` and `dictyBase:DDB_G0280043` should work once the fix is in.
The fix is still pending, do not try/test yet.

**Comment by kltm** [comment]
This is now cleared in the public noctua.

**Comment by pfey03** [comment]
Thanks for fas action!!
