### ISSUE TITLE
GAF output only generates MF annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#417]
Hello, 

When exporting a model to GAF, for eg: http://noctua.berkeleybop.org/editor/graph/gomodel:5900dc7400000138
Only the MF are exported, not the BPs. 

Thanks, Pascale

**Comment by cmungall** [comment]
Thanks for filing ticket.

One potentially confusing thing to note is that there are currently two procedures:

 * sparql-based, new, by @balhoff  https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/
 * within noctua and also https://build.berkeleybop.org/job/export-lego-to-legacy/ -- this is the older one

Clearly this is not a good situation, we should rewire, but in the interim it's important the core noctua team are aware of this current state of affairs and can inform curators as necessary. cc @ukemi @vanaukenk @monicacecilia @dougli1sqrd 

The sparql-based one is the one we should be targeting. In this case we are indeed missing the process associations:

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/5900dc7400000138.gpad/*view*/

Is this something you've seen @ukemi or @vanaukenk

**Comment by ukemi** [comment]
I suspect they are missing because there is no evidence on the relations between the functions and processes. But there are still issues with assigning correct evidence in the GPAD files once models become very branched. #407

**Comment by vanaukenk** [comment]
Yes, this looks to be an evidence issue.  Thinking out loud a bit here (and also based on some of the feedback I am getting from WB curators), perhaps some strategically placed reminders when curators select certain actions would be helpful.

For example, when you select Export GAF (or any other export file format), you get a window that says "Do you have evidence on all your relations?  Only annotations with evidence will be exported."

Or when curators are adding evidence, have a reminder that they need to choose evidence that includes 'manual assertion' (at least for now).

Although I'd love it if people read through all our documentation, I think we have to be realistic about how much text curators are willing to read and wherever we can, help them with immediate feedback, tips, etc.  When I was gathering specs for the CAF, the idea of wanting real-time feedback came through loud and clear.
