### ISSUE TITLE
Fix GPAD export from Noctua

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#418]
Continued from #416 

 - [x] rewire Noctua so it doesn't link to Heiko GAF exports, replace with sparql inferences (this repo, @kltm ) [DONE](https://github.com/geneontology/minerva/issues/105)
 - [ ] Document in the docs on this site (@cmungall)
 - [ ] Retire old Jenkins job (Heiko) <-- don't do this until @ukemi says ok
 - [ ] TBD: publish sparql-inference jobs to S3 or Jenkins (TBD, @kltm, @dougli1sqrd )
 - [ ] Decide on evidence strategy and document (@ukemi, @vanaukenk )
 - [ ] Ensure protein complex inferences are correct
 - [ ] Remove blocker: https://github.com/geneontology/neo/issues/17 (@cmungall)

**Comment by kltm** [comment]
Trying to determine severity and timeline here--"showstopper"/"hotfix" is pretty much drop everything and fix.

**Comment by kltm** [comment]
OI equal import: geneontology/minerva/#99

**Comment by kltm** [comment]
We'll need @cmungall and @thomaspd for this with @ukemi .

**Comment by ukemi** [comment]
and @vanaukenk

**Comment by ukemi** [comment]
- [ ] Be sure annotations to regulation terms are generated.

**Comment by cmungall** [comment]
What's the connection to 99?
