### ISSUE TITLE
Import from BEL

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#42]
Add import features from BEL:
http://neurolex.org/wiki/Category:Resource:Biological_Expression_Language_Framework

**Comment by cthoyt** [comment]
I'm maintaining @pybel and would be able to help facilitate this

**Comment by vanaukenk** [comment]
Not actively being worked on; maybe a Pathways2GO project?

**Comment by cthoyt** [comment]
true I have not been spending a lot of time on PyBEL at the moment but I'm not really sure what your comment means

**Comment by cthoyt** [comment]
Also a better link for BEL itself is https://biological-expression-language.github.io/
