### ISSUE TITLE
lack of connection between cell types and anatomical structures

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#420]
Often, it seems really ridiculous that I have to have the cell type and the anatomical structures in separate individuals and label the evidence between them. For example, in PMID-23525783-KRCX, I am trying to represent that 4 genes (Dnah5, Dnah9, Dnaic1, & Dnaic2) have been shown (by immunofluorescence evidence) to be present in a (9+2) motile cilium that is in an ependymal cell from a lateral ventricle (of the brain). 

For lack of anything sensible to do, I have labelled these two edges with the same immunofluorescence evidence that shows that each gene is present in the motile cilium.
* 'occurs in' edge between the individuals that indicate that (anonymous) function of each of these genes occurs in the '9+2 motile cilium' 
*  'part_of' edge between 'ependymal cell' and 'lateratal ventricle'

However, I keep finding to redundant and  really time consuming that I have to add the same evidence 3 times for something that isn't separable. In an experiment like this, the fact that the cililum is part of an ependymal cell that is part of a lateral ventricle is not shown by immunofluorescence, but is basic info based on the experimental setup, i.e. what tissue was used for the experiment.

**Comment by kltm** [comment]
@krchristie As stated, I'm not sure if this is a modelling issue (pinging @cmungall @vanaukenk @ukemi) or a use case for the template mechanism that is outlined #231 .

**Comment by cmungall** [comment]
This is a curation best practice question.

I would opt for not including evidence, and taking these as given. This is analogous to what we do now for c16, and I would assume that the evidence should not be required to get the CL class into c16 -- see #418 for general issues regarding GAF export. We should do an experiment and test this is rendered to GPAD as expected.

**Comment by vanaukenk** [comment]
We may want to work through a few more use cases here to agree on best practices.  I have models where I have experimental evidence that a gene/product is expressed in a given cell or tissue (e.g. by a promoter reporter fusion) but only ISS or IC evidence for a specific CC.  Sometimes, the supporting evidence for these two statements comes from different papers.  
I would like to be able to include both pieces of information in the GO-CAM model, but if the evidence for the two statements is different, we may need to restrict the GPAD export to the CC annotation only, without the accompanying cell/tissue in C16.

**Comment by krchristie** [comment]
I agree that we may not always want to tie things specific things together, but this is a situation that comes up a lot for mouse, and it is tedious to add the evidence in triplicate for something that is not separable in this particular experiment.

In moving forwards as part of being more specific with the evidence, it might be worth thinking of giving the curator some options to decide which things are tied together based on the same evidence.

**Comment by kltm** [comment]
This issue was moved to geneontology/noctua-models#30
