### ISSUE TITLE
more than one edit to individual per time opening the individual editing window

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#421]
The more I use Noctua, the more frustrated I get. I feel like I spend all my time opening editing windows, doing one thing which automatically closes the window, and then I have to reopen the same editing window multiple more times to do everything I need to do.

I would really like to have the option, at least as a permanent option I can select, if not the only workflow, to be able to have the editing windows not close till I click to close them, so that I can do multiple things without having to repeatedly open the same one.

**Comment by kltm** [comment]
Duplicate.
Requires: #399 
Similar: #117
