### ISSUE TITLE
Add ability to disconnect / reconnect edge to transfer relation (etc.) to different individual

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#423]
It would be really nice to be able to edit relationships by moving them from one individual to another individual. If I have realized I need to add an individual in between two existing ones, it would be a real time saver to be able to just move an endpoint of a relationship to the new correct individual.

Instead, what happens now if I try that is the the original relationship in the incorrect place stays, and  a new relationship in the correct place is created, but without the evidence. So, instead of being able to fix my model with one simple move, I have to do three things: 1. create the new relationship, 2. separately add evidence to the new relationship, 3. delete the old relationship.

**Comment by krchristie** [comment]
Actually, it's four things, since I have to select the relationship type again, instead of it keeping the existing one of relationship I wanted to move.

**Comment by kltm** [comment]
As stated, this is likely to be enough against the grain of the current toolkit that we're using that it is unlikely to be addressed this way.

That said, items like #352 (or an of the tabular/form inputs issues) would likely address the immediate problems.

**Comment by kltm** [comment]
For future reference to myself, I'm a little worried about the event stream in the graph on disconnect/reconnect. Currently, the action is stateless--a disconnect is a single concrete action. Disconnect/reconnect will have to be stateful, and I think that the updates as they are currently handled might be hard to track. I believe that an early version actually had this, but was buggy enough that it was dropped. I should check my notes there--the only thing I'm sure about is a large number of connect/disconnect issues in early versions.

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for now.
