### ISSUE TITLE
ability to edit evidence with statement

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#424]
It seems that there should be some way to edit the with statement available in the 'clone evidence' editor. It was pointed out that for an MGI allele, I need to use "MGI:MGI:12345", not just "MGI:12345". However, there is no overall way to fix this everywhere I have used the wrong with entry. Instead, I have to go find them (by **manually clicking** through every place I have evidence) and changing to the correct one.

**Comment by kltm** [comment]
As stated, given how brittle and marginal the "clone evidence" pop-up is, there is unlikely to be such functionality added in the current form of the application (#399).
That said, I believe that this use case is captured variously by form editing tickets and "update"/toolkit tickets. (#352, #165, etc.)

**Comment by krchristie** [comment]
Let me add that my main point here is not whether or not something gets added to the existing tool kit, but that it is on the list that there should be a better way to correct an evidence statement that has been used in multiple different places. It took me a really long time to find all of them in this model since I had used the same mutant phenotype line at least 10 times.

**Comment by kltm** [comment]
Yes, the various form/tab editing tools that are intended to replace the tabs at the bottom of the graph editor will give a quick searchable overview that is capable of making fast edits without climbing through the main editor interface.
