### ISSUE TITLE
Add option to hide tab set at the bottom of the graph editor

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#425]
I would often prefer to have more space in the editing panel, so it is sometimes frustrating that I can't adjust the vertical space taken up by the giant bar at the bottom that has four tabs in it, most of which I never use. I would like to be able to adjust the position of the dividing line between the bottom bar and the rest of the window, OR click a button to hide/reduce the bottom bar (which should then leave a small button for when I want to bring it back), OR both of those.

The "Info" tab seems generally useful, but it also seems like this info could be put into the bottom of gray-green bar on the left and just show up all the time.

I'm not even sure what I would do with the info in the other three tabs. 
* 'Individuals' - If I did want to see this list, it seems like it would still be useful to either be able to make it tall enough to see more of the list at one time, or to be able to open it into a new window. This tab doesn't seem very useful though, as this list doesn't _do_ anything. I can't click on it to highlight where that individual is in the model, or edit it.
* Indv. Rels. - This tab seems useless to the curator as it isnt' even close to human readable since the subject and object are only listed by their gomodel IDs, and some of the relationships aren't even translated into their names instead of the RO ID. I could see this tab being useful if I could select a row, see where it is in the model, AND use it to edit the relationship.
* Remote Activity - I can't even think of any use to the curator for this information.

**Comment by kltm** [comment]
It's possible that this could be partially addressed with toggling screenshot mode: [View] -> [Toggle screenshot].

There have been various utilities for the tabs in the past, but they are mostly placeholders at this point for most users.

Further action is ideally dependent on #399, but a half-measure may be easily added, a la the screenshot toggle mode.

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for now.
