### ISSUE TITLE
dragging relationship endpoints is misleading wrt actions performed

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#427]
While it would be nice to be able to must move a relationship graphically:

https://github.com/geneontology/noctua/issues/423#event-1073581580 

if this isn't going to do something useful, perhaps it should be completely disallowed since what it looks like is going to do is misleading with respect to what it actually does (as outlined in ticket referred to above.)

**Comment by kltm** [comment]
We can take a look at this at the meeting with more users. So far, most people seem to be okay with the current workflow, but of course there can always be improvements.

**Comment by kltm** [comment]
Related to #328 .

**Comment by krchristie** [comment]
Who is included in 'most people seem to be okay with the current workflow'?

I do not have the impression that most MGI curators currently trying to use Noctua are satisfied with the workflow. Honestly, I felt pretty open minded when I first started, but the more I use it, the more frustrated I am.

**Comment by kltm** [comment]
Well, given the number of complaints I've received about this specific issue at various workshops, tutorials, tracker, preview releases, and workflow viewing, this does not seem to be a particularly sore point with curators. Naturally, nobody is completely happy with any given workflow, and there are huge numbers of inconsistencies in the interface; many are addressed in various issues in this tracker, many are not.

For the case of this one point, given that it has marginal utility (people use it) and no alternative at this point (#328), it is unlikely to be addressed soon. While it is marked `wontfix`, we do have `revisit` on it for future consideration and precedence in the tracker.

**Comment by ukemi** [comment]
I wonder if it would be worthwhile to make a wishlist and have users rate their wishes. I also think it would be really nice to be able to drag the relations between individuals.

**Comment by kltm** [comment]
I think that a forum (Noctua WG?) might be better for a first pass at trying to get a feel for the way that users want the graph editor to go. Unfortunately, a lot of this is locked with lack of bandwidth and a toolkit/framework that will not allow further expansion in many directions. While it's good to capture user wishes, at this rate, many things will no longer be relevant by the time we get around to them (or rediscover them in the tracker).

For future reference to myself, I'm a little worried about the event stream in the graph on disconnect/reconnect. Currently, the action is stateless--a disconnect is a single concrete action. Disconnect/reconnect will have to be stateful, and I think that the updates as they are currently handled might be hard to track. I *believe* that an early version actually had this, but was buggy enough that it was dropped. I should check my notes there--the only thing I'm sure about is a large number of connect/disconnect issues in early versions.
