### ISSUE TITLE
Clean up, or at least decruft, the Noctua landing page

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#428]
The current landing page includes things like references to "wizards", menu items that no longer exist, and asking people to stay tuned for updates throughout 2016. It needs a little scrubbin'.

@cmungall @ukemi @vanaukenk Would it be possible for you to check the linked documentation and add anything that needs to be changed here? As well, if there is any specific verbiage you'd like let me know.
Otherwise, I'll just give it a quick once-over to remove the obviously old and/or wrong items and wording.

**Comment by vanaukenk** [comment]
@kltm 
I'm happy to look over the linked documentation.  @ukemi  - do you want to do this together?

**Comment by vanaukenk** [comment]
@kltm 
We do need to make updates to the Quick Start Guide.  Is the best thing to do here just to go to the md file, fork the project, edit, and then generate a pull request?  Thx.

**Comment by kltm** [comment]
Hey, yeah, if you're willing to that that, then please.

**Comment by ukemi** [comment]
Yes. Let's do it together @vanaukenk 
Lots to do before the meeting though.
