### ISSUE TITLE
Move towards having a plugin architecture

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#43]
Consider plugin architecture, maybe as part of refactor.
Would like to start a general framework for adding things like this on startup, scan plugins namespace and add things found to the plugins found, e.g.:

``` JavaScript
bbop.mme.plugin.foo = function([???]){
  this.name = "Bar";
  // ...
};
```

Has option of adding tab below.

Is one of these types: always on, toggleable, clickable.

Chris's DL query (#1) would be the clickable type--operating incrementally on that event, likely having the ability to add classes to the display to accomplish the activity.
Plugins would be able to store their own state.

I think that with this, several of the things in tabs now could be rewritten as plugins, improving code structure.

**Comment by vanaukenk** [comment]
@kltm - is this ticket still relevant?  If not, can you close it?
