### ISSUE TITLE
Reasoning broken in Noctua

### ISSUE THREAD

**Issue by dosumis** [geneontology/noctua#433]
Basic reasoning used to work in Noctua, but now appears to be broken.

e.g. the biological_process node here should show an inference to 'regulation of glucose metabolic process':

![image](https://cloud.githubusercontent.com/assets/112839/26148841/ef0d63c8-3aef-11e7-93d5-f144e108f32f.png)

Here's the same inference working in Protege (with ELK):

![image](https://cloud.githubusercontent.com/assets/112839/26148899/1d035792-3af0-11e7-9f0f-a3108bf9ba5a.png)

**Comment by dosumis** [comment]
It would be good to get this fixed ASAP - certainly before the Corvallis workshop.  It's much harder to demonstrate the utility of design-patterns/templates without it.

**Comment by balhoff** [comment]
Yesterday we tried to swap in the latest code which supports Arachne as the reasoner in the editor. But Seth ran into some issues with his testing environment which entailed unexpected work (#430). However I'm not sure why ELK isn't working for now.

**Comment by dosumis** [comment]
Pretty sure ELK was broken last week.  Only just got around to testing properly today.  

Here's a more accurate test showing ELK reasoning over OPA in Protege.

![image](https://cloud.githubusercontent.com/assets/112839/26157239/a7bede68-3b10-11e7-9cd2-5994b90cb8a9.png)

**Comment by kltm** [comment]
Not a dupe of https://github.com/geneontology/noctua/issues/402 ?

**Comment by dosumis** [comment]
Not a dupe of #402 .

That ticket highlights missing inference due to limitations in the import chain.  The missing inference here is one that doesn't require any imports.  

This comment mentions that a similar inference to that one that is broken here was working on Feb 7th:

https://github.com/geneontology/noctua/issues/402#issuecomment-277922596

**Comment by kltm** [comment]
Let's try and distinguish the titles then.

@cmungall Any thoughts here?

**Comment by cmungall** [comment]
First I need to know how it's configured? Elk? Elk+SLME? Is there a way to query the minerva API for this?

If annotation deepening is not in the profile for the reasoner strategy selected, then annotation profile is  not guaranteed. This matrix in the GO-CAM drive shows the tradeoffs for the different strategies:

https://docs.google.com/spreadsheets/d/1RZZCBhVfcTeiAfBOrAgKjhwVDBQ0dF9tJkaeDZ87_6o/edit#gid=0

Note for Elk+SLME (which has historically been what we have used, though justification was dubious in retrospect), deepening is not guaranteed. It may have worked on some occasions if the deepened class was already present directly or indirectly in the module

**Comment by dosumis** [comment]
> It may have worked on some occasions if the deepened class was already present directly or indirectly in the module

It worked consistently for internal GO axioms such as the regulation one above.    I'd settle for that for now.  

IIRC - Jim switched from ELK + SLME to straight ELK last Nov => much improved performance.  Would it be possible to use SLME to update relevant modules in the background as the model is built - e.g. adding a new CL node should prompt a check for whether it is in the import modules, followed by an SLME run to update in the background if not.

**Comment by dosumis** [comment]
BTW - the A-Box/OPA support issue for ELK is confusing.  The example above in Protege shows it successfully using a single OPA. As far as I can tell, it also works fine with chains of OPAs + the ontology to infer types.  Here's an example Noctua in from when reasoning was working:

![image](https://cloud.githubusercontent.com/assets/112839/26189063/a12710a4-3b9a-11e7-93f7-769b8c44bbe0.png)

(I believe this was with ELK.  IIRC I managed to replicate these inferences in Protege with the downloaded model.)

The lack of support seems to affect pure A-box queries.

**Comment by dosumis** [comment]
Looking at the reasoner trade-off matrix, it certainly looks like Arachne does everything we need.  From previous discussions, I understand that the main drawback is that it is hard to filter out all of the inferences that we would consider redundant for the purposes of deepening (e.g. from transitive closure).  Could we cope with this if we used Arachne for live reasoning -> deepening in Noctua?

**Comment by balhoff** [comment]
@dosumis the redundant inferences are no longer a problem for Arachne. So I think you would be pretty satisfied if we can get it deployed.

**Comment by dosumis** [comment]
Cool.  Looking forward to seeing it in action.  It will make demonstrating the utility of the new MF patterns/templates much easier.

**Comment by dosumis** [comment]
Fixed by #430

**Comment by cmungall** [comment]
How is the performance of Arachne when the complete T-Box is translated to rules to support deepening?

**Comment by balhoff** [comment]
Very fast.

**Comment by balhoff** [comment]
On my laptop it takes about 30 seconds to transform go-lego into rules and then build the data structures used by the reasoner. This is a one-time thing that happens at Minerva startup. Then to materialize all triples for a give model takes somewhere from 0.5 to 1 second.
