### ISSUE TITLE
Unable to add 'directly positively/negatively regulates' relations to a model

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#434]
Hi,

I'm working on a model and trying to add a 'directly positively regulates' relation between two activities, but am getting the following error message:

<img width="953" alt="directly_positively_regulates" src="https://cloud.githubusercontent.com/assets/1730534/26316587/badd63cc-3ee2-11e7-8df9-949d5f81451c.png">

Thx.
--Kimberly

**Comment by cmungall** [comment]
@kltm is there an easy way to determine what versionIRI of each ontology is loaded into Minerva?

I assume it should parallel:
http://noctua-amigo.berkeleybop.org/amigo/load_details

which has 2017-04-11, which is the latest public release, which contains the relation

```
$ curl -L http://purl.obolibrary.org/obo/ro.owl | egrep '(versionIRI|0002629)'
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/ro/releases/2017-04-11/ro.owl"/>
        <rdfs:subPropertyOf rdf:resource="http://purl.obolibrary.org/obo/RO_0002629"/>
    <!-- http://purl.obolibrary.org/obo/RO_0002629 -->
    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002629">
```

everything looks good here. This suggests either

 * minerva is somehow picking up an older or different import chain. Does it mirror the import chain on disk?
 * some other bug in minerva

**Comment by cmungall** [comment]
I examined the code, I think it must be number 1.

@vanaukenk can you just check, try using a different relation for the exact same two nodes. The other possibility is that there is just something weird with your model, seems unlikely but lets check

**Comment by vanaukenk** [comment]
Thanks @cmungall 
I just tried adding a 'positively regulates' relation between the same two nodes and that worked fine.

**Comment by balhoff** [comment]
Taking a look at the command arguments on toaster shows that Minerva is using a catalog file here: `/home/swdev/local/src/svn/geneontology.org/trunk/ontology/extensions/catalog-v001.xml` If I am reading things correctly, I think the local copies of ontologies there are out of date.

**Comment by kltm** [comment]
@cmungall You opened a ticket for this last week here: https://github.com/geneontology/minerva/issues/104

**Comment by kltm** [comment]
@balhoff I'll try a restart once things clear out on the server.

**Comment by kltm** [comment]
This seems to work now.

**Comment by vanaukenk** [comment]
Yes, I just added the new relation to my model.  Thank you all!
