### ISSUE TITLE
Create buttons in Create tab on landing page don't work

### ISSUE THREAD

**Issue by elserj** [geneontology/noctua#435]
The "Create" button from the "Create" tab on the landing page does nothing. Looks to me like there is no code associated to the button on submit. 

Initial ticket in Planteome/noctua#9

**Comment by kltm** [comment]
Looking at this, it seems that the top and bottom button do not respond. 

This is in the "go" context, so this may be different in other contexts.

Likely just a manager fix is necessary, but maybe it is time for them to be removed? Given that this is the first complaint and we've heard nothing from curators, it may be that this could just be removed.

**Comment by elserj** [comment]
I should point out, on ours, I just commented out the line for the Create tab in templates/noctua_landing.tmpl.

**Comment by kltm** [comment]
It seems that the id/button mappings got mixed-up/disconnect during the development of the phenote sub-client. Looking at it, without a little thought, the rewiring would likely disrupt something in there. I'm going to go ahead and just remove or deactivate these parts.
