### ISSUE TITLE
Fix watcher for inconsistent-p flag

### ISSUE THREAD

**Issue by balhoff** [geneontology/noctua#436]
Currently if the model is inconsistent (according to the reasoner), the background stays gray to indicate reasoner mode but no inferred types are shown (understandable). However I don't see any notice that the model is inconsistent.

A slightly different issue is that with Arachne, inconsistencies are pretty localized, so that it would be useful to display which individuals have been inferred to be instances of owl:Nothing.

**Comment by kltm** [comment]
Noctua has the mechanism, but if Minerva is not reporting, it won't display. The issue would be in Minerva methinks.

**Comment by kltm** [comment]
Aaaarrrgghh!
