### ISSUE TITLE
Add label-ized version of new GPAD output to informational tabs (or workbench)

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#437]
As discussed in a previous meeting, we really need a human readable version of exactly what annotations are being generated.

In the long term, this might be accomplished by having a Protein2GO style table of annotations.

In the short term, we agreed to have Noctua use Jim Balhoff's reasoner internally to generate GPADs. For human readability, it is also essential to add the gene and term names for all of the various IDs.

**Comment by kltm** [comment]
For the long term, I believe we're covered by items like #352 and maybe #150; it's generally recognized that the lower tabs are to be replaced with tabular information/editor.
However, when it comes to the "reduced product" associated with a particular model, there is still a need for quick feedback for the curators (tagging @cmungall )
@balhoff Now that we have Arachne pushed out and working, what is the state of the GAFs and GPADs available via the API?

**Comment by kltm** [comment]
Talking to @cmungall , to bridge the user case that falls between the GPAD output and the future tables editors (etc.), we'll try something along the lines of grabbing the GPAD via an API call and "enriching" it with the labels in the client-side model. Either with a table in the editor or a workbench.

**Comment by balhoff** [comment]
Nice!

**Comment by krchristie** [comment]
This is really awesome! :)

Just a couple requests. 

1. Could the line with the summary of how many annotations lines there are, e.g. "**Showing 1 to 17 of 17 entries**", be at the top as well as (or instead of) at the bottom. It's really useful to see this number right next to the option to change the number that are displayed, instead of having to scroll to the bottom to see how many lines are present and then back to the top to change the number displayed.
2. It would be more curator friendly if the title bar used the Name of the model instead of the ID, so
* this: **Annotation Preview for PMID-26023097-KRC Ift27 & Hspb11** 
* rather than this: **Annotation Preview for gomodel:591f58ab00000021**

or if you think it's essential to have the model ID present, then both, maybe like this:
* **Annotation Preview for PMID-26023097-KRC Ift27 & Hspb11 (gomodel:591f58ab00000021)**

**Comment by kltm** [comment]
For number `1`, the toolkit does not support such placement, so this could maybe be revisited when we switch to a new toolkit.

Issues `2` has been fixed and will be available after the next restart.

**Comment by krchristie** [comment]
Thanks Seth!

Since the preview is so fast, perhaps the default could be higher, maybe the 50 instead of the 10. That would minimize the need to change the setting to see all.

For future, when we switch to a new toolkit, it would be great if the summary line was at the top.
