### ISSUE TITLE
visualization of evidence within graph

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#440]
It would be really helpful if there was an option to visualize all of the evidence within the graph.

It is currently quite tedious to have to click through a bunch of evidence boxes to see what is in each one if I need to check if I've put the right evidence in the right place. As suggested in today's Noctua meeting, visualization on mouse-over would be better than clicking, but is not a complete solution as it only visualizes one evidence statement at a time (perhaps all instances of that evidence at the same time). 

There are times where I would really like to see all the evidence that is present all at the same time. I realize that the evidence statements are too long to visualize well on the graph, so this might work best if there is a place for a curator to attach a short label (only for use within Noctua, not for export) to each evidence line. This short label might also be really useful in the evidence selection menu, as currently I find it difficult to select the correct evidence if I have multiple IDs of the same type in the with field, e.g. multiple MGI allele IDs or multiple UniProtKB protein IDs.

**Comment by kltm** [comment]
I suspect that addition textual information would likely work poorly in the interface as it stands, although hovers, coloration, etc. could be explored.
How about a tab for evidence information that could be tied the graph interface?

**Comment by krchristie** [comment]
I'm open to options, but I don't think I understand how a a tab for evidence information that could be tied the graph interface would allow me to see ALL of the evidence at the same time.

Maybe things should only be in the same individual if they have the same evidence, and then there would only need to be one section in the individual to show the evidence.

**Comment by kltm** [comment]
Well, for larger models, you would not be able to see all of the evidence anyways, there will likely need to be some additional steps to get full information. For this, an embedded tabular display could give a bit more flexibility there. However, likely little to be done until #399 is taken care of.

I'm not quite sure about your second comment--could you clarify that with an example?

**Comment by cmungall** [comment]
Let's discuss at the workshop

**Comment by vanaukenk** [comment]
Closing as we now have several options for seeing all the evidence and new functionality will not likely be added to the graph editor.
