### ISSUE TITLE
Add additional fields to to model-level annotation in "Info" tab in graph editor

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#441]
Originally as a side comment in https://github.com/geneontology/noctua/issues/439#issuecomment-303803590 from @krchristie: 

...it would be great if the "Annotation state", i.e. production, development, etc. was listed in the Info tab at the bottom, so I don't even have to open the menu to figure out if I've made it production or not.

**Comment by krchristie** [comment]
thanks!

not super important, but the title is now present twice, both as the **Name** field, and the title subsection of the **Annotations**

**Comment by kltm** [comment]
That is correct--I am trying not to filter model-level annotations at this point and title is just another one.
