### ISSUE TITLE
need for Login Success screen?

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#443]
Is there really a need for the "Login Success" screen?

It seems like an extra screen to click through every time I login without any info that is useful to the curator. Could successful login just take you directly to the Noctua landing page? 

If this login info (color, token) is needed, perhaps it could be tucked somewhere that you can access if needed without having a whole screen to click through to show it, but I can't think of a single time I have ever needed this info.

Also, if this screen can not be avoided, could the "Return" button be labeled something more intuitive, maybe "Go to Noctua" or just "Noctua".

**Comment by kltm** [comment]
For the time being, yes--there is still a separation between barista and noctua that needs to be maintained and it is just a single additional click.

**Comment by kltm** [comment]
That said, this may fall out naturally with the transition to "tokenless" management https://github.com/geneontology/noctua/issues/379

**Comment by krchristie** [comment]
For what it's worth, another MGI curator has expressed this wish to not have this extra screen every time too.
