### ISSUE TITLE
Annotations may be changing without direct action by user?

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#446]
Today I went in to check if I had consistently used MGI:MGI for my with fields for IMP and I discover that many of my annotation are now changed;
Example: 
for gomodel:5900dc7400000890 
The evidence used for an activity is now changed to 
imaging assay evidence used in manual assertion; http://orcid.org/0000-0003-2689-5511; date: 2017-05-10; PMID:18952058

I would NOT have made that; it's an assay, not imaging evidence.

In other models, the gene object is now separated from the process annotations (no more enabled by).
I don't see anyone else having edited my annotations.
Also, now I see that things are being autosaved (?); i severed a link but did not save the chage, but now I go in and the change is there.

**Comment by balhoff** [comment]
The 'imaging assay evidence' has been in the file since May 10: https://github.com/geneontology/noctua-models/blame/master/models/5900dc7400000890.ttl

So it doesn't seem like something that got swapped in after it was first created. Maybe it was an autocomplete mistake?

I will check into whether autosaving is happening. It shouldn't be but I made some changes to Undo/Redo recently. Have you been using Undo by any chance?

**Comment by hdrabkin** [comment]
No; 
If someone were editing/altering my annotations, is that somewhere is some history?

**Comment by hdrabkin** [comment]
I also noticed in our stats that I track that for some reason we have 7 less annotations from Noctua n our EI than we did last week. I'll have to ask around if anyone removed their annotations.

**Comment by balhoff** [comment]
It doesn't record who makes the edits; however the history of the file will be in GitHub, recorded at some interval throughout the day.

Something that may be confusing is that if you make a change but don't save, the change will still be there in memory. It won't be saved out to GitHub, but you will see it in the browser.

**Comment by hdrabkin** [comment]
Even if I close the tab, then re-enter Noctua (re-logging in) and returning to the model? I have not noticed that before.

**Comment by balhoff** [comment]
@kltm am I correct that Noctua/Minerva has always worked this way? Not sure about this.

**Comment by hdrabkin** [comment]
I don't ever remember this happening, but I'm old and my memory lapses. 8-)

**Comment by kltm** [comment]
Okay, catching up on this thread now.
* Any editing done on a model, even deletes (IIRC) should be captured as a model-level annotation.
* There is *no* autosaving
* If you look to the saved original model on GitHub, you can track what changed when at periodic intervals

**Comment by kltm** [comment]
The model seems to only have one contributor, so if any change was made, it was not by a user.
The only other mechanisms are direct model manipulation (sparql scripts or direct model editing). @balhoff unless you can think of something there...

**Comment by kltm** [comment]
Link to model in question: http://noctua.berkeleybop.org/editor/graph/gomodel:5900dc7400000890
Link to file in question: https://github.com/geneontology/noctua-models/blob/master/models/5900dc7400000890.ttl

**Comment by kltm** [comment]
This model has a very short history: https://github.com/geneontology/noctua-models/commits/master/models/5900dc7400000890.ttl

**Comment by kltm** [comment]
I see that @balhoff has already gone down this road. It looks an awful lot like this was pretty much there in the first place. And since it was there on the 10th before there sparql updates happened (on the 17th), there is no mechanism I know of where this could have happened.

@hdrabkin I'm afraid that without a pattern or a mechanism...

**Comment by kltm** [comment]
@hdrabkin Can you give links to other models where this happened?

**Comment by hdrabkin** [comment]
Here is one that really threw me; note the white boxes to the right.
http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00000000
note how the Enho and Cnt6 boxes is disconnected from two MF boxes that then go to processes. I never would have done that; the mfs would have  been used for mf enabled by Enho... 
I was returning to this model to make sure about the alleles in the with fields, and noted this. 
I also see that two of the evidences are "inferred from genetic interaction used with manual assertion". I don't recall ever using that code with noctua; begining to doubt my memory.
It's as if someone else had been editing, expanded the view but they never came back together again. 
I'll have to re-read the papers but again, I think I would have remembered doing these things.

**Comment by kltm** [comment]
@balhoff Could you verify that the links do not seem to be present in the first iterations of the models?

**Comment by kltm** [comment]
https://github.com/geneontology/noctua-models/commits/master/models/586fc17a00000000.ttl

**Comment by hdrabkin** [comment]
How would I do that?
I’m going to put them back in once I reread the papers
H

**Comment by hdrabkin** [comment]
Let's just close this;  I'll just go in and redo them .
