### ISSUE TITLE
Issue with accessing Noctua

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/noctua#447]
Hi guys,

I tried logging into Noctua with my GitHub account and it is not allowing to log in. It is reporting a bad session token. Any chance this can be fixed?

Best,

George

**Comment by kltm** [comment]
Noctua uses GitHub for authentication, not authorization.
You are currently not found in the users.yaml file, so you would not be able to login.
If you have already filled out the new user form, I'll input those before the workshop.
