### ISSUE TITLE
Warn user that evidence code is required to adding evidence

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/noctua#448]
When using the evidence dialog box, it is not intuitive that a curator is not able to **only** enter a source (e.g. PMID)  in support of the assertion.

It would be useful to have a warning, or a label (and a star?), clearly indicating to users that they must always enter an evidence code, and that the identifier for the source of the evidence can only be added to the model if an evidence code is also used. At the moment, the user can see an error message reading: "need all arguments for xxxxxxxx" (it looks like an identifier, md5?). 

It was not immediately clear that 'need all arguments' means that an Evidence Code is required. The error was specially confusing because I could enter only an evidence code without adding the source for the code I just used, and Noctua would take it, demonstrating that it does not actually 'need all arguments'. 

To reproduce: 
- bring up the 'evidence' dialog box
- enter an identifier for the source of the evidence, without adding an evidence code
- click 'Add.'

**Comment by kltm** [comment]
I think for most traditional GO annotation that this has been a pretty safe base assumption.
Maybe to revisit with bringing in non-GO curators?

**Comment by kltm** [comment]
Also, it should be noted that form validation will be occurring in any new framework #399 , likely making this a non issue.

**Comment by kltm** [comment]
Will look at fixing text.

**Comment by monicacecilia** [comment]
How did I know the life expectancy of this issue was going to be about 30 seconds.... o_O
