### ISSUE TITLE
Within editor, links should open in new windows

### ISSUE THREAD

**Issue by deustp01** [geneontology/noctua#449]
A new user discovered that once an evidence instance with a PMID citation has been saved in a Noctua project, when it's re-opened, clicking on the PMID:nnnnn string opens the PMID instance at NCBI. Neat! Definitely useful. The problem is that after the user is done with the NCBI page, this user at least gets rid of it by closing the NCBI window. That's too bad because it's not a new window so the "close" ends the Noctua session and loses any unsaved material in the project being edited.

So, to help avoid this error, could clicking on the PMID:nnnnn string pop open a NEW window or tab to display the NCBI information?

**Comment by kltm** [comment]
No material is lost when "closed".

**Comment by kltm** [comment]
I think that this will generally become an non-issue when #308 is likely rolled out more generally (i.e. raw IDs should not be exposed to users), But this is a more general issue.

That said, I'm not sure I think this is right. Links in a browser go new places. I think as long as we're uniform we're okay. That said, these links are not particularly "linky". Hmm...will ponder for a bit.
