### ISSUE TITLE
Batch application of properties

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#45]
Feature request by David when trying a more complicated example.

The take away from the request is that there is an option at the [model] level that says something like [Add PMID to all instances] -> pop-up with single input, and then batch request for all additions.

Time saver in larger models.

**Comment by vanaukenk** [comment]
@ukemi @kltm 
I'm working on cleaning up the Noctua tracker.  Would you like to leave this ticket open?

We do have 'clone evidence' in the graph, as well as shortcuts in the form (some existing, some new ones coming) to help make adding evidence faster.

Happy to keep this open for consideration for future Noctua development, though.

**Comment by ukemi** [comment]
I would like to see a project centering around graph editor enhancements. @ktlm, it would be good to have a brainstorming session about the kinds of feedback we have gotten from curators as well as what we see when we watch curators work. Could we leave this ticket open and put it in that project? Or perhaps close it and start from fresh.

**Comment by vanaukenk** [comment]
Would be good to roll this into a larger project on evidence workflows, but closing for now.
