### ISSUE TITLE
delimiters for numbers in causal relation icons

### ISSUE THREAD

**Issue by deustp01** [geneontology/noctua#450]
A new user creates a part_of relationship between two items in a Noctua model and sees the label "part of 0/2". Adding an evidence instance to the relationship changes the label to "part of 1/2". Okay, thinks the metrics-obsessed users, that's progress and now I'm 1/2 done. But what's the missing bit?.

If the "/" delimiter were replaced with one like ":" or "|" that people have been trained to recognize as a delimiter this bit of confusion might be lessened.

**Comment by kltm** [comment]
The issue is already around here somewhere, maybe folded in with one of the evidence visual redos...
