### ISSUE TITLE
Word wrap / overflow issue in some individuals

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/noctua#451]
Hi all,

Just wanted to report this bug where if you delete the type after cloning the original entry, then editing the clone by deleting the type and entering in the new one. Not a big deal but figured I would make you aware. 
![noctua_1_bug](https://cloud.githubusercontent.com/assets/21035247/26764580/1d229a12-491e-11e7-978a-342dfc347baa.png)

Best,

George

**Comment by ggeorghiou** [comment]
![noctua_bug](https://cloud.githubusercontent.com/assets/21035247/26764613/ada3874a-491e-11e7-828f-2e2fca3917f7.jpg)

**Comment by kltm** [comment]
I'm not quite following here--could you supply a link to the model?

**Comment by kltm** [comment]
Is the reported issue the different labeling on the activity (possible issue) or the bounding box issue (I'm guessing you're on firefox then?)

**Comment by ggeorghiou** [comment]
Yes, this is in regards labeling on the activity where it does not fit on the box. I am doing this on firefox. Model is ID gomodel:593423e000000159

**Comment by kltm** [comment]
Talked quickly with @ggeorghiou to clarify.
This is a know issue that may actually be a bug in firefox or jsPlumb (or something). This has been persistent for some time; for the time being, users annoyed by this are recommended to use Chrome.

**Comment by kltm** [comment]
No known way to attack the bug at the moment, but marking it here and moving on.
