### ISSUE TITLE
Sometimes GO IDs lack labels in Annotation Preview

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#452]
Spotted by @RLovering 

http://noctua.berkeleybop.org/editor/graph/gomodel:593423e000000473

We see some inferences through annotation deepening to PMPBPP and 'neuron part'

![image](https://cloud.githubusercontent.com/assets/50745/26765288/d72d839a-492d-11e7-9925-c98c4139b540.png)

These are correct, all good

In annotation preview:

http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:593423e000000473&barista_token=

We see the inferred types are shown as bare IDs, no labels:

![image](https://cloud.githubusercontent.com/assets/50745/26765299/184c60a8-492e-11e7-84f8-5f39fa5b4e11.png)

I hypothesize this is due to the label lookup being done on what is loaded from minerva about the asserted model

**Comment by kltm** [comment]
So let's narrow this down to a single test case for now; `GO:0120038`. The label should be `plasma membrane bounded cell projection part`. This is not, however, found anywhere in the "standard" model, but may be findable if we requested and processed the reasoned data from minerva.
