### ISSUE TITLE
Add a workbench for showing SPARQL query results in Noctua

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#465]
This workbench will show the results of sparql queries over an *individual* GO-CAM. The queries may be a mixture of reporting and validation. For validation there will be overlap with [SPARTA report](https://github.com/geneontology/go-site/tree/master/graphstore/rule-runner).

This could be implemented in different ways

 1. Minerva issues SPARQL queries, and returns payload in some TBD SPARQL format
 2. Workbench sends SPARQL to blazegraph (via barista/minerva) according to SPARQL1.1 protocol

**Comment by kltm** [comment]
When is the interactivity here with a model/set/etc.?

**Comment by cmungall** [comment]
Analogous to annpreview - no modification of models

As an extension we may want the option to allow repair for a subset of rules. For example, https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000020.md

for 'replaced by', there could be a checkbox for auto-repair with the suggested replacement. For consider there would be a selection.

But we'd need to think about this. The generic way to do the repairs would be via a SPARQL update, which has various issues eg syncing with minerva in memory models

But this ticket is about the reporting aspect

**Comment by cmungall** [comment]
@kltm did I imagine there was a bbop-manager-sparql package?

**Comment by cmungall** [comment]
I'm going to add some rules to get us started:

 * [ ] the subject of an enables relationship must be an instance of a molecular function (see https://github.com/geneontology/noctua-models/issues/44#issuecomment-328123441)

(more to come, i will edit ticket)

Note some of these may be implementable by reasoning rather than queries, eg the enables restriction but this gets a bit awkward in some cases, and in any case some redundancy may be OK here.

@dougli1sqrd can you start working on the query bank and implement in sparta for now and we can work on the workbench when @kltm gets back.

**Comment by cmungall** [comment]
Some examples of potentially useful non-violation reports (all in a single GO-CAM)

 * basic aggregate stats (number of distinct classes used, number of instances)
    * broken down by high level category (e.g. MF, BP, CC)

**Comment by kltm** [comment]
I’ve had some thoughts on this; I think what we might want is a custom format that can then be compiled to something usable by the UI we select (if we don’t go custom). I think a format with description, variable declarations, context (optional, see Noctua plugins), and template. These would be usable for both the general SPARQL frontend and Noctua/Minerva as canned queries that could appear in different context.

**Comment by kltm** [comment]
bbop-manager-sparql will hopefully be a product of this week.

**Comment by kltm** [comment]
bbop-manager-sparql will hopefully be a product of this week.

**Comment by kltm** [comment]
@cmungall @dougli1sqrd 

One use case set we have is both a goose/gannet replacement as well as canned queries for noctua to trigger on the client for minerva (which may partially or completely overlap with this ticket). I'd proposed that these both have the same format more-or-less, with something along the lines of what I'll be using elsewhere in noctua for grabbing external data using SPARQL; three variations of the exact same query in this proposed format:

https://github.com/berkeleybop/bbop-manager-sparql/blob/master/examples/template-01.yaml
https://github.com/berkeleybop/bbop-manager-sparql/blob/master/examples/template-02.yaml
https://github.com/berkeleybop/bbop-manager-sparql/blob/master/examples/template-03.yaml

**Comment by kltm** [comment]
There is now a `bbop-manager-sparql` in play.
As well, https://github.com/geneontology/noctua/blob/master/context/go/sparql-templates/pubmed-info.yaml is used in-repo as well.

**Comment by kltm** [comment]
This is essentially complete, but I'm running into some cross-site issues.

**Comment by kltm** [comment]
Completed, except for a talk about what to pass back (and the extension of bbop-manager-sparql) to handle it.

**Comment by vanaukenk** [comment]
@kltm @cmungall - do you want to keep this ticket open?

**Comment by kltm** [comment]
I believe that this is probably safe to close for now, unless we change tack.
