### ISSUE TITLE
Order of evidence in display is not consistent

### ISSUE THREAD

**Issue by chris-grove** [geneontology/noctua#466]
When I'm adding evidence to a node or edge of a noctua graph, the existing evidence is listed with the evidence code first, but then an inconsistent order of the remaining bits, such that the PMID, "with" entry, submitter ORCID ID, and date of entry are listed in varying orders, making it often difficult to compare and see which pieces of evidence have already been added. Here's a screenshot:

![screen shot 2017-07-18 at 10 45 03 am](https://user-images.githubusercontent.com/611382/28323535-2adfb8a0-6ba7-11e7-803d-c1909c79af4f.png)

Could these fields be listed in a consistent order to make it easier to review the existing evidence entries?

Thanks!

**Comment by kltm** [comment]
Huh. My initial reaction was `wontfix` as this all needs to be redone anyways and we're trying to avoid spending too much time on surface stuff (the every-present #399), but I'm not even sure why this would be happening in the first place--I'll dig in and see what's up.

**Comment by kltm** [comment]
Going to guess "random" iteration through annotation hash.

**Comment by kltm** [comment]
Pushed to production.

**Comment by chris-grove** [comment]
@kltm   Beautiful! That's perfect! Thanks!
