### ISSUE TITLE
Xenbase entities not usable in Noctua (issues with NEO?)

### ISSUE THREAD

**Issue by malcolmfisher103** [geneontology/noctua#467]
Trying to use the recently added Xenbase entities in Noctua gives the following error.
![image](https://user-images.githubusercontent.com/23216004/28332244-1e163cd2-6bc2-11e7-998e-ea764094d8de.png)

In addition the naming of the Xenbase entities is not up to date with recent Neo builds. The suggestions still show the naming from the first time the entities were loaded, not reflecting subsequent change from separate species identifiers to the higher level 'Xenopus' genus identifier.
![image](https://user-images.githubusercontent.com/23216004/28332566-47cdb856-6bc3-11e7-8d83-23b2a26ff870.png)

**Comment by kltm** [comment]
I wonder if this is not actually due to the fact that we have had restarts of Minerva recently, but have actually paused the NEO loading since the Stanford outage (I forgot to turn that back on).

The test will be to add an individual like `ephx2.L`.

The load normally goes over the weekend, and takes about two hours. Maybe I can do a restart later today/tonight when it will be less disruptive. Otherwise, we would have to wait for the regular timing over the weekend.

**Comment by kltm** [comment]
Things have been clear a while and it is still before 5am in the UK--I'm going to go ahead and trigger the reindexing.

**Comment by kltm** [comment]
That did not go well; paging @cmungall 
https://build.berkeleybop.org/view/GOlr/job/load-golr-noctua-neo/80/console

**Comment by kltm** [comment]
Second try working; odd the timeout.

**Comment by kltm** [comment]
@cmungall @balhoff neo instance reloaded (in retrospect obviously unnecessary) and minerva restarted fresh; the issue persists, although they are now correctly identified as `Xenopus`.

```
Error (error): Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Unknown URI protocol: Xenbase:XB-GENE-947549; your operation was likely not performed.
org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException: Unknown URI protocol: Xenbase:XB-GENE-947549
	at org.geneontology.minerva.curie.MappedCurieHandler.getIRI(MappedCurieHandler.java:114)
	at org.geneontology.minerva.server.handler.M3ExpressionParser.parse(M3ExpressionParser.java:61)
...
```

The key here likely `Unknown URI protocol: Xenbase:XB-GENE-947549` in the curie handler. Are the contexts still loaded at compile time? E.g: minerva/minerva-core/target/classes/amigo_context_gen.jsonld ?

**Comment by balhoff** [comment]
> Are the contexts still loaded at compile time?

Yes — I'll try to address this soon.

**Comment by kltm** [comment]
@cmungall In the meantime, it would be good to get something in there for xenopus; do you have a mapping in mind?

**Comment by kltm** [comment]
@malcolmfisher103 
I talked to @cmungall about this a little. There are a few factors here, and maybe we can start addressing these at the next GO meeting, but for the time being how would you feel about this solution?
What we need is for identifiers of the form `Xenbase:XB-GENE-947549` to be expandable to a "full" identifier. For the time being, we'd like the identifier to `http://identifiers.org/xenbase/XB-GENE-947549`.

**Comment by kltm** [comment]
Whoops--accidentally closed with comment.
This has now been pushed to production and tested: I can now use xenbase ids.

**Comment by malcolmfisher103** [comment]
@kltm 
That seems fine as a stopgap. Should the identifier information come from the 'db-xrefs.yaml' metadata?
