### ISSUE TITLE
DataTable update error in annotation preview workbench

### ISSUE THREAD

**Issue by dosumis** [geneontology/noctua#468]
![image](https://user-images.githubusercontent.com/112839/28599520-1dab2882-71e6-11e7-8996-be1d5e8f0544.png)

On model http://noctua.berkeleybop.org/editor/graph/gomodel:5970219a00000269

![image](https://user-images.githubusercontent.com/112839/28599541-43f91792-71e6-11e7-969a-ce21edef571c.png)

**Comment by kltm** [comment]
@ukemi Thank you for reporting this. I'm wonderig if this is just the same as #453 . If you destroy the preview tab and rebuild it, does it work fine?

Also, if you get the error again, could you copy the text into the issue so we can search on it in the future?

**Comment by kltm** [comment]
Nevermind, got it:
```
DataTables warning: table id=ann-tbl - Requested unknown parameter '1' for row 0. For more information about this error, please see http://datatables.net/tn/4
```
as alert popup.

**Comment by kltm** [comment]
@ukemi As I can reproduce with this model every time, would you mind leaving it be until maybe tomorrow so I can play with it?

**Comment by kltm** [comment]
can dupe.

**Comment by kltm** [comment]
Ah--apparently this is a condition that only comes up when there are no annotations to be had at initialization.

**Comment by kltm** [comment]
Hacky fix until (drum roll) we switch to better framework.
