### ISSUE TITLE
Has model gomodel:5970219a00000402 gone missing?

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#469]
This model seems to have disappeared.

http://noctua.berkeleybop.org/editor/graph/gomodel:5970219a00000402

**Comment by kltm** [comment]
I cannot find this in the GH history either.
Is it possible it was created, never saved, then got blinked out when we restarted last Sunday?

**Comment by kltm** [comment]
It looks like it was likely created, but never saved, blinking out on the last restart.
