### ISSUE TITLE
Relations: 'overlaps' in Noctua vs. 'part-of' in Protein2GO

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua#470]
Hello,

I was recently working in a CO-CAM model based on PMID:12181340:
noctua-model-id=gomodel:598826eb00000261\|contributor=http://orcid.org/0000-0002-3898-1727

After I looked at the exported GPAD file to check whether the individual annotations appear correct I was concerned that the relation used between a cellular component (primary GO term in an annotation) and a cell type (specified in annotation extension) was 'overlaps' rather than 'part_of'.

The screenshots below show how the Noctua-generated annotation compares to the same annotations generated in Protein2GO:

Noctua:
<img width="652" alt="screen shot 2017-08-14 at 10 49 31" src="https://user-images.githubusercontent.com/16541096/29266898-5010ff3e-80de-11e7-9631-1e889532510e.png">

Protein2GO:
<img width="799" alt="screen shot 2017-08-14 at 10 35 44" src="https://user-images.githubusercontent.com/16541096/29266351-62520320-80dc-11e7-9c9b-4ee5d23e655c.png">

I do not think the 'overlaps' relation truly reflects what the experimental findings show. If an experiment is done in a specific cell type, the cellular component being annotated does not 'overlap' with that cell, but it is in fact a 'part_of' it.

Why does this discrepancy exist between Noctua and Protein2GO? And how is it being addressed?

Based on the Noctua training, which I attended, my understanding was that the output from both Noctua and Protein2GO would be standardised to enable interoperability within GO. I think this is especially important now that GO-CAM data is available in GO annotation files and GO browsers.

Barbara

cc: @RLovering

**Comment by balhoff** [comment]
Hi @BarbaraCzub I took a look at the model and see that there are two relevant statements: 
- the molecular function *occurs_in* a terminal bouton
- the molecular function *occurs_in* a hippocampal neuron

The reasoner can infer that the gene product is *part_of* each of these. But there isn't enough information to know which one is part of the other. They must overlap though. Since you know that this terminal bouton is part of the hippocampal neuron, you can just put that in the model. Instead of saying the molecular function occurs in the hippocampal neuron, just connect the terminal bouton to the hippocampal neuron with *part_of*. And actually then the reasoner will infer the statement that the molecular function *occurs_in* the hippocampal neuron.

**Comment by BarbaraCzub** [comment]
Thank you for explaining this @balhoff . Now at least I understand why this happened, but I am still unsure about how best to approach the model to make the changes that you suggest. Is there a way to 'explode' one annoton at a time? I do not think I can make the changes that you suggest in the Noctua 'Editor' view? If I 'explode all out' (or choose the 'Compact' view, which is _not_ compact at all...), the model becomes very hard to manoeuvre due to the 'exploded' fragments being relocated to the very far rhs. Based on my experience, the 'exploded (all out)', or 'compact' view renders the model rather prone to errors, as it is easy to accidentally break edges, when you try to bring the 'exploded' far-away boxes back to the field of view. Or perhaps something is not right with my settings that the boxes 'explode' so far away?

**Comment by balhoff** [comment]
I was going to suggest 'Compact' view as the way to do this, but I agree that the resulting layout is hard to use. @kltm is there any way to  auto-layout the exploded view to make things easier to find?

**Comment by kltm** [comment]
A few, actually.

Easiest is under [Tools], "Compact layout (into 700)" will map all nodes into an area about the size of your screen, but keep all of their relative positions.

As well, under [Workbenches], there is the "Cytoscape layout tool", which can be used to do various transformations on a model, including group movement using shift + drag and drop.

For both of these, remember to save and refresh after you are happy with your new layout.

**Comment by BarbaraCzub** [comment]
Thanks @kltm 
I was not aware of the "Cytoscape layout tool". It gives a good first impression, but it does not show entities in the 'editor' view; whereas in the 'compact' view, too many boxes overlap, so it seems like a good solution only for small models.
Wrt to "Compact layout (into 700)", I do not find this option helpful, as it makes the individual boxes overlap as well, so again this is not a good solution for medium-large-sized models (or really any model that aims to cover all experiments from one paper), as it is too tedious to move the boxes around after compacting. 
Plus, how do you undo "Compact layout (into 700)"? There is not option to 'untick' it and bring back the previous layout, is there?
Based on this I think that working in the 'Compact' view from the very beginning is the best solution to avoid layout issues, when/if changes need to be made to a model, or the model needs to be compared to the output file.

**Comment by kltm** [comment]
@BarbaraCzub 
The layout workbench allows you to move between differently folded views, to apply different force layouts to them, and to bulk move sets of items. It should function easily on models into hundreds of nodes. It is not meant to be another view over the data, but rather a layout editing mode with access to cytoscape layout tools.
The compact tool is meant to be a gross way of compacting smaller models while keeping relative position. Unfortunately, for this (inline) tool, there is no "undo"--memory is only kept for the current user now. I would suggest redoing a layout in the layout workbench. We'll try and mark that to make more clear what will happen when you click.

**Comment by BarbaraCzub** [comment]
Thanks @kltm
