### ISSUE TITLE
Make changes to "Add annoton" wizard behavior in graph editor for restrictions and input

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#473]
These changes will make the add-annoton more similar to simple annoton editor, and also clarify #471 

 * enabled_by: leave as-is, including ability to force in CURIE (this is option 1 of #471)
 * MF:
     * restrict to MF ontology (or at least eliminate ability to force in CURIE).
     * keep behavior whereby blank entry -> root node with enables
 * BP:
     * restrict to BP ontology (or at least eliminate ability to force in CURIE).
     * if blank, don't add any individuals (rather than root instance as it is now)
  * CC:
     * restrict to CC ontology (or at least eliminate ability to force in CURIE).
     * if blank, don't add any individuals (rather than root instance as it is now)

I think we can also remove add-function and add-process wizards

**Comment by kltm** [comment]
To clarify, would a correct reformulation of "restrict to X ontology (or at least eliminate ability to force in CURIE)" be "restrict to X ontology and eliminate ability to force in CURIE"?

**Comment by cmungall** [comment]
> To clarify, would a correct reformulation of "restrict to X ontology (or at least eliminate ability to force in CURIE)" be "restrict to X ontology and eliminate ability to force in CURIE"?

correct.

**Comment by kltm** [comment]
Part of the issue here is that this is essentially undocumented behavior. I'll maybe try to add something to the UI that will indicate that users can indeed do (or not do) this.

**Comment by cmungall** [comment]
Suggested placeholder attributes:

 * GP: "GP ID or autocomplete"
 * MF/BP/CC: search for term

**Comment by kltm** [comment]
No text changes (would require reworking panel a little) and leaving in the BP and CC sections for now.
Otherwise, lightly tested and pushed into production.
