### ISSUE TITLE
Noctua model view - how to minimise the window below?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua#474]
When making a model in Noctua, is there a way to minimise or hide the (rather large) white area with "Info/Individuals/Indv. Rels./Remote Activity"?
![screen shot 2017-08-24 at 10 51 33](https://user-images.githubusercontent.com/16541096/29661070-dd52ccfe-88ba-11e7-8ac1-bfce15d646b5.png)
Or would it be possible to provide this functionality?

cc: @RLovering

**Comment by kltm** [comment]
Dupe of https://github.com/geneontology/noctua/issues/425
