### ISSUE TITLE
Updating annotations in a model without losing data

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua#475]
When working on a model in Noctua, is there a way to update a GO term and evidence within an annoton and/or between individuals (rather than having to create a new annoton and new edges)?

E.g.
ID - gomodel:5993df9e00000254
Name - SynGO no. 1f GLS2_PMID:24121663

In this model I originally added individuals, which resulted in an annotation, which showed that TP73 regulates the expression of _GLS2_, based on qPCR. That annotation was visually represented like the one in the screenshot below with the exception of the '[continuant]':
![screen shot 2017-08-24 at 11 09 01](https://user-images.githubusercontent.com/16541096/29661666-ab98967e-88bc-11e7-9182-cfe5bc1f6205.png)

After having made this 'regulation of gene expression' annotation, based on the qPCR, I came across additional ChIP and luciferase reporter assay evidence, which showed that TP73 actually bound to the promoter and regulated transcription:
![screen shot 2017-08-24 at 11 11 24](https://user-images.githubusercontent.com/16541096/29661799-063bfaf8-88bd-11e7-89ff-9ba1a358b765.png)

In order to capture this more specific information I needed to create new individuals and edges, clone the 'old' evidence and include the 'new' evidence, and then delete the 'old' individuals. 

Would it be possible to instead enable editing of GO terms and updating evidence within existing individuals and edges (or annotons)? Or alternatively at least make it possible to detach an edge from one 'old' individual and then attach it to a 'new' one, so that the evidence and notes (e.g. figure numbers) already included in the edge are not lost?

In this specific example, had I not become distracted half-way, I should have made the 'regulation of transcription' annotation immediately, as all the evidence was provided in just one figure. But if a model is being made, based on several different papers (e.g. where one paper shows just qPCR evidence, but the next provides additional luciferase reporter assay evidence), then the option to update exiting individuals and edges (rather than having to create new ones) would make the annotation process in Noctua more efficient. 

Related to the above: being able to copy an existing annoton to use a mini-template for the next annotation (in which e.g. only the '[continuant]' would be different), would also be very useful.

Or perhaps these functionalities are already available? Maybe the 'Simple annoton editor', which I recently discovered under the 'Workbenches' tab (but have not tried using it yet), makes such edits/updates and/or copying possible?

cc: @RLovering

**Comment by kltm** [comment]
There are several issues wrapped up in this. For matters of workflow, it might be best to touch bases with @vanaukenk or @ukemi .

As far as the literal ability to do various updates or moves, these are covered by issues 
#423 , #117 , and others, mostly hinging on #399.

The "Simple annoton editor" does allow for some types of editing, but there can be some destruction involved if used improperly. I'm not sure where the training stands with that.

There are some cloning operations for evidence ("Clone other") and annoton nodes ("Clone" under "Other operations").

Templates of various types have all sorts of tickets, such as #254 , #150, and many others.

**Comment by BarbaraCzub** [comment]
Hi @kltm , I have been using 'clone other' for evidence, but I was not aware of 'clone' for the annoton nodes. I'll try this, when working on the next model. Thanks!
