### ISSUE TITLE
Ensure Noctua curator documentation is up to date

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#476]
We have excellent detailed documentation here:
https://docs.google.com/document/d/18ihslb7prB6CWtu2yjF-pMHZBTY1-AdXJAu-ZyuyXS4/edit#
(note: this is linked from the front page)

However, it is a lot of work to keep this up to date. For example, this doesn't mention the cloning function. And then we have newer components like the SAM.

As new curators come on board it's important that they read the complete documentation, and that the documentation is as complete as possible.

**Comment by kltm** [comment]
Subservient to #527
