### ISSUE TITLE
Export gpad has reverted to terse annotation lines

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#478]
The very readable display has changed back to what it was before: only the ids display not the term name, etc. see example gomodel:5993df9e00000631

**Comment by kltm** [comment]
@hdrabkin Can you confirm this for the "Annotation preview" workbench? This works for me:

![screenshot_2017-08-25_17-44-34](https://user-images.githubusercontent.com/2687900/29737095-1ee344f2-89bd-11e7-8252-6b63b1ce740a.png)

**Comment by hdrabkin** [comment]
Strange, this was not what I saw on Friday, but now it looks fine; I hate it when this happens. At least Li saw it also when I was demo-ing it. 
However, now notice I have orphan gene product boxes (that's in a separate ticket). 
I'll close this now.
