### ISSUE TITLE
Is there a way to select several individuals and move them together?

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#479]
_From @BarbaraCzub on August 25, 2017 14:25_

Is there a way to select a few individuals and annotons in a model to move them around the canvas as a group?

E.g. when a new annoton is added to an exiting model, it usually appears at the far rhs of the canvas. If a few annotons and individuals are added sequentially, and then I want to move them to the area of the canvas where I can see most of the annotons and individuals added earlier, is there a way to select the new ones and move them on the canvas all together as a group? Or can they only be moved one by one (which is what I have been doing so far)?

_Copied from original issue: geneontology/noctua-models#38_

**Comment by kltm** [comment]
The behavior that you're seeking is "rubber banding", which is currently not a feature of the toolkit we use in the main editor, discussed here: https://github.com/geneontology/noctua/issues/360 .

This feature *is*, however, included in the "Cytoscape layout tool" workbench; discussion https://github.com/geneontology/noctua/issues/344 and https://github.com/geneontology/noctua/issues/442

The layout issues are widely documented in the tracker, and there are a set of tools that can be used to tame them. Besides the "Cytoscape layout tool" workbench, already mentioned, there is the compaction tool (I think we talked about that in another thread) and the layout reset tool.

finally, as to why you don't know these things, training and documentation are still a work in progress (https://github.com/geneontology/noctua/issues/476)--welcome to the cutting edge!

**Comment by BarbaraCzub** [comment]
Thanks @kltm I'll try the Cytoscape tool next time, when I need to move several objects together.
