### ISSUE TITLE
Noctua GO terms do not automatically update

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#480]
_From @BarbaraCzub on August 25, 2017 16:53_

I have just noticed that although the GO term name of GO:0006900 was changed from 'membrane budding' to 'vesicle budding from membrane' over a month ago, the term is still displayed as 'membrane budding' in my model (screenshots below) (I added it today). Have some updates not gone through?

<img width="869" alt="screen shot 2017-08-25 at 17 48 33" src="https://user-images.githubusercontent.com/16541096/29723875-319fd622-89be-11e7-90c4-44a87fc3ba62.png">

<img width="294" alt="screen shot 2017-08-25 at 17 52 10" src="https://user-images.githubusercontent.com/16541096/29723868-29fe09fc-89be-11e7-971c-d628f845d03b.png">

cc: @RLovering 

_Copied from original issue: geneontology/noctua-models#39_

**Comment by kltm** [comment]
Tagging @cmungall and @balhoff 

This is either due to minerva not being updated in a while and using old labels or to minerva reusing labels that have already been saved within the system. I believe the former to be true, in which case it will be solved with the eventual switch to the new pipeline (which will include weekly restarts). If the latter is true, We'll need to having a discussion of data updates and cleansing earlier in the pipeline. Either way, the issue will not reside in the noctua code.
That said, as this is appearing in a noctua client, this issue will be kept open here until the responsible location is understood.

**Comment by kltm** [comment]
One option will be eliminated with the restart later tonight.

**Comment by kltm** [comment]
As (mostly) expected, the minerva restart seems to have cleared this.
Automated minerva maintenance restarts (or hot updates) will be a feature of our pipeline system in the future, but it is a manual task currently. I think this is captured in the roadmap somewhere, but I am unable to currently find it.

**Comment by BarbaraCzub** [comment]
Hi @kltm , yes, I have just had a look at my model and the term name has been updated. Thanks!
