### ISSUE TITLE
Model is frozen -- cannot move any individuals on canvas

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#481]
_From @BarbaraCzub on August 29, 2017 14:37_

I do not seem to be able to move individuals and annotons around the canvas, delete them, or create relations between them. It is as if everything on the canvas was somehow frozen. I checked whether I can move items around in another model (gomodel:586fc17a00001446), and everything worked normally in that one, so this seems to be a model-specific issue. Could you please help with this?

Thanks,
Barbara

cc: @RLovering 

(optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:586fc17a00001826)

_Copied from original issue: geneontology/noctua-models#40_

**Comment by kltm** [comment]
Looks like the "unpossible: glyph triggered...

**Comment by kltm** [comment]
Fixed in production.

**Comment by BarbaraCzub** [comment]
Thanks @kltm . The fix seems to have worked.
