### ISSUE TITLE
Rewrite Noctua model browser (landing page search)

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#484]
Currently, we are using jQuery DataTable and a single metadata load from minerva as the driver and UI for in-Noctua model browsing for editors. While this has served us well, the slight noticeable initialization lag introduced by the syngo model drop (+>600) highlights that it is not a long-term solution.

While epione was very scalable, it relied on an external monitor script, a solr instance, was rather brittle, and did not have deep understanding of the data model. That said, it was fast, worked, and was able to do several information injection tricks that able to get information into the table that we have not yet been able to recreate elsewhere.

With a slight policy change and a small addition to minerva/noctua, we may be able to indefinitely defer the scaling problem. With the new pipeline getting close, we'll likely be able to look towards AmiGO and new GOlr loads driven from SPARQL to drive the main production views of the models. Over time, that should be the vast majority of the models. If we add a flag to minerva to be able to give us the model metadata available for different model statuses, we could limit ourselves to one subset or another, possibly greatly cutting down on the number of models needing to be displayed *by default*.

Another option would be to start adding solr-like functionality to minerva (paging, searches, fields, etc.). This has been discussed at great length in the past, and would likely lead to an embedded solr in minerva, complicating the codebase and mixing concerns.

Related:
#273 
#380

**Comment by cmungall** [comment]
We also separately discussed the ability to executed canned templates 
SPARQL queries directly on the live blazegraph instance. This would be 
useful in a number of cases, including this one. SPARQL supports 
limit/begin, so paging should be straightforward. This is potentially 
extendable to complex queries, e.g. "what models have an instance of a 
kinase regulating part of cell proliferation".

**Comment by kltm** [comment]
Yes, definitely another way of attacking the problem, and probably more efficient than loading more into the metadata wire protocol (which we could maybe partially do away with then). Done right, it also gets us around having to worry about paging and searching, as we can still leave them to the client. The only things standing in our way there is trigger access to minerva for controlled preset queries and the in/out objects for clients to work with.
Some of the latter may be accomplished with hackathon projects. I can also get into minerva again for the former, but that might be more efficient after I finally switch to the new laptop :)

**Comment by kltm** [comment]
On consideration, at least for experimentation queue, I think @cmungall 's approach is the best https://github.com/geneontology/noctua/issues/484#issuecomment-326180087 .
It would also give us an easy way to limit curator views based groups and ORCIDs. Paper-thin walls may be sufficient for partitioning curator and group workspaces.

**Comment by cmungall** [comment]
Overall requirements for this are being gathered in 

https://docs.google.com/document/d/1w3mkF1RQIzwROOCMTkqjYaOn8ZbdsW52t-xA4DKt0vg/edit# see Noctua Client

**Comment by kltm** [comment]
I think we're good here.
