### ISSUE TITLE
Make unsaved status more prominent - make top-level and highlightable

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#487]
Currently visible on front page and in browser tab of a model. However, browser tab is often obscured.

Something in the working area would help prevent unintended save omissions. Screen color would be a bit obnoxious and not compose well with reasoning. Perhaps just some prominent large text.

Perhaps also attempts to leave model e.g. with back button / close tab should confirm if user intends to leave unsaved model.

**Comment by kltm** [comment]
https://github.com/geneontology/noctua/issues/485#issuecomment-326395397

**Comment by kltm** [comment]
I'd like to avoid adding overrides, especially as many interactions with Noctua are intended not to be saved (e.g. fiddling with layout during a demo, etc.) and overrides themselves can cause other problems. As well, that may reduce uniformity/portability to other clients.

The point with the tab being obscured is well taken. Ideally, we could have the prominent in a model status tab, but that whole section is easily ignored at this point as it is essentially unused. Of the things that may be reusable and not hard to maintain given the current framework, I am thinking of modifying the `Model` menu item to *Model (modified)* or the like.

**Comment by kltm** [comment]
Save, store, modified.

**Comment by cmungall** [comment]
Somewhat tied in with this but having the save button more easily accessed

**Comment by krchristie** [comment]
It would really be nice for curators if the Save command was somewhere visible all the time, not just buried in a menu.

**Comment by kltm** [comment]
Yes, and that would make highlighting it much easier--good idea.

**Comment by vanaukenk** [comment]
This has been improved for the Noctua form-based UIs, so closing for now.
