### ISSUE TITLE
Autocomplete selection not being recognized in CC box of "Add annoton"

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#488]
The cellular_component box in the "Add annoton" is not working properly. When I type something into the box, I get appropriate autocomplete options based on what I type, and I can select something and the corresponding ID shows up in the box, just like for the gene product, MF, and BP boxes. However, when I click the "Add" button, I get a pop up that says "Must select something from autocomplete list for cellular_component". 

I first noticed this a few days ago, but it was the end of the day and I didn't have time to confirm that it was the interface versus a user error or to submit a ticket, but it is still happening today and is specific for that box. There is no problem with any of the other three boxes in the "Add annoton" section. The "Add individual" section also works properly, even for adding CC terms.

**Comment by kltm** [comment]
Duplicated. Ugh, likely a reversion from #471 ... checking now.

**Comment by cmungall** [comment]
I believe the error message should actually be "Must select something from autocomplete list for *molecular function*". It is forcing you to add an MF, even if root. I think it should make a root MF instance for you if the field is blank, but that aside I think this is just a reporting error.

**Comment by krchristie** [comment]
It doesn't matter whether there is something in the MF box or not. If there is anything in the CC box, I get this error, either with the MF box blank or filled.

**Comment by kltm** [comment]
I believe that fix should now be public. Do a hard refresh of your page and the fix should be picked up in the client.

**Comment by krchristie** [comment]
Yes, fixed now :1st_place_medal:
