### ISSUE TITLE
Switch to new relations handling (on the end client)

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#49]
Currently using /getRelations in bootstrap, need to switch to the new handler.
Talk to Heiko if you forget (again).

**Comment by kltm** [comment]
@hdietze Are we still considering having the per-model relations call, or are we good enough with the starting meta call? It's far enough back I'm a little unsure how we stand now...

**Comment by cmungall** [comment]
Division of responsibilities between minerva and golr doesn't seem clear to me. on the one hand, golr is the general source of things in the world, is used for autocomplete for classes. on the other minerva has the semantics which will likely be required for #165

For the 2015-08 push it probably doesn't matter, all the models import go-plus which imports ro

**Comment by kltm** [comment]
Okay, talking to @hdietze, this is a bit of an historical artifact that has since been changed (we are no longer going to have per-model import chains). The change in bootstrapping was done in June, but I'll close it here as we have the final clarification.
