### ISSUE TITLE
Add ability to search on landing page using model ids

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#491]
Apologies if this is in another ticket; I couldn't find one.
It appears that one cannot search for a specific model id
example:
I get a qc report during our Noctua gpad load that flag annotations from Noctua where there is something wrong with a relationship, or duplicate annotation, etc. 
Example: 
Invalid Property (214):  RO:0002408
GO:0005515	MGI:88379	J:222849	TAS			GO_Noctua	20160927		MGI	has_input&=&MGI:1921395&==&RO:0002408&=&GO:0003810&==&lego-model-id&=&gomodel:57c82fad00000695&==&contributor&=&http://orcid.org/0000-0001-7476-6306&==&go_qualifier&=&enables&==&evidence&=&ECO:0000304

So the model id gomodel:57c82fad00000695
Yes, I CAN search on the orcid, but that returns ALL models, not the ONE I need to look at (in this instance, this curator has greater than 100 models either created or worked on; which one is the gomodel:57c82fad00000695?

There should be a way in Noctua to search on the specific gomodel id.

**Comment by kltm** [comment]
Hm. We try to avoid exposing the Ids like that. Ideally, the report should just give you a link; would you know where the report is coming from?
As a workaround, you can just past the ID into the URL where the IDs are and directly jump to the model.

**Comment by cmungall** [comment]
I think it would be useful to search by model id. These often become separated from the full URL, as in the gpad above or in tickets on the noctua-models tracker. But as you say it's possible to just sub when on a random model edit page.

This looks like a badly messed up gpad line. The one that is exported from Noctua looks like this:

```
MGI     MGI:1921395     enables GO:0003810      PMID:18224415   ECO:0000315     MGI:5645817             20160920        GO_Noctua       part_of(GO:0007596),part_of(GO:0072378),preceded_by(GO:0003674),occurs_in(EMAPA:35690),occurs_in(UBERON:0001969),has_input(CHEBI:5054) contributor=http://orcid.org/0000-0001-7476-6306|noctua-model-id=gomodel:57c82fad00000695
```

(although MGI are using the heiko gpad export which is no longer supported, cc @ukemi).

something weird is happening as it passes through MGI as the final column is messed up in what harold posted

**Comment by kltm** [comment]
Don't worry, I didn't close it--I was still pondering.
Given the widget that we're using, I think I'll probably add the searchable ID text in a teeny font under the actual title (assuming a different.)

**Comment by hdrabkin** [comment]
Sorry about the format; it was a cut paste form a qc report but from a web browser. It looks much prettier.  The point being that I can see the model id in our qc; that's not the issue.
I want to paste it into the noctua tool to find it. Karen, LI, and I all agree this is important for tracing what model an annotation came from. Again, searching on the user orcid is not helpful when that user has many many models.
