### ISSUE TITLE
Ideas for improving instance / node editing modal popup

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#493]
- It would be more logical from a curator's perspective if the With column came immediately after the Evidence column, since the with column is essentially an extension of the evidence.

- It is nonsensical for the sample fill of the With column to say "PMID:5678". There are numerous IDs that are allowed in the With field, but PMID is not one of them. Could this either list several possibilities, something like:
`MGI:MGI:1234567; UniProtKB:Q9QZH1; RGD:621088; ...`
or something more generic like:
`PREFIX:id`

**Comment by vanaukenk** [comment]
I'd like to suggest some additional clarification on the text in the evidence boxes to try to make things as clear as possible:

Enter Evidence Code (e.g., IDA or ECO:0000314 or direct assay evidence used in manual assertion)
Enter With (or) From (e.g., UniProtKB:P35052 or SGD:S000002885); only appropriate for some evidence types
Enter Reference (e.g., PMID:id or GO_REF:id)

@kltm Is this text getting too long for the boxes?

**Comment by kltm** [comment]
@vanaukenk You'd have about 70 characters to work with:
"Enter Evidence Code (e.g., IDA or ECO:0000314 or direct assay evidence..."
"Enter With (or) From (e.g., UniProtKB:P35052 or SGD:S000002885); only ..."

**Comment by vanaukenk** [comment]
@kltm 

How about this:

Enter evidence code (3-letter code, ECO ID, or ECO label)
If appropriate, enter With/From value (Must be in form of PREFIX:id)
Enter reference (Must be in form PREFIX:id)

**Comment by kltm** [comment]
Will be updated on next rollout.
