### ISSUE TITLE
template, copies or non-editable options

### ISSUE THREAD

**Issue by RLovering** [geneontology/noctua#495]
Hi 

I would like Barbara to share her SynGO Noctua models with other members of SynGO, however I do not want her to loose information if someone makes change, either because they disagree with the way it is set up or by a mistake. The people the model links will be sent to will not be used to using Noctua.

Would it be possible to somehow fix these models, either by creating a copy that she doesn't circulate the link to, or by adding an option to make the model uneditable, or by saving the model as a 'template'.

If not I will advise her to circulate the links with the request that people sign out of Noctua (or do not log on) so that no changes will be made

Thanks

Ruth

@barbaraczub

**Comment by kltm** [comment]
There are already tickets for both aspects of this (e.g. #379 #347, etc.)

Models are saved every half hour if they are saved. If they are unsaved, the pipeline never knows about the changes and they will be reset on the next restart.

The safest thing to do is circulate links that do not have an access token in their URLs and do not log users in--they have no control at that point and caon only view.
As well, there is the undo/redo controls for unsaved models.

There is also a method to create "non-existent" using the TTL upload function, but I suspect that may create more confusion than it fixes.

**Comment by BarbaraCzub** [comment]
How do we make sure that a link does not have an access token in the URL?

**Comment by kltm** [comment]
Look at the URL and remove anything including and after a question mark.
