### ISSUE TITLE
Populate PMIDs in annoton edit modal with PubMed title information from Wikidata 

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#496]
The is an experimental waypoint from BH17 (https://github.com/dbcls/bh17/wiki/Noctua-SPARQL-Interactions).

It is becoming apparent that we are severely limited in many ways from populating data from remote sources in the client (in SPARQL) by #399 , but we'd still like to demo and have something useful anyway.

This ticket is completed when we are able to Populate PMIDs in annoton edit modal with PubMed title information from Wikidata.

**Comment by kltm** [comment]
Initial attempts to thread this through fell afoul of too many conflicts (or just being to hard to figure out) for the interactions between jQuery and Bootstrap 3 for general toolkit information. Bailed out on that and will just update with titles in place.

**Comment by kltm** [comment]
See talk with Sebastian in DBCLS wiki item:
- for a lot of our papers, they do not seem to be in the Wikidata system yet
- Sebastian suggested an automatic population API (in slack #general); after initial run, we'll look at scripting that in our pipeline somehow

**Comment by kltm** [comment]
The following essentially makes it all work; takes a couple of hours to do the initial ~1350 items:
```bash
grep -Gro 'PMID:[0-9]\{1,10\}' * | cut -d ':' -f3 | sort | uniq | sed -e 's/^/https\:\/\/tools.wmflabs.org\/pmidtool\/get_or_create\//' > /tmp/pmidrun.txt
while read p; do sleep 3 && curl -O "$p"; done < /tmp/pmidrun.txt 
```

**Comment by kltm** [comment]
While we may need to revisit this or add something along these lines to the pipeline, at least at this point we are "caught up".

**Comment by cmungall** [comment]
totally not following this, but maybe it doesn't matter...

**Comment by kltm** [comment]
I can explain it real fast when you're around. It mostly doesn't matter, but it turns out that the vast majority of publications that we've used for annotation in noctua were not yet in wikidata; this script called an online tool that helps populate wikidata with the basic information that we need.

**Comment by krchristie** [comment]
I'll put this comment here for now, but can make a new ticket if more appropriate than reopening this one.

1. I actually miss having the PMID in the editing window because now I can no longer copy/paste the PMID out of a different evidence line when adding a new type of evidence. Could it be included as well as the title?

2. The information that I personally use mentally to keep track of most citations is first author and year. It would be great if we could have that info displayed as well.

**Comment by kltm** [comment]
For 1, I can re-add the the PMID itself to the display no problem.

For 2, Wikidata does not yet reliably have that information, so it cannot be added by this method.

**Comment by krchristie** [comment]
Do you want to keep the request for additional citation info, regardless of method, in this ticket, or should I create a new ticket for this?

**Comment by kltm** [comment]
Yes, let's open a new ticket.

**Comment by krchristie** [comment]
I've made a new ticket for adding additional citation info to display of references.

I notice you've closed this, even though the PMID's haven't been added back. Is that part (#1) is fitting for this ticket since it doesn't require changing to a new method to acquire citation info?
