### ISSUE TITLE
Noctua is very slow today

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#497]
I've been working on my Notch model today and have found Noctua to be quite slow at times when performing various functions, e.g. saving, running the reasoner, changing the layout.

Sometimes I also get the error message:
There was a manager error (error): message and message_type must always exist

The model I'm working on is:  http://noctua.berkeleybop.org/editor/graph/gomodel:5745387b00001750

Any thoughts about what might be going on?

Thx.

**Comment by kltm** [comment]
@vanaukenk Could you confirm that this is working better now?

**Comment by kltm** [comment]
Note to @cmungall After the restart over the weekend, it seems like Galaxy managed to resurrect itself, and then proceed to spin up ~1350 children. Should be completely off now.

**Comment by cmungall** [comment]
bizarro. thanks for tracking this down.
