### ISSUE TITLE
Various minor tweaks for Gosling

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#498]
Gosling is the noctua goose, introduced in #494 available from top-level workbenches
http://noctua.berkeleybop.org/workbench/gosling/

 * [ ] add link to example queries, or have ability to select from bank of queries @dougli1sqrd 
 * [ ] add default prefixes, using standard jsonld contexts, e.g. GO, MGI, ...
 * [ ] make named graphs consistent with rdf.geneontology.org @balhoff 
 * [ ] document whether this queries over asserted or reasoned graph (I think latter?)
 * [ ] make individual URIs resolvable

**Comment by kltm** [comment]
Before any of the above, I'd like to hammer out a uniform format for our SPARQL with @cmungall @dougli1sqrd @balhoff .

See thread from here, to end:
https://github.com/geneontology/go-graphstore/issues/9#issuecomment-328248229

And:
https://github.com/geneontology/noctua/issues/465#issuecomment-328244894

**Comment by kltm** [comment]
I think this is safe to close out for now--unlikely to be more work there unless we change tack.
