### ISSUE TITLE
Extending form editor to include standard GO-CAM model fields

### ISSUE THREAD

**Issue by thomaspd** [geneontology/noctua#499]
On the form interface for Noctua, we could add two additional fillable fields for each line (MF, BP, CC):

MF: [has_input (gene product)] [occurs_during (biological phase)]
This would give the added triplets MF—(has_input)—>gene product, and MF—(occurs_during)—> phase

CC: [part_of (cell type)] [part_of (anatomy term)]
This would give CC—(part_of)—>cell type, and cell type—(part_of)—>anatomy

BP: [part_of (BP')] [part_of (BP")].
This would give BP—(part_of)—>BP', and BP'—(part_of)—>BP"

All the triplets from a given line would be associated with the same evidence.

This way, one could enter all the parts of a standard annoton from a single form, as defined in our upcoming GO-CAM paper:
![screen shot 2017-09-21 at 5 28 20 pm](https://user-images.githubusercontent.com/11966328/30724846-89d6c1f6-9ef5-11e7-92cc-9139ca4d0712.png)

This will be a great help for ensuring that users build models that adhere to our standard as much as possible, and should help with at least some of the usability issues.

**Comment by kltm** [comment]
This issue was moved to geneontology/simple-annoton-editor#12
