### ISSUE TITLE
GPAD missing annotations via 'causally upstream of'?

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#500]
This model:
ID - gomodel:59bee34700000110
Name - TEST: causally upstream of - KRC

contains three lines, each with at least one 'causally upstream of or within' relationship.

Only one of them generates this annotation: "_acts_upstream_of_or_within_ cardiac septum morphogenesis"

Checking with @ukemi, he expected that all three would and said this:

> It appears that there is a property chain that might be missing, 
> part_of_o_causally_upstream_of_or within->causally_upstream_of_or_within.
> 
> I have also been looking more closely at the annotation extensions. I
> think we need to revisit this because I do think that a lot of them are
> 'wrong'. I originally had a restriction in their generation where they
> were only allowed if they came from the same publication with the same
> evidence. That restriction was later removed. This makes many annotations
> (extensions) incorrect with respect to the evidence and publication. If a
> user tries to trace back evidence to back up extensions to the publication
> cited in the annotation, in many cases, it will not be supported.
>

**Comment by kltm** [comment]
Any thoughts from @cmungall or maybe @balhoff ?

**Comment by balhoff** [comment]
I think @ukemi is right. If that chain (`part_of o causally_upstream_of_or within -> causally_upstream_of_or_within`) is added, then it ought to work. I'll leave it to the GO editors whether it ought to be added.

**Comment by ukemi** [comment]
Hi @balhoff 

Tagging @vanaukenk so she can think about this property chain too. I think it is solid. But the real test is to add it and then test a bunch of models to be sure.

Also what about adding the restriction back on the extensions (same paper, same evidence)? Hopefully it was just commented out in the code. I knew there had to be a reason for including it, even though I couldn't think of it off the top of my head during the call when we decided to remove it.

**Comment by cmungall** [comment]
I think the property chain is valid

**Comment by krchristie** [comment]
Perhaps someone could explain why this model: 
**ID** - gomodel:59b38c1100000189 
**Name** - TEST: why no cardiac septum morph annot for Mks1 - KRC 
does NOT generate an annotation to 'cardiac septum morphogenesis for Mks1

while this one does:
**ID** - gomodel:59c8885900000227 
**Name** - PMID:27340223 Dnah11 Mks1 - KRC 

If it's because the first causally_upstream_of_or_within relationship has lost its annotations for Contributor and Date, perhaps there could be a more informative way of failing, with an error message about what is missing. 

Otherwise, I have no idea.

**Comment by cmungall** [comment]
OK, this is a bit mysterious

I can confirm that the underlying inference is there, from the explanations workbench:

![image](https://user-images.githubusercontent.com/50745/30888153-dc01b684-a2d3-11e7-88ff-7739540af6b3.png)

So I believe there must be some kind of post-processing filtering step happening, perhaps to do with evidence. However, this hypothesis doesn't make much sense given the part-of chain shown above does have everything, and it uses identical evidence.

@balhoff do you have any tips for debugging this?

@vanaukenk @ukemi can you see if there is something obvious we're not noticing here?

**Comment by balhoff** [comment]
It is mysterious to me so far! Probably something weird in the filtering step, but I don't see the problem.

**Comment by balhoff** [comment]
There is a bug somewhere related to explanations: the explanation lists an inferred triple in its list of asserted triples: `molecular_function#59b38c1100000207 causally_upstream_of_or_within cardiac septum morphogenesis#59b38c1100000211`

**Comment by balhoff** [comment]
Strange: there is a direct `causally_upstream_of_or_within` link from the MF to `cardiac septum morphogenesis#59b38c1100000211` in the OWL file, but it doesn't appear in the model UI.

**Comment by kltm** [comment]
@balhoff Which model is this?

**Comment by balhoff** [comment]
http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000189

**Comment by balhoff** [comment]
The triple missing from the UI:

```turtle
<http://model.geneontology.org/59b38c1100000189/59b38c1100000207> <http://purl.obolibrary.org/obo/RO_0002418> <http://model.geneontology.org/59b38c1100000189/59b38c1100000211>
```

**Comment by balhoff** [comment]
Oh, and since there is no evidence on that triple, no annotation. So I guess that explains things from the Arachne side. But there is something out of sync between Minerva and Noctua, or Noctua is hiding this for some reason.

**Comment by kltm** [comment]
@balhoff The mystery deepens. I can confirm that the model that comes over the wire from Minerva (via Barista) does not contain the triple here https://github.com/geneontology/noctua/issues/500#issuecomment-332386414 and is displaying as advertised.

**Comment by kltm** [comment]
Other weirdness. The axioms in the OWL model (http://noctua.berkeleybop.org/download/gomodel:59b38c1100000189/owl appear to be):
```
   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000201> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/BFO_0000050> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000202> ;

   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000201> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002333> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000200> ;

   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000202> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/BFO_0000050> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000196> ;

   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000206> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002418> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000211> ;

   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000207> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002333> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000205> ;

   owl:annotatedSource <http://model.geneontology.org/59b38c1100000189/59b38c1100000207> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002418> ;
   owl:annotatedTarget <http://model.geneontology.org/59b38c1100000189/59b38c1100000206> ;
```

and over the wire (the same ones in the same order):
```
"subject": "gomodel:59b38c1100000189/59b38c1100000201"
"property": "BFO:0000050",
"object": "gomodel:59b38c1100000189/59b38c1100000202",

"subject": "gomodel:59b38c1100000189/59b38c1100000201"
"property": "RO:0002333",
"object": "gomodel:59b38c1100000189/59b38c1100000200",

"subject": "gomodel:59b38c1100000189/59b38c1100000202"
"property": "BFO:0000050",
"object": "gomodel:59b38c1100000189/59b38c1100000196",

"subject": "gomodel:59b38c1100000189/59b38c1100000206"
"property": "RO:0002418",
"object": "gomodel:59b38c1100000189/59b38c1100000211",

"subject": "gomodel:59b38c1100000189/59b38c1100000207"
"property": "RO:0002333",
"object": "gomodel:59b38c1100000189/59b38c1100000205",

"subject": "gomodel:59b38c1100000189/59b38c1100000207"
"property": "RO:0002418",
"object": "gomodel:59b38c1100000189/59b38c1100000206",
```

No mention either place of your triple.

**Comment by balhoff** [comment]
It is in the OWL at the link you posted: http://noctua.berkeleybop.org/download/gomodel:59b38c1100000189/owl

But it has no evidence so is not in the form of the annotated axioms. It's in here:

```turtle
###  http://model.geneontology.org/59b38c1100000189/59b38c1100000207
<http://model.geneontology.org/59b38c1100000189/59b38c1100000207> rdf:type owl:NamedIndividual ,
                                                                           <http://purl.obolibrary.org/obo/GO_0003674> ;
                                                                  <http://purl.obolibrary.org/obo/RO_0002333> <http://model.geneontology.org/59b38c1100000189/59b38c1100000205> ;
                                                                  <http://purl.obolibrary.org/obo/RO_0002418> <http://model.geneontology.org/59b38c1100000189/59b38c1100000206> ;
                                                                  <http://geneontology.org/lego/hint/layout/x> "8"^^xsd:string ;
                                                                  <http://geneontology.org/lego/hint/layout/y> "228.99998474121094"^^xsd:string ;
                                                                  <http://purl.obolibrary.org/obo/RO_0002418> <http://model.geneontology.org/59b38c1100000189/59b38c1100000211> ;
                                                                  <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0001-5501-853X"^^xsd:string ;
                                                                  <http://purl.org/dc/elements/1.1/date> "2017-09-12"^^xsd:string ;
                                                                  <http://purl.org/pav/providedBy> "http://informatics.jax.org"^^xsd:string .
```

**Comment by ukemi** [comment]
@balhoff is correct. If there is no evidence, an annotation will not be made.

**Comment by cmungall** [comment]
OK, do I have what you're saying right:

This triple:

```
<http://model.geneontology.org/59b38c1100000189/59b38c1100000207> <http://purl.obolibrary.org/obo/RO_0002418> <http://model.geneontology.org/59b38c1100000189/59b38c1100000211>
```

corresponds to a direct link between the MF instance and the cardiac septum morphogenesis instance here:

![image](https://user-images.githubusercontent.com/50745/30917076-eba03a12-a34f-11e7-82db-e2165be3dd13.png)

This direct link is not being shown, for reasons unknown (someone is trying to do something smart and remove redundant edges?)

Furthermore, although this link should be *inferred* (resulting in a GPAD line since all visible assertions have evidence), it is in some way blocking production of a GPAD line (which sounds odd, I'm just hypothesizing here).

I think we should take this OWL, use SLME to make a module and add it as a junit test in minerva, which will help determine where to look (and build up a good test case at the same time).

**Comment by balhoff** [comment]
Yes, you got it. The reason it's blocking the GPAD line is that the link does not need to be inferred, so it is being used as a justification for the inferred `acts_upstream_of_or_within`. This indicates a weakness of the Arachne method for this—it doesn't compute all possible explanations. It only has the justification for the way it got to each inference it made.

So if there are redundant ways to infer something in the model, and one of the ways meets evidence requirements and one doesn't, it will depend on which way the inference happened. This hasn't been a problem so far as far as I can see. And this situation is particularly weird because this hidden triple is confusing everything.

**Comment by cmungall** [comment]
The hidden relation is now visible (see #504)

![image](https://user-images.githubusercontent.com/50745/31072776-44892b9c-a761-11e7-8e79-f20add134ceb.png)

because this edge is more direct, it takes precedence over the ones with evidence. This explains the issue. It's not clear what the ideal behavior is here but I suggest we put requests here in a separate ticket.
