### ISSUE TITLE
providedBy should be used in GPAD export

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#502]
the assigned by field shows up as GO_Noctua

**Comment by kltm** [comment]
There appears to be no Minerva analog to this.

Other somewhat related items: 
https://github.com/geneontology/minerva/issues/119
https://github.com/geneontology/noctua/issues/459

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/go/metadata/groups.ttl now available
