### ISSUE TITLE
Under some circumstances, annotations and edges may disappear from a model

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/noctua#504]
Hi,
This morning, after Seth's email, I  attempted  to saved my model in Noctua (ZP3- induced acrosome reaction in the mouse sperm). It did save the two changes I did, but lost all the relationships and the protein IDs that enable the functions that were in the model before that. Is it possible to get the previous version please? 
Thanks,
Penelope

**Comment by kltm** [comment]
Additional issue from Penelope:

I  just attempted  to saved my model in Noctua (ZP3- induced acrosome reaction in the mouse sperm). It did save the  two changes I did, but lost all the relationships and the protein IDs that enable the functions that were in the model before that. Is it possible to get the previous version please?  Is this the same issue that Karen was having?

**Comment by kltm** [comment]
Likely the minerva upstream: https://github.com/geneontology/minerva/issues/141

**Comment by kltm** [comment]
From Guilia:

I have an issue with Noctua, and I thought you might help me. It’s the second time that I make a model, I name it, I save it, and the day after all the relationships are gone. I am attaching a screenshot of a model that I made yesterday, and that is currently here: http://noctua.berkeleybop.org/editor/graph/gomodel:59c8885900000374
As you can see, my model doesn’t look at all like it was, only the entities are left. Do you know why this is happening? I could try to build a third model, but am a bit afraid to lose everything a third time!

<img width="1424" alt="screen shot 2017-09-28 at 01 54 02" src="https://user-images.githubusercontent.com/2687900/30989446-994429aa-a452-11e7-9c3d-7114b9a096ef.png">

![screenshot_2017-09-28_13-41-29](https://user-images.githubusercontent.com/2687900/30989514-d82ce7c4-a452-11e7-97ac-b01fdf557887.png)

**Comment by kltm** [comment]
Fix now being tested, thanks to: @cmungall, @balhoff, and @yy20716

**Comment by kltm** [comment]
Noctua now live again, doing some looking around...

**Comment by kltm** [comment]
Upstream information for work done in Minerva.
 https://github.com/geneontology/minerva/issues/141

**Comment by pgarmiri** [comment]
Everything seems to be back for me. Thank you all very much! 

Penelope
