### ISSUE TITLE
additional Annotation State to indicate models that are 'tests' never intended to become production

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#506]
I have a number of models that are 'tests' that should never be marked production, but are also 'done', i.e. not in a development stage either. None of these possible choices for "Annotation state" seem appropriate:

- production
- review
- development
- closed
- delete

It seems it might be appropriate to have another choice for 'test' or something to indicate models that have a purpose in testing, that are no longer in 'development', but for which none of these other statuses seem approriate.

**Comment by kltm** [comment]
@krchristie 

I would probably go ahead and call them `closed`--editable, but never exported.

For context:
https://github.com/geneontology/noctua/issues/148#issuecomment-124228215
