### ISSUE TITLE
Add Dicty Anatomy to Noctua

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#510]
Please add the dicty anatomy to Noctua so we may use it for annotations
 Get it here: https://github.com/dictyBase/migration-data/tree/master/ontologies
or here: https://www.ebi.ac.uk/ols/ontologies/ddanat

Many thanks!

**Comment by cmungall** [comment]
We always take ontologies from their official PURLs, these can always be found at obofoundry.org

For example
http://obofoundry.org/ontology/ddanat.html

Lists the official purl for the obo and for the owl.

For ddanat the contact is still Rex, and no license is entered. Should you be updated as the contact? Can we make it CC-BY or CC-0?

**Comment by cmungall** [comment]
One problem is this: https://github.com/obophenotype/cell-ontology/issues/486

the CL classes have already been used for annotation by someone. We'll need to replace these when the CL classes become obsolete. This is a bit hard to do until we have #279

**Comment by pfey03** [comment]
Yes, add me as the contact for the DDANAT, that's ok. Sorry for being ignorant what is the CL class in the DDPHENO and can I fix it using OBOedit? A bit more info please! Thanks!

**Comment by kltm** [comment]
@cmungall @pfey03 
I looked around a bit, and the dictybase.org site seems to be completely devoid of any usage or license information. That said, the contents of the https://github.com/dictyBase/migration-data, including the ontology files, seems to be pretty clearly under an MIT license.
@pfey03 It might be worth enquiring if this was the intention or not.

**Comment by kltm** [comment]
@cmungall As far as I can tell, this is closeable except for the restart of Minerva?

**Comment by cmungall** [comment]
merging https://github.com/geneontology/go-ontology/pull/14311 will close the issue (but yes minerva will need to be restarted after the next snapshot is built)

**Comment by cmungall** [comment]
> what is the CL class in the DDPHENO and can I fix it using OBOedit

The issue is with the cell ontology, which includes dicty cell types. We bring in the cell ontology, so this will cause confusion since there will be a choice and this will lead to inconsistent practice.

You can see Robert used these here:
http://noctua.berkeleybop.org/editor/graph/gomodel:59bee34700000000

which is of course fine as he didn't have ddanat to do use instead.

We'd welcome help fixing CL to get rid of the stale classes (see the ticket I linked to for details) but you can't do this in oboedit, it requires Protege

**Comment by pfey03** [comment]
OK, yes, remember we discussed Cell Ontology before and that Dicty will be expelled. @rjdodson used 'pre stalk cell' from CL and David, also working on a Dicty model used 'stalk cell'. 
http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000331

Since I'm not an editor I don't use Protege so far. However, I can go through the CL and send all IDs and terms that are Dicty-specific and send that. Whom should I send it to, you? 
Thanks!

**Comment by pfey03** [comment]
@kltm 
We are working on a COMPLETE overhaul of dictybase. What you see on git is the new database and data is completely migrated now working still on middleware and then front end. A part (strains/phenotypes/literature/colleagues/stock center ordering will be released very soon. The GO will come later.
Please ignore the current dictyBase, it's history. But we need to keep it for our users until we are completely in new.

**Comment by cmungall** [comment]
You can still select a license for the ontology separate from the database. Are you the contact person for this purpose @pfey03 ?

**Comment by pfey03** [comment]
For all biological ontologies I'm the contact, yes. Talking about CL lIcense here? Can't get obo file here, is too big https://github.com/obophenotype/cell-ontology/blob/master/cl.obo

**Comment by cmungall** [comment]
No, sorry for not being clear. My main concern is the ddanat license. This is not declared: http://obofoundry.org/ontology/ddanat.html

Before we import anything in to a GO resource we would like it to have an explicit open license declaration.

I can update the obo page (or you can - just click edit and make a pull request). However, only you or someone there can decide what the license is. 

There is no license issue with CL - the problem with CL is the duplicate dicty cell terms. I have a PR on the cl repo that obsoletes these

**Comment by pfey03** [comment]
Here is a reference for the DDANAT: https://www.ncbi.nlm.nih.gov/pubmed/18366659
Regarding licence, maybe you can cite that but name me as the current license holder as I manage all ontologies in dictyBase since Pascale left 7 years ago and the holding is dictyBase. Or name dictyBase attn Petra Fey or such if that is possible.

Great you can obsolete those in CL, thanks!

**Comment by cmungall** [comment]
I will put you as the contact on the OBO page for DDANAT. For the license, you should choose one. OBO Foundry recommends one of these two:

 * CC-0
 * CC-BY

There is vigorous debate over which is preferred. If you want my opinion, I would go for CC-0 (i.e. public domain) for ddanat.

**Comment by pfey03** [comment]
yes, do CC-0

And as it goes, if published it is usually public and our Git is public where it resides.

**Comment by kltm** [comment]
CC0 is not quite "public domain", but it is by far and away the least restrictive sensible terms you can give your data, and also allows for it to be ingested into resources like Wikidata.

**Comment by cmungall** [comment]
@pfey03 can you click on this link
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/497

And write "I approve" or "+1". Many thanks!

**Comment by kltm** [comment]
@cmungall (in the form of a haiku)
```
snapshots are nightly; 
I restarted minerva--
please check output now
```

**Comment by kltm** [comment]
@pfey03 @cmungall Is there any more action here?

**Comment by balhoff** [comment]
@pfey03 I opened a pull request to import ddanat into Noctua. The [duplicate CL term issue](https://github.com/obophenotype/cell-ontology/issues/486) still remains, so once ddanat appears in Noctua there may be a little confusion there.

**Comment by pfey03** [comment]
@balhoff As far as I see the CL terms have all been obsoleted. When I tried 'prespore cell' in Noctua it gave me the CL term that said (obsoleted). And just checked the ontology for prestalk, see the snapshot
<img width="550" alt="screen shot 2018-05-13 at 09 04 58" src="https://user-images.githubusercontent.com/1349602/39967633-fbe4fda4-568c-11e8-87d6-8665e6d3def7.png">

**Comment by balhoff** [comment]
This will appear next time go-lego is released and then  the Noctua stack is restarted. I'll close this ticket, although the related ticket in CL remains.

**Comment by cmungall** [comment]
Adding this as a confirmation this works:

![image](https://user-images.githubusercontent.com/50745/56667910-7f986500-6663-11e9-8927-569b48cb19dd.png)
