### ISSUE TITLE
Create a pathway view (reduced information) for consumption by external resources

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#512]
Create a pathway view (reduced information) for consumption by external resources

Include nestable `part_of,` better layout algorithms, single title nodes (gp, then function), info pop-ups, removal of singletons, removal of "unneeded" relations, etc.

@ValWood @hattrill

**Comment by kltm** [comment]
An initial version of this is now live.

**Comment by goodb** [comment]
One thing that could be useful here would be a conversion to the Systems Biology Graphical Notation ([SBGN](http://sbgn.github.io/sbgn/)) format. Huaiyu from USC was heavily involved in designing this standard for visualizing pathways.  GO-CAMs would likely fit in their [activity flow](http://biecoll.ub.uni-bielefeld.de/volltexte/2015/5369/pdf/jib_265.pdf) structure pretty well.  Would allow a number of viz tools to be employed - e.g. http://www.cs.bilkent.edu.tr/~ivis/SBGNViz.js/sample-app/# .   (Likely conversion process would first go from go-cam to format like biopax or sbml that already has sbgn converters).
