### ISSUE TITLE
Simple annoton form suggestion: Add a “clone annotation” option

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#515]
It would be useful to add an “clone annotation” option. 
This would re-populate the form with the elements of an existing annotation (same as the current “edit” option), then allow curators to change one (or more) of the elements and save as a new annotation. 
This is a useful tool when we need to make multiple annotations which differ by only one element. 

If it would be helpful, I can demonstrate similar “cloning” options we frequently use in ZFIN.

**Comment by kltm** [comment]
This issue was moved to geneontology/simple-annoton-editor#17
