### ISSUE TITLE
Relation to use for regulation terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#516]
At the Cambridge 2017 GOC meeting, it was decided that for assertions of type “Gene product involved_in X regulation”, we will use default ‘involved in’. 

This needs to be documented. 

(Question: Is the relation 'regulates to be obsoleted?)

**Comment by kltm** [comment]
@pgaudet What is the action here? If this for documentation within this repo, or more general documentation?

**Comment by kltm** [comment]
@pgaudet I see that there is also now a "Documentation" project. While a `documentation` label could be useful for marking non-code requests withing the repo, I'm not sure how you envision that interacting with a GH project?

**Comment by vanaukenk** [comment]
Hi,
I actually created the Documentation project in the Noctua repo yesterday to keep track of the status of overhauling the documentation for using Noctua.
There is some blurring on the Noctua repo of issues related to the mechanics/functionality/features of the tool with modeling decisions that might better be housed in the go-annotation repo.  
I also created a Documentation project in go-annotation, and am okay if we prefer to track Noctua/GO-CAM documentation there instead of in the Noctua repo.
--K.

**Comment by vanaukenk** [comment]
@kltm  - Sure, feel free to add 'overhaul' to the ticket and description.
For columns, @ukemi started a Documentation project at geneontology and I think we would want to roughly mirror the columns there:
https://github.com/orgs/geneontology/projects/3
New Documentation Required
Documentation Updates Required
Documentation in Progress
Documentation Completed
I'd like to clarify on the managers call tomorrow, though, about exactly how we want to track documentation projects.  It makes sense to me to have them in specific repos, but I don't know if everyone feels that way,

**Comment by kltm** [comment]
@vanaukenk I've added "overhaul" to the project.
Would there be a good venue to discuss the columns that would be used (as we are already rather off-topic here)?

**Comment by vanaukenk** [comment]
@kltm - maybe a Skype with you, me @pgaudet @ukemi and anyone else interested to flesh out good practices in github project column use?  
I can see that the column names originally made for Documentation projects don't align with what exists for other projects, but maybe conceptually is not that far off.

**Comment by kltm** [comment]
@vanaukenk That would be fine with me.

**Comment by ukemi** [comment]
Me too.

**Comment by pgaudet** [comment]
Me too.

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-annotation#1687
