### ISSUE TITLE
Proposal for Protein complexes representation in Noctua 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#517]
At the Oct 2017  GOC meeting, we decided to form a working group to provide guidance for protein complex representation in Noctua: Formulate the issue; make a proposal

**Comment by kltm** [comment]
@pgaudet I'm not sure that this repo is the right venue for this.

**Comment by vanaukenk** [comment]
This is probably an issue that crosses both noctua and go-annotation.  I'm happy to move this one to go-annotation, though, as it probably has more general implications than just Noctua/GO-CAM.
@pgaudet - is that alright with you?

**Comment by pgaudet** [comment]
Hi @vanaukenk yes you can move this in any tracker - I just guessed where it should be, I'm happy that it moves anywhere (as long as there's a ticket !)

**Comment by kltm** [comment]
This issue was moved to geneontology/go-annotation#1663

**Comment by kltm** [comment]
(@vanaukenk just in case you don't know/use it, we've been happy with https://github-issue-mover.appspot.com/ to move issues around.)

**Comment by vanaukenk** [comment]
Thanks for the link @kltm  
I'll use that going forward.
