### ISSUE TITLE
Ensure GPAD files made by Noctua are easily consumable by contributing groups

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#518]
Action item from the Oct 2017 GOC meeting
 Chris: document where to slurp up GPADs

**Comment by kltm** [comment]
@pgaudet @cmungall What will the final location of this documentation be? I do not think it will land in the noctua repo, even including noctua-centric documentation.

**Comment by vanaukenk** [comment]
I actually have this issue (i.e. where/how to consume GPAD files from Noctua) as one of the headings in my outline of revised Noctua documentation since it is part of the overall Noctua/GO-CAM pipeline.
Work in progress, but here is the link to the doc in the Google drive:
https://docs.google.com/document/d/1hmYNEP7lWFwWGJbDOHfsfDvT77yBNRH4IW1TAPyhdqg/edit#heading=h.wyss1ui99rg5

**Comment by kltm** [comment]
We may want to revisit this. There is the Noctua editor/stack for creating GO-CAM models, then there is the pipeline and downstream data products that are produced from GO-CAMs, whatever their source (e.g. SynGO), as well as documentation for GO-CAM itself.
I think that part of the problem may come from that we used noctua early on as the interface to all things GO-CAM, but this will quickly change in the future--I believe that things like SPARQL endpoints, AmiGO delivery, pipeline output, etc., do not belong within the scope of the Noctua (often graphical GO-CAM editor).

**Comment by cmungall** [comment]
Discussed on the go-managers call, we need a ticket here as this is a blocker for adoption of Noctua.

We have an open ticket somewhere about the main blocker here, which is a trivial issue that we are not combining the models into per-group files. I can't find this ticket though. Once this is done the documentation should be straightforward, I can put on the main noctua site.

We have some related tickets:

 - https://github.com/geneontology/go-site/issues/169 Add CI jobs for LEGO downstream artefacts 
 - https://github.com/geneontology/go-site/issues/265
 -

**Comment by balhoff** [comment]
@cmungall were you looking for one of these?

- https://github.com/geneontology/noctua/issues/418
- https://github.com/geneontology/go-site/issues/431

**Comment by kltm** [comment]
@cmungall So this is a documentation ticket?
Have you checked the project list here?
https://github.com/geneontology/noctua/projects/3

I want to convert this into something actionable within the repo, or as part of a project.

**Comment by vanaukenk** [comment]
I think we can close this for now, but note that additional Noctua pipeline documentation would still be helpful.
