### ISSUE TITLE
End-user tools for consuming and displaying Noctua models 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#519]
Mix of several Action items from the Oct 2017  and June 2017 GOC meetings

* Create a working group to define the needs of end-user tools for displaying Noctua models 
David, Chris are interested (Sandra to if this includes a bigger choice of output formats)
**PIs Need to prioritize the development of end-user tools for displaying Noctua models**

* Provide ways for users to recover and digest GO-CAM units (Gene Ontology-based Causal Activity Model). Ideas include rule-based generations of text statements from model, cytoscape view of network described, etc.
(Seth?) I believe that this is a more exploratory and open project. We now offer an RDF enpoint, in addition to the APIs we already have, as well as the proposed feeding from AmiGO. If this is still open in the future, it may be very good Hackathon material. Needs more discussion.

**Comment by kltm** [comment]
@pgaudet what is the action here? Workgroups and PI priorities are not actionable within a repo.
For the latter remarks, we have https://github.com/geneontology/noctua/issues/512 and (new) #520 .

**Comment by pgaudet** [comment]
First task is to provide specification for the end-user tools
Participants: Huaiyu, Helen, Val, Kimberly etc

**Comment by lpalbou** [comment]
@kltm Is there a repo or channel for that discussion ?

@pgaudet This seems like a high priority and the issues described in this GitHub are more technical in nature, whereas this discussion is more high-level. Perhaps could we organize a call with all those interested and having an opinion ?

**Comment by kltm** [comment]
The (fairly technical) gitter channel is: geneontology/noctua, which you are already a member of.

This should perhaps be a project, in the wiki, or have some calls before adding more concrete/actionable items.

**Comment by vanaukenk** [comment]
Closing this ticket as it came from a meeting AI and the work requested is covered in other projects and more specific tickets.
