### ISSUE TITLE
Need help interpreting an error (?) message

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#522]
Hi,

I was working some more on test models for protein complexes:

http://noctua.berkeleybop.org/editor/graph/gomodel:59c8885900000281

and when trying to add evidence to assertions am getting a new (at least to me) message:

<img width="1644" alt="screen shot 2017-10-23 at 5 00 59 pm" src="https://user-images.githubusercontent.com/1730534/31912990-cec8a504-b813-11e7-8c28-399b93d2ea17.png">

I added a valid ECO code and a valid PMID, but when I click on Add, I am getting the message that says: 

![image](https://user-images.githubusercontent.com/1730534/31913072-1316e202-b814-11e7-8425-e6fc2e2bde55.png)

What does this mean?

Thx.

**Comment by kltm** [comment]
Text: "need all arguments added for"

**Comment by kltm** [comment]
I believe that this is related to the change made here:
https://github.com/geneontology/noctua/issues/493
For what you want to do, you'd want to fill the 1st and 3rd column?

**Comment by vanaukenk** [comment]
Okay, got it; that makes sense now; I was used to adding the paper directly after the evidence code.

It would be helpful to have more explicit wording for the 3rd row:

Enter source (i.e. PREFIX:id) -> Enter Reference (e.g., PMID:id or GO_REF:id)

**Comment by kltm** [comment]
No problem. For a verbiage change, would you mind following up on https://github.com/geneontology/noctua/issues/493#issue-256870047 ?

**Comment by vanaukenk** [comment]
Added a follow-up comment to #493 
Will continue discussion there.
Thx @kltm
