### ISSUE TITLE
Sometimes impossible to select right human protein except in Add Individual widget

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#523]
This issue is compounded by https://github.com/geneontology/neo/issues/22 which makes it a near-blocker for human annotation for many genes like FANCA.

once https://github.com/geneontology/neo/issues/23 takes effect this will be far less critical, and will vanish altogether when we do a general overhaul of AC. So this ticket is largely  pre-emptive (I am surprised not come up before? Not enough people doing human annotation?)

impossible to select the right protein the complex-creator:

![image](https://user-images.githubusercontent.com/50745/32100050-a5f27428-bae0-11e7-80a4-e665ef7d1a1f.png)

![image](https://user-images.githubusercontent.com/50745/32100062-b2eefcaa-bae0-11e7-88c4-81ebcaeb7dd9.png)

It's available here (the first O entry):
![image](https://user-images.githubusercontent.com/50745/32100192-2a78cd5a-bae1-11e7-91b5-98e347c694ee.png)

not available here:

![image](https://user-images.githubusercontent.com/50745/32100215-41c591e6-bae1-11e7-813f-1c47d8d36c2d.png)

nor here:

![image](https://user-images.githubusercontent.com/50745/32100251-52f553f2-bae1-11e7-9732-e6d314a973a0.png)

or in the SAE:

![image](https://user-images.githubusercontent.com/50745/32100402-9b28a8d6-bae1-11e7-9ddf-7367613c3e68.png)

## Workaround for curators

If the reference protein not available anywhere else, use Add individual.

**Comment by kltm** [comment]
(Assuming) closing after next NEO reload?

**Comment by vanaukenk** [comment]
This problem has been, at least partially, addressed by only including reviewed UniProtKB entries in neo and also by expanding the number of autocomplete matches in the form editors.
If using the graph editor, curators can always add the id directly, if an isoform id doesn't appear in the original list of 10 autocomplete entries.
