### ISSUE TITLE
Allow negation in Noctua and SAE and in GPAD export

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#524]
- [x] allow negation in main Noctua interface
 - [ ] allow negation in current SAE (not xSAE) https://github.com/geneontology/simple-annoton-editor/issues/3
 - [x] ensure negated GOCAMs are exported to GPAD correctly https://github.com/geneontology/minerva/issues/149

Note: this ticket replaces #218

**Comment by kltm** [comment]
Just a note: the branch remains unmerged for Noctua.

**Comment by kltm** [comment]
has own ticket, so closing super
geneontology/simple-annoton-editor#3
