### ISSUE TITLE
Finicky autocomplete behavior: Possible to autocomplete on partial matches?

### ISSUE THREAD

**Issue by chris-grove** [geneontology/noctua#525]
I've noticed that while entering in some GO process terms into the "Add process" biological process field that the autocomplete suggestions are very finicky and don't work on partial exact matches. For example, when trying to pull up the term "G-protein coupled serotonin receptor signaling pathway" I start getting terms that match "G-protein" and then as soon as I start typing "coupled" all matches disappear even though there are clearly many terms with the exact phrase "G-protein coupled" in their term names. Similarly, once I type the entire phrase "G-protein coupled" into the field I get several matches, none of which happen to be "G-protein coupled serotonin receptor signaling pathway", so I continue typing. As soon as I enter "G-protein coupled s" all matches disappear again, even though there are many terms that start with that exact phrase. Here's a screen recording of what I'm talking about:

https://www.dropbox.com/s/aqbw1v5psdo64xa/Noctua_process_autocomplete_issue.mov?dl=0

Would it be possible to adjust the autocomplete behavior to display exact matches, even if partial, to a phrase being searched?

**Comment by kltm** [comment]
@chris-grove This is known behavior, with the lame workaround of "try and hit the spacebar" for now. While we have AC tickets in Noctua that touch on this (e.g. https://github.com/geneontology/noctua/issues/257 https://github.com/geneontology/noctua/issues/261), the "roadmap" understanding is that as these are currently all driven directly from AmiGO, the issues live there. 

https://github.com/geneontology/amigo/issues/132
https://github.com/geneontology/amigo/issues/131
https://github.com/geneontology/amigo/issues/102

The short of it is that these are being held up on our switch to Solr 6 and better use of EdgeNGramFilter. The approach has already been tested, but is waiting for bandwidth for updates and rollout.

**Comment by chris-grove** [comment]
OK thanks, @kltm! Sounds good.
