### ISSUE TITLE
Evidence codes are only autocompleting on high throughput codes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#526]
Hi,

We are working on a model at WB right now and can only seem to autocomplete on the high throughput evidence codes.

Either typing text or the ECO IDs say, for example, direct assay evidence...' or 'ECO:0000314' does not autocomplete on any ECO code.  

Thx.

**Comment by kltm** [comment]
@vanaukenk I think I can confirm this. Very odd--currently looking into it...

**Comment by kltm** [comment]
http://amigo-dev-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=document_category:%22ontology_class%22&fq=source:%22eco%22&fq=regulates_closure:%22ECO:0000352%22&facet.field=source&facet.field=idspace&facet.field=subset&facet.field=is_obsolete&q=dir*&qf=annotation_class^3&qf=annotation_class_label_searchable^5.5&qf=description_searchable^1&qf=synonym_searchable^1&qf=alternate_id^1

**Comment by kltm** [comment]
Closing over: http://www.ontobee.org/ontology/ECO?iri=http://purl.obolibrary.org/obo/ECO_0000352

**Comment by cmungall** [comment]
It works in the SAE

difference:

 * SAE uses noctua-golr
 * SAE does not constrain by closure=ECO:0000352

it appears closure not working in amigo-dev-golr

closure is working in noctua-golr:

http://noctua-golr.berkeleybop.org//select?_=1511812355947&callback_type=search&defType=edismax&facet=true&facet.field=source&facet.field=subset&facet.field=regulates_closure_label&facet.field=is_obsolete&facet.limit=25&facet.mincount=1&facet.sort=count&fl=*,score&fq=document_category:%22ontology_class%22&fq=source:%22eco%22&indent=on&json.nl=arrarr&packet=1&q=manual*&qf=annotation_class%5E3&qf=annotation_class_label_searchable%5E5.5&qf=description_searchable%5E1&qf=comment_searchable%5E0.5&qf=synonym_searchable%5E1&qf=alternate_id%5E1&qf=regulates_closure%5E1&qf=regulates_closure_label_searchable%5E1&qt=standard&rows=10&start=0&wt=json&json.wrf=angular.callbacks._5&fq=regulates_closure:%22ECO:0000352%22

two quick fixes present themselves. Either of the two:

 1. change main interface to use noctua-golr (which it should be doing anyway?)
 2. temporarily remove closure constraint until we figure this out.

**Comment by kltm** [comment]
Can see load on: http://tomodachi.berkeleybop.org/amigo/search/ontology

**Comment by kltm** [comment]
Likely immediate fix is to switch over to the NEO server for evidence autocomplete as the dev server can be too variable.

**Comment by cmungall** [comment]
http://tomodachi.berkeleybop.org/amigo/load_details

![image](https://user-images.githubusercontent.com/50745/33289977-1259b9e8-d376-11e7-823a-2aa8a084121e.png)

no ontologies loaded!

A tiny subset seems to have sneaked in:

![image](https://user-images.githubusercontent.com/50745/33289950-011798b2-d376-11e7-8eb1-e0a8a20be7a0.png)

**Comment by kltm** [comment]
The fix should now be in production.
