### ISSUE TITLE
Create curator documentation

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#527]

**Comment by cmungall** [comment]
We have user documentation: http://wiki.geneontology.org/index.php/Noctua

And technical documentation for developers: https://docs.google.com/document/d/1w3mkF1RQIzwROOCMTkqjYaOn8ZbdsW52t-xA4DKt0vg/edit#

The technical docs are far from perfect. They are intended to provide a high level view of how the pieces fit together, and to indicate where they are not quite fitting together as intended. We also have a glossary aimed at developers.

**Comment by cmungall** [comment]
TODO

## Noctua

 * [ ] link to user docs http://wiki.geneontology.org/index.php/Noctua from noctua Learn More box
 * [ ] eliminate duplication between markdown and wiki
 
## Wiki

 * [ ] Add documentation on workbenches (other than SAE which looks done, but may need revisited after new features)
 * [ ] Align terminology (e.g. "graph canvas" vs "graph editor")
 * [ ] Add a troubleshooting/FAQ page?
 * ...

**Comment by lpalbou** [comment]
So I was reviewing the existing documentations for the 1.0 release and the [landing page](https://github.com/geneontology/go-site/issues/558), and so far here is what I have:

## Wiki
- [Noctua](http://wiki.geneontology.org/index.php/Noctua)
- [Noctua Quick Start](http://noctua.geneontology.org/doc/quick-start-guide) (wiki-like)

## Doc (file)
- [Developer Noctua Full Stack](https://docs.google.com/document/d/1w3mkF1RQIzwROOCMTkqjYaOn8ZbdsW52t-xA4DKt0vg/edit#heading=h.du3v9zif59jp)
- [Noctua User Guide](https://docs.google.com/document/d/1hmYNEP7lWFwWGJbDOHfsfDvT77yBNRH4IW1TAPyhdqg/edit#)
- [GO-CAM Curation Guide](https://docs.google.com/document/d/18ihslb7prB6CWtu2yjF-pMHZBTY1-AdXJAu-ZyuyXS4/edit#)
- [Developer Noctua Workbenches](https://docs.google.com/document/d/1ScazN8xL8iMpiPvSO3zBZ9AVsOs8LULvb9aMpwHsKkk/edit)

## GitHub
- [Developer Noctua Full Stack](https://github.com/geneontology/noctua#the-noctua-editor--barista--minerva-stack)
- [Developer Minerva Setup](https://github.com/geneontology/minerva/blob/master/INSTRUCTIONS.md)
- [Developer Barista Credentials / Login](https://github.com/geneontology/noctua/issues/270)
- [Developer Noctua Model Specifications](https://github.com/geneontology/minerva/blob/master/specs/owl-model.md)
- [Developer Minerva Request API](https://github.com/berkeleybop/bbop-manager-minerva/wiki/MinervaRequestAPI)
- [Developer Noctua REPL](https://github.com/geneontology/noctua-repl)

There are other GitHub repos, but I think those are sufficient to get everything up and running and do some tests !

## Proposed Improvements
* For the moment, the documentations are done mostly for either "_curator_" or "_developer_". I am not sure there is any documentation for a "_user_" that just want to search & access a model ?
* I think we should now always consider 3 categories of users: "_biologist_" (search & access model), "_curator_" (create & edit) and "_developer_" (HTS access & integration)
* For the "_biologist_" and "_curator_", I would put everything on the wiki (easy access), for the "_developer_", all of our documentations could be on the GitHub but I would add a single general wiki page to guide them through all the components ?
* On the front-end, can we speak only of GO-CAM model and not "Noctua Model" ?
* Following these remarks, I think these documentations needs to be re-organized a bit... could we create a group or agenda to clean them ?

**Comment by cmungall** [comment]
- curator docs should go on the wiki, agreed
 - For the biologist/researcher, we need at least a summary page on drupal. But I think it's OK to have a soft release where some end-user facing docs are on the wiki
 - GitHub OK for developers but at the moment it's just too spread out.
 -

**Comment by lpalbou** [comment]
I have created a single entry point to the documentations on the go wiki: [documentation](http://wiki.geneontology.org/index.php/cam/docs/)

And each type of users can access its own documentation here:
* [research](http://wiki.geneontology.org/index.php/cam/docs/research)
* [curation](http://wiki.geneontology.org/index.php/cam/docs/curation)
* [development](http://wiki.geneontology.org/index.php/cam/docs/development)

These pages are still very basic, but it's at least a unique starting point for each documentation.

**Comment by cmungall** [comment]
Can we stick to GO-CAM rather than CAM?

The pseudo-directory structure is interesting, but we have thus far 
organized using categories of Prefix:Page conventions.

http://wiki.geneontology.org/index.php/Wiki_best_practice

**Comment by vanaukenk** [comment]
Closing; this is ongoing work but this ticket is older and not as relevant.
