### ISSUE TITLE
Add UI-level tests to the client (behave/selenium webdriver)

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#53]
It would be useful to have an environment to write integration tests, e.g.
1. createNewDiagram()
2. i = addIndividual( type: foo, enabled_by: zod)
3. j = addIndividual( type: bar)
4. addLink(i,part_of,j)

This could be used to help test cases where minerva appears to hang after a few operations

**Comment by kltm** [comment]
Some stuff that can be used here now from the work on geneontology/amigo#176 and monarch-initiative/monarch-app#576. Would still need more specific Noctua steps, but not too hard (probably--very drag and drop-y).

**Comment by kltm** [comment]
Things have gotten easier and more pressing on this front. I'll take this on a little assuming I get some more from the 2015-07-push done.

**Comment by vanaukenk** [comment]
@kltm 
Please take a look and close if you think we can.
If not, and there is a more useful label to add here, please feel free.
