### ISSUE TITLE
Link to GPAD from front page goes to old GPAD report

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#533]
Either

 1. Change to SPARQL/Arachne based view e.b. http://noctua.berkeleybop.org/workbench/annpreview/?model_id=gomodel:59a9023b00000151
 2. Remove link altogether

**Comment by kltm** [comment]
@cmungall Are you sure these are different?
http://noctua.geneontology.org/download/gomodel:59a9023b00000151/gpad

**Comment by kltm** [comment]
I agree with @goodb that we may want to dump that link all together, if we do not want to get a separate landing page.

**Comment by kltm** [comment]
@cmungall The preview is a "live" re-viewer of the exported gpad from minerva with labels injected as available. An empty one would still be empty.
