### ISSUE TITLE
Restrict entries in ontology autocompletes in editors solely to is_a relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#534]
In order to prevent annotation errors, we would like to restrict ontology autocompletes to is_a relations.

Currently, for example, protein complexes with capable_of relationships to MF terms in the ontology are also available on the MF autocomplete.

**Comment by cmungall** [comment]
Note: while we should properly use is_a closure for this (see my PR), a quick improvement is to change this from regulates_closure (what it is using now, which includes a range of relations) to isa_part_of (which will still conflate MF/BP, but will be an improvement).

**Comment by kltm** [comment]
The schema was added to the PR and is now live on NEO and tomodachi/2.5/dev Solr servers.
We will not be able to act on this until reloads over the weekend.

**Comment by kltm** [comment]
Possibly working? Seems to return results:

http://noctua-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=1&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=document_category:"ontology_class"&fq=isa_closure_label:"molecular_function"&facet.field=source&facet.field=idspace&facet.field=subset&facet.field=is_obsolete&q=foo*&qf=annotation_class^3&qf=annotation_class_label_searchable^5.5&qf=description_searchable^1&qf=synonym_searchable^1&qf=alternate_id^1

**Comment by kltm** [comment]
@tmushayahama From the email thread, this is more an issue of with the close than the particular parameters. It may possibly be as simple as switching over to the `isa_closure` for what you're doing. If you want to dig into the parameters a bit, it is just Solr. That said (and from this https://github.com/geneontology/simple-annoton-editor/issues/26#issuecomment-360627280), I would encourage the use of the managers as is done elsewhere, instead of the custom code you inherited.

**Comment by kltm** [comment]
@vanaukenk We had this crop up somewhere else recently, yes?

**Comment by vanaukenk** [comment]
@kltm Yes, it did in our discussion on the workbenches call:

https://github.com/geneontology/noctua-form/issues/34

**Comment by vanaukenk** [comment]
This has been addressed in the Noctua forms, but not in the graph editor.
Closing for now as we are not actively working on it for the graph editor.
