### ISSUE TITLE
Include gorel.owl axioms in reasoning

### ISSUE THREAD

**Issue by balhoff** [geneontology/noctua#535]
The reasoning would be happening in Minerva, but I'm putting it here as there are some decisions to make that may affect what users see. We discussed at the GO docathon that users will want to see properties such as `has_regulation_target` in their annotation extensions. This isn't currently included in go-lego. So...

- Should we add gorel.owl to the go-lego imports?
- If so, will that make a bunch of new relations available in the Noctua editor, and is that desired?

**Comment by cmungall** [comment]
We could also put this one directly in RO

**Comment by pgaudet** [comment]
@balhoff We are moving all relations into RO. Is this still relevant ?

**Comment by pgaudet** [comment]
Also -  specifically 'has_regulation_target' will be obsoleted.

**Comment by balhoff** [comment]
If there aren't going to be special annotation extension-only relations, then I think we can close this.
