### ISSUE TITLE
Show rdfs:label as a name of node when present

### ISSUE THREAD

**Issue by goodb** [geneontology/noctua#536]
Currently, nodes rendered in the Noctua graphical editor list the names of the classes that the owl individual represented by the node is a member of.  In some cases it can be useful to display nodes that don't yet have class assignments.  It may also be useful to provide a specific name for a particular node apart from its list of classes.  It is a widely accepted pattern in the semantic web community to render rdfs:label as a name for entities that bear that annotation.

**Comment by kltm** [comment]
Strictly speaking, the (not OWL) model that Noctua operates with deals with objects like:

```json
                "id": "gomodel:5798651000000002/5798651000000009",
                "type": [
                    {
                        "type": "class",
                        "id": "UBERON:0001723",
                        "label": "tongue"
                    }
```

What we would need to affect this would be a change in Minerva that used `rdfs:label` for the label field in cases where it was needed.

...or is the idea here that if an individual had a `rdfs:label` annotation it would show/override with that?

**Comment by goodb** [comment]
My idea is the latter.  Where the rdfs:label annotation was present, it would be shown in addition (not overriding but perhaps at the top) to the list of types.  This would stop me from needing to create owl classes strictly for the purpose of showing a label as I am doing now.  Could mean a change to minerva to add the individual labels to the json it generates and then a change to logic of displaying them.  Unless the UI adopts a more freeform policy for authoring these graphs, this would only impact people building models outside of the framework - but I think that could be important.

**Comment by goodb** [comment]
Noting that the labels aren't making it through into the Pathway view workbench.  Nodes without class assignments show up there as empty.  It is working in main editor view.  (testing on local installation with most recent commits to master).

**Comment by kltm** [comment]
Correct, the workbenches have a different (and separate) renderer for the nodes. We can reopen to get at those a little later today maybe.

**Comment by kltm** [comment]
Interesting to note that the `onmouseover` events do not seem to fire in the big graphs. My guess is that this is some kind of cytoscape js optimization, but have not had time to dig in.

**Comment by goodb** [comment]
See the labels there now.  Wondering why they have <<  >> around them?  But not a big deal.

**Comment by kltm** [comment]
As the `rdfs:label` is a "developer" feature for GO-CAM at this point, and we already have other bracketing to highlight other information (e.g. `[` and `(`), I went with the easy to see `<<`.
