### ISSUE TITLE
Display of NOT annotations in graphical editor

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#540]
Hi,

The NOT annotations that we are testing in the SAE appear to be entered correctly, but their display in the graphical interface is a little tricky to see.
Depending on the GO term, the exclamation point is sometimes nearly hidden by the green and grey boxes in the upper left corner.
Can the display of a NOT annotation be made more obvious by:
- displaying the word 'NOT'
- making the display of the term more prominent in the individual box

Also, would it make more sense to display the NOT in the same box as the relation, e.g. NOT part_of.

Thx.

**Comment by kltm** [comment]
This is already fixed in issue the #218 branch, with an update to  the `class-expression` lib; it will be merged in with the completion of #218 
https://github.com/geneontology/noctua/commit/78400df73d5c3e1e0fde2d3dffdb8dc3175f8879
