### ISSUE TITLE
undesirable output in Annotation Preview & GPAD for CC extensions

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#546]
In this model: http://noctua.berkeleybop.org/editor/graph/gomodel:5a7e68a100000324 

I am only wanting to make component annotations with extensions, e.g. DNAH11 is shown to be in an axoneme that is part_of a "9+2 motile cilium" that is part_of a "respiaratory epithelial cell". Thus, I have used part_of relationships between the individuals.  @ukemi please correct me if I have some misconception about this.

However, the GPAD export is producing results that seem inconsistent with CC annotations. Focusing on the annotation of human DNAH11 that I gave the example of above, here is what the Annotation preview shows:

```
Object  Qualifier       GO Term DB Ref  Evidence        With/From       Taxon   Date    Assigned By     Ann. Exts.      Ann. Props.
DNAH11 Hsap     part_of axoneme PMID:26909801   direct assay evidence used in manual assertion  -       -       20180308 GO_Noctua  contributor=http://orcid.org/0000-0001-5501-853X|noctua-model-id=gomodel:5a7e68a100000324
DNAH11 Hsap     involved_in     9+2 motile cilium       PMID:26909801   direct assay evidence used in manual assertion  -       -       20180308        GO_Noctua       part_of(respiratory epithelial cell),part_of(owl:Nothing)       contributor=http://orcid.org/0000-0001-5501-853X\|noctua-model-id=gomodel:5a7e68a100000324
owl:Nothing     part_of 9+2 motile cilium       PMID:26909801   direct assay evidence used in manual assertion  -       -       20180308        GO_Noctua       part_of(respiratory epithelial cell),part_of(owl:Nothing)       contributor=http://orcid.org/0000-0001-5501-853X\|noctua-model-id=gomodel:5a7e68a100000324
```

Since I am making a CC annotation for "9+2 motile cilium", I want the part_of relationship, but the line that includes both the gene as the Object being annotated and the appropriate GO term as the GO  term used for annotation uses the relationship "involved_in". Then, it produces another line for the same GO term using the part_of relationship I want, but with "owl:nothing" as the Object being annotated.

**Comment by kltm** [comment]
tagging @balhoff

**Comment by cmungall** [comment]
The model is inconsistent (screen goes red when you switch on the reasoner). This is why you get the odd owl:Nothings in the annotation preview. I think the preview should give a clear message to curators.

Debugging inconsistencies is not always trivial, but in this case it's the use of part-of to connect the activity to the component. Either this should be occurs_in, or the axoneme should be part of the cilium

**Comment by cmungall** [comment]
Here is a demo model:
http://noctua.berkeleybop.org/editor/graph/gomodel:5a7e68a100000416?

![image](https://user-images.githubusercontent.com/50745/37314270-66fa8288-2610-11e8-82aa-d62622f30610.png)

two GPAD lines inferred:

![image](https://user-images.githubusercontent.com/50745/37314280-75797c42-2610-11e8-9a6c-105505b236a0.png)

so I think this can be closed - but may want a new ticket about clarifying the annot preview page?

**Comment by balhoff** [comment]
I think the GPAD exporter should return no annotations at all if the model is inconsistent (nothing can be trusted). If you all agree I'll make a ticket in Minerva for that.

Should it actually throw an error rather than return empty data?

**Comment by cmungall** [comment]
I agree. Just showing zero rows is to confusing. It should explicitly tell
curator to fix. We should write a section on the curator guide on the wiki
and link to it

**Comment by balhoff** [comment]
This is [implemented in Minerva](https://github.com/geneontology/minerva/issues/168) now. @cmungall can you point me to the curator guide wiki?

**Comment by cmungall** [comment]
http://wiki.geneontology.org/index.php/Noctua

**Comment by vanaukenk** [comment]
Closing this ticket; the reasoner is working fine and the model in question was incorrect.
