### ISSUE TITLE
New PRO terms not available in Noctua autocomplete

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#554]
Sorry is this is the wrong tracker for this; if it is please feel free to move.
I have a new PRO id which was in our GPI on Thursday (PR:000049975), as evidenced by our EI allowing it's use for Tubb3. 
To be on the safe side I have still been uploading gpad and gpi to the svn gpad-gpi/submission . 
I thought that the gaf, gpad, and gpi were, however, now being picked up directly from our site. 
Cannot use the new PRO id in Noctua. 
Is this some timing issue?

**Comment by hdrabkin** [comment]
Closing this because it appears to be missing the the gpi file on Friday; sigh

**Comment by hdrabkin** [comment]
Nope it IS in the GPI file

**Comment by kltm** [comment]
@hdrabkin Okay, we had a NEO load on the 14th, so one would expect that it's in there.
Can you give me location of the autocomplete that you're using, the input text, and the desired result?

**Comment by hdrabkin** [comment]
Ok, so in the graphical interface, new annoton, I start typing in this PRO id : PR:000049975 with a space into the enabled by,  and nothing comes up.

**Comment by hdrabkin** [comment]
FWIW, I also tried going into the SAE, and it would not accept the PR:000049975 as a gp either.

**Comment by kltm** [comment]
That's actually a good thing :)

**Comment by hdrabkin** [comment]
That isn't if we want to use SAE to use PRO terms as direct annotation objects ...

**Comment by kltm** [comment]
It is in that all autocompletes should have the same data backing them and if you are getting different results different places there are possibly more serious issues going on.

**Comment by hdrabkin** [comment]
ah, got ya

**Comment by kltm** [comment]
@hdrabkin I think this should be cleared now (not entirely sure, but just checking in on the ticket).

**Comment by hdrabkin** [comment]
Yes, just checked PR:000049975 and it took. I'll try a new one on Monday.
