### ISSUE TITLE
Rename "Simple annoton editor" to "Noctua form"

### ISSUE THREAD

**Issue by thomaspd** [geneontology/noctua#555]
Per @vanaukenk and @pgaudet, please change the name in the Workbenches dropdown, from "Simple annoton editor" to "Noctua form".

cc @tmushayahama

**Comment by kltm** [comment]
@tmushayahama Could you also move your repository over to `geneontology/noctua-form`?

**Comment by kltm** [comment]
@tmushayahama Whoops--to clarify, this is, I believe, entirely an issue in the SAE/NF workbench config YAML. We can either keep the issue here or move it to the SAE/NF repo. It should be just a simple string fix.

**Comment by kltm** [comment]
@tmushayahama As well, we should probably keep the rest of the info aligned, so the id should go from `simple-annoton-editor` to `noctua-form`.
