### ISSUE TITLE
unable to use CURI format for reference in the form editor

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#565]
In the Form Editor: I am unable to add a reference in the following format: 
ZFIN:ZDB-PUB-170818-4 
The message on the form is : "The proper format for references in a GO annotation is 'DB:accession_number': evidence(1)"

When using the "Search Database" function, the reference imported in the ZFIN:ZDB-PUB-### format. 
The form not allowing this format is an issue, especially for the reference which do not have corresponding PMID. (I can add example if needed)

Note: There does not seem to be an issue when using the Graph view.

**Comment by vanaukenk** [comment]
This issue was moved to geneontology/simple-annoton-editor#76
