### ISSUE TITLE
Graphical Editor autocomplete system appears to be malfunctioning

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#566]
In my new models I am creating in the graphical editor, gene symbols and cell types are appearing as identifiers rather than term labels.

See: http://noctua.berkeleybop.org/editor/graph/gomodel:5ae3b0f600001114

**Comment by kltm** [comment]
This is likely an issue with the NEO load. Reloading and restarting now.

**Comment by kltm** [comment]
I mean, that said, it currently looks correct to me...

**Comment by kltm** [comment]
![screenshot_2018-06-25_12-44-50](https://user-images.githubusercontent.com/2687900/41872035-9be51564-7875-11e8-8e5d-875d24d0d748.png)

**Comment by ukemi** [comment]
Yup They are back. Still not autocompleting on CL term 'hair germinal matrix cell'

**Comment by kltm** [comment]
Okay, working for me under "Add individual". Could you hard refresh and confirm?
