### ISSUE TITLE
Implement server-side error checks

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#567]
This ticket encompasses the creation and implementation of server-side checks in minerva <strike>in SPARQL</strike>.

This may possibly be done breaking down into the following tasks:

- [ ] implement the reading of SPARQL templates
- [ ] implement a run and return mechanism
- [ ] implement the running of checks on request (maybe skip?)
  - [ ] coordinate implementing a workbench to test usability/timing
- [ ] if speed acceptable, automatically run checks and inline check response in TBD format, like reasoner response
  - [ ] coordinating implementing into noctua clients

Tagging @balhoff and @dougli1sqrd

**Comment by balhoff** [comment]
Will any of these checks require query over the inferred graph, or only asserted triples? For example, requiring X be, not necessarily stated, but at least inferred, to be an instance of Y.

**Comment by kltm** [comment]
For testing, manipulating models and checking responses could be done with https://github.com/geneontology/noctua-repl . I've added some more examples and a couple of new functions to help with query construction and examination.

I guess next is to figure out the return structure and what is feasible? As "unsaved" (in-memory) models are unavailable for SPARQL, that would seem to limit some of the approaches.

**Comment by kltm** [comment]
Treating as dupe of https://github.com/geneontology/minerva/issues/212
