### ISSUE TITLE
Change evidence / provenance model regarding providedBy

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua#573]
I was discussing with Paul and Tremayne about the recent problem with providedBy and they would prefer the providedBy to be linked not to the gocam itself, but to the evidence. In effect, it would allow a gocam to have multiple providedBy and would solve (at least partially) the problem of gocam ownership if someone edit it/review it after.

**Comment by kltm** [comment]
This is a question about changing the evidence model?
As it stands now, all operations generate a provided-by on all entities, by design, as well as adding them to the model-level. I think there would have to be a pretty strong case against to change that.
Tagging @cmungall for discussion.

**Comment by lpalbou** [comment]
Sounds good, thanks
