### ISSUE TITLE
Loss of entity (label) in autocomplete / NEO / display

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#580]
Marie-Claire has been working on a model for which we are now getting a reasoner error:

http://noctua.geneontology.org/editor/graph/gomodel:5b318d0900000658

The model is relatively straightforward, just linking functions to processes, but it looks like the Y58A7A5 entity is no longer available in the autocomplete (it was there originally when she made the annotation).

Right now, this seems the only possible reason that we are getting an error, i.e. the reasoner doesn't know what Y58A7A5 actually is.

Y58A7A5 currently has no GO annotations, so it must have come from the WB gpi file suggesting that the full content of our gpi file was in NEO but perhaps NEO now only contains previously annotated genes?

There were some issues with our gpi file, but we thought we had fixed them:

https://github.com/geneontology/go-site/issues/595

**Comment by balhoff** [comment]
The `RNA polymerase II regulatory region sequence-specific DNA binding` is being inferred to be both a `molecular function` and a `biological process`.

Aha - there is an inference of [OBI:binding](http://purl.obolibrary.org/obo/OBI_0001588) which is a `biological process`. For some reason the ontology includes

`sequence-specific DNA binding` SubClassOf `OBI:binding`

**Comment by vanaukenk** [comment]
Note that we also have two other models that are giving reasoner errors.  These models are more complicated, but only used entities that already had GO annotations.

http://noctua.geneontology.org/editor/graph/gomodel:5b528b1100000186
http://noctua.geneontology.org/editor/graph/gomodel:5b528b1100001416

We currently can't figure out what might be wrong with these models.  

For the model mentioned in the first part of this ticket, a hint about what might be wrong came from looking at the table at the bottom of the form, where the annotation between Y58A7A5 and its molecular function was flagged as being an incorrect relationship, but we don't see anything flagged in the form for these two other models.

Any insight would be welcome before we start fully deconstructing these models to find the errors.

Thx.

**Comment by vanaukenk** [comment]
Thanks @balhoff  - we didn't catch the OBI:binding inference.
But I'm curious as to why the OBI is even used for GO-CAM models.

**Comment by balhoff** [comment]
This is coming in from OBI, through ECO. I'm not sure why OBI includes axioms putting molecular functions as subclasses of biological processes. I made a change a few weeks ago to try to prevent these problems: https://github.com/geneontology/go-ontology/pull/16239

But I suspect the newest go-lego.owl is not being used in Noctua yet. @kltm we will need a restart to pick up the latest ontology.

**Comment by kltm** [comment]
If it's okay, I'll put a restart into the schedule for this Friday?

**Comment by vanaukenk** [comment]
@kltm - this touches on an issue we discussed at USC, i.e. how frequently we need to update the ontology in minerva for Noctua users.  An update from the daily snapshot would be ideal.

For now, the earlier the update, the better as Marie-Claire needs to QC the GPAD output for a WormBase upload and we can't get the GPAD output if there is an inference error.  

Thx.

**Comment by vanaukenk** [comment]
Thanks @kltm

**Comment by kltm** [comment]
Minerva has now been updated and is restarting.

**Comment by vanaukenk** [comment]
Thanks @kltm . I just checked a number of our models that were throwing reasoner errors and they look okay now.

We still see the original issue for this ticket, though, i.e. entities that were once available for annotation are now no longer available in the autocomplete in either the graph or form editor.

And interestingly, after the minerva restart and updating, in the model that originally started this ticket, the entity name in the graph and form editor changed from 'Y58A7A5' to 'WBGene00021979':

http://noctua.geneontology.org/editor/graph/gomodel:5b318d0900000658

I don't quite understand what is happening here.

**Comment by kltm** [comment]
(changing title to redefine scope of ticket)

My guess is that minerva is using one of the public amigo loads to find labels that it does not have and that this gene is no longer in the data:
http://amigo.geneontology.org/amigo/medial_search?q=Y58A7A5
For that matter, the gene does not appear to be in the NEO load.

**Comment by vanaukenk** [comment]
We're now reviewing annotations to the model that originally had annotations to Y58A7A5.  Marie-Claire deleted those annotations using the graph editor but the annotations still appears in the table at the bottom of the form (with an error message that doesn't make sense) and then also in the GPAD output from Jenkins.  

This is the model:
http://noctua.geneontology.org/editor/graph/gomodel:5b318d0900000658

I'm not sure what's actually happening here, but if there's anything we can do to help troubleshoot, let me know.

**Comment by kltm** [comment]
@vanaukenk I suspect that this is a different issue completely, likely to the annotons being off-screen.

**Comment by vanaukenk** [comment]
The form editor, graph editor, and cytoscape now all seem to agree on the correct number and content of annotons.  Thx.
