### ISSUE TITLE
Refactor collapsed view to preserve relation directionality

### ISSUE THREAD

**Issue by goodb** [geneontology/noctua#582]
Consider a folded function node X such as 'Beta-catenin is released from the destruction complex' in http://noctua-dev.berkeleybop.org/editor/graph/gomodel:-80976963

Relations such as:
Z 'involved in positive regulation of' X and
X 'enabled by' Y 

are shown to the user like:
'involved in positive regulation of' Z
'enabled by' Y 

as if Z and X were switched, resulting in confusion.  See https://github.com/geneontology/pathways2GO/issues/18  

When folding incoming relations, show instead something like
Z 'involved in positive regulation of'

**Comment by vanaukenk** [comment]
Closing for now.  We can open a new ticket if the issue comes up again.
