### ISSUE TITLE
Form "has input" field does not recognise UniProt accessions, cannot add multiple inputs

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#583]
1) Under MF in Form, I'm trying to add a protein by UniProt accession, but it won't autofill. Even if you type out "UniProtKB'", when you continue with the ":" all results disappear.  I made the model with a UniProt and the information is lost (with no warning to user). I had to type out the name/organism, when I already had the accession to paste in.

2) I need to add two "has_input"s to an annotation.  Is there a way to tweak the Form? I managed to do this through the Graph Editor but it wasn't intuitive (two different titles for what, to the user, are the same thing: "sub-nodes"/"edge & class expression" 

Thanks for any help.

**Comment by kltm** [comment]
Okay, I'm trying to find a general ticket that covers this, but I've been having trouble finding one that fully captures it.
In summary, use the "Add annoton" section, put in the full id (sithout selecting), and then add a GO term, etc. For example:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:5b4695e900000155

As a matter of policy at this point, we only want people annotating to entities that they've identified in their GPIs that we ingest (the NEO load). Practically speaking, this breaks down with UniProtKB identifiers as we currently do not ingest them (https://github.com/geneontology/noctua/issues/471). As a temporary workaround, we remove this restriction from the "Add annoton" input.

**Comment by kltm** [comment]
As I understand general curator training at this point, annotons should be generally created in the Form editor (under workbenches), and then wired together, as necessary, in the graph editor. I do not know off the top of my head the state of input for the Form editor.

**Comment by vanaukenk** [comment]
For issue 1 - it would be desirable to be able to cut and paste an accession or id into the 'enabled by' fields of the form and graph editor and autofill on the correct entity.  With the exception of the 'Add individual' field (which isn't an 'enabled by' field), cutting and pasting an accession or id does not yield anything from the autocomplete list.

For issue 2 - perhaps we could add a feature to the form that would allow curators to add another row of contextual information, although we will want to be selective about which rows could be duplicated.  

The graph editor was designed to be more general, though, allowing contextual information (of whatever relevant type) to be added to any node.  Perhaps we could put a more user friendly label on the 'Add edge and class expression' section of the graph editor, though.  Would 'Add contextual information' be suitable?

**Comment by vanaukenk** [comment]
@kltm - let me know if we should split this out into two separate tickets.  I've done that for the related tickets on the simple-annoton-editor tracker.

**Comment by vanaukenk** [comment]
Closing for now.  @suzialeksander if there are still outstanding issues here, please reopen.
