### ISSUE TITLE
GO term autocomplete not working for Add function and Add process in graph editor

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#585]
Hi,

I am unable to use the GO term autocomplete in the graph editor for the Add function and Add process widgets.  When I type in the beginning of a term name, e.g. 'nematode' for process, I get a spinning wheel response.  A hard refresh didn't seem to help.

The autocomplete is, however, working for the same search in the form and in the Add individual and Add annoton widgets on the graph editor.

**Comment by kltm** [comment]
Duplicate:
* Login
* search "scratch"
* select http://noctua.berkeleybop.org/editor/graph/gomodel:55ad81df00000001
* select 'Add function' panel
* enter "foo" into molecular function
* endless spinning

**Comment by kltm** [comment]
amigo-dev-golr (stove) seems to have had solr/jetty9 become unresponsive silently, with no issues apparent on machine. restart cleared issue.

**Comment by vanaukenk** [comment]
Thank you @kltm !

**Comment by kltm** [comment]
Once we get our feet a little better, we should have something to 1) prevent this from happening in the first place (centralized) autocomplete and 2) something to catch it before we need a report (deeper automated testing).

**Comment by kltm** [comment]
I'm going to poke around a little and see if I can find why it disappeared.
