### ISSUE TITLE
Under some circumstances, the landing page errs and does not load

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#588]
Reported by @goodb .

1) reset chrome
2) restart computer
3) load http://noctua-dev.berkeleybop.org
4) login via github from the landing page
5) return from login to landing page
5.1) error occurs

```
noctua-dev.berkeleybop.org says
There was a manager error (error): message and message_type must always exist
```

Under Chrome, in the network debug view, the m3Batch endpoint ambiguously reports "(failed)" as the Status and under Response "Failed to load response data".

This has been tried and behaves similarly under Safari and Chrome [untried in Firefox?]. There are apparently no ad blockers or plugins in use in either browser.

A workaround seems to be going directly to a model and logging in from there.

**Comment by kltm** [comment]
Unable to replicate on home connection with:
 Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
 OS X: 10.13.4 (17E199)

**Comment by vanaukenk** [comment]
@kltm - do you want to keep this ticket open?
