### ISSUE TITLE
Noctua form "view" menu inconsistent with graph editor "view" menu

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#593]
The Noctua form "view" dropdown shows workbenches (GE, Annotation Preview, etc). These are the options on the Graph Editor's "Workbenches" menu.  The GE "view" is about zoom/exploding the model, etc.

Is there a way these can be a little more uniform? Preferably, the "view" menu has the same options no matter which workbench you're on.

**Comment by kltm** [comment]
Related to #399 , etc.

**Comment by kltm** [comment]
If there is low hanging fruit, we should certainly go for it. If you make the suggestions here, we can see what needs to be done and work out where it goes.

**Comment by vanaukenk** [comment]
Closing for now; not actively being worked on.  We can review all of the form-based UIs for consistency.
