### ISSUE TITLE
zebrafish genes unavailable in Noctua

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#595]
I am unable to find zebrafish gene in both the form and in the graph view. 
The genes I am trying to annotate (and are not found in the interface) are: 
- nrp1a (ZFIN:ZDB-GENE-030519-2)
- nrp1b (ZFIN:ZDB-GENE-040611-1)
- robo2 (ZFIN:ZDB-GENE-001019-1)

These genes are in our GPI file. 

thanks!

**Comment by kltm** [comment]
All three in upstream: https://zfin.org/downloads/zfin.gpi.gz
Note loader failure https://build.berkeleybop.org/job/load-golr-noctua-neo/161/
Trying refresh.

**Comment by cmungall** [comment]
Confirming ZDB-GENE-030519-2 made it into http://purl.obolibrary.org/obo/go/noctua/neo.owl, so the solr loader failure seems most likely explanation

**Comment by kltm** [comment]
I've been unable to get the job to run in Jenkins or manually.
@cmungall Has anything significant changed in the load/NEO that you know of?
Also, is there anything in the command that could be peeled out? It always seems to run for a while, then chokes on a 
```
Exception in thread "main" org.apache.solr.client.solrj.SolrServerException: java.net.SocketException: Broken pipe (Write failed)
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:475)
```
after a half to two and a half hours.
```
java -Xms1024M -DentityExpansionLimit=4086000 -Djava.awt.headless=true -Xmx192G -jar ./java/lib/owltools-runner-all.jar http://purl.obolibrary.org/obo/go/extensions/go-lego.owl http://purl.obolibrary.org/obo/eco.owl http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl http://purl.obolibrary.org/obo/cl/cl-basic.owl http://purl.obolibrary.org/obo/go/extensions/gorel.owl http://purl.obolibrary.org/obo/pato.owl http://purl.obolibrary.org/obo/po.owl http://purl.obolibrary.org/obo/chebi.owl http://purl.obolibrary.org/obo/uberon/basic.owl http://purl.obolibrary.org/obo/wbbt.owl http://purl.obolibrary.org/obo/go/extensions/go-modules-annotations.owl http://purl.obolibrary.org/obo/go/extensions/go-taxon-subsets.owl --log-info --merge-support-ontologies --merge-imports-closure --remove-subset-entities upperlevel --remove-disjoints --silence-elk --reasoner elk --solr-taxon-subset-name amigo_grouping_subset --solr-eco-subset-name go_groupings --ontology-pre-check --solr-url http://localhost:8080/solr/ --solr-config /home/bbop/local/src/git/amigo/metadata/ont-config.yaml --solr-log /tmp/golr_timestamp.log --solr-purge --solr-load-ontology --solr-load-ontology-general
```

**Comment by cmungall** [comment]
nothing changed I know of

**Comment by kltm** [comment]
After a worrying number of retries, I *believe* that I've gotten at least a full load in piecemeal.
For now, I've suspended the `load-golr-noctua-neo` job, as it can no longer apparently complete on its own.

**Comment by vanaukenk** [comment]
Hi - I'm having a similar issue with a C. elegans gene, cyk-7, that I'm trying to annotate in Noctua.

It is not available in the autocomplete in the form or graph editor.

Here is its entry in our gpi file:

WB	WBGene00015591	cyk-7	CYtoKinesis defect	CELE_C08C3.4	gene	taxon:6239		UniProtKB:P34325

That can be found here:
ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/gene_product_info/c_elegans.PRJNA13758.current.gene_product_info.gpi.gz
  
Is the C. elegans gpi file being loaded into NEO? 

We have discussed a similar issue with another gene in a separate ticket, but I don't think this ever got resolved:

https://github.com/geneontology/noctua/issues/580

**Comment by kltm** [comment]
@vanaukenk Your issue is a separate one--the above issue is about the loader, your issue seems to be about being in NEO, which is seems to not be:
```
sjcarbon@moiraine:/tmp$:) wget http://purl.obolibrary.org/obo/go/noctua/neo.owl
sjcarbon@moiraine:/tmp$:) grep "cyk-7" neo.owl | wc
      0       0       0
```
The source we have for you is
```
   source: ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/PRJNA13758/annotation/gene_product_info/c_elegans.PRJNA13758.current.gene_product_info.gpi.gz
```
with the last load a few days ago. If your GP is less recent than that, we should open up a new ticket.

**Comment by vanaukenk** [comment]
Thanks @kltm 
Then we should probably open a new ticket, since I can see the "cyk-7" entry in our source gpi file which was generated 2018-11-10.
I'll create a new ticket.

**Comment by kltm** [comment]
You may want to try https://github.com/geneontology/neo for Chris--the entity does not appear in the NEO file as currently downloaded apparently (see my example above).

**Comment by vanaukenk** [comment]
Okay, I'll create a ticket in neo (there is also now one in https://github.com/geneontology/noctua)

**Comment by vanaukenk** [comment]
Closing this ticket, as I think the issues have been resolved.  Please re-open if I'm mistaken.
