### ISSUE TITLE
Allow workbenches to take parameter arguments (pass parameters)

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#599]
Currently, all workbenches are invoked with a plain URL. The closure of this would allow parameters (body?) to be passed back to workbenches, either/both as parameters or globals (necessary in post).

There is a chance this is a duplicate.

**Comment by tmushayahama** [comment]
@kltm is it possible to start using local storage

**Comment by kltm** [comment]
I'm not sure what you mean by local storage.

**Comment by kltm** [comment]
If you are referring to this, I'd rather not: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Local_storage
The framework is based on parameter passing and I'd 1) rather not have two ways of passing control and 2) we want to preserve passing control to non-origin clients.

**Comment by vanaukenk** [comment]
@kltm @tmushayahama - do we still need to keep this ticket open?

**Comment by tmushayahama** [comment]
@vanaukenk You can close this one I think
