### ISSUE TITLE
Create embeddable "activity-only" graph widget

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#600]
The completion of this issue is the creation of a limited information/"activity-only"/annoton-only graph view that can be used to easily tie together different annotons.

The main use case is to 1) "wire" together annotons within the form view. An auxiliary use cases may be to clarify BP selections for the annotons (pending feedback from @vanaukenk ).

**Comment by cmungall** [comment]
I suggest the following terminology

 * X-_centric_ : all boxes in display MUST show only instances of X. The boxes may contain additional info (e.g activity-centric may show gene products, location)
 * X-_only_ : X-centric AND no other info

I posit there are use-cases for activity-centric, occurrent-centric, entity-centric, entity-only. I'm not sure there is a use-case for activity-only.

**Comment by lpalbou** [comment]
Google presentation of the requirements: https://docs.google.com/presentation/d/1vdwVyMrfj4YdbdJLuzfoTGf3BSWlXlLw4maXR7XtYUU/edit#slide=id.p1

**Comment by lpalbou** [comment]
This is the repo for developments related to that graph widget: https://github.com/geneontology/activity-flow-editor 

@kltm @cmungall I added some notes about both user & technical requirements here: https://github.com/geneontology/activity-flow-editor/issues/1

@tmushayahama I added there the intended way to integrate the widget. Let me know if you have questions 

Also, it seems we'll be referring to this "graph widget" as "Activity Flow Editor" or AFE 😄

**Comment by vanaukenk** [comment]
Closing this ticket for now.  The new VPE seems to cover  at least some of this functionality.
