### ISSUE TITLE
Improve autocomplete/autosuggest such that we could just type the first few letters of each word to find a term

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#601]
The correct term can be found by just typing the first few letters of each word of a term to find the term. (This saves curators a lot of time)
Examples:
Type: “di ma as” finds the term “direct assay by manual assertion”.
Type: “d bin tr fac ac” finds term “DNA-binding transcription factor activity”

This feature is available at ZFIN (I would be happy to make a demonstration). 
ZFIN developers would be able to answer questions (and maybe share some code?) about how it works at ZFIN.

**Comment by vanaukenk** [comment]
Closing for now.  We could re-visit if we want to review the autocomplete functionality more generally.
