### ISSUE TITLE
Noctua GPAD: discrepancies between updated annotations in models and in GPAD file 

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#607]
In the ZFIN Noctua-GPAD: 
2 annotations appear different in the GPAD and in the actual models. 
In both cases, the ID in the “with” field was originally entered incorrectly, and were later updated (the date on the models is 2019-03-01). 
In other words: the IDs in the models are correct (and updated), but the IDs in the GPAD are incorrect (I added the lines of the GPAD below). 

(This might be due to the fact that a new GPAD has not been created since 2019-03-01? If so, how often is a GPAD created?)

Here are the GPAD lines: 
ZFIN      ZDB-GENE-050208-114  acts_upstream_of_or_within     GO:0007601              PMID:27033669              ECO:0000315     ZFIN IZFIN:ZDB-MRPHLNO-180504-1                          20180912           ZFIN                     noctua-model-id=gomodel:5b91dbd100000059|contributor=http://orcid.org/0000-0002-4142-7153|model-state=production

ZFIN      ZDB-GENE-030131-3196              enables GO:0000981              PMID:29084713              ECO:0000353     ZFIN ID: ZDB-GENE-991105-4                             20181114           ZFIN              part_of(GO:0006357),has_input(ZFIN:ZDB-GENE-991105-4)              noctua-model-id=gomodel:5b91dbd100000676|contributor=http://orcid.org/0000-0002-4142-7153|model-state=production

**Comment by balhoff** [comment]
@dougli1sqrd @kltm my guess is that this is a result of the Noctua models git commits not being pushed to GitHub in quite a while (last commit Jan 14). Someone needs to unstick it on the server.

**Comment by cmungall** [comment]
Thanks Jim, this will happen next week

>

**Comment by kltm** [comment]
I believe the issue started with a non-SOP model push to `master` (https://github.com/geneontology/noctua-models/commit/5a7ce38afb99c84d709baddac1e360ca72f8bcfa), which causes a hang-up unless coordinated. 
I've added a rule for now to keep this from happening again, hopefully: https://github.com/geneontology/noctua-models/settings/branch_protection_rules/4884320
We may want to revisit the S3 dropbox (or similar) that we started with originally, and just syncing that to a GH repo--that would give us the best of both.

**Comment by goodb** [comment]
Apologies @kltm that was an accident on my part.

**Comment by vanaukenk** [comment]
Closing, as I think this issue has been addressed.  @kltm please re-open if that's not correct.
