### ISSUE TITLE
Noctua group/funding attribution lost

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua#610]
Hi @kltm 
My option to select 'ARUK-UCL' as the group/funding, which my GO-CAMs should be associated with, seems to be lost; my only option atm is BHF-UCL (screenshot below), whereas previously I was (at some point) able to choose from ARUK-UCL, SynGO-UCL and BHF-UCL. Could we please bring ARUK-UCL back?
Thanks,
Barbara

cc @RLovering 

Related issues:
https://github.com/geneontology/noctua/issues/569
https://github.com/geneontology/noctua/issues/458

![Screenshot 2019-04-16 at 15 04 22](https://user-images.githubusercontent.com/16541096/56216481-6d159e80-6059-11e9-9d35-1949eacdc782.png)

**Comment by cmungall** [comment]
The URLs have to match

This is wrong:

https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl

Should be:

https://www.ucl.ac.uk/functional-gene-annotation/neurological

**Comment by kltm** [comment]
I had thought we had a hard check to prevent things like this from happening, but it turns out that there is only a soft check right now.

```
sjcarbon@moiraine:~/local/src/git/go-site[master]$:) python3 ./scripts/sanity-check-users-and-groups.py --verbose --users metadata/users.yaml --groups metadata/groups.yaml
INFO:sanity:Verbose: on
INFO:sanity:Will operate on users: metadata/users.yaml
INFO:sanity:Will operate on groups: metadata/groups.yaml
Ruth Lovering has mistaken group entry: http://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/aruk-ucl
Ruth Lovering has mistaken group entry: https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl
Barbara Kramarz has mistaken group entry: http://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/aruk-ucl
Barbara Kramarz has mistaken group entry: https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl
Jesualdo Tomás Fernández Breis has mistaken group entry: https://greekc.org
Belén Juanes Cortés has mistaken group entry: https://greekc.org

No URI, or no ORCID:
===================


No Groups:
===================


Both Bad:
===================

Non-failing run.
sjcarbon@moiraine:~/local/src/git/go-site[master]$:) 
```

Looking at these, what do people want to use?

**Comment by kltm** [comment]
http://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/aruk-ucl
https://www.ucl.ac.uk/functional-gene-annotation/neurological/projects/tabs/syngo-ucl

vs 

https://www.ucl.ac.uk/functional-gene-annotation/neurological
https://www.ucl.ac.uk/functional-gene-annotation/neurological/syngo

note that the former resolve but that the latter seem to look a little safer

**Comment by kltm** [comment]
Never mind, none resolve - going with @cmungall 's alignment.

**Comment by kltm** [comment]
This should hopefully be solved now.

**Comment by BarbaraCzub** [comment]
Hi @kltm the choice of groups/funding is back now. Thank you!

**Comment by RLovering** [comment]
Hi Seth
unfortunately the URLs need updating

Please could you point me to where I can do this, or change these as follows:
ARUK-UCL: https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/neurological-gene-2
SynGO-UCL (not sure that we actually need this one any more): https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/neurological-gene-4
BHF-UCL: https://www.ucl.ac.uk/cardiovascular/research/pre-clinical-and-fundamental-science/functional-gene-annotation/cardiovascular-gene

Thanks

Ruth

**Comment by kltm** [comment]
@RLovering These are not *really* URLs, in the web browser sense,  but URIs used as a universal unique identifier for a specific concept. In general, these are not updated as one would a link to a website.

**Comment by RLovering** [comment]
oh OK one less thing to do ;)

Ruth
