### ISSUE TITLE
Add systematic sorting to Annotation Preview

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#617]
I am finding it very difficult to be able to check that I have entered all of the annotations that I meant to in Noctua. There does not seem to be any simple way to sort by either annotated gene, or term annotated to.

This is particularly problematic when you have entered a significant number of annotations such as in this model.
**ID** - gomodel:5c4605cc00003312
**Name** - SPATA7 maintains photoreceptor-specific distal connecting cilium - PMID:29899041 - KRC

The annotation table in the Form view appears to have a random order, and it's not just that new annotations push older ones down. While I haven't taken notes on this, I often do look for existing annotations in the table so that I can copy them into the form and there is no clear pattern about where in the table the newest annotation will show up, and no systematic order related to either gene name or GO term.

The Annotation Preview has pretty much the same issues as the annotation table in the Form view. 

At a minimum, it would be helpful if the both the annotation table in the Form view and the Annotation Preview had a predictable order related to gene name and GO term name. It might be even better if they were sortable, or at least one of them. Having an option to download the Annotation Preview as an Excel file could also be helpful.

**Comment by kltm** [comment]
@krchristie Could you split out the Form feature request into the https://github.com/geneontology/simple-annoton-editor/issues repo?

**Comment by vanaukenk** [comment]
From 2019-07-31 call:

@kltm will add column sorting to the existing Annotation Preview.

**Comment by kltm** [comment]
While "done" this is held in Clearing for now as it is only available on "dev" until master is rebased onto it.
