### ISSUE TITLE
Add a minimal interface to the graph editor for displaying validation / shex results

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#629]
The emphasis here is minimal. While we are still looking at how to move forward with the consumption of the Minerva/ShEx framework, we want to expose a minimal interface at minimal cost to allow people to explore the space a little.

This is a minimal expression of geneontology/minerva#212

Tagging @vanaukenk 

Initially, failed validation is marked in title ("!"), on top-level nodes, and as "INVALID" in the info. As a minimal usability extension, a summary of violations should be offered.

**Comment by kltm** [comment]
@vanaukenk (from our discussion, just a few minutes towards a richer goal, but useful)
On `dev`, there is now an additional demonstrator that adds the violation "identifier" (when available) and the label (type composite) of the node that it occurs in. This information is found in the lower [Info] box in the graph editor.
Also tagging @goodb

**Comment by goodb** [comment]
For demo purposes, I grabbed some screenshots of shex debugging in progress for reactome models: https://github.com/geneontology/pathways2GO/issues/69#issuecomment-536749152  

Would be nice if those new fields in the info box could be clickable and would bring you to the node in question.  (But I guess premature to be concocting fun UI tricks before doing a real design).  I think the minimal implementation running now actually goes a long way as it is.

**Comment by kltm** [comment]
@goodb Yes, that's exactly it--there is no real method in the current system for snap-to on nodes. While that is a final goal, and there will be more discussion there (@vanaukenk was a note/stub for it), this ticket is for getting what useful easy bits we can from the current code and (glued together) framework.

**Comment by vanaukenk** [comment]
We have a minimal interface for displaying validation/shex results in the graph editor.  It needs more work, but I think that would best be done in a new ticket/project with specific requirements.
