### ISSUE TITLE
view annotations

### ISSUE THREAD

**Issue by Antonialock** [geneontology/noctua#632]
Hi,
Sorry if this is the wrong tracker.

Congratulations on the paper. I wanted to view the 'standard' annotations that are created by Noctua ("The GO-CAM-derived annotations are integrated into the standard GO annotation releases and thus are already in widespread use. ")

I clicked on the "browse" tab here: http://noctua.geneontology.org/ 
and followed the link to amigo2lab
http://tomodachi.berkeleybop.org/amigo/search/model_annotation

is this where the "standard GO annotations" outputted by noctua should be displayed? I am getting an error when I try to access the page.

<img width="1183" alt="Screenshot 2019-10-03 at 13 24 05" src="https://user-images.githubusercontent.com/12727506/66126340-27d23280-e5e1-11e9-8eb4-a747a99547e6.png">

I also tried to look in AmiGO but I can only find 49 annotations with Contributor GO_noctua? This is clearly not correct since "Currently there are more than 2,300 GO-CAMs of varying complexity, containing more than 11,000 distinct triples, encompassing 16 species and more than 1,600 gene products"

<img width="1032" alt="Screenshot 2019-10-03 at 13 38 50" src="https://user-images.githubusercontent.com/12727506/66127446-96b08b00-e5e3-11e9-80eb-d0dd9ae814bd.png">

Thanks!

**Comment by vanaukenk** [comment]
@Antonialock 
For any given model in Noctua, you can click on the 'GPAD' link to the right of the model name in the table on the Noctua landing page to see the standard annotations output for that model.

The contributor for a model should be the annotation group (e.g. MGI, Zfin, WB, etc.).  In the example you show above, I'm not sure why we get GO_Noctua as contributor, but we'll look into it.

@kltm can comment further on the current behavior of the Browse link, but know that we also have a link from geneontology.org that you can use to browse and search go-cams:  https://geneontology.cloud/browse

Please let us know if you have any additional feedback on the browse link above.

Thx.

**Comment by Antonialock** [comment]
Thanks Kimberley. 

I started having a browse through the content at https://geneontology.cloud/browse
I'm not sure it is working as intended. 

For example, only 25 gene products are shown when applying the Gene Product Filter (but there should be 1600+?).

When using the date filter, it looks like the only models displayed went into production during a week in June?

<img width="1160" alt="Screenshot 2019-10-03 at 17 31 01" src="https://user-images.githubusercontent.com/12727506/66145949-b061ca80-e603-11e9-9f92-7773fdef50bd.png">

Also, using the contributor filter, only a handful of people are shown (you are missing for example) or when filtering by group only ZFIN and MGI are showing

**Comment by vanaukenk** [comment]
@Antonialock 
Can you tell me more about how you're filtering?
I am there as a contributor (maybe there's an extra 'e' in your search string, i.e. Kimberley instead of Kimberly) and I can find WB models by typing in 'WB', for example.

**Comment by Antonialock** [comment]
sorry for the confusion
I'm not using the search box, I'm unchecking the 'displayed columns'

<img width="1007" alt="Screenshot 2019-10-03 at 18 01 32" src="https://user-images.githubusercontent.com/12727506/66147996-da1cf080-e607-11e9-8fb0-946675ec4ccb.png">

**Comment by Antonialock** [comment]
yes, when I use the search box I see your name!

if I use the search box to search for "WB" is see 3 CC terms (nucleus, cytoplasm, striated muscle dense body)
if I use the search box to search for "Kimberly"  is see 5 CC terms (gut granule, RNA pol II core complex, nucleus, striated muscle dense body, integral component of plasma membrane)

**Comment by vanaukenk** [comment]
Okay, thanks for the info; that helps.

Try setting the 'Items per page' to 100 and now see what you get.  Perhaps you were initially only seeing the results of the default first 10.

![image](https://user-images.githubusercontent.com/1730534/66150169-9c59a100-e5e2-11e9-9cfa-a12296be085c.png)

**Comment by Antonialock** [comment]
aha....I think, once I had scrolled down to the bottom of the page it wasn't obvious that page 1/x was showing.

Thanks.
