### ISSUE TITLE
Fix incorrect ORCID for MGI curator

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#636]
An incorrect ORCID was added for an MGI curator a couple of years ago during a final push to capture all curators in the system (https://github.com/geneontology/go-site/issues/453). This ORCID is incorrect:

http://orcid.org/0000-0002-5283-5283

should be:

https://orcid.org/0000-0003-3394-9805

This error currently occurs in 81 different files:
```
grep -r "0000-0002-5283-5283" * | cut -d ":" -f 1 | sort | uniq -c | wc -l
81
```

Any thoughts from @balhoff or @goodb on how to best approach this? Is this just a job for sed on the next restart?

Originally reported by @krchristie

**Comment by kltm** [comment]
There should be no more bad data in the system, but it will take getting through the next release for others to pick it up.

**Comment by krchristie** [comment]
As of 12/20/19, there are several models that are now associated with both the incorrect and the correct ORCID for Dmitry, easily findable by searching for both at the same time: "0000-0003-3394-9805 0000-0002-5283-5283" or just the old ID "0000-0002-5283-5283".

**Comment by kltm** [comment]
I think I see what happened here--while @dms321 was updated, I don't think the data was fully purged, with his current session continuing to contain the old data. I could force a purge, but everybody's sessions would be canceled out.

@dms321, could you log out of and back into Noctua?

Looking at where we're at for the moment:

```
grep -c 0000-0003-3394-9805 * | grep -v ":0" | wc -l
104
grep -c 0000-0002-5283-5283 * | grep -v ":0" | wc -l
8
```

Files affected:

5db9c9a500000051.ttl
5db9c9a500000246.ttl
5db9c9a500000609.ttl
5db9c9a500000632.ttl
5db9c9a500000801.ttl
5db9c9a500000838.ttl
5db9c9a500000929.ttl
5db9c9a500000946.ttl

**Comment by kltm** [comment]
I found a way of logging out @dms321. The can be added as another item when I do #665 . There should be no further bad IDs added.

**Comment by vanaukenk** [comment]
I believe this is now fixed.  If not, please re-open the ticket @kltm
