### ISSUE TITLE
GO:0120219 is not available in Noctua

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#644]
Dmitry and I were just trying to curate a paper and wanted to use the cellular component GO:0120219 (subapical part of cell) and it was unavailable in the graph editor.

**Comment by goodb** [comment]
Looks like it was added to the ontology pretty recently and that there are no existing annotations to it.  https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0120219#term=history 
http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0120219%22&sfq=document_category:%22bioentity%22 

Guessing time and restarts will cure it, but I know that is unsatisfying...

**Comment by ukemi** [comment]
No worries then. We can close this if that's all it is.
