### ISSUE TITLE
Choosing an annotation group is missing

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#646]
Upon login, I used to see my group next to my name and be able to choose a group. In my case it was MGI or GOC. I no longer see that choice.

**Comment by vanaukenk** [comment]
@ukemi 
That functionality is in the graph editor and in the form - do you still see it there?
I just checked, and I do.

**Comment by ukemi** [comment]
OK, weird. It's there now. It wasn't before.

**Comment by kltm** [comment]
If you’re /sure/ you saw it, it’s a little...odd. Were  you perhaps on a WiFi or unusual network?

**Comment by ukemi** [comment]
I am on my home wifi.

**Comment by ukemi** [comment]
I may have figured it out. I don't see it when I am logged into the home page. I only see my group when I go to a model.

**Comment by kltm** [comment]
I believe that it just how it works at this point. I believe there is a ticket to work out better passing of group information , but it is current sub-app specific.
