### ISSUE TITLE
Check on annotations in database for a new Noctua model

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#652]
Li Ni created a model using the CC only version of the form, but the annotations aren't displaying in the table:

http://noctua.geneontology.org/workbench/noctua-form/?model_id=gomodel:5df932e000002299

I can't reproduce this error generally, but is there a way to determine what annotations exist in the database for this model so we can know whether this is a display issue or possibly something else?

Thx.

**Comment by goodb** [comment]
I'd look at the graph editor and then export to OWL.  That will show what is in there for sure.  http://noctua.geneontology.org/editor/graph/gomodel:5df932e000002299

**Comment by vanaukenk** [comment]
Will do.  Thanks @goodb

**Comment by vanaukenk** [comment]
It looks like there isn't an actual CC annotation.  I'll make a ticket to ensure that a curator can't save from the CC only form if the CC field isn't filled in.  Similar functionality exists in other configs of the form.
