### ISSUE TITLE
Task 3 - API - add route to list groups and fetch meta for a group

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua#657]
Task requirement from Noctua Landing Page Project

- [ ] Create a /groups route that provide the list of groups
- [ ] Create a /groups/{group acronym} that provide the meta for a given group

Both information are available on barista which is the authentication layer of the Noctua stack. Barista will be the one handling those two routes.

Note: similar ticket but for groups: https://github.com/geneontology/noctua/issues/658

**Comment by goodb** [comment]
@kltm @lpalbou not sure this should be coming out of minerva?  
I can add a route to provide all the contributors/groups that have added to any model but don't currently have any metadata about the contributors.  My understanding was that this came from elsewhere.

**Comment by kltm** [comment]
@goodb I believe this is for barista. If correct, the ticket should reflect that.

**Comment by lpalbou** [comment]
Apologies, I didn't specified it was indeed a work to be done on barista (hence the assignment to @kltm and not you ben and the fact I created the ticket here where barista.js lives, instead of the minerva repo).

**Comment by kltm** [comment]
Remember general URIs

**Comment by lpalbou** [comment]
@kltm any update or ETA ?

**Comment by kltm** [comment]
@tmushayahama Here are a couple of paths for groups, now available on barista dev:

* /groups
* /groups_info_by_id/<ENCODED_URI>

**Comment by kltm** [comment]
Apologies, I've mixed this thread up with #658 . I'll try and rationalize them.

**Comment by vanaukenk** [comment]
@tmushayahama @kltm - Do we need to leave this open?

**Comment by kltm** [comment]
I think this can be closed out for now.
