### ISSUE TITLE
Task 3 - API - add route to list contributors and fetch meta for a contributor

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua#658]
Task requirement from Noctua Landing Page Project

- [ ] Create a /contributors route that provide the list of contributors
- [ ] Create a /contributors/{orcid} that provide the meta for a given contributor

Both information are available on barista which is the authentication layer of the Noctua stack. Barista will be the one handling those two routes.

Note: similar ticket but for contributors: https://github.com/geneontology/noctua/issues/657

**Comment by lpalbou** [comment]
@kltm any update or ETA ?

**Comment by kltm** [comment]
Possibly later this week when/if things have settled down a bit.

**Comment by kltm** [comment]
@tmushayahama Here are a couple of paths for users, now available on barista dev:

* /users
* /user_info_by_id/<ENCODED_URI>

**Comment by tmushayahama** [comment]
@kltm it seems there are many users not on the list of /users . In the below if there is an orcid on table, it means a user was not found.

![image](https://user-images.githubusercontent.com/2273929/79371386-262ae500-7f09-11ea-96a5-72704618e8ac.png)

@vanaukenk

**Comment by tmushayahama** [comment]
In case it might help, Here is the list of 67 contributors in models but not in the new /users list API and a nice json. 


![image](https://user-images.githubusercontent.com/2273929/79378410-1ebc0980-7f12-11ea-820e-0facdae0f583.png)
![image](https://user-images.githubusercontent.com/2273929/79378344-00eea480-7f12-11ea-910f-d62e496a2055.png)


```json
[
  {
    "orcid": "http://orcid.org/0000-0002-1190-4481",
    "name": "Achsel Tilmann"
  },
  {
    "orcid": "http://orcid.org/0000-0002-2094-7491",
    "name": "Alexandros Kanellopoulos"
  },
  {
    "orcid": "http://orcid.org/0000-0002-7620-2704",
    "name": "Arthur de Jong"
  },
  {
    "orcid": "http://orcid.org/0000-0003-0662-9523",
    "name": "Carlo Sala"
  },
  {
    "orcid": "http://orcid.org/0000-0002-2666-0758",
    "name": "Casper Hoogenraad"
  },
  {
    "orcid": "http://orcid.org/0000-0003-2949-9725",
    "name": "Chiara Verpelli"
  },
  {
    "orcid": "http://orcid.org/0000-0001-5495-4588",
    "name": "Christina James-Zorn"
  },
  {
    "orcid": "http://orcid.org/0000-0002-4419-210X",
    "name": "Claudia Bagni"
  },
  {
    "orcid": "http://orcid.org/0000-0001-7351-8706",
    "name": "Cordelia Imig"
  },
  {
    "orcid": "http://orcid.org/0000-0002-9880-1214",
    "name": "Daniela Dieterich"
  },
  {
    "orcid": "http://orcid.org/0000-0003-3394-9805",
    "name": "Dmitry Sitnikov"
  },
  {
    "orcid": "http://orcid.org/0000-0001-9377-7414",
    "name": "Eckart Gundelfinger"
  },
  {
    "orcid": "http://orcid.org/0000-0001-5518-6584",
    "name": "Eunjoon Kim"
  },
  {
    "orcid": "GOC:ab",
    "name": "GOC:ab"
  },
  {
    "orcid": "GOC:als",
    "name": "GOC:als"
  },
  {
    "orcid": "GOC:dms",
    "name": "GOC:dms"
  },
  {
    "orcid": "GOC:dos",
    "name": "GOC:dos"
  },
  {
    "orcid": "GOC:hjd",
    "name": "GOC:hjd"
  },
  {
    "orcid": "GOC:hm",
    "name": "GOC:hm"
  },
  {
    "orcid": "GOC:id",
    "name": "GOC:id"
  },
  {
    "orcid": "GOC:kltm",
    "name": "GOC:kltm"
  },
  {
    "orcid": "GOC:kmv",
    "name": "GOC:kmv"
  },
  {
    "orcid": "GOC:krc",
    "name": "GOC:krc"
  },
  {
    "orcid": "GOC:lb",
    "name": "GOC:lb"
  },
  {
    "orcid": "GOC:pde",
    "name": "GOC:pde"
  },
  {
    "orcid": "GOC:pt",
    "name": "GOC:pt"
  },
  {
    "orcid": "GOC:sjc",
    "name": "GOC:sjc"
  },
  {
    "orcid": "GOC:sp",
    "name": "GOC:sp"
  },
  {
    "orcid": "http://orcid.org/0000-0002-5676-366X",
    "name": "Hana Goldschmidt"
  },
  {
    "orcid": "http://orcid.org/0000-0002-6153-3586",
    "name": "Harold MacGillavry"
  },
  {
    "orcid": "http://orcid.org/0000-0001-5259-4945",
    "name": "Jan van Weering"
  },
  {
    "orcid": "http://orcid.org/0000-0002-5615-1014",
    "name": "John Chua"
  },
  {
    "orcid": "http://orcid.org/0000-0002-3774-5896",
    "name": "Jolene Ramsey"
  },
  {
    "orcid": "http://orcid.org/0000-0002-0269-0311",
    "name": "Karl-Heinz Smalla"
  },
  {
    "orcid": "http://orcid.org/0000-0002-3898-5197",
    "name": "Mahdokht Kohansalnodehi"
  },
  {
    "orcid": "http://orcid.org/0000-0002-1585-539X",
    "name": "Maria Andres-Alonso"
  },
  {
    "orcid": "http://orcid.org/0000-0002-2514-0216",
    "name": "Matthijs Verhage"
  },
  {
    "orcid": "http://orcid.org/0000-0003-0575-6950",
    "name": "Michael Kreutz"
  },
  {
    "orcid": "http://orcid.org/0000-0002-0808-7003",
    "name": "Momchil Ninov"
  },
  {
    "orcid": "http://orcid.org/0000-0001-9425-2935",
    "name": "Niels Cornelisse"
  },
  {
    "orcid": "http://orcid.org/0000-0003-0938-8534",
    "name": "Nils Brose"
  },
  {
    "orcid": "http://orcid.org/0000-0002-0755-5899",
    "name": "Noa Lipstein"
  },
  {
    "orcid": "http://orcid.org/0000-0002-1558-1958",
    "name": "Pascal Kaeser"
  },
  {
    "orcid": "http://orcid.org/0000-0001-7806-5662",
    "name": "Peter McPherson"
  },
  {
    "orcid": "http://orcid.org/0000-0002-9681-3318",
    "name": "Rainer Pielot"
  },
  {
    "orcid": "http://orcid.org/0000-0003-1542-3498",
    "name": "Reinhard Jahn"
  },
  {
    "orcid": "http://orcid.org/0000-0001-9783-5183",
    "name": "Richard Huganir"
  },
  {
    "orcid": "http://orcid.org/0000-0002-8862-2562",
    "name": "Roberto Malinow"
  },
  {
    "orcid": "http://orcid.org/0000-0002-9900-4233",
    "name": "Ruud Toonen"
  },
  {
    "orcid": "SynGO:SynGO-bagni",
    "name": "SynGO:SynGO-bagni"
  },
  {
    "orcid": "SynGO:SynGO-brose",
    "name": "SynGO:SynGO-brose"
  },
  {
    "orcid": "SynGO:SynGO-hoogenraad",
    "name": "SynGO:SynGO-hoogenraad"
  },
  {
    "orcid": "SynGO:SynGO-mcpherson",
    "name": "SynGO:SynGO-mcpherson"
  },
  {
    "orcid": "SynGO:SynGO-mcpherson-mcpherson",
    "name": "SynGO:SynGO-mcpherson-mcpherson"
  },
  {
    "orcid": "SynGO:SynGO-pim",
    "name": "SynGO:SynGO-pim"
  },
  {
    "orcid": "SynGO:SynGO-sala",
    "name": "SynGO:SynGO-sala"
  },
  {
    "orcid": "SynGO:mcpherson",
    "name": "SynGO:mcpherson"
  },
  {
    "orcid": "SynGO:testuser",
    "name": "SynGO:testuser"
  },
  {
    "orcid": "SynGO:verhage",
    "name": "SynGO:verhage"
  },
  {
    "orcid": "http://orcid.org/0000-0002-3670-7863",
    "name": "Thomas Biederer"
  },
  {
    "orcid": "http://orcid.org/0000-0003-2533-9548",
    "name": "Timothy Ryan"
  },
  {
    "orcid": "http://orcid.org/0000-0003-0912-1514",
    "name": "Tony Cijsouw"
  },
  {
    "orcid": "http://orcid.org/0000-0003-3185-5709",
    "name": "Vincent O`Connor"
  },
  {
    "orcid": "http://orcid.org/0000-0002-9848-0262",
    "name": "Vittoria Mariano"
  },
  {
    "orcid": "http://orcid.org/0000-0001-5472-917X",
    "name": "http://orcid.org/0000-0001-5472-917X"
  },
  {
    "orcid": "http://syngo.vu.nl/brose",
    "name": "http://syngo.vu.nl/brose"
  },
  {
    "orcid": "http://orcid.org/0000-0002-5265-6306",
    "name": "Àlex Bayés"
  }
]
```
 

tagging @vanaukenk  @kltm @goodb @lpalbou 

 
--

**Comment by kltm** [comment]
@tmushayahama Could you just give me an example of a user not on the endpoint that you otherwise have?

**Comment by tmushayahama** [comment]
@kltm see the list above

**Comment by kltm** [comment]
@tmushayahama Okay, let's go through some examples then.

```
    "orcid": "GOC:kltm",
    "name": "GOC:kltm"
```
^ This me, either a development account or wildly out of date and should be considered a data bug. I suspect that this would go away during a cleaning. Also, GOC:kltm is definitely not an `orcid`, it is an xref being used as the id.

```
    "orcid": "SynGO:SynGO-hoogenraad",
    "name": "SynGO:SynGO-hoogenraad"
```
^ This is not in users.yaml and should flagged in the data pipeline and/or otherwise considered illegitimate; the syngo models have a lot of issues in this respect, however they are not locally edited, so not our problem for the moment here. That said, there is a user Casper Hoogenraad in users.yaml, which I'm guess is this one. I think this is more an issue that the SynGO models need to be regenerated with corrected data in them, with the old ones being flushed out.

```
    "orcid": "http://orcid.org/0000-0003-0938-8534",
    "name": "Nils Brose"
```
^ This person is in users.yaml, but does not have "noctua edit" permission, so is not returned as they cannot be a legitimate user of the interface. Yet they've made models through a backdoor. That's interesting and may lead us to wanting to define a third tier of noctua "user"--those that are remote editors. That would allow us to have a listing of what we expect to see in the curation system. I think it's also worth considering the utility of having uncurateable resources in the system muddying the waters. I'd like to add this case as a topic for tomorrow @vanaukenk , if you're available--there are a *lot* of SynGO people in there.

**Comment by dustine32** [comment]
The `SynGO:username` ORCIDs (e.g. `SynGO:SynGO-hoogenraad`) are coming from 40 models in `noctua-models/master` but have since been deleted in `noctua/dev` via commit https://github.com/geneontology/noctua-models/commit/7437a00fec9174e22d39475c612e3ad4f6fce162. This push of 2984 SynGO models needs to be merged from `dev` into `master`, ideally in a way that will also delete those 40 problem models, which should resolve the `SynGO:username` "ORCID" problem. This merge might be complicated to do but I'll talk with @kltm about it.

To clarify, these models were "deleted" because they were not in the newest [SynGO annotation JSON](https://github.com/geneontology/syngo2lego_data_conversion/blob/master/json/SynGO_export_2018-10-11.json).

**Comment by dustine32** [comment]
Although, I'm not sure why we're seeing those `SynGO:username` contributors associated with models being returned when SPARQL-ing the rdf-internal endpoint. Isn't rdf-internal supposed to somewhat mirror the models loaded into noctua-dev, which would include the current state of `noctua-models/dev`? I couldn't find `SynGO:username` examples in the SYNGO models of `noctua-models/dev`:
```
/noctua-models
$ git checkout dev
$ git pull origin dev
$ grep "SynGO:" models/SYNGO_* | wc -l
       0
$ git checkout master
$ git pull
$ grep "SynGO:" models/SYNGO_* | wc -l
     274
```

**Comment by kltm** [comment]
@dustine32 rdf-internal is a pipeline load with "development" and "production" models on the `master` branch of noctua-models. For our current use case, it's use is not particularly close to what is seen on noctua-dev.

**Comment by kltm** [comment]
@dustine32 We're essentially going to have to figure out a new route to bring in the SynGO annotation. That said, I think that this ticket is done and the data fixing issues should be carried out elsewhere: the route is created and works as it should.

**Comment by dustine32** [comment]
@kltm Ahh, right! It just snapped together for me. Thanks for explaining rdf-internal!

**Comment by tmushayahama** [comment]
Just to clarify more on this if it helps. @kltm @vanaukenk @dustine32 . Maybe **API users/** was not the correct terminology . It is more of anyone who has contributed to any model **API contributors/** before despite current edit permission. Any id (GOC, orcid, syngo) was acceptable not only orcid. So far, the use cases for the API are

### 1. As a bulk resolver to the ids (main one)
The payload, comes as list of ids to both Noctua Form and Landing Page. So to resolve this. there is already a quick internal lookup of cached contributors made when API /users was called at startup. So before it was calling minerva sparql. 

e.g.
**On Noctua Form** these are resolved from contributor annotations (ids)
![image](https://user-images.githubusercontent.com/2273929/79626854-77dd9600-80e8-11ea-891e-b71b06c47624.png)

**And on Landing Page**
![image](https://user-images.githubusercontent.com/2273929/79626978-5f21b000-80e9-11ea-9f13-36cc1db34ba1.png)

### 2. To search/filter any contributor models

![image](https://user-images.githubusercontent.com/2273929/79627025-d0616300-80e9-11ea-9206-116a70ebf741.png)


The snippet for resolver is (populateContributors)

it gets list of contributor annotations and do a lookup and if found, rertuns the metadata
![image](https://user-images.githubusercontent.com/2273929/79627367-61d1d480-80ec-11ea-9638-dbdf0c6545e2.png)

**Comment by kltm** [comment]
Apologies, I've mixed this thread up with #657 . I'll try and rationalize them.

**Comment by lpalbou** [comment]
We have two routes in this task:
* one to list contributors
* one to get the meta of a contributor

For the first route listing contributors, I think I agree with @kltm that this is not a priority as we probably don't want users browsing the models of test accounts. However, @tmushayahama did an important comment: we want to differentiate users that have contributed at any point in time, from users that are **still** currently contributing. Since this route is designed for the browsing of models, it has to list any user that have ever contributed. I don't know if we have started removing names from users.yaml, but if we have, we probably should have a secondary file to keep all the meta ever aggregated about users and this would need a separate ticket.

For the second route, getting the meta of a contributor, the data should always be accessible, whether it was a test account or not, since this is used in the actual display summary of a model.

**Comment by kltm** [comment]
After conversation with @vanaukenk , we're reverting to the original behavior and only returning the information for users with editorial permissions--all users turned out to be quite distracting and confusing and we believe that editorial users should eventually better align with what we want displayed.

**Comment by lpalbou** [comment]
Sounds good for now. Let us know when the change is in effect ? Thanks

**Comment by kltm** [comment]
I believe we can close this for the time being.
