### ISSUE TITLE
Barista / bbop-manager error management: maybe use HTTP status codes

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua#667]
@kltm I am still unfamiliar with dealing with loading errors. The system is hanging without proper catching the errors. Scenerios

- Server restarted
- Model gone, deleted, removed
- Token expires
- Query Timeout 
- Didn't save
- Server gone

HTTP Status codes will be helpful together with readable message. Readable codes alone don't show priority over another, i.e. (auth errors) barista token fail should log user out but query timeout will act differently

**Comment by lpalbou** [comment]
Following up on that, this is an example of a curious response from barista:

![Screen Shot 2021-03-26 at 4 19 27 PM](https://user-images.githubusercontent.com/24249870/112701940-348abc00-8e4f-11eb-82aa-cb7cfe579d4d.png)

The message type is success, while the message is bad response. 

# Proposal
* make sure message and message_type are consistent
* introduce status code for rapid/better error handling

**Comment by kltm** [comment]
I think we can close this as the roadmap is aimed towards a unified API. We can reopen if this becomes urgent for some reason.

**Comment by tmushayahama** [comment]
@vanaukenk I think this should not be closed and get fixed and not marked as complete bcz this new API might take few years. This keeps bringing problems in different forms, I can list some example recently barista was misbehaving and noway to know if the problem from both the curator or the client code. You can tell during the GO meeting things failed silently and model info lost, Then now lets say copy model doesn't work, it fails silently, but it says successful etc.
