### ISSUE TITLE
Annotation preview should show entity and term labels, not ids

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#671]
The annotation preview for a model used to show the label for the annotated entity, GO term, evidence code, and annotation extension value.

The preview now just shows IDs for each field which makes it harder to perform a quick sanity check of the expected GPAD output:

![image](https://user-images.githubusercontent.com/1730534/80816755-1d3f4200-8b9e-11ea-859e-f27769bf7249.png)

**Comment by vanaukenk** [comment]
And what was weird about this ss that the first time I looked at the Annotation Preview, the labels were there.  I thought I'd closed this tab, but I didn't and here's what I saw the first time, that then was replaced with the ids in the screenshot above:

![image](https://user-images.githubusercontent.com/1730534/80817368-47453400-8b9f-11ea-947e-dd3cf6b3a7b0.png)

**Comment by kltm** [comment]
@vanaukenk @goodb After some digging, I believe this is a functional dupe of #670.

Once the "GAF" comes in, the client turns on the reasoner and asks for the model so it can fill in the labels for the identifiers that minerva knows about. Minerva returns no individuals at this point, so they are not filled in.

While this is a different expression of the underlying issue, I think it's best to put it all in one place (#670) as we can just continue to enumerate different places this causes issues.

**Comment by kltm** [comment]
@vanaukenk I would assume that this has hopefully cleared along with the other issue?

**Comment by vanaukenk** [comment]
This looks to be working fine on dev and production.
