### ISSUE TITLE
Are we loading the full CL into Noctua?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#673]
@LiNiMGI

Li has reported not being able to autocomplete for 'granule precursor cell' (CL:0002362) in the Noctua form and I can reproduce the error on noctua and noctua-dev.

I know there's been some work in this area of CL (https://github.com/obophenotype/cell-ontology/pull/620/commits/7ba2de364da2157294dff84a8bd1852b2c3fdebd), but I don't think this term was actually deleted.

Did some CL terms perhaps get dropped from CL or the CL import?  

I also can't find 'neural crest derived neuroblast ' (CL:0002676).

**Comment by goodb** [comment]
@vanaukenk I don't believe we are loading the full CL into Noctua - only the subset that comes through via GO-Plus, which I believe are the terms that get used in any of the GO axioms.

**Comment by balhoff** [comment]
@goodb is right. I'm thinking we should probably load larger chunks (probably all) of ontologies like CL and Uberon.

**Comment by balhoff** [comment]
Was this term previously available?

**Comment by goodb** [comment]
@balhoff why aren't we loading all of CL and Uberon?  I recall that there was a reason, but I forget what it was.

**Comment by balhoff** [comment]
I don't think there is really a reason. This is how it was when I got involved. In general we do sometimes run into logical incompatibilities the more stuff we try to mush together.

**Comment by goodb** [comment]
I guess there might also be redundancies between the ontologies that produce a confusing type-ahead experience.

**Comment by vanaukenk** [comment]
Thanks @goodb @balhoff 

I don't know if the term was previously available.  I don't otherwise see it in the MGI Noctua gpad file on snapshot.

I think we'll want to figure out how to load all of CL and UBERON.....

**Comment by balhoff** [comment]
> I think we'll want to figure out how to load all of CL and UBERON.....

I'll give it a shot.

**Comment by vanaukenk** [comment]
Thank you @balhoff !
