### ISSUE TITLE
Change default landing page to noctua-landing-page workbench

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#674]
Currently, the default noctua location is a rather unhelpful basic search and admin page. We'd like to have the default experience for users be the noctua-landing-page workbench.

Currently, the way workbench "plugins" are rendered, it's hard to make an arbitrary workbench seamlessly take over the default route, although we'd like to work towards that in a little refactor at some point.

For now, it would seem to be expedient to move forward with taking the current interface and bumping it to a hidden /admin, and using a 302 (temp) forward on the default route to get to the workbench.

**Comment by kltm** [comment]
Obviously this should be a config, not hardcoded.
Tagging @dustine32

**Comment by kltm** [comment]
Noting that that we are missing forwarding the token parameter as well--that is a breaking issue.

**Comment by tmushayahama** [comment]
@kltm just a quick bug, maybe it is related to the above. When it redirects, it drops the barista_token param. I check and the token is on the href

![image](https://user-images.githubusercontent.com/2273929/83600504-96c2ab00-a523-11ea-9403-2a9a9d89b70a.png)

**Comment by kltm** [comment]
@vanaukenk I believe this is now working on noctua-dev.

**Comment by vanaukenk** [comment]
@kltm - yes, Tremayne and I tested this a bit earlier today and I just re-checked.  
It looks to be working okay.
