### ISSUE TITLE
Hide barista_token param from address bar

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua#676]
Extension of https://github.com/geneontology/noctua/issues/675 . The address bar to hide the barista_token param in the local_storage

tagging @kltm @lpalbou @vanaukenk

**Comment by vanaukenk** [comment]
Hiding the barista token in the URL appears to be working fine for the landing page and the form, but not the graph editor.
I can still see the barista token in the URL when logged in and working in the graph editor.

**Comment by kltm** [comment]
@vanaukenk This is current a form (and landing?) feature and would have to be worked on separately for other locations.

**Comment by vanaukenk** [comment]
Thanks @kltm 
That's what I thought, but wanted to note that here in the ticket.
This is included in the list of unified UX issues for the Noctua planning meeting tomorrow.

**Comment by vanaukenk** [comment]
This is done for the form, but not the graph editor.  
@kltm - should we leave this one open?

**Comment by vanaukenk** [comment]
Just noting here that we had another report of clicking on a bookmarked Noctua URL with no visible token resulting in opening a Noctua instance where a different curator from the one who had clicked on the bookmark was logged in.

I tried the same URL from an email and was taken to the Noctua landing page and wasn't logged in.

I'm not sure how to recreate this issue or test further but wanted to note that this happened more recently.

**Comment by kltm** [comment]
@vanaukenk Honestly, I think this may be a red herring and something else went on here.

**Comment by kltm** [comment]
Closing in preference to https://github.com/geneontology/noctua/issues/379
