### ISSUE TITLE
Fix "Show has_input" toggle on PathwayView

### ISSUE THREAD

**Issue by dustine32** [geneontology/noctua#678]
The "Show has_input" toggle in the Pathway Viewer doesn't seem to have any affect:
![image](https://user-images.githubusercontent.com/2678599/85172808-aa118e00-b226-11ea-9fbb-f3e6ebd05c08.png)
The "has_input" edges are still rendered.

@kltm I made a real simple fix for this a looong time ago and would like to see if you guys thought it should get into the main code. No rush but the PR will be coming in a sec. Let me know if you have any questions.

**Comment by kltm** [comment]
Should be deployed?

**Comment by dustine32** [comment]
@kltm Yeah if it's no big deal to deploy. Thanks!

**Comment by vanaukenk** [comment]
Closing as this issue seems to have been fixed.
