### ISSUE TITLE
Add 'still under development' text to the red box pop-up

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#681]
For catching some of the more straightforward modeling errors, the explanations in the red box pop-up can be helpful, but 
we've also had some feedback that the current output can be too cryptic for curators to understand, and one case even when it took some digging (@ukemi ) to eventually sort out what the error message was likely indicating.

Since we still need to work on more user friendly output, let's add some text at the top of the pop-up window to let curators know that this feature is still under development.

How about:

"This feature is currently under development with more user friendly error reports coming.  If you have questions about the error messages you're seeing, please create a ticket on https://github.com/geneontology/noctua."

@kltm @goodb @lpalbou @tmushayahama

**Comment by vanaukenk** [comment]
To do: generate a doc with text of all current error messages so we can prioritize which types of errors to describe better for curators.

**Comment by kltm** [comment]
@vanaukenk Sounds good.
As an idea on a variation, instead of a software bug tracker, what about a wiki or doc page that had a little more information on 1) what they are seeing 2) why it might be unintuitive and 3) a list of common ones they might see?

**Comment by vanaukenk** [comment]
Thanks @kltm

A link to documentation on the red box validation reports would indeed be helpful.  The wiki is probably the best location for this.

If it's possible to get the list of common error messages, though, it might be better to spend time upfront writing text for more user friendly messages than spending time writing explanations for the current format.

Either way, though, more wiki documentation will be needed.

**Comment by kltm** [comment]
@vanaukenk For your consideration: http://noctua-dev.berkeleybop.org/editor/graph/gomodel:596ef51500000088

**Comment by vanaukenk** [comment]
Perfect; thank you @kltm !

**Comment by kltm** [comment]
@vanaukenk Just to confirm: I'll go ahead and merge `dev` into `master` to get this out ASAP.

**Comment by vanaukenk** [comment]
@kltm 
Yes, thank you!

**Comment by kltm** [comment]
@vanaukenk Finalized: http://noctua.geneontology.org/editor/graph/gomodel:596ef51500000088

**Comment by vanaukenk** [comment]
Add color fill to the error message to try to make the message more apparent to the user.

**Comment by kltm** [comment]
@vanaukenk Hopefully better? http://noctua-dev.berkeleybop.org/editor/graph/gomodel:596ef51500000088

**Comment by vanaukenk** [comment]
This work is done.
