### ISSUE TITLE
Fix noctua graph client to handle model-level violations

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#683]
The violation checks in the current client code do not handle well (crash) model-level violations.

The code should: 1) crash less and 2) display the information.

Derived from https://github.com/geneontology/minerva/issues/330
A good description of the issue there.

**Comment by goodb** [comment]
Note that for testing, its easy to reproduce.  Just delete the title from the model and then run the reasoner.

**Comment by kltm** [comment]
@goodb This workaround should now be on noctua-dev. As it's a model-level violation, it will (of course) not show up with a red box in the main part of the graph editor, but it should be "visible" in the *Info* tab at the bottom (as well as the fact that the model is INVALID).
Obviously there is more work to be done here, but it should no longer crash.

**Comment by goodb** [comment]
Looks like a good start to me.  Much better than crashing :).

**Comment by vanaukenk** [comment]
@kltm - I think we can close this?

**Comment by kltm** [comment]
Maybe? If not, we can reopen.
