### ISSUE TITLE
Add new children of 'has participant' to the top of the relations pop-up window

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#685]
A handful of new child relations of 'has participant' are now available in RO and could be used in GO-CAM models.

Can we add these relations to the relations pop-up window in the graph editor as children of 'has participant':

'has participant'
- 'has small molecule regulator' (RO:0012000)
-- 'has small molecule activator' (RO:0012001)
-- 'has small molecular inhibitor' (RO:0012002)
- 'acts on population of' (RO:0012003)

Thx.

**Comment by kltm** [comment]
@vanaukenk This should now be on noctua-dev.

**Comment by vanaukenk** [comment]
@kltm 

These new relations are now available in the graph editor pop-up window and are working fine.

Note that we'll need to add these relations to the ShEx as valid for specific MF and BP terms, respectively.
