### ISSUE TITLE
Updating Production Workflow: An intermediary duplicate testing workbenches on production before replacing

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua#686]
Directly replacing workbenches on production caused so many issues last time because dev did not fully emulate production environment. These includes testing production variables, browsers etc. Luckily the issues were caught before potential production server disruptions and reverted the code back. But the pressure was there.

Maybe a seamless way of updating workflow without pressure or disruptions might work. We can have some intermediary workbench check/test on production. This will be a very minimum change to no changes to implement. However, this is not a testing environment, but a quick check. 

### Potential workflow - Duplicate workbenches
This includes the landing page as well

1. When there is an update available, we will not directly replace any workbench, but make a duplicate workbench with the new update as shown below.  
2. To test, just go to "xxxx - Landing Page Testing only"
3. @vanaukenk @kltm and and selected testers will just briefly make sure it is working
4. If all good, then replace the actual workbench with the intermediary.
5. So now, these 2 workbench are the same then if a curator goes to either it will not be a disaster because they are now the same.

![image](https://user-images.githubusercontent.com/2273929/88854706-85ee8880-d1a6-11ea-8605-fc6bc8649e5b.png)

tag @vanaukenk @ukemi @kltm @lpalbou @goodb

**Comment by vanaukenk** [comment]
@tmushayahama - should we keep this ticket open?

**Comment by tmushayahama** [comment]
@vanaukenk I think this is resolved
