### ISSUE TITLE
is this instruction  always valid?

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#690]
<img width="335" alt="Screen Shot 2020-09-14 at 14 22 32" src="https://user-images.githubusercontent.com/7359272/93109756-5b03b980-f6ac-11ea-9af6-3d16443ab62f.png">

I was confused here about the reaction product section:

I can't parse the comment:
Does the product of reaction 1 REGULATE or  become the substrate for activity 2

If reaction 1 is a protein kinase the  products is the phosphorylated substrate  (which is the  'enabled by" entity of activity 2)

For example  activity 1, protein kinase (enabled by wee1)  phosphorylates cdc2 (the enabled_by entity for activity 2)

Here, reaction 1  regulates activity 2- 
 the  product of reaction 1 (phosphorylated cdc2), doesn't regulate itself?
phosphorylated cdc2 regulates onward processes, through other substrates, not it's own activity (well it may regulate it's own activity too  as part of a positive feedback loop but that is not what we are modelling here).

So neither option is true?

@thomaspd is this wording correct?

**Comment by thomaspd** [comment]
Sorry for the confusion. @vanaukenk and I need to revise the questions in the 'relations wizard'. The question is trying to ask you to distinguish between:
1. does the upstream activity directly regulate the downstream one (use directly +/- regulates relation), versus
2. does the upstream activity provide the substrate for the downstream one (use directly provides input for)

So in this case, if wee1 phosphorylates cdc2 to inhibit the activity of cdc2, it should be case 1 above. In a hypothetical case where wee1 phosphorylates cdc2, and then a second kinase further phosphorylates cdc2, you'd use directly provides input for.

**Comment by vanaukenk** [comment]
Yes, let's review @thomaspd - especially in light of the discussions we've been having on the modeling call.

**Comment by ValWood** [comment]
Well, people always say that wee1 inhibits cdc2 because that's the way they would draw it in an causal model. But I think it inhibits by sequestration. The activity isn't altered it just can't reach the nuclear substrates. 

At PomBase our model is   entity centric   (uses has_input) but as we transition to (or map to) activity-centric I would like to be more precise to be more precise  to make the models  more useful in the future to all potential consumers.

Ideally, we will be able to curate in such a way that we can generate an entity-centric or gene-centric view on demand but I'm trying to figure out what's what. I haven't been paying attention to this area but I should have more time now....
