### ISSUE TITLE
Login does not persist

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#697]
After turning on my machine in the morning and going to the Noctua landing page, the page shows that I am logged in. If I click on the graph or form editor for a model, I am sometimes not logged in when I am in the model. If I refresh the landing page several times, I am then suddenly logged out. If I log back in and click on the graph or form editor in the model, I am logged in.

**Comment by ukemi** [comment]
To top it off, I just tried to modify a rat model that I made last week and seemed to be loggied in, but got htis message:

Error (error): Save model failed: validation error(s) before save; your operation was likely not performed.
The model has no contributors. All models must have an association with their contributors.

**Comment by vanaukenk** [comment]
Closing this in favor of #675
