### ISSUE TITLE
In the Function Companion, external links within the search widget go to localhost

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#698]
In the Function Companion, external links within the search widget go to localhost:9999.

Appropriate behavior should be to link to the public amigo instance.

This would be fixed with ensuring that the linker is pointing to the appropriate resource.

Tagging @ukemi @vanaukenk

**Comment by kltm** [comment]
@vanaukenk @ukemi This should now be fixed on `dev`.

**Comment by vanaukenk** [comment]
@kltm 
I tested links to gene products and GO terms and they seem to be working fine, i.e. they go to AmiGO.
@ukemi could also double-check, but it should be fine for him, too.
Thx.

**Comment by vanaukenk** [comment]
Noting that the GO_REF link outs don't work on the Function Companion.  
I don't know how many people still use the Function Companion workbench, but if this is an easy fix, we should do it.

**Comment by vanaukenk** [comment]
Closing this ticket for now.  If the non-functional GO_REF link becomes a problem for curators, we can re-open and fix it.
