### ISSUE TITLE
Please preserve Noctua layout

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#699]
Please can you make Noctua preserve the layouts  as saved (i.e similar to a 'grouping' function that could be used to  freeze a specific module). It is impossible to make large models because  the pathway continually  rearranges itself.

The layout  also seems quite random.

For instance, is there a way force linear pathways are always laid out linearly?

I keep lining it up, but it insists that one pathway component looks nicer randomly positioned over to the right? 

<img width="1358" alt="Screenshot 2020-11-17 at 21 05 10" src="https://user-images.githubusercontent.com/7359272/99520151-aa0aeb00-298a-11eb-9229-325b52282db0.png">

**Comment by lpalbou** [comment]
This one is really important I think. @kltm I am actually a bit surprised as I thought the x and y positions were always saved upon a mouserelease event (when you drag & drop and release the click).. but even when saving the model, the layout was never kept for me either. I don't think that would be a lot of work to look at, but it probably has a large impact for all our users (I had to redo several times the layout for the figure of the GO article and if people come and see the model, the layout I did was not conserved).

**Comment by ValWood** [comment]
It's the most annoying thing about Noctua I think. I  won't  be using it  until this is done, because I don't have the time to keep rearranging the model, especially as it gets bigger.....so right now  I am just doing the data and evidence gathering

**Comment by thomaspd** [comment]
For layout, try the layout tool. In the Noctua graph editor menu, go to:
Workbenches > Cytoscape layout tool

In the layout tool, there's a drop-down menu labeled "Layout". Choose "Noctua default" to see the layout you currently have in the graph viewer.

Then, drag activity units around to position them. When you're satisfied, press the button "Set layout", and it will return you to the graph viewer with your new layout set.

**Comment by kltm** [comment]
@lpalbou x/y is saved when the model is "saved", not on mouse events.
If the layout is not being saved, there may be something else going wrong, that can be examined.
As a temporary workaround as these issues are dealt with, the layout tool the current recommendation, as outlined by @thomaspd above.

**Comment by ValWood** [comment]
I got this to work. It would be better if you could 'preserve' layout with a single click from the graph editor.

**Comment by vanaukenk** [comment]
Closing this for now, but we can re-open if we decide to do more work on visualization in the graph editor.
