### ISSUE TITLE
MF autocomplete on graph editor populates BP terms

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua#700]
I was testing validation and added an activity using "Add Annoton" feature on the graph editor. First I thought validator was reporting correct models as violations. @lpalbou pointed out that it was a BP

![image](https://user-images.githubusercontent.com/2273929/99613686-d5162e80-29cc-11eb-8a98-4adb9388e4aa.png)

It seems like the MF is autocompleting to BP terms 

![image](https://user-images.githubusercontent.com/2273929/99613695-db0c0f80-29cc-11eb-99be-7a489bb87d2e.png)

tagging @kltm @lpalbou

**Comment by vanaukenk** [comment]
Closing this for now.  We can re-open if we want to work on the graph editor autocomplete.
