### ISSUE TITLE
Upside down bug

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#702]
This happens periodically. I don't know what actions I did to cause this.

<img width="1239" alt="upside down" src="https://user-images.githubusercontent.com/7359272/99780604-a011f500-2b0e-11eb-8ad4-5343a6618236.png">

**Comment by ValWood** [comment]
(The annotons are upside down and the connections are lost)

**Comment by kltm** [comment]
@ValWood That is very...unexpected. I have so far been unable to reproduce. In fact, I'm having trouble with how it could even happen in the first place...

@suzialeksander Didn't something like this happen to you waaay long ago?

**Comment by ValWood** [comment]
It happened to me twice. Unfortunately I have no idea what I did to make it happen either time!

**Comment by suzialeksander** [comment]
Yes it's happened to me once, I have not seen it since nor do I have any helpful info about reproducing.  I do know my model had relations drawn in already and those too were flipped.

**Comment by kltm** [comment]
Okay, we can work with this...

@ValWood I'm going to close out here and reopen in the older ticket.
If you could add any details about your browser or environment (either here or there), we may be able to start building a detailed enough picture to figure out what's going on.

**Comment by ValWood** [comment]
All I can tell you is that I was using Chrome Version 65.0.3325.181 (Official Build) (64-bit)

I don't know what caused it, but I have a feeling that both time it happened I maybe hadn't waited for something to complete. I'm impatient.
and It might have happened when I switched between the graph view and cytoscape view and back. But  I'm just guessing, my memeorey is hazy....
