### ISSUE TITLE
Graph editor allows malformed references, but then they are unsearchable

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#707]
On a couple of occasions recently curators have cut and pasted evidence references that have trailing spaces or sometimes spaces between the PMID: and the number. Noctua allows these references, but then they are not searchable on the landing page. As a result, they cannot be found easily. In an ideal world, curators would be required to use valid references, but if that cannot be done, the malformed ones should at least be searchable.
Ping @hdrabkin. This is the issue we had the other day.

**Comment by pgaudet** [comment]
Could the software remove any spaces for this field ? Rather than fixing the search ? It's really hard to copy from PubMed without and spaces.

**Comment by ukemi** [comment]
Yesterday @hdrabkin and I noticed that the graph editor will also allow preceding spaces in references. Whe these are added the 'trick' of looking to see if the id is converted to a title doesn't work. The title still shows up in the interface. However, the GPAD output contains the space and resulting loads that check for valid references fail.
