### ISSUE TITLE
Noctua URL + access to various file formats

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua#712]
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/owl

Will get you the OWL. It would be nice that

http://noctua.geneontology.org/download/gomodel:R-HSA-71064/ttl

Gets you the TTL and same principles for json, causaltab, sif, etc

**Comment by balhoff** [comment]
FYI, the OWL is the TTL, and the TTL is the OWL. 😉 I don't think we have a means within Minerva to generate the other formats, do we?

**Comment by lpalbou** [comment]
Oops, I meant owl (ttl) vs owl (xml).

For the other formats, it's related to the possible refactoring of some codes in minerva for the "business logic" layer and the PPT that is circulating regarding go cam graphs.

**Comment by lpalbou** [comment]
So to clarify further, the proposal would be to have:

http://noctua.geneontology.org/download/gomodel:R-HSA-71064/gpad (already here)
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/owl.ttl (same as current /owl)
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/owl.xml
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/json (could be the Cytoscape format)
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/tsv (discussed in go cam graph PPT)
http://noctua.geneontology.org/download/gomodel:R-HSA-71064/sif

Note: why http://noctua.geneontology.org/download/gomodel:R-HSA-71064/owl is not the same as https://raw.githubusercontent.com/geneontology/noctua-models/master/models/R-HSA-71064.ttl ? It's probably the same annotations but the files are different. The /owl files seems better formatted, while not flush them on GH noctua-models ?

**Comment by balhoff** [comment]
> Note: why http://noctua.geneontology.org/download/gomodel:R-HSA-71064/owl is not the same as https://raw.githubusercontent.com/geneontology/noctua-models/master/models/R-HSA-71064.ttl ?

The first is an export from the in-memory (and possibly not saved) OWL ontology object via OWL API. The second is a direct export from the triplestore, which is much faster in bulk.

**Comment by cmungall** [comment]
There are some good ideas here, but let us park this issue for now until we prioritize this

**Comment by vanaukenk** [comment]
Closing for now; we can reopen if we want to do this as part of a more general export file project.
