### ISSUE TITLE
In some circumstances, a model created or modified does not get saved

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#715]
@robnash ( http://orcid.org/0000-0002-3726-7441) made a model on YGL015C (aka BIL2 but that info isn't in Noctua yet), we last looked at it the morning of March 4 and he marked as production about 9:30am PT.  We realised it's missing when the annotation didn't come through our pipeline.  http://noctua.geneontology.org/workbench/annpreview/?model_id=gomodel:600ced8500002513

Concerningly, a search in Noctua for BIL2 now shows nothing and the URL doesn't work.  This is similar to when Stacia's model made the morning of the last maintenance also didn't survive maintenance.  

Note: Rob is re-making the model probably today to get the info on SGD, but the original model is the one we can't locate.

**Comment by suzialeksander** [comment]
@ukemi yes, both this model (by @robnash ) and the one that disappeared last maintenance were both marked production.

**Comment by ukemi** [comment]
@mdolanme did an analysis of the latest snapshot versus the February release and did not find any models missing. The annotations must have been lost by some other mechanism (obsoletions, merges, new filtering rules...).

**Comment by suzialeksander** [comment]
If it helps, the annotations in question for us were not marked production until 4 March so as far as I know didn't make it in to any snapshots before disappearing.  Maybe they were cached somewhere???

And by 'not existing' I mean the whole model is gone now: 
<img width="1326" alt="Screen Shot 2021-03-15 at 3 46 32 PM" src="https://user-images.githubusercontent.com/13735608/111225928-08954e00-85a6-11eb-809f-c5b1f4088fdf.png">

**Comment by kltm** [comment]
Noting that this is separate from https://github.com/geneontology/pipeline/issues/172

**Comment by kltm** [comment]
@ukemi says this model has much more recent edits that have not been pushed to GitHub: https://github.com/geneontology/noctua-models/blob/master/models/60418ffa00000375.ttl
@balhoff Unfortunately, it looks like that file got "saved" very soon after you reported that there was another model. @ukemi For the gomodel:60418ffa00000375 case, what interface had you been using with it? It's weird that these end up getting saved automatically somehow right after discovering them. I'm beginning to think this might be an issue with the client code (or minerva) rather than the flush to GitHub itself (in which case we'll want to open a new issue to start putting a picture together).

**Comment by kltm** [comment]
Another case from @dustine32

From geneontology/pipelime#229. Looks like another instance [...]

SGD model 60418ffa00002093.ttl (titled "Pex35 regulates peroxisome abundance") was created and marked "production" on noctua prod 2021-03-31 but not pushed to noctua-models via automated commit until 2021-04-05 geneontology/noctua-models@50090ad. Note there were four other auto-commits between this 4/5 on and 3/31.

Tagging @suzialeksander @kltm

**Comment by ukemi** [comment]
I almost exclusively use the graphical interface.

**Comment by kltm** [comment]
@balhoff This may be related to https://github.com/geneontology/minerva/issues/378

**Comment by vanaukenk** [comment]
Closing this ticket for now, as we *think* this has been addressed.

We'll continue to monitor, this, though, in future updates of Noctua in case the issue arises again.
