### ISSUE TITLE
Synonym is appearing in GE, Annotation Preview

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#718]
Not sure if it's maybe just a character limit, but https://www.ebi.ac.uk/QuickGO/term/GO:0007094 mitotic spindle assembly checkpoint signaling is appearing as just "mitotic spindle assembly checkpoint" (also an exact synonym for the term) in the GE/Form/Annotation Preview: 

noctua.geneontology.org/editor/graph/gomodel:5e72450500004648

I tried the Soft Refresh and Reset, no change. Not really a problem for this specific term but could be an issue for other terms??

**Comment by kltm** [comment]
@suzialeksander Looking at the Changelog in QG, I think that the name change is recent enough that minerva doesn't have the updated name and is giving you the "older" one.

**Comment by suzialeksander** [comment]
sounds good enough for me, thanks for checking.  Will reopen if I see anything else in a few weeks or so.

**Comment by pgaudet** [comment]
Could we display somewhere in Noctua the date the ontology was last loaded?
