### ISSUE TITLE
MGI identifier not resolving

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#724]
MGI:MGI:3651956	Ttc39aos1	Ttc39a opposite strand RNA 1	Gm12750	SO:0001263	NCBITaxon:10090					

In Noctua, this is not resolving to display the gene symbol of _Ttc39a_. See gomodel:5ce58dde00002247

**Comment by vanaukenk** [comment]
@ukemi 
I just tested this and it looks to be working okay in the form and graph editor.
If there are any other issues with unresolved MGI ids, please open a new ticket.
Thx.
