### ISSUE TITLE
Anatomical Structures are not available

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#725]
I am trying to make a model with a process that occurs in an anatomical structure and I am unable to autocomplete on any anatomical structures in Noctua (EMAPA or UBERON).

**Comment by vanaukenk** [comment]
@ukemi 
Are there specific terms missing?  I can see some EMAPA and UBERON terms, e.g. liver,  in the graph editor.

**Comment by ukemi** [comment]
I tried metanephros and GO terms came up, but no anatomy terms.

**Comment by ukemi** [comment]
@vanaukenk suggested I try the identifier rather than the term name. That worked. So although not ideal, I am closing this. At least they are there.
