### ISSUE TITLE
Update obsolete evidence codes in SynGO models

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#726]
In doing some QC investigating for @slaulederkind wrt rat CC annotations coming from SynGO models, I found that the SynGO models currently include an ECO code, ECO:0006065, in vitro cell based assay evidence used in manual assertion, that is now obsolete in ECO.

ECO recommends replacing ECO:0006065 with a child of ECO:0001565, cell-based assay evidence.

Perhaps in the case of these SynGO models, replacing with ECO:0007695, cell-based assay evidence used in manual assertion, would be okay.

@thomaspd  - Does this sound okay to you?  We would want to contact SynGO to confirm.

@kltm - I can make a corresponding ticket in minerva, if needed, as this would be a wholesale replacement of an evidence code in existing SynGO production models.  Note that I double-checked Noctua to make sure we don't still have ECO:0006065 as an option for evidence and we don't.

**Comment by kltm** [comment]
@vanaukenk Updating syngo would be more the realm of @dustine32 at this point--he is the current point person for the syngo ingest into TTL, where they would just be updated in noctua-models.

Stepping back a bit, this is part of the more general "how do we update obsolete/wrong stuff" problem that I think we probably want to attack more generally and get some decent tooling/SOPs in place.

**Comment by vanaukenk** [comment]
Thank you @kltm   I've added @dustine32 to the ticket.

> Stepping back a bit, this is part of the more general "how do we update obsolete/wrong stuff" problem that I think we probably want to attack more generally and get some decent tooling/SOPs in place.

I completely agree.  These things seem to be increasingly common and we should draw up some SOPs with appropriate tooling.

**Comment by kltm** [comment]
@vanaukenk I think this might be a dupe of https://github.com/geneontology/pipeline/issues/283 ?

**Comment by vanaukenk** [comment]
Closing this one in lieu of the pipeline tickets.
