### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#728]
I. saw this periodically  while trying to add annotons.

<img width="1104" alt="Screenshot 2021-07-11 at 12 01 27" src="https://user-images.githubusercontent.com/7359272/125194174-2454ec00-e248-11eb-93d8-9e071728e23c.png">

I don't know what I did to cause it, and I could not tell from the error message.

**Comment by kltm** [comment]
@ValWood Could you give a break down of operations performed to get to this error?

**Comment by ValWood** [comment]
I can't remember only taht I was adding an "annoton" and all 4 fields were completed acceptably.

I am  meeting with @ukemi  tomorrow to resolve another problem. If it happens then hopefully I'll be able to give more details.

**Comment by vanaukenk** [comment]
@ValWood 
I'm going to close this ticket for now.  I just tried adding some annotations using gtr2 and it worked okay.
If you have this problem again, please open another ticket.
