### ISSUE TITLE
yeast complexes missing in Form & GE-Add Individual?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#729]
We can't get ComplexPortal:CPX-1683 to pop up in Autocomplete, and both GE-Add Individual and Form require you to pick an autocomplete suggestion.

CPX-168, a human complex, pops up, and CPX-1683 has an autosuggest for taxon:1683.  Scer complexes used to appear, I believe we've annotated to some, but now they aren't there(?)

**Comment by vanaukenk** [comment]
Hi @suzialeksander 
Can you do a quick check of the SGD gpi file to make sure the ComplexPortal entries are there?
Thanks.

**Comment by suzialeksander** [comment]
sgd.gpi.gz ? No, there are no complexes at all in there, is there somewhere else they might have been?

**Comment by suzialeksander** [comment]
Hmm, I found we've used complexes in http://noctua.berkeleybop.org/editor/graph/gomodel:5df932e000001843 but it looks like maybe we just forced that in as has_input, maybe we haven't had them appear? What would we need to do to get CP IDs in?

**Comment by kltm** [comment]
@suzialeksander 
It appears you're using your GAF as your input for NEO.
If CP is needed, they immediate way forward would be to generate a GPI for NEO to consume that had what you wanted. Otherwise, we would need to circle around on refactoring NEO.

**Comment by vanaukenk** [comment]
@suzialeksander 
In the datasets metadata file for SGD, you can see the SGD gpi entry is commented out, thus, as @kltm commented, the source for annotatable S. cerevisiae entries in neo and Noctua is the SGD GAF.

https://github.com/geneontology/go-site/blob/master/metadata/datasets/sgd.yaml

**Comment by suzialeksander** [comment]
update, SGD has decided we'd like to move forward on this, and we're talking with ComplexPortal.  Is this as "simple" as producing the new GPI with complexes added, throwing it where our yaml is looking for it, and un-commenting-out that stanza in sgd.yaml?

**Comment by kltm** [comment]
@suzialeksander Yes, it's close to being that simple. Assuming a well-formed and correct GPI, one additional wrinkle will be an update to https://github.com/geneontology/neo to reflect your changes, but that should be "invisible" to you (although we'll need to know when it happens).

**Comment by vanaukenk** [comment]
@suzialeksander - just checking to see how this is going on the SGD end.  When your new gpi file with CPX identifiers is ready, let us know and we'll update neo.

Thx.

**Comment by suzialeksander** [comment]
We're still awaiting word from Complex Portal, I will check on the progress.

**Comment by vanaukenk** [comment]
2021-08-10 from conversation with @kltm and @suzialeksander 
SGD is working on getting their gpi file together.  As soon as it's ready, we will do some testing to make sure all is working okay.

**Comment by suzialeksander** [comment]
OK, we think we have a GPI 1.2 ready.  I haven't added it to the SGD yaml yet, should I go ahead and make that PR?

https://downloads.yeastgenome.org/latest/gpi.sgd.gz

**Comment by kltm** [comment]
@suzialeksander A PR mostly never hurts and gives another place to get eyeballs on something, so I'd generally encourage it.
In addition, we'll have to confirm that the NEO build can/will pick it up.

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/pull/1726

**Comment by kltm** [comment]
Prepping for NEO run later in the week by trying metadata push now on NEO pipeline. Can test from that.

**Comment by kltm** [comment]
Okay, doing a little checking, `CPX 1683` is now showing up as (http://noctua-amigo.berkeleybop.org/amigo/term/SGD:S000218071). This is hopefully indicating that the GPI has been ingested as desired?

**Comment by suzialeksander** [comment]
yes, i think it's working, thanks!
