### ISSUE TITLE
Missing eco codes or inconsistence eco codes across resources.

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua#733]
Some of the eco codes are missing but resolving on the autocomplete

Here is an example with bunch of arrows. As you can see, the **ECO:0006303** resolves to label **microscale thermophoresis evidence used in manual assertion** but the id doesn't exist anymore (from the second diagram) and also from minerva it doesn't have a label (table on the right)
![image](https://user-images.githubusercontent.com/2273929/129828134-07d2fc72-d44d-4314-896a-1205bf5f4e1f.png)

if check the eco site 
![image](https://user-images.githubusercontent.com/2273929/129827887-79890fc8-df47-4f7d-932c-6b0b2b2f5b3b.png)

tagging @vanaukenk @ukemi @cmungall @kltm

**Comment by cmungall** [comment]
Great detective work!

This is super puzzling. Afaicr this term has never been in eco. There is a
related term requested by disprot recently
https://github.com/evidenceontology/evidenceontology/issues/277

We should follow up with suvvi. Maybe there was some email agreement to add
this term in future and the Id was privately reserved. I discourage this.

Ethier way how did this get into our solr index? Which owl file is this
indexing exactly? Could it have been injected via a model file? This part
should be easy to track down

**Comment by kltm** [comment]
Well, it is definitely there:
http://noctua-amigo.berkeleybop.org/amigo/term/ECO:0006303
This AmiGO loads two files:

            "http://skyhook.berkeleybop.org/issue-35-neo-test/ontology/extensions/go-lego.owl"
            "http://skyhook.berkeleybop.org/issue-35-neo-test/ontology/neo.owl"

We'd expect it to be in (the rather large) go-lego.owl and it is indeed there.
This term is also found in eco: http://purl.obolibrary.org/obo/eco.owl .

**Comment by vanaukenk** [comment]
@tmushayahama and I just took a closer look at this.

As @kltm points out, ECO_0006303 is in the eco.owl file as one of the DisProt project evidence codes.

Searching on either ECO's website (or OLS) doesn't retrieve this code, but if it's in eco.owl and in go-lego.owl then I guess the outstanding question is why the term label doesn't resolve in the Noctua form table.

**Comment by cmungall** [comment]
OK, sorry for the blind alley. Yes it is in eco.owl. It was added 7 days
ago.

So Minerva is just lagging behind the golr index.

I know it's puzzling that the eco site doesn't have it but their site is
just a wrapper to OLS and OLS hasn't done an update yet. I would make a
ticket on the eco tracker to make the version transparent

**Comment by nsuvarnaiari** [comment]
Hi All,

OLS had some issues last month due to which ECO's previous release terms were not displaying in the tree, although the terms were visible in search results.

Chris, just to clarify, we haven't reserved ECO terms till date. Don't think we want to do that.

Is this issue resolved? 
BTW, I will be pushing a new release in few mins. Please let me know if things still fail at your end.

@mgiglio99

Thanks,
Suvvi

**Comment by vanaukenk** [comment]
This is fixed on production.
See test model here:  http://noctua.geneontology.org/workbench/noctua-form/?model_id=gomodel%3A6197061700003133
and here: http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A619bece100000036
