### ISSUE TITLE
XSS vulnerability in noctua server-side client

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#735]
It is currently possible to inject disrupting code into the url (query parameters) that could be used to create an XSS attack for users on bad links. For example, the following URLs illustrate this, disrupting the variable creation:

/workbench/noctua-form/?model_id=%22%3E%3C%2Fscript%3E%3Cimg%2Fsrc%3Dlo2%20onerror%3Dalert(1)%3E
/workbench/noctua-landing-page/?barista_token=%3C%2Fscript%3E%3Cimg/src=x%20onerror=alert(document.domain)%3E

**Comment by kltm** [comment]
@vanaukenk A fix has been rolled out to noctua-dev. I would appreciate any feedback on any issues that you might run into: while this fix _should not_ affect anything, there is always a chance that I have misunderstood something; the fix mostly works by rewriting/fixing internal variables related to URL parameters, so it might be worth noting when giving purposefully bad inputs or moving between pages.

**Comment by vanaukenk** [comment]
@kltm - let me know if there is more specific testing you'd like to do on this one.

**Comment by kltm** [comment]
@vanaukenk Ah, hm. IIRC, I think, realistically at this point if you haven't noticed anything odd on dev (and we have fully updated in the interim), I believe that there is probably no other testing needed.
