### ISSUE TITLE
Annotation extension (existence starts and ends during) not appearing in final annotation

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua#740]
We commonly capture "ProteinX is located in this CC during PhaseY" type information.  Example at http://noctua.geneontology.org/editor/graph/gomodel:61283a3000000723

similar use case to https://github.com/geneontology/go-annotation/issues/2677#issuecomment-543548984

The issue here is we can't get the AE of "existence starts and ends during" to display in Annotation Preview.  I think I've mentioned this to @vanaukenk and it is a known issue, but I couldn't find a ticket.

**Comment by vanaukenk** [comment]
@suzialeksander 
Let me follow up with @balhoff before making a ticket.

**Comment by balhoff** [comment]
I think it needs to be added to the list of allowed relations. I made an issue in Minerva: https://github.com/geneontology/minerva/issues/413.

**Comment by balhoff** [comment]
Oh, sorry, we already had an issue for this at https://github.com/geneontology/minerva/issues/406. Something else may be going on.

**Comment by balhoff** [comment]
I don't think this has been deployed to production yet.

**Comment by suzialeksander** [comment]
well that explains it.  Closing this as it's essentially a duplicate of https://github.com/geneontology/minerva/issues/406, thanks @balhoff
