### ISSUE TITLE
ZFS terms seem to be missing from GO-LEGO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#749]
In doing some testing for https://github.com/geneontology/noctua-form/issues/152 , I can't find ZFS life stage terms on either noctua-dev, production noctua, or noctua-amigo.

From earlier successful testing on that ticket (2021-11), they were there, so I'm not sure exactly when they went missing.

@balhoff @kltm @tmushayahama

**Comment by balhoff** [comment]
Looks like they are no longer in go-lego. Perhaps they were formerly included in ZFA and no longer are? (@ybradford @cerivs was there a change?)

I think I can start importing ZFS into go-lego.

**Comment by cerivs** [comment]
The ZFS is still released with the zebrafish_anatomy.obo file.  The change might be how the release tool handles the  bundled  ontologies.

**Comment by balhoff** [comment]
Thanks @cerivs! I'm retrieving `http://purl.obolibrary.org/obo/zfa.owl`. ZFS doesn't seem to be in there. No problem, though, we're now importing ZFS directly.

**Comment by ybradford** [comment]
@balhoff we recently started releasing ZFA using ODK - it seems I didn't figure ZFS in to that. Are you getting ZFS from obo foundry purl?

**Comment by balhoff** [comment]
> @balhoff we recently started releasing ZFA using ODK - it seems I didn't figure ZFS in to that. Are you getting ZFS from obo foundry purl?

Yes, sound good?

**Comment by ybradford** [comment]
Yes I think that is fine. just double checking and wondering what we need to do with ZFS and ODK

**Comment by balhoff** [comment]
The current situation seems clean, but I guess there is some worry that some other users would be taken by surprise. Not too hard to resolve though.

**Comment by matentzn** [comment]
I just checked the ZFA ODK setup. 

It is configured to release "zfa.owl" as the "simple" release, which by definition only contains ZFA classes. 

Both the zfa-full and the zfa-base file contain all the ZFS classes.

@balhoff @cerivs is right in that the ZFA edit file contains all the ZFS classes.. Not sure what to do here, switching zfa.owl to full release (that would include only RO relations alongside ZFA and ZFS)?

Its a minute work, let me know what you think is best..

**Comment by balhoff** [comment]
I leave it up to the ZFIN folks for what they want to publish in each file. I think we have what we need here by adding the new import.

**Comment by matentzn** [comment]
Not sure if you are adding the best possible one though. Look where ZFS is being redirected. That file has not been updated in probably 8 years..

**Comment by balhoff** [comment]
> Not sure if you are adding the best possible one though. Look where ZFS is being redirected. That file has not been updated in probably 8 years..

Oh! Thanks for pointing that out. I will switch to `zfa-base` only then. I just took a look at it.

**Comment by matentzn** [comment]
I would recommend to switch to zfa-full for now so we are not meeting here again in three months when ZFA and ZFS will become properly split :D 

In any case, even with zfa-base you will probably be ok 86.8%. @ybradford and @cerivs should perhaps discuss requesting ZFS to be deprecated from OBO Foundry and continue having it in ZFA..

**Comment by balhoff** [comment]
We're merging a lot of ontologies, so I feel better about the base file.

**Comment by vanaukenk** [comment]
@balhoff 

The ZFS label shows on the autocomplete, but not in the Noctua form table or Noctua graph once a ZFS term is added (it was showing prior to this ZFS update).

Also, we still need root types for the ZFS terms.

Here's a test model that shows ZFS terms as well as WBls terms.  The WBls terms are behaving as expected but not the ZFS terms:

http://noctua-dev.berkeleybop.org/editor/graph/gomodel:6202e3b700000254

Let us know if you need more info.  Thx. @tmushayahama

**Comment by balhoff** [comment]
I see the term labels in go-lego (snapshot, not release). Perhaps noctua-dev needs an ontology refresh? @kltm 

If that's the case then it is a likely cause of the root types issue as well.

**Comment by kltm** [comment]
Running rebuild cycle on `dev`.
