### ISSUE TITLE
DSL for generating models

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#75]
I am addicted to
https://www.websequencediagrams.com/

some kind of DSL for LEGO would be cool. E.g.

Shh activates Sox9 in cytosol via binding
Sox9 regulates Wnt3 via transcription factor activity
Shh and Sox9 part of limb development

**Comment by kltm** [comment]
Beyond wishlist and considering all of the machinations that have to happen to with barista, I think it would be best to group this with geneontology/noctua-repl for now. It should also have a file runner for scripting at some point in addition to the REPL, which could be extended into a DSL if the current environment was not enough (it's pretty easy to build complicated requests as it stands).

It's initially being built up to test the new models and wire protocol so specific cases can be tried as the graph editor as being changed to handle all of the recent changes on the backend and in the libraries. But it will be very handy/fun afterwards--it's neat to see your models change in the browser from simple commands given interactively to a node module. It will also answer the question: can't there be an expert/power user mode?
