### ISSUE TITLE
Allow graph editor autocompletes to work with GO:0032991 OR CHEBI:33695

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#753]
This ticket can be closed when the autocomplete in the graph editor is brought into alignment with the ShEx
https://github.com/geneontology/go-shapes/blob/55e7054d0c3ad617d862b296ef57f44369e060dd/shapes/go-cam-shapes.shex#L378

Essentially, the enabled_by autocompletes need to be able to pull children from either GO:0032991 or CHEBI:33695.
For example, http://noctua-amigo.berkeleybop.org/amigo/term/SGD:S000218101
Currently, it only operates on CHEBI:33695.

The problematic code is, at the highest level:
https://github.com/geneontology/noctua/blob/6778c5e0441ae4e787dc178f76fbcc965f1ccdc6/js/NoctuaEditor.js#L1849
and
https://github.com/geneontology/noctua/blob/6778c5e0441ae4e787dc178f76fbcc965f1ccdc6/js/NoctuaEditor.js#L2085

Related to https://github.com/geneontology/noctua-form/issues/111

@vanaukenk I'm not sure what the best project is for this...

**Comment by kltm** [comment]
Responsible search box autocomplete code https://github.com/berkeleybop/bbop-js/blob/master/lib/bbop/widget/search_box.js (self-contained with manager)

**Comment by kltm** [comment]
Some possible paths come to mind:

* it's possible that I either have the code already for an "OR" already somewhere in the system or that overriding the system as it stands now is "easy" (<-- will obviously explore these first)
* Create additional enabled_by slots in the two panes limited to the other aspect and rewire the logic to accept either, but not both
* Create additional panes for limited use; i.e. add "Add function 1" and "Add function 2" (spaghetti code and creates visual confusion, but "easy" and correct)
* Extend/restart development on the search_box widget (or create a new widget) to allow for this functionality (time consuming as working with very old code outside of original intentions; thinking that bbop-js may fight)
* See if noctua-form widgets can be ported in (longshot)
* Make it a free-for-all and release all constraints (to make things "consistent"; obviously easy)

**Comment by vanaukenk** [comment]
@kltm - just checking on a comment above:  'Currently, it only operates on GO:0032991.'  Did you mean it only operates on CHEBI:33695?

Also, it *is* possible for curators to enter protein-containing complexes via the 'Add Individual' box on the graph editor, so if other fix options look onerous, we could always fall back on that.

**Comment by kltm** [comment]
After a little digging, I found similar overloading done in some very old (6-7yo) `bbop-widget-set/lib/live_geospatial.js`...that's a bit of a trip. It looks like this has been done successfully before, so I'll proceed to see if I can test this directly at the top level on dev.

**Comment by kltm** [comment]
Merging to make testing easier.

**Comment by vanaukenk** [comment]
Thanks @kltm 

I just tested adding protein-containing complexes of GO, SGD, and Complex Portal id spaces using the Add Annoton section of the graph editor on noctua-dev and all was working as expected.

Here's the test model:

http://noctua-dev.berkeleybop.org/editor/graph/gomodel:6202e3b700000250

There are still some issues with typing Complex Portal identifiers correctly on minerva-dev, but that only affects the noctua form table display.

Unless you think there's more testing we should do (and maybe @suzialeksander could help here for at least the SGD complexes), I think this fixes the problem on the graph editor.

One other side note: the GPAD output doesn't currently output GO protein-containing complexes as annotation subjects.  This will need to be addressed with the GPAD output project.

**Comment by vanaukenk** [comment]
@kltm - we can move this onto production when you are able, and I can double-check it there before closing.  Thx.

**Comment by kltm** [comment]
@vanaukenk How would tomorrow, during/after the outage work for you? I don't know if that is more or less convenient.

**Comment by vanaukenk** [comment]
@kltm - tomorrow would be fine.  Thx.

**Comment by vanaukenk** [comment]
Moved to production and tested.
