### ISSUE TITLE
Switch to all-individual model, including variable references

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#76]
Details outlined here for now
https://docs.google.com/document/d/1scuE-BJwJwAMEBrsanIvTDI26YqlRvBQf7m4xwBDS3c/edit#

@dosumis to comment

Milestone: probably post-Barcelona

**Comment by kltm** [comment]
![Uploading IMG_20150310_151601.jpg . . .]()

Adding image of board explanation of the current API work on this issue.

**Comment by kltm** [comment]
![img_20150310_151601](https://cloud.githubusercontent.com/assets/2687900/6591393/0de0d0a8-c77c-11e4-8f67-73ba34a9c253.jpg)

**Comment by kltm** [comment]
Top priority as is preventing adoption; adding bug status.

**Comment by kltm** [comment]
Talked to @hdietze and he added a more abstract method for adding instances. It now looks complete to me; best look at Minerva wire API now here:

 https://github.com/berkeleybop/bbopx-js/wiki/MinervaRequestAPI

**Comment by kltm** [comment]
Including the related (and necessary) work on having a passable variable reference.

**Comment by kltm** [comment]
From this point on, I believe that @hdietze 's changes to Minerva are running all-individual, as well as the new request_sets. Remaining issues are separate, such as conversion and manager/UI updates to deal with these things (referenced above).
