### ISSUE TITLE
Cannot use 'information biomacromolecule' anymore? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#767]
Hello, 

In the pas I have used  'information biomacromolecule' as the enabler for templates, see 

http://noctua.geneontology.org/editor/graph/gomodel:600ced8500000901

but right now I cannot do that, either in the Graph or in the Visual Pathway editor - has this been disabled? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
'information biomacromolecule' is still valid as far as the ShEx is concerned and I can access it in the Noctua form (although the autocomplete in this case seems a little slow).

@tmushayahama - let's take a look at this together.
