### ISSUE TITLE
Issue with reasoner (is small molecule activator)

### ISSUE THREAD

**Issue by pmasson55** [geneontology/noctua#771]
Hi,

@thomaspd 
We showed Paul during our last discussion that models using the relation "is small molecule activator" do not pass the reasoner. Is there a specific issue with the use of this relation?
Example: SP-PDE3A/SLFN12 intrinsic apoptotic signaling pathway 
http://noctua.berkeleybop.org/editor/graph/gomodel:6205c24300000188
Thx for your help...

**Comment by thomaspd** [comment]
@pgaudet and @vanaukenk are the small molecule regulator relations in the ShEx file?

**Comment by kltm** [comment]
Original issue by @pmasson55

---

Hi,

@thomaspd
We showed Paul during our last discussion that models using the relation "is small molecule activator" do not pass the reasoner. Is there a specific issue with the use of this relation?
Example: SP-PDE3A/SLFN12 intrinsic apoptotic signaling pathway
http://noctua.berkeleybop.org/editor/graph/gomodel:6205c24300000188
Thx for your help...

**Comment by pgaudet** [comment]
I created a PR in the RO tracker https://github.com/oborel/obo-relations/pull/608
Maybe this will fix the issue?

**Comment by pgaudet** [comment]
This now works, thanks!
