### ISSUE TITLE
searching for template models for aromatic amino acid biosynthesis 

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#772]
I am searching for template models for "aromatic amino acid biosynthetic process"
but I don't find any models which seems strange if all of some species annotations are imported?

**Comment by ValWood** [comment]
Thanks @kltm 

@vanaukenk  may know. 
I'm never sure which tracker to use.

**Comment by vanaukenk** [comment]
@ValWood 
We don't currently have many templates, and definitely not one for "aromatic amino acid biosynthesis".
