### ISSUE TITLE
Retire http://noctua.berkeleybop.org

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua#773]
Many people get confused... Can http://noctua.berkeleybop.org be retired ?? 

and maybe a redirect to http://noctua.geneontology.org if you want.

Thanks, Pascale

**Comment by tmushayahama** [comment]
tagging @kltm . This cause many technical problems as well

**Comment by kltm** [comment]
A redirect may be the best thing here for the moment--ad alarming number of things seems to be hardwired to the legacy URL, but a forward should give us a good off ramp.

**Comment by kltm** [comment]
Okay, after looking at the setup, maybe something like
```apache
<VirtualHost *:80>
    ServerName noctua.berkeleybop.org
    RedirectPermanent / http://noctua.geneontology.org/
</VirtualHost>

It might be best to test this out during the next planned outage. (@vanaukenk)
Best to scan around for the incorrect URL in docs as well--I've already found one and will correct.

**Comment by kltm** [comment]
@vanaukenk @pgaudet With all the other maintenance and exploring needing to be done today during the outage (see: https://github.com/geneontology/noctua/issues/775), I've gone ahead and tried to put this forward in place. Please let me know if there are any further oddities with this.

**Comment by pgaudet** [comment]
looks like this is working ! thanks :)
