### ISSUE TITLE
Make model copy available from the workbenches

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua#778]
I can't ever think of a time when I will copy a model without looking at it first. So having the copy function on the landing page is not useful. I would prefer to have the availability from the graph editor or the form, and probably the VPE as well.

**Comment by vanaukenk** [comment]
Currently, we have the copy functionality available from:

- [ ] Noctua landing page
- [ ] Noctua form editor

We still would like to have the copy functionality available from:

- [ ] Noctua pathway editor (@tmushayahama is there a ticket for this?)
- [ ] Noctua graph editor (@kltm - tagging you here, but I don't know what the exact work would be, so we can talk about that further)

**Comment by tmushayahama** [comment]
@vanaukenk for VPE I didn't make a ticket, but already have it working and tested by Swiss-Prot on that USC server. I will be PRing to dev soon. Do you want me to make a ticket?

**Comment by vanaukenk** [comment]
Model copy is not available from the graph editor.
I'm closing this ticket since it is available from all the other workbenches.
We can open a new ticket specifically for the graph editor, if desired.
