### ISSUE TITLE
Review wiki documentation for existing MF-MF relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#793]
- [x] [causally upstream of](https://wiki.geneontology.org/Causally_upstream_of)  - Documentation now says not to use 
- [x] [causally upstream of, positive effect](https://wiki.geneontology.org/Causally_upstream_of,_positive_effect) 
- [ ] [causally upstream of, negative effect](https://wiki.geneontology.org/Causally_upstream_of,_negative_effect) - STILL NEEDS AN EXAMPLE
- [x] [provides input for](https://wiki.geneontology.org/Provides_input_for)
- [x] [directly negatively regulates](https://wiki.geneontology.org/Directly_negatively_regulates)
- [x] [directly positively regulates]( https://wiki.geneontology.org/Directly_positively_regulates)

Link to proposal: https://docs.google.com/document/d/171G2vCVlMPmoeFJE1rNvpzAwEv_IXncW4OJNaoJQ3bo
Link to new template: https://docs.google.com/document/d/1H9_VLRFIMPkNSOJB9tKavRBhL7AGSJIRTl_z9zD7q2I

To do:
1. Review what's currently on the existing wiki page
2. On each page, include an Overview, Usage Examples, Link to RO, Date Last Reviewed
3. Quality Control will include a link to the ShEx and any relevant GO rules

**Comment by ukemi** [comment]
Causally upstream of: https://wiki.geneontology.org/Annotation_Extension_Relation:causally_upstream_of
Last reviewed 2020-12-11
1. This is currently under the annotation extension section of the documentation. Do we want to have one central location for all of these on the wiki?
2. The page is not of the format specified above. Do we want to edit this page or just start a new one?
3. Do we want to keep the conventional annotation examples?
      a. They are both process examples. So in any case, we need to add MF to MF examples.
5. Do we need to reorganize the relations documentation on the wiki as a whole?

**Comment by ukemi** [comment]
Causally upstream of negative effect- https://wiki.geneontology.org/Causally_upstream_of_negative_effect
This is just a placeholder. We should mover this over to the write documentation ticket.

**Comment by ukemi** [comment]
causally upstream of, positive effect - https://wiki.geneontology.org/Causally_upstream_of,_positive_effect

1. I edited this entry to make it better fit with the new definition.
2. I only have one example.
3. I added an abbreviated form of the Shex to the QC section.
4. I left in the children section for now.

**Comment by vanaukenk** [comment]
Regulates - https://wiki.geneontology.org/Regulates

To start:

1. This is a very old page and will need completely new content.
2. This also raises the issue of standardizing page names and wiki URLs.

**Comment by ukemi** [comment]
directly provides input for - https://wiki.geneontology.org/Directly_provides_input_for

1. I edited this entry to make it better fit with the new definition.
2. I  have two examples. One of the ones in the draft doc seems to point to the wrong model.
3. I added an abbreviated form of the Shex to the QC section.

**Comment by ukemi** [comment]
'removes input for' is a new relation

**Comment by vanaukenk** [comment]
Positively regulates - https://wiki.geneontology.org/Positively_regulates

To start:

1. This is another old page that will need completely new content.

**Comment by vanaukenk** [comment]
Negatively regulates - https://wiki.geneontology.org/Negatively_regulates

To start:

1. This page has three words "See positively_regulates"

**Comment by vanaukenk** [comment]
Directly positively regulates - https://wiki.geneontology.org/Directly_positively_regulates

To start:

1. This page has text but also a message at the top that the relation has been deprecated.

**Comment by vanaukenk** [comment]
Directly negatively regulates - https://wiki.geneontology.org/Directly_negatively_regulates

To start:

1. This page has text but also a message at the top that the relation has been deprecated.

**Comment by vanaukenk** [comment]
Made a separate ticket for the example for causally upstream of, negative effect:

https://github.com/geneontology/noctua/issues/820
