### ISSUE TITLE
Create wiki documentation for new MF-MF relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#794]
- [x] [constitutively upstream of](https://wiki.geneontology.org/Constitutively_upstream_of)
- [x] [removes input for](https://wiki.geneontology.org/Removes_input_for)
- [x] [indirectly positively regulates](https://wiki.geneontology.org/Indirectly_negatively_regulates)
- [x] [indirectly negatively regulates](https://wiki.geneontology.org/Indirectly_positively_regulates)

Link to proposal: https://docs.google.com/document/d/171G2vCVlMPmoeFJE1rNvpzAwEv_IXncW4OJNaoJQ3bo
Put the new pages here: https://wiki.geneontology.org/Annotation_Relations#Molecular_Function_to_Molecular_Function
Link to new template: https://docs.google.com/document/d/1H9_VLRFIMPkNSOJB9tKavRBhL7AGSJIRTl_z9zD7q2I

To do:
1. Create a wiki page
2. On each page, include an Overview, Usage Examples, Link to RO, Date Last Reviewed
3. Quality Control will include a link to the ShEx and any relevant GO rules

**Comment by ukemi** [comment]
https://wiki.geneontology.org/Constitutively_upstream_of

- [ ] Update page to include a link to the RO class
- [ ] Open a ticket to add this relation to the Shex
- [ ] Add GO-CAM examples once this relation is available in Noctua.

**Comment by ukemi** [comment]
https://wiki.geneontology.org/Removes_input_for

- [ ]  Update page to include a link to the RO class
- [ ] Open a ticket to add this relation to the Shex
- [ ] Add GO-CAM examples once this relation is available in Noctua.

**Comment by ukemi** [comment]
https://wiki.geneontology.org/Causally_upstream_of_negative_effect

- [ ] Still need to add examples
- [ ] Update page to include a link to the RO class
- [ ] Open a ticket to add this relation to the Shex
- [ ] Add GO-CAM examples once this relation is available in Noctua.

**Comment by vanaukenk** [comment]
@pgaudet @ukemi 
Two questions for discussion on Thursday:
1) Which version, i.e. workbench view, of the model should we link to from the wiki documentation page?
2) Do we want to include a screenshot on the wiki of the relevant causal relation and, if so, same question as above - from which workbench view?

**Comment by vanaukenk** [comment]
From 2023-02-02 call with @ukemi and @pgaudet 

We will include screenshots of GO-CAMs, taken of models in the pathway editor 9VPe), in our relations documentation.
