### ISSUE TITLE
Switch Noctua relation / edge /glyph metadata from amigo-based to separate (forked) upstream

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#804]
Currently, Noctua requires the `amigo2-instance-data` NPM package to build. Unfortunately, the build is very awkward for AmiGO due to some legacy design decisions. We'd like to just spin this out to a new "clean" and modern location and depend on that instead (with an eventual eye to get this info into an upstream ontology at some point).

See https://github.com/geneontology/noctua/issues/801 and https://github.com/geneontology/noctua/issues/802 .

Looking to @vanaukenk To help pick the best project. If nothing fits well, I think we'd probably want this in the "proactive fixes" project.

**Comment by kltm** [comment]
In the interim, we're just manually apply on-disk fixes to production. Basically,
`mg ./deploy/js/NoctuaEditor.js`
```
indirectly activates -> indirectly positively regulates (RO:0002407)
indirectly inhibits -> indirectly negatively regulates (RO:0002409)
```

**Comment by vanaukenk** [comment]
@kltm 
The only other project that might fit is [Noctua maintenance and bug fixes](https://github.com/geneontology/project-management/issues/3), but if this work is likely to be part of a larger effort to make Noctua more robust, I'll defer to your "proactive fixes" suggestion.

**Comment by kltm** [comment]
@vanaukenk Actually, I hadn't realized there was a separate project for MF links. It might be good to hang there as it's closer to ending and it would be good to make sure that closes clean?

**Comment by kltm** [comment]
@vanaukenk Okay, I believe I have a slightly more permanent (if a little ugly) fix for this. We could go ahead and slate this for the 1st outage, if you're interested. We can also put this up on noctua-dev, but before I did so, as long as I have this all cracked open, I wanted to see if there were any changes that you'd like on things like edge colors and edge terminal glyphs (arrow types)?

**Comment by vanaukenk** [comment]
@kltm
I could take a look on noctua-dev, if you like.  That's usually a good idea :-)
For now, I don't have any other changes in mind.
Thanks.

**Comment by kltm** [comment]
@vanaukenk This is now on noctua-dev.

**Comment by vanaukenk** [comment]
I've tested each of the new MF-MF relations in the graph editor and all is behaving as expected.
For reference, here is the test model:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:636039dd00000000

**Comment by kltm** [comment]
@vanaukenk Okay, sounds good. If there is no further issue, I'll slate this update for the outage tomorrow.
