### ISSUE TITLE
Add additional metadata output to AmiGO (ComplexAnnotation) GOlr load for browsing

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#81]
The core objects used in the GOlr loader for complex annotations now extend LegoMetadata(.java), giving us access to a few more fields that would be nice to push into the schema and load (thanks @hdietze!).

**Comment by cmungall** [comment]
This may be moved to other repo:

 * load golr from github
 * change golr loader to work with all-individual model (@hdietze)
 * add additional fields, e.g. model metadata

Once this is done we can replace or supplement the select widget with either autocomplete or an embedded widget (but the current workflow where the user goes into amigo labs, finds, clicks edit, is OK)

open question: golr load frequency

**Comment by kltm** [comment]
This adds a new schema, that will have to be coordinated for labs rollout with geneontology/amigo#226.
