### ISSUE TITLE
Update label of RO:0002413 to 'provides input for' from 'directly provides input for'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#818]
From 2023-02-08 Geneva GO-CAM meeting:

@kltm can we update the Noctua graph editor workbench so that the label for RO:0002413 reflects the latest RO release, i.e. from 'directly provides input for' to 'provides input for'?

Thanks and let me know if you have any questions.

**Comment by kltm** [comment]
@vanaukenk Added to `master` code branch; can be put out on your schedule.

**Comment by vanaukenk** [comment]
Thank you @kltm 
We can update to production whenever you have time.
Will this also update the graph editor on noctua-dev?

**Comment by kltm** [comment]
Once on `master`, there is a mechanical step to get it onto `dev` (they have an unclear relation). I've gone ahead and merged `dev` to be up-to-date with `master`, so it should be there now.

**Comment by kltm** [comment]
@vanaukenk I believe this should also be compiled and updated/pushed out on `master` on production.

**Comment by vanaukenk** [comment]
Looks good.  Thanks @kltm
