### ISSUE TITLE
known_relations metadata should be 'provides input for' not 'directly provides input for'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#825]
From the 2023-02-08 Geneva GO-CAM meeting:

@tmushayahama 

Can you check all of the Noctua workbenches code to make sure that anywhere we use RO:0002413 the label is updated to 'provides input for' from 'directly provides input for'.

The current RO release no longer uses the 'directly' in the label.

Thanks and let me know if you have any questions.

**Comment by kltm** [comment]
Notes:
go-lego-react.owl looks fine
over-the-wire (from minerva) looks fine

**Comment by kltm** [comment]
Okay, I think that the template for this is #805 and #804.

**Comment by kltm** [comment]
Now have `+ ontology-ui-overlay-data@0.0.2`

**Comment by kltm** [comment]
@vanaukenk I have a possible fix in place on noctua-dev. If you could check it and it seems okay, we can role it out whenever on prod.

**Comment by vanaukenk** [comment]
@kltm 
I've checked existing models on noctua-dev and also added new 'provides input for' relations to test models and everything seems to be working and displaying fine.  This can go to production whenever you're ready.
Thank you!

**Comment by kltm** [comment]
@vanaukenk If it works for you, maybe let's just do this tomorrow during the outage?

**Comment by vanaukenk** [comment]
Checked the graph editor and the VPE again on production after the 2023-03-23 outage and all is working fine.
