### ISSUE TITLE
Contributors often come back as an ID (ORCID or otherwise), not super helpful

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#84]
As written, the contributors IDs that are stored in the model, which are then displayed in Noctua, are more often then not IDs/URIs, which isn't great for trying to figure out who to contact (but usable-ish).

Likely, the client is going to have to get this information on their own.

One possibility is to async ask Barista to resolve them, a la the login information as it is currently handled.

Another possibility is that Barista can turn over all non-sensitive user information to the client (like http://toaster.lbl.gov:3400/user_info as an API call); seems odd, but would prevent async code from worming its way into the UI.

An extension of this thought would be to have this information come from AmiGO in more or less the same manner we're planning on using to resolve the gene product label issue that we're dealing with.

**Comment by ukemi** [comment]
I'm hoping this is the correct ticket in which to add this, but we also need a mechanism to display the group who made the annotation, for example in AmiGO2 or in a GAF, the contributing group is displayed. In the gaf generated from a model column 15 is populated with GO_Noctua. As different groups start using the tool, we will want this to reflect the submitting group in the Assigned By field in AmiGO2 as it currently does for manual annotations. I assume this would be achieved by some kind of mapping between OrcIDs and the group to which a curator belongs.

**Comment by kltm** [comment]
We've had some discussion about this before (tagging on @cmungall and @hdietze), I think related to the geneontology/go-site repo and the discussion about the users.yaml file. One of the main issues was that since people move around between organizations through time we can't just have an additional map, we'll have to add an extra tag optional group contributor's tag that takes the current value found for that person in the users.yaml and passes it make to minerva during the annotation. Not a large addition, but it will require more information capture.

**Comment by kltm** [comment]
And, while we're here, there might also be interest in adding the tool used (or client) to the annotation metadata captured.

**Comment by cmungall** [comment]
Attribution Requirements: At the Geneva meeting we floated the idea of setting up an attribution working group, perhaps led by @pgaudet and @mellybelly. It's important we get this right

Recording a globally unique persistent URI denoting a person for each atomic assertion is probably good enough for most cases, and we already do that.

> One of the main issues was that since people move around between organizations through time we can't just have an additional map

We also capture a datestamp on every assertion, so in theory we can map to time-varying membership of organizations. However, this won't always work. If a triple has 3 contributors and 3 datestamps, these are independent (this is kind of unlikely, but it's not verboten), so in these cases we technically can't map back to the organization.

> we'll have to add an extra tag optional group contributor's tag that takes the current value found for that person in the users.yaml and passes it make to minerva during the annotation. Not a large addition, but it will require more information capture

So if the user has two orgs, would they have a "switch role" option in Noctua?

I feel we need a bit more analysis on long term requirements (not just how to get the GAFs looking like they were). We want to make sure everyone's contributions were preserved, what organizations contributed, possibly what grant paid for it. At the same time we don't want to overload the application and recreate http://openvivo.org

**Comment by kltm** [comment]
Pondering this, the "switch role" concept would actually relatively easy to do--it could be essentially the same code path as displaying the nickname right now. Assuming that we have these roles in the users.yaml (fields: preferred and possible roles), a user could simply select them from a dropdown and they would be sent down the pipe along with the ORCID. The only addition would be the tag in minerva. Same for grants, etc.

Adding more information to the capture in Noctua/Minerva is easy, getting that dumped back out to a GAF not so much. Would it be on the table to have a final upgrade to GAF that allows a richer attribution field?

Is there something like ORCIDs for institutions?

**Comment by cmungall** [comment]
On 5 May 2016, at 16:47, kltm wrote:

> Pondering this, the "switch role" concept would actually relatively 
> easy to do--it could be essentially the same code path as displaying 
> the nickname right now. Assuming that we have these roles in the 
> users.yaml (fields: preferred and possible roles), a user could simply 
> select them from a dropdown and they would be sent down the pipe along 
> with the ORCID. The only addition would be the tag in minerva. Same 
> for grants, etc.

We should probably be careful about the term role. In VIVO (and in the 
upper ontology we use, BFO), a role is something like "curator" or 
"engineer". I think it's formally correct to think of something like 
"curator at MGI" as a precomposed role, let's call it an "organizational 
role". But if we really mean the organization, e.g. MGI, we should call 
the field "organization" or similar.

</overontologizing>

> Adding more information to the capture in Noctua/Minerva is easy, 
> getting that dumped back out to a GAF not so much. Would it be on the 
> table to have a final upgrade to GAF that allows a richer attribution 
> field?
>
> Is there something like ORCIDs for institutions?

Yes, @mellybelly would know

**Comment by mellybelly** [comment]
so we've already spent some time overontologizing relationships between people and orgs ;-).
see https://github.com/openrif @marijane is currently coordinating efforts there and working on contribution roles for non-publication contributions: https://github.com/openrif/contribution-ontology

RE orgs, I would use the Digital Science GRID data, we've been talking to them about aligning efforts and they are very receptive to requests: https://www.grid.ac/
These are curated orgs and their synonyms, though there isn't much structure to the relations between them and other entities, @mconlon17 has been working on making the GRID data available for openVIVO consumption here:
https://github.com/openvivo/grid-rdf

Simon Porter is a good contact for Digital Science, but can't seem to find his github handle, will point him here.

For GO, it would be nice to have both the individual contributor identified (with an ORCID or other person identifier - can also be foaf or ResearcherID) and their org identified with a GRID ID, so that when they move on there is still some credit that belongs to the org. member_of or some such is fine. 

Note that I also as a random workshop exercise created a GO org record in wikidata, and wikidata is also somewhat coordinated with GRID: https://www.wikidata.org/wiki/Q23809253
Simon would know the status of this.

Happy to work with @pgaudet on GO Attribution issues.

**Comment by kltm** [comment]
This will cease to be a problem with the ORCID (or any other) resolution to #270.
