### ISSUE TITLE
Restore DBxref three-letter codes to ECO code display

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#860]
Does NEO still include a value for the has_dbxref for ECO terms?  It seems to only be available in the synonym field.

We used to display the three-letter GO ECO codes in the evidence code display for the autocomplete, re-use drop down, and form table, but that information is no longer shown in Noctua.

@balhoff @kltm

**Comment by kltm** [comment]
Some still exist; at least: http://noctua-amigo.berkeleybop.org/amigo/term/ECO:0000501
@balhoff May have some other recollection, but I don't know if this has changed much recently. As well, I'm not sure where they would appear in the GOlr/Solr data except under synonym.

**Comment by balhoff** [comment]
Synonym seems like the right place to me. I don't know of any changes in this area though.

**Comment by balhoff** [comment]
I've done some looking at current releases of ECO and go-lego, and I do see that some info from ECO is not making it all the way into go-lego, including the stuff you're looking for. I'll try to figure out what's happening.

**Comment by kltm** [comment]
@pgaudet We need this assigned to a project: ontology needs or noctua?

**Comment by cmungall** [comment]
https://github.com/geneontology/go-ontology/blob/c057cd10f464425eb609c301e0d62a50898967c5/src/ontology/Makefile#L506-L522

**Comment by balhoff** [comment]
Thanks @cmungall — I don't think anything has changed here in the last 7 years. I wonder if Noctua is seeing a difference corresponds with possibly using the local copy of ECO to merge into go-lego rather than downloading off the internet. Oh, probably when we switched to building go-amigo rather than loading various ontologies directly into solr.

**Comment by kltm** [comment]
Talking to @vanaukenk this is not pressing in any way right now and this item can be bypassed until it's added to a TODO column in some project.

**Comment by vanaukenk** [comment]
Noting that this issue has been fixed on Noctua dev and production.
The three-letter ECO abbreviations are back on display in the Noctua form and VPE autocompletes.
Thanks @balhoff @kltm

**Comment by balhoff** [comment]
Great!
