### ISSUE TITLE
Can not sign in

### ISSUE THREAD

**Issue by IvanTsers** [geneontology/noctua#872]
I can't sign in, I'm stuck in a loop with Barista Session Login ("sign in with github/login+return", as on the screenshots attached). 

<img src="https://github.com/geneontology/noctua/assets/66322545/74c060bc-81c6-4f77-a441-69536e5c1b33" width=90% height=90%>
<img src="https://github.com/geneontology/noctua/assets/66322545/cb28ab46-c722-4cd1-b47a-65ae6a5f1dbe" width=90% height=90%>

My data are already included in users.yaml (nickname: 'Ivan Tsers') and groups.yaml (shorthand: IMPRS-EB), as a part of my [onboarding](https://github.com/geneontology/helpdesk/issues/474). However, it seems that after the last maintenance outage (2024-04-11), I'm still not listed as a user (contributor) in Noctua:

<img src="https://github.com/geneontology/noctua/assets/66322545/076a043e-b632-4ac2-a9a2-78b2123403f6" width=50% height=50%>

The same with my group (it's a new group). I've tried to revoke my GitHub OAuth for Barista application and re-authorize. The issue persists. I suspect neither Noctua nor Barista are picking my credentials for some reason. Are any further actions required from my side?

**Comment by vanaukenk** [comment]
@IvanTsers 
I'll try to troubleshoot this and let you know when to try again.
Our sincere apologies for the problems.

**Comment by IvanTsers** [comment]
Hello @vanaukenk !
Many thanks for your help! Everything's working now, I've signed in.

**Comment by vanaukenk** [comment]
Wonderful!  I'm glad things are now working for you.

If you need help with anything else, please let us know.
