### ISSUE TITLE
Importing evidence into an activity unit not working (GO-CAM)

### ISSUE THREAD

**Issue by rozaru** [geneontology/noctua#875]
Hello,

Importing an existing evidence for a GO term in an activity unit of a GO-CAM model is not working. When using the "Add annotation", the annotation is there but the evidence code is missing, the annotation can be selected. After clicking "Done" it will appear for 4s and then disappear. The evidence field is empty.
![image](https://github.com/geneontology/noctua/assets/22237719/4ddd39fe-826c-41a9-81eb-874c3768235d)

System: MacOS, Safari

Thanks

Rossana

**Comment by pgaudet** [comment]
Hi Rossana, 

This feature is unavailable due to a problem in the last GO release. We are working to have a new release, hopefully this week, that should fix the problem. The ticket for this work is here: https://github.com/geneontology/amigo/issues/716

Thanks, Pascale
