### ISSUE TITLE
Many existing annotation are not visible in Noctua

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#876]
Many existing annotation are not visible in Noctua
For example:

FOr spc7 I see no MF annotations
<img width="836" alt="Screenshot 2024-04-23 at 14 22 31" src="https://github.com/geneontology/noctua/assets/7359272/eee82282-9a07-414f-890f-31457afe4db7">

even though they are present:
https://www.pombase.org/gene/SPCC1020.02

I don't want to remake the annotations unless they are duplicated (and also not time effective).

**Comment by pgaudet** [comment]
Searching for MF: 

<img width="469" alt="image" src="https://github.com/geneontology/noctua/assets/4782928/0eafd90e-4bb1-490c-b51f-04dfcbb1d762">

Searching for BP

<img width="484" alt="image" src="https://github.com/geneontology/noctua/assets/4782928/4dfecfde-32c8-4055-ad4c-f7d511d88388">



There is a little lag; could that be the problem?

**Comment by ValWood** [comment]
No I don't think so. I'm aware of the lag, but this is in addition, they never appear. It is happening to @PCarme too

**Comment by vanaukenk** [comment]
@ValWood 
Click on one of the specific terms.  Do you see the evidence then?

**Comment by ValWood** [comment]
No it's random. Sometimes I see the terms, and sometimes, I don't. In the cases where I don't see them I have been adding manually

**Comment by ValWood** [comment]
In the other case, I can see the terms, I select them but the annotation doesn't appear

**Comment by ValWood** [comment]
In this example, only one of the existing annotations is visible (IMP), although I think I have seen EXP  (will double-check)

<img width="1169" alt="Screenshot 2024-04-23 at 15 52 48" src="https://github.com/geneontology/noctua/assets/7359272/927f9a78-a150-419e-ae56-a736997c6d63">

**Comment by PCarme** [comment]
In this example I can see annotations with EXP evidence.

![image](https://github.com/geneontology/noctua/assets/163283897/8bf046a8-2fb9-4feb-bc10-05ca8b075a74)

**Comment by ValWood** [comment]
Yes I have seen EXP annotations too, so it isn't that...

**Comment by ValWood** [comment]
I think a one was a user error. I  think I wasn't selecting the term when I had a single term, only selecting the evidence
