### ISSUE TITLE
Cannot add part_of BP to existing MF

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#878]
If I add a part_of BP here, it does not appear

<img width="630" alt="Screenshot 2024-04-23 at 15 04 09" src="https://github.com/geneontology/noctua/assets/7359272/3195d5ce-67e5-4841-bcdc-71dae5bd2fc0">

**Comment by ValWood** [comment]
sometimes I see this I see this but cannot add
<img width="1139" alt="Screenshot 2024-04-23 at 15 05 02" src="https://github.com/geneontology/noctua/assets/7359272/0e517678-5415-485a-bc73-277f81a32967">

sometimes I can add but they don't display

**Comment by pgaudet** [comment]
Zoom ? I never had issues with this one.

**Comment by ValWood** [comment]
I think I was doing this wrong. I wasn't clicking to select when there was only one process.
