### ISSUE TITLE
Link to PomBase production models in Noctua gives "no results yet."

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/noctua#895]
Hi.

We'd like to be able to link to a list of PomBase production models from pombase.org but we're seeing a bug.  If there's a preferred way to do this, please let us know.

I filtered for group: PomBase and state: production on the front page.  That worked (there are 15 models listed) but I wasn't able to re-use the URL.

This is the URL after filtering:
http://noctua.geneontology.org/workbench/noctua-landing-page/?offset=0&limit=50&group=http://www.pombase.org&state=production&expand&debug

If I paste this URL into a new tab, after a bit of redirection the state parameter in the URL becomes "undefined"

This is the resulting URL:
http://noctua.geneontology.org/workbench/noctua-landing-page/?offset=0&limit=50&group=http%3A%2F%2Fwww.pombase.org&state=undefined&expand=&debug=

```
"no results yet."
```

Thanks.

@ValWood

**Comment by kltm** [comment]
@kimrutherford @ValWood Unfortunately, we generally do not allow the curation system to be a public interface. (For example, we've had problems in the past when bots crawl external sites that link to us, the curation system gets hammered.)

I think the trick here to find you a way to get a list of released production PomBase models, which you can then link into AmiGO (see https://amigo.geneontology.org/amigo/model/66187e4700001573).

**Comment by kimrutherford** [comment]
> I think the trick here to find you a way to get a list of released production PomBase models, which you can then link into AmiGO

That sounds like a plan.  Thanks.

**Comment by kltm** [comment]
@kimrutherford In the interim, I would point out that the http://snapshot.geneontology.org/products/upstream_and_raw_data/noctua_pombase.gpad.gz file and (soon) the combined GPAD from our downloads page would have all models that are production, part of the release, and have extractable annotations. That might be something to work with until the big fix is out.

**Comment by kimrutherford** [comment]
Thanks, that's very useful.
