### ISSUE TITLE
 Existing term not available in Noctua

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#899]
In this model, I was unable to select "outer kinetochore" as a term (for import or de novo annotation

http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A666b894f00001940

**Comment by vanaukenk** [comment]
We investigated this one and it is an issue with parentage in the ontology, i.e. a function cannot 'occur in' a protein-containing complex.
