### ISSUE TITLE
Add ability to drop in geneRIFs

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#90]
NCBI geneRIFs are n-ary associations between 1-many genes, a PMID, and a piece of text.

This makes a good seed for a diagram. E.g. when starting from a PMID, we may use eutils or the monarch API to look up all geneRIFs for that PMID. We could then seed the model with MF boxes with an anonymous function, enabled_by gene-productN, for each gene. An anonymous BP node would group these, with the rif text added as metadata.

More advanced extensions would be possible - e.g. entity recognition on the RIF text to seed functions, phenotypes, etc

**Comment by kltm** [comment]
Fun, but I don't see this as particularly likely unless we have some NLP going on at one end or the other.

**Comment by cmungall** [comment]
Should be easy for someone to do this as a workbench, using scigraph-annotator. I can prototype this as a standalone app that exports minervaJSON that can be pasted in via dangerzone.

**Comment by kltm** [comment]
Do you have a link for `scigraph-annotator`?

**Comment by cmungall** [comment]
https://scigraph-ontology.monarchinitiative.org/scigraph/docs/#/annotations

we'll also have a multi-annotator wrapper soon exposed via biolink
