### ISSUE TITLE
Large numbers of entities are not exporting to the API

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#906]
@kimrutherford has made a query so that we can track our genes in GO-CAMs
https://www.pombase.org/results/from/id/f99d8133-3206-4941-b44e-9314e7cae3d2

However, it seems that any part of the model that does not have evidence on  any outputs/inputs are not exported?

i.e here:

**http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000459

dfg10
gpt2
alg1
are not exported (even though they do appear in the pathway widget).

1. I'm not sure why we need to add evidence to inputs and outputs that are recorded in the  MF activities?  the MF evidence should be sufficient? 
2. It would be nice if there was  a way to access a list of the entities in production models that are missing evidence (I have many which I am waiting to plug in the  annotation when it comes through from PomBase. These aren't exported either.

thanks 

VAL

@PCarme  I think we have done a lot more than it appears!

**Comment by vanaukenk** [comment]
@ValWood 

I think the original idea was that curators wouldn't release models to production until they were fully evidenced.
That said, there may be things we can do to make it easier and faster to add evidence so models can be released more quickly.

I'd need to know more about your workflow to help with this.

**Comment by vanaukenk** [comment]
@ValWood - also one curation issue I noticed when looking at the model above was that there are some MFs annotated with 'occurs in' a protein-containing complex' child term.
You'll want to update those CC terms to a non-protein-containing complex term.
Let me know if you have any questions.

**Comment by ValWood** [comment]
Hi @vanaukenk 
1) I  will fix  the CC annotations, I didn't realise this at first
2) I think we can make all of the missing non-experimental annotations in Noctua rather than in PomBase (I'll talk to @PCarme about this, (although it is confusing because we do access these genes via the widget, just not from the API). However, if there is anything that can be done to speed up our experimental annotations through to Noctua that would always be useful.
3) I still don't really want to add evidence to all of the inputs and outputs because these are already supported by the MF activity term? This should be automatic?

Did you mention that there was a way to do edits without deleting and recreating the annoton and losing the connections? if so, can you point me to the docs for this?

**Comment by ValWood** [comment]
It is a quick workaround to add NAS evidence to the has_input/output so that entities get exported. I did this for some of my amino acid biosynthesis pathways, and it worked fine. However when I tried to add for this pathway
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000459
it would not let me and gave the error:

Error: it seems like you do not have permission to perform that operation. Did you remember to login?

(I did)

**Comment by ValWood** [comment]
Also on this one
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000015

**Comment by vanaukenk** [comment]
@ValWood 
Just chatting a bit about the login issue with @kltm, it seems a probable explanation is that your token had expired.
If this happens again, though, ping me on email or Slack so we can look at it together asap.

**Comment by ValWood** [comment]
It was weird, though, because I could edit all of the other models except these 2 (I edited some other models in between).
Will try again today, but I think it is particular to these sessions, as I tried  to edit one of them before

**Comment by ValWood** [comment]
It's still a problem.
I  also can't add inputs to this pathway
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A667dfe8d00001131

**Comment by ValWood** [comment]
(I can edit some pathways and not others)

**Comment by ValWood** [comment]
It seems this was an expired token, and a reload should fix it.
