### ISSUE TITLE
fix tracker configuration

### ISSUE THREAD

**Issue by ValWood** [geneontology/noctua#915]
cannot filter on authors
@rozaru
or @pcarme
and they don't appear  with an "@"

**Comment by ValWood** [comment]
@vanaukenk 
Can you also make it so that I can add labels on this tracker?
tks
Val

**Comment by pgaudet** [comment]
This has to do with which GH Team everyone is part of 

@kltm should we add the noctua repos to the Annotation team?

**Comment by kltm** [comment]
@ValWood We've added the annotation github group to more repos, you should now be able to "@" people in that group here (and some other noctua-related repos).

**Comment by ValWood** [comment]
Thanks, I'll let you know if I need others, but this is *immediately* better
