### ISSUE TITLE
Remove or deprioritize barista (and other) hard-coded URLs in noctua-alliance-pathway-preview

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#922]
During experimentation with an AWS version of Noctua, we noticed that the noctua-alliance-pathway-preview attempted to contact barista.berkeleybop.org, instead of the desired https://am-barista-test-2024-10-15.geneontology.io.

The workbench should either be driven by a variable or draw the correct value from its environment.

Quite possibly related to developments at https://github.com/geneontology/wc-gocam-viz/issues/46

**Comment by kltm** [comment]
Specifically, for example, at https://am-noctua-test-2024-10-15.geneontology.io/workbench/noctua-alliance-pathway-preview/?model_id=gomodel:66e382fb00001468 , with:
`Blocked loading mixed active content “http://barista.berkeleybop.org/search/stored?id=gomodel:66e382fb00001468”`

**Comment by kltm** [comment]
@pgaudet would it be okay if I got somebody to look at this, as it's blocking closing out the first phase of this project?

**Comment by kltm** [comment]
I'm looking at whether to "file" this as a noctua maintenance issue (in which case it might be something on @tmushayahama 's plate) or a widget fix issue (in which case it might be something that @pkalita-lbl might be able to look at in the course of his widget work). Do either of you have a strong preference for how this goes? @tmushayahama , in the end, it will have to go into noctua workbenches anyways, so it might make sense for you to look at it either way.

This behavior can still currently be seen at https://am-noctua-test-2024-10-15.geneontology.io/workbench/noctua-landing-page/ (while it's still up). 

Also tagging @vanaukenk as, while this is not a direct feature fix from users, it is a fix that's necessary to proceed on the Noctua in AWS project that affects Noctua.

**Comment by pkalita-lbl** [comment]
I believe all the necessary changes have already been made to the widget. As far as I can tell [this page](https://am-noctua-test-2024-10-15.geneontology.io/workbench/noctua-alliance-pathway-preview/?model_id=gomodel:65a1f4f800000617) is still using version `0.0.52` of the widget. In [version `1.0.0`](https://github.com/geneontology/wc-gocam-viz/releases/tag/v1.0.0) of the widget the default data access endpoint became `https://api.geneontology.org/api/go-cam/%ID` and if that needs to change the client page can use the `api-url` attribute.

**Comment by kltm** [comment]
@pkalita-lbl Thank you for the explanation.

@tmushayahama Would it be possible to update the workbench to grab the barista value from the environment and put it into that variable? I believe that would essentially close this issue.

**Comment by tmushayahama** [comment]
PR fix here https://github.com/geneontology/noctua-alliance-pathway-preview/pull/17 . This is for dev and will PR for production once tested

Sorry, I didn't see this earlier as it was not in the workbench repo issue tracker

cc @kltm @pkalita-lbl

**Comment by kltm** [comment]
@tmushayahama No worries--I was still trying to figure out the best place to put this. Thank you for the fix!

**Comment by kltm** [comment]
@tmushayahama As far as testing goes, I think the proof will be in the pudding for this one :) Looking at noctua-dev, it's going to the right barista-dev, so that's all good. We'll need to see how it works with the AWS deployment.

@vanaukenk For that, it might be easiest for us working on the devops to just get this onto `master` so we can redeploy the image and see if the fix "works" as intented on our tests. There is some upgrade in the version of the pathways widget here; I'd appreciate it if you could look at this on dev and "sign off" on it. We'd don't have to schedule this for the next outage, but it's fine too if you want to add it to the upcoming outage (we can skip it this time around otherwise).

**Comment by mugitty** [comment]
@kltm, @tmushayahama:
I have https://am-noctua-test-2024-10-15.geneontology.io using [geneontology/noctua:v6](https://hub.docker.com/layers/geneontology/noctua/v6/images/sha256-6651d91402f385480a1133000633748701d763e0dce59e45afca7f5914bd7789?context=explore) which includes updates for this ticket

**Comment by kltm** [comment]
@mugitty @tmushayahama So far, with my testing, this seems to be fixed--thank you!
