### ISSUE TITLE
Showing versionIRIs for loaded ontologies

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#94]
When using Noctua, it may be useful to know the version of all loaded ontologies, just as in AmiGO.

The challenge here is that the Solr index and Minerva may be out of sync, so we'd have to show two versionIRIs. This is potentially v confusing. What should we do about this?

**Comment by kltm** [comment]
Looking at the current API, I'd like to batch most of these meta things (#49, #67, etc.) into a single client start-up call or two.

**Comment by balhoff** [comment]
@goodb and I ran into this today. It would be really useful to display the versions of all ontologies loaded into Minerva. I don't think it's so critical to know the Solr index version, since at least for me this is mostly for debugging inference differences across environments.

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for now.
