### ISSUE TITLE
Zoom levels and viewport moves can cause strange and buggy behavior for node and connector positioning

### ISSUE THREAD

**Issue by rbalakri** [geneontology/noctua#95]
Sometimes the edges that connect the nodes vanish if I try to move the nodes around. Is this a feature?

R

**Comment by kltm** [comment]
Likely, as part of the math issues, in some cases, connecting edges sometimes vanish during node movement.

**Comment by kltm** [comment]
There also seems to be an effect where there seems to be something with the math at various zoom levels that essentially makes a small move "remember" itself to be farther away?

**Comment by kltm** [comment]
Well, I want to back off from "math" issues.
As an experiment for some other issues (#341 #268 etc.), I upgraded to jsPlumb 2.1.7. This upgrade, while causing a small amount of other breakage, seems to have fixed this issue.
I'm tempted to go back and see if the last in the jsPlumb 1.x series has a balance of fixing this issue and not causing any breakage.

**Comment by kltm** [comment]
I found the undocumented downloads for 1.7.10, the final in the 1.x series. This seemed to fix a lot of things, but still had some kind of "limit to canvas" area issue, that would cause elements to snap back to a smaller area than I had defined, and would not let them leave that area. Hm. 2.1.7 also exhibited this, but I assumed that it was just general breakage. (2.1.7's other main issue was z-index on the fixtures at the end of edges.)
To double check, I reverted to 1.5.5...and found that not only did 1.5.5 not have the "bounds" issue, but also no longer had the edge displacement issue.
Great. A little playing showed it wasn't the difference between the jquery and non-jquery versions of the code (although I'm surprised that works at all).

So I've finally figured out the answer:
If the "canvas" is defined too small (e.g. min-height: 600px; min-width: 800px;), when dragging the *farthest out* item inwards, the graph workspace starts to shrink down. While this shrinking happens, the node and the fixture have slightly different arithmetic going on, causing the fixtures movement to add the shrinkage, which causes it to lift away from the node.

Fixes could include a large workspace, or just not using the min-height/width in favor of just having a lot of space.

**Comment by kltm** [comment]
Note that 1.6.2 seems to have some API break, which might explain why I'm having trouble with the snapping boundry:
```
Important This is a change from versions of jsPlumb prior to 1.6.2. In versions prior to 1.6.2 you could assign the Container directly via the jsPlumb.Defaults.Container property. You can still do this - we're in Javascript here of course, it's a free-for-all - but it will be ignored.
```

**Comment by kltm** [comment]
I took a look at other libraries for this kind of thing. It turns out for the good ones, jsPlumb is the *least* proprietary in that they have a "community" version.
