### ISSUE TITLE
Seed lego models - bottom up using GOlr 

### ISSUE THREAD

**Issue by hdietze** [geneontology/noctua#98]
Alternate way of seeding LEGO, as proposed by Paul Thomas:

Combining annotons into larger processes (“seeding”)
The general flow is the following:

1. get all molecular components (or, once there is a library of LEGO models) molecular processes that are to be combined.  For now, we will do that by getting all gene products that have been annotated to the process (allowing the user to specify the evidence types that can be used for this).

2. Associate each molecular component with a function term.  For now, we will do that by choosing the term with the highest information content.  If more than one term is available (and it is not an ancestor of the chosen term), the box on the annoton should be flagged somehow, and the user should be able to choose other available terms from a drop-down.  If two molecular components have the same annotation (or if one is an ancestor of the other in the GO), and they both have a contributes_to annotation, combine into a complex (i.e. a single annoton).

3. Associate each molecular component with a cellular component term.  Use the same rules as for MF above.  Note that these cannot be macromolecular complex terms, but if the term also has an ancestor outside the macromolecular complex branch then that is a valid possible term.

4. Find potential links between molecular processes.  For now, we will do that by: first, find all cases where the molecular function of one annoton (see step 2 above) has the second molecule in the extension field, and link via a directional link (regulates by default but could be more informative—e.g. direct-- depending on the class); second, find all cases where two annotons are linked via a protein-protein interaction, and link via a non-directional link.  Note that protein-protein interactions might be used as evidence for a complex (combining gene products together into a single functional unit), or for a molecular effect relation.

**Comment by hdietze** [comment]
This request is an alternate way for seeding LEGO, this is also related to #36.

**Comment by hdietze** [comment]
First implementation of a simple example of B cell apoptotic process in Mouse:

![screen shot 2015-03-06 at 5 10 15 pm](https://cloud.githubusercontent.com/assets/5142396/6539232/144949da-c424-11e4-8c07-1124c4efa8ee.png)

This implements step 1-3.

**Comment by hdietze** [comment]
@cmungall

**Comment by hdietze** [comment]
Relevant code: `owltools.annotation.lego.generate.GolrSeedingDataProvider`
Currently part of the MolecularModelServer module in owltools

**Comment by kltm** [comment]
Talking with @hdietze, it looks like an entirely different server, so there will have to be manager changes. (Double check what we do with the nasty old getRelations.) For the currently discussed formulation, we have:

* The access paths will be "seed/fromProcess" and "seed/fromProcessPrivileged".
* The arguments to be supplied will be the strings: process and taxon.
* The response will be a model-id on success (this can then be handled essentially the same way as exports, which is waaay better than what were doing currently for model creation, etc.).

**Comment by kltm** [comment]
Have a partial implementation, but need a way of knowing what URL to target depending on the contents of the request. I assume the "entity" is "model; what is the "operation" here?

**Comment by kltm** [comment]
@hdietze BTW, AFAICT, I no longer need any of the getRelations stuff, so feel free to clean that out.

**Comment by kltm** [comment]
According to @hdietze, there is no operation...but I kind of need one here, so we're going to try and make one up and see what happens.

**Comment by kltm** [comment]
Okay, baby steps here. On input:
```
 http://localhost:6800/seed/fromProcessPrivileged?intention=action&requests=%5B%7B%22entity%22%3A%22model%22%2C%22operation%22%3A%22seed-from-process%22%2C%22arguments%22%3A%7B%22process%22%3A%22GO%3A0008053%22%2C%22taxon%22%3A%22taxon%3A9606%22%7D%7D%5D&uid=GOC%3Akltm
```
AKA:
 ```
http://localhost:6800/seed/fromProcessPrivileged?intention=action&requests=[{"entity":"model","operation":"seed-from-process","arguments":{"process":"GO:0008053","taxon":"taxon:9606"}}]&uid=GOC:kltm
```
 Or just requests:
```json
[
 {
  "entity":"model",
  "operation":"seed-from-process",
  "arguments": {
   "process":"GO:0008053",
   "taxon":"taxon:9606"
  }
 }
]
```

to the seed/fromProcessPrivileged service gives me the following error:

```
"signal": "rebuild",
"message-type": "error",
"message": "Could not successfully handle batch request. Exception: org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException. Expected non-null value for: The request may not be null.",
"commentary": "org.geneontology.minerva.server.handler.OperationsTools$MissingParameterException: Expected non-null value for: The request may not be null.\n\tat org.geneontology.minerva.server.handler.OperationsTools.requireNotNull(OperationsTools.java:18)\n\tat ...
```
Not sure where to go with that...

**Comment by hdietze** [comment]
`request` vs `requests`
At the moment, the seed API expects a single seed request in the `request` param (not an array).

**Comment by hdietze** [comment]
After discussion with @kltm, updated seed api to be inline with batch api for parameters.
See commit geneontology/minerva@c5d5736d4e40aee9e63146e33571f50bb336e6ee

**Comment by cmungall** [comment]
The autocomplete for process and taxon seems to only accept leaf nodes, which is no good as process leaves are typically regulation (not good for seeding) and taxon leaf nodes are strains (no annotations at the level other than E coli)

For example it's impossible to select the process `synaptic vesicle endocytosis`, even with the secret space suffix (but the regulation children are available)

It's also impossible to select Mus musculus (10090) or Homo sapiens (9606), with or without magic whitespace. However, 'Homo sapiens neanderthalis' is available but unfortunately we have no GO annotations for neanderthals. There is also a Homo/Mus xenograft available.

Weirdly, if I type in "NCBITaxon:10090" (the ID for Mus musculus the species) it gives me lots of mouse strains; so it really knows that I want a mouse, it just won't give it to me.

**Comment by cmungall** [comment]
Hmm, my hypothesis that this is leaf nodes is wrong, as Escherichia coli is findable in autocomplete

'synaptic vesicle endocytosis' is also unavailable in autocomplete in the macro wizards. However, it is autocompletable on http://tomodachi.berkeleybop.org/amigo

**Comment by kltm** [comment]
Ugh. I can duplicate it locally now as well. It does seem to be the case that the GOlr load on tomodachi only made the leaves available for NCBITaxon, GO and CHEBI do not seem to have been affected by whatever is going on. While not a noctua issue, I'll keep it here for now until we can sort out what is going on.

**Comment by kltm** [comment]
Terrific:
 http://nakama.berkeleybop.org/amigo/load_details
 http://tomodachi.berkeleybop.org/amigo/load_details
Maybe the load somehow went pear-shaped silently. Going to give up and reload tonight.

**Comment by kltm** [comment]
Spinning this out into a more specific AmiGO item--AFAICT, the widget is correct and the fix (if it's not a transient issue) lies with AmiGO/Makefile/GOlr loader code: geneontology/amigo#228.

**Comment by cmungall** [comment]
Proposed refinement to Paul's spec:

> Associate each molecular component with a cellular component term

This underspecifies whether or not each source CC annotation generates a new individual or whether individuals of the same class are shared

I propose creating a new individual

 1. This is more conservative, we do not know for sure whether in the underlying biology these are of the same individual.
 2. In the short term it works better in the display, as shared individuals do not get folded. So even though the underlying model has more individuals this way, the editors view will have fewer nodes

**Comment by kltm** [comment]
@hdietze I believe this was fixed already?

**Comment by cmungall** [comment]
Example for Paul:
http://noctua-dev.berkeleybop.org:8909/editor/graph/gomodel:55dce5d200000001?barista_token=tklkzaew50jh2dlplnc1#

**Comment by cmungall** [comment]
@hdietze would you prefer us to open new minerva tickets for changes from here on (unless they involve the hookup with Noctua?)

For example:

 * inclusion of evidence
 * created/date annotations
 * model-level annotations (seeded from X)
 * algorithmic refinements: has_part, extensions, use of binding partner

**Comment by hdietze** [comment]
Creating new tickets is preferred. See also #223 for evidence handling while seeding.

**Comment by cmungall** [comment]
#229 for PPIs
