### ISSUE TITLE
Figure out pipeline for correcting GAFs at source

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#99]
Not sure this really belongs in this tracker, part of wider GO pipeline. As discussed on 2015-03-16 Noctua call.

When doing noctua annotation on a seeded model we may decide we need to fix source annotations. This may not be necessary if the noctua model becomes the source but in the interim how do we deal with 'challenges' etc

**Comment by kltm** [comment]
@cmungall This has been a while--it this still considered to be a relevant ticket? Or just a shadow of the more modern #361 ?
